= Cōdex [1603:44:101]: /Dictiōnāria basibus dē sceleribus contrā persōnam/
:doctype: book
:title: Cōdex [1603:44:101]: /Dictiōnāria basibus dē sceleribus contrā persōnam/
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum
:front-cover-image: image:1603_44_101.mul-Latn.codex.svg["Cōdex [1603_44_101]: /Dictiōnāria basibus dē sceleribus contrā persōnam/",1050,1600]




{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-03-12

|
numerus editionis
|
2022-03-15T00:22:49

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:44:101]**_ is the book format of the machine-readable dictionaries _**[1603:44:101] /Dictiōnāria basibus dē sceleribus contrā persōnam/**_, which are distributed for implementers on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.
    +++<br><br>+++
    **ABOUT LEXICOGRAPHY**
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    **ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**
    +++<br><br>+++
    We're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.
    +++<br><br>+++
    Since the full list of prototypal-dictionaries and dictionaries is huge, one way cited by objective audiences is the following:
    +++<br><br>+++
    ....
    1. Humanitarian aid
    2. Development aid
    3. Human rights
    4. Military relief (or conflict and conflict-resolution related concepts)
    ....
    +++<br><br>+++
    The itens 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).
    +++<br><br>+++
    Note that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    The lexicographers of this work are both volunteers, doing it for free, pro bonō publicō, and don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books. Most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.
    +++<br><br>+++
    There's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work considering it is feasible over 200 languages? The logistics to decide who should be paid, then worldwide cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither sufficient money nor humans interested in being coordinators exist.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
Rēs interlinguālibus::
  /scope and content/@eng-Latn:::
    `+//Dictiōnāria basibus de scielus contrā persōnam//+` (literal English translation: _Basic dictionaries about crimes against person_; person on singular) contains basic (id est, not fully detailed) concepts about crimes against humans at mostly at individual level and crimes against group of humans without intent of exterminate entire community (which have e dedicated dictionaries) for non-political reasons.



==== Referentia
Referēns 1::
  /reference URL/@eng-Latn:::
    link:https://www.youtube.com/watch?v=s_-YueQMLRU[]
  Linguae multiplīs (Scrīptum incognitō):::
    /TODO document/@eng-Latn

Referēns 2::
  /reference URL/@eng-Latn:::
    link:https://www.ohchr.org/EN/NewsEvents/Pages/DisplayNews.aspx?NewsID=27756&LangID=E[]
  Linguae multiplīs (Scrīptum incognitō):::
    /TODO document/@eng-Latn


=== Methodī ex verbīs in dictiōnāriīs
NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    The ***[1603:44:101] /Dictiōnāria basibus dē sceleribus contrā persōnam/*** uses Wikidata as one strategy to conciliate language terms for one or more of it's concepts.
    +++<br><br>+++
    This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up to date translations.
    +++<br><br>+++
    **How reliable are the community translations (Wikidata source)?**
    +++<br><br>+++
    The short, default answer is: **they are reliable**, even in cases of no authoritative translations for each subject.
    +++<br><br>+++
    As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).
    +++<br><br>+++
    However, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.
    +++<br><br>+++
    **Major reasons for "wrong translations" are not translators fault**
    +++<br><br>+++
    TIP: As a rule of thumb, for already very defined concepts where you, as human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.
    +++<br><br>+++
    The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.
    +++<br><br>+++
    It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.
    +++<br><br>+++
    From the point of view of data conciliation, the following methodology is used to release the terminology translations with the main concept table.
    +++<br><br>+++
    . The main handcrafted lexicographical table (explained on previous topic), also provided on `1603_44_101.no1.tm.hxl.csv`, may reference Wiki QID.
    . Every unique QID of  `1603_44_101.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!
    .. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares then for general use.
    . The query result, with all QIDs and term labels, is shared as `1603_44_101.wikiq.tm.hxl.csv`
    . The community reviewed translations of each singular QID is pre-compiled on an individual file `1603_44_101.wikiq.tm.hxl.csv`
    . `1603_44_101.no1.tm.hxl.csv` plus `1603_44_101.wikiq.tm.hxl.csv` created `1603_44_101.no11.tm.hxl.csv`


=== Rēs dē factō in dictiōnāriīs
==== Concepta: 22

==== Rēs linguālibus: 95

[%header,cols="15h,25a,~,17"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
23

|
ara-Arab
|
https://glottolog.org/resource/languoid/id/arab1395[arab1395]
+++<br>+++
https://iso639-3.sil.org/code/ara[ara]
+++<br>+++ https://www.wikidata.org/wiki/Q13955[Q13955]
|
Macrolingua Arabica (/Abecedarium Arabicum/)
|
17

|
hye-Armn
|
https://glottolog.org/resource/languoid/id/nucl1235[nucl1235]
+++<br>+++
https://iso639-3.sil.org/code/hye[hye]
+++<br>+++ https://www.wikidata.org/wiki/Q8785[Q8785]
|
Lingua Armenia (Alphabetum Armenium)
|
9

|
ben-Beng
|
https://glottolog.org/resource/languoid/id/beng1280[beng1280]
+++<br>+++
https://iso639-3.sil.org/code/ben[ben]
+++<br>+++ https://www.wikidata.org/wiki/Q9610[Q9610]
|
Lingua Bengali (/Bengali script/)
|
11

|
rus-Cyrl
|
https://glottolog.org/resource/languoid/id/russ1263[russ1263]
+++<br>+++
https://iso639-3.sil.org/code/rus[rus]
+++<br>+++ https://www.wikidata.org/wiki/Q7737[Q7737]
|
Lingua Russica (Abecedarium Cyrillicum)
|
18

|
hin-Deva
|
https://glottolog.org/resource/languoid/id/hind1269[hind1269]
+++<br>+++
https://iso639-3.sil.org/code/hin[hin]
+++<br>+++ https://www.wikidata.org/wiki/Q1568[Q1568]
|
Lingua Hindica (Devanāgarī)
|
8

|
kan-Knda
|
https://glottolog.org/resource/languoid/id/nucl1305[nucl1305]
+++<br>+++
https://iso639-3.sil.org/code/kan[kan]
+++<br>+++ https://www.wikidata.org/wiki/Q33673[Q33673]
|
Lingua Cannadica (/ISO 15924 Knda/)
|
3

|
kor-Hang
|
https://glottolog.org/resource/languoid/id/kore1280[kore1280]
+++<br>+++
https://iso639-3.sil.org/code/kor[kor]
+++<br>+++ https://www.wikidata.org/wiki/Q9176[Q9176]
|
Lingua Coreana (Abecedarium Coreanum)
|
15

|
lzh-Hant
|
https://glottolog.org/resource/languoid/id/lite1248[lite1248]
+++<br>+++
https://iso639-3.sil.org/code/lzh[lzh]
+++<br>+++ https://www.wikidata.org/wiki/Q37041[Q37041]
|
Lingua Sinica classica (/ISO 15924 Hant/)
|
1

|
heb-Hebr
|
https://glottolog.org/resource/languoid/id/hebr1245[hebr1245]
+++<br>+++
https://iso639-3.sil.org/code/heb[heb]
+++<br>+++ https://www.wikidata.org/wiki/Q9288[Q9288]
|
Lingua Hebraica (Alphabetum Hebraicum)
|
15

|
lat-Latn
|
https://glottolog.org/resource/languoid/id/lati1261[lati1261]
+++<br>+++
https://iso639-3.sil.org/code/lat[lat]
+++<br>+++ https://www.wikidata.org/wiki/Q397[Q397]
|
Lingua Latina (Abecedarium Latinum)
|
6

|
tam-Taml
|
https://glottolog.org/resource/languoid/id/tami1289[tami1289]
+++<br>+++
https://iso639-3.sil.org/code/tam[tam]
+++<br>+++ https://www.wikidata.org/wiki/Q5885[Q5885]
|
Lingua Tamulica (/ISO 15924 Taml/)
|
10

|
tel-Telu
|
https://glottolog.org/resource/languoid/id/telu1262[telu1262]
+++<br>+++
https://iso639-3.sil.org/code/tel[tel]
+++<br>+++ https://www.wikidata.org/wiki/Q8097[Q8097]
|
Lingua Telingana (/ISO 15924 Telu/)
|
5

|
tha-Thai
|
https://glottolog.org/resource/languoid/id/thai1261[thai1261]
+++<br>+++
https://iso639-3.sil.org/code/tha[tha]
+++<br>+++ https://www.wikidata.org/wiki/Q9217[Q9217]
|
Lingua Thai (/ISO 15924 Thai/)
|
7

|
zho-Zzzz
|
https://glottolog.org/resource/languoid/id/sini1245[sini1245]
+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q7850[Q7850]
|
/Macrolingua Sinicae (?)/
|
18

|
por-Latn
|
https://glottolog.org/resource/languoid/id/port1283[port1283]
+++<br>+++
https://iso639-3.sil.org/code/por[por]
+++<br>+++ https://www.wikidata.org/wiki/Q5146[Q5146]
|
Lingua Lusitana (Abecedarium Latinum)
|
14

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
22

|
fra-Latn
|
https://glottolog.org/resource/languoid/id/stan1290[stan1290]
+++<br>+++
https://iso639-3.sil.org/code/fra[fra]
+++<br>+++ https://www.wikidata.org/wiki/Q150[Q150]
|
Lingua Francogallica (Abecedarium Latinum)
|
18

|
nld-Latn
|
https://glottolog.org/resource/languoid/id/mode1257[mode1257]
+++<br>+++
https://iso639-3.sil.org/code/nld[nld]
+++<br>+++ https://www.wikidata.org/wiki/Q7411[Q7411]
|
Lingua Batavica (Abecedarium Latinum)
|
16

|
deu-Latn
|
https://glottolog.org/resource/languoid/id/stan1295[stan1295]
+++<br>+++
https://iso639-3.sil.org/code/deu[deu]
+++<br>+++ https://www.wikidata.org/wiki/Q188[Q188]
|
Lingua Germanica (Abecedarium Latinum)
|
18

|
spa-Latn
|
https://glottolog.org/resource/languoid/id/stan1288[stan1288]
+++<br>+++
https://iso639-3.sil.org/code/spa[spa]
+++<br>+++ https://www.wikidata.org/wiki/Q1321[Q1321]
|
Lingua Hispanica (Abecedarium Latinum)
|
18

|
ita-Latn
|
https://glottolog.org/resource/languoid/id/ital1282[ital1282]
+++<br>+++
https://iso639-3.sil.org/code/ita[ita]
+++<br>+++ https://www.wikidata.org/wiki/Q652[Q652]
|
Lingua Italiana (Abecedarium Latinum)
|
15

|
gle-Latn
|
https://glottolog.org/resource/languoid/id/iris1253[iris1253]
+++<br>+++
https://iso639-3.sil.org/code/gle[gle]
+++<br>+++ https://www.wikidata.org/wiki/Q9142[Q9142]
|
Lingua Hibernica (Abecedarium Latinum)
|
9

|
swe-Latn
|
https://glottolog.org/resource/languoid/id/swed1254[swed1254]
+++<br>+++
https://iso639-3.sil.org/code/swe[swe]
+++<br>+++ https://www.wikidata.org/wiki/Q9027[Q9027]
|
Lingua Suecica (Abecedarium Latinum)
|
13

|
sqi-Latn
|
https://glottolog.org/resource/languoid/id/alba1267[alba1267]
+++<br>+++
https://iso639-3.sil.org/code/sqi[sqi]
+++<br>+++ https://www.wikidata.org/wiki/Q8748[Q8748]
|
Macrolingua Albanica (/Abecedarium Latinum/)
|
2

|
pol-Latn
|
https://glottolog.org/resource/languoid/id/poli1260[poli1260]
+++<br>+++
https://iso639-3.sil.org/code/pol[pol]
+++<br>+++ https://www.wikidata.org/wiki/Q809[Q809]
|
Lingua Polonica (Abecedarium Latinum)
|
13

|
fin-Latn
|
https://glottolog.org/resource/languoid/id/finn1318[finn1318]
+++<br>+++
https://iso639-3.sil.org/code/fin[fin]
+++<br>+++ https://www.wikidata.org/wiki/Q1412[Q1412]
|
Lingua Finnica (Abecedarium Latinum)
|
13

|
ron-Latn
|
https://glottolog.org/resource/languoid/id/roma1327[roma1327]
+++<br>+++
https://iso639-3.sil.org/code/ron[ron]
+++<br>+++ https://www.wikidata.org/wiki/Q7913[Q7913]
|
Lingua Dacoromanica (Abecedarium Latinum)
|
9

|
vie-Latn
|
https://glottolog.org/resource/languoid/id/viet1252[viet1252]
+++<br>+++
https://iso639-3.sil.org/code/vie[vie]
+++<br>+++ https://www.wikidata.org/wiki/Q9199[Q9199]
|
Lingua Vietnamensis (Abecedarium Latinum)
|
10

|
cat-Latn
|
https://glottolog.org/resource/languoid/id/stan1289[stan1289]
+++<br>+++
https://iso639-3.sil.org/code/cat[cat]
+++<br>+++ https://www.wikidata.org/wiki/Q7026[Q7026]
|
Lingua Catalana (Abecedarium Latinum)
|
18

|
ukr-Cyrl
|
https://glottolog.org/resource/languoid/id/ukra1253[ukra1253]
+++<br>+++
https://iso639-3.sil.org/code/ukr[ukr]
+++<br>+++ https://www.wikidata.org/wiki/Q8798[Q8798]
|
Lingua Ucrainica (Abecedarium Cyrillicum)
|
12

|
bul-Cyrl
|
https://glottolog.org/resource/languoid/id/bulg1262[bulg1262]
+++<br>+++
https://iso639-3.sil.org/code/bul[bul]
+++<br>+++ https://www.wikidata.org/wiki/Q7918[Q7918]
|
Lingua Bulgarica (Abecedarium Cyrillicum)
|
9

|
slv-Latn
|
https://glottolog.org/resource/languoid/id/slov1268[slov1268]
+++<br>+++
https://iso639-3.sil.org/code/slv[slv]
+++<br>+++ https://www.wikidata.org/wiki/Q9063[Q9063]
|
Lingua Slovena (Abecedarium Latinum)
|
10

|
war-Latn
|
https://glottolog.org/resource/languoid/id/wara1300[wara1300]
+++<br>+++
https://iso639-3.sil.org/code/war[war]
+++<br>+++ https://www.wikidata.org/wiki/Q34279[Q34279]
|
/Waray language/ (Abecedarium Latinum)
|
1

|
nob-Latn
|
https://glottolog.org/resource/languoid/id/norw1259[norw1259]
+++<br>+++
https://iso639-3.sil.org/code/nob[nob]
+++<br>+++ https://www.wikidata.org/wiki/Q25167[Q25167]
|
/Bokmål/ (Abecedarium Latinum)
|
10

|
ces-Latn
|
https://glottolog.org/resource/languoid/id/czec1258[czec1258]
+++<br>+++
https://iso639-3.sil.org/code/ces[ces]
+++<br>+++ https://www.wikidata.org/wiki/Q9056[Q9056]
|
Lingua Bohemica (Abecedarium Latinum)
|
13

|
dan-Latn
|
https://glottolog.org/resource/languoid/id/dani1285[dani1285]
+++<br>+++
https://iso639-3.sil.org/code/dan[dan]
+++<br>+++ https://www.wikidata.org/wiki/Q9035[Q9035]
|
Lingua Danica (Abecedarium Latinum)
|
14

|
jpn-Jpan
|
https://glottolog.org/resource/languoid/id/nucl1643[nucl1643]
+++<br>+++
https://iso639-3.sil.org/code/jpn[jpn]
+++<br>+++ https://www.wikidata.org/wiki/Q5287[Q5287]
|
Lingua Iaponica (Scriptura Iaponica)
|
17

|
nno-Latn
|
https://glottolog.org/resource/languoid/id/norw1262[norw1262]
+++<br>+++
https://iso639-3.sil.org/code/nno[nno]
+++<br>+++ https://www.wikidata.org/wiki/Q25164[Q25164]
|
/Nynorsk/ (Abecedarium Latinum)
|
4

|
mal-Mlym
|
https://glottolog.org/resource/languoid/id/mala1464[mala1464]
+++<br>+++
https://iso639-3.sil.org/code/mal[mal]
+++<br>+++ https://www.wikidata.org/wiki/Q36236[Q36236]
|
Lingua Malabarica (/Malayalam script/)
|
5

|
ind-Latn
|
https://glottolog.org/resource/languoid/id/indo1316[indo1316]
+++<br>+++
https://iso639-3.sil.org/code/ind[ind]
+++<br>+++ https://www.wikidata.org/wiki/Q9240[Q9240]
|
Lingua Indonesiana (Abecedarium Latinum)
|
15

|
fas-Zzzz
|

+++<br>+++
https://iso639-3.sil.org/code/fas[fas]
+++<br>+++ https://www.wikidata.org/wiki/Q9168[Q9168]
|
Macrolingua Persica (//Abecedarium Arabicum//)
|
15

|
hun-Latn
|
https://glottolog.org/resource/languoid/id/hung1274[hung1274]
+++<br>+++
https://iso639-3.sil.org/code/hun[hun]
+++<br>+++ https://www.wikidata.org/wiki/Q9067[Q9067]
|
Lingua Hungarica (Abecedarium Latinum)
|
9

|
eus-Latn
|
https://glottolog.org/resource/languoid/id/basq1248[basq1248]
+++<br>+++
https://iso639-3.sil.org/code/eus[eus]
+++<br>+++ https://www.wikidata.org/wiki/Q8752[Q8752]
|
Lingua Vasconica (Abecedarium Latinum)
|
9

|
cym-Latn
|
https://glottolog.org/resource/languoid/id/wels1247[wels1247]
+++<br>+++
https://iso639-3.sil.org/code/cym[cym]
+++<br>+++ https://www.wikidata.org/wiki/Q9309[Q9309]
|
Lingua Cambrica (Abecedarium Latinum)
|
5

|
glg-Latn
|
https://glottolog.org/resource/languoid/id/gali1258[gali1258]
+++<br>+++
https://iso639-3.sil.org/code/glg[glg]
+++<br>+++ https://www.wikidata.org/wiki/Q9307[Q9307]
|
Lingua Gallaica (Abecedarium Latinum)
|
9

|
slk-Latn
|
https://glottolog.org/resource/languoid/id/slov1269[slov1269]
+++<br>+++
https://iso639-3.sil.org/code/slk[slk]
+++<br>+++ https://www.wikidata.org/wiki/Q9058[Q9058]
|
Lingua Slovaca (Abecedarium Latinum)
|
4

|
epo-Latn
|
https://glottolog.org/resource/languoid/id/espe1235[espe1235]
+++<br>+++
https://iso639-3.sil.org/code/epo[epo]
+++<br>+++ https://www.wikidata.org/wiki/Q143[Q143]
|
Lingua Esperantica (Abecedarium Latinum)
|
14

|
msa-Zzzz
|

+++<br>+++
https://iso639-3.sil.org/code/msa[msa]
+++<br>+++ https://www.wikidata.org/wiki/Q9237[Q9237]
|
Macrolingua Malayana (?)
|
9

|
est-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/est[est]
+++<br>+++ https://www.wikidata.org/wiki/Q9072[Q9072]
|
Macrolingua Estonica (Abecedarium Latinum)
|
7

|
hrv-Latn
|
https://glottolog.org/resource/languoid/id/croa1245[croa1245]
+++<br>+++
https://iso639-3.sil.org/code/hrv[hrv]
+++<br>+++ https://www.wikidata.org/wiki/Q6654[Q6654]
|
Lingua Croatica (Abecedarium Latinum)
|
7

|
tur-Latn
|
https://glottolog.org/resource/languoid/id/nucl1301[nucl1301]
+++<br>+++
https://iso639-3.sil.org/code/tur[tur]
+++<br>+++ https://www.wikidata.org/wiki/Q256[Q256]
|
Lingua Turcica (Abecedarium Latinum)
|
11

|
oci-Latn
|
https://glottolog.org/resource/languoid/id/occi1239[occi1239]
+++<br>+++
https://iso639-3.sil.org/code/oci[oci]
+++<br>+++ https://www.wikidata.org/wiki/Q14185[Q14185]
|
Lingua Occitana (Abecedarium Latinum)
|
4

|
bre-Latn
|
https://glottolog.org/resource/languoid/id/bret1244[bret1244]
+++<br>+++
https://iso639-3.sil.org/code/bre[bre]
+++<br>+++ https://www.wikidata.org/wiki/Q12107[Q12107]
|
Lingua Britonica (Abecedarium Latinum)
|
4

|
arz-Latn
|
https://glottolog.org/resource/languoid/id/egyp1253[egyp1253]
+++<br>+++
https://iso639-3.sil.org/code/arz[arz]
+++<br>+++ https://www.wikidata.org/wiki/Q29919[Q29919]
|
/Egyptian Arabic/ (/Abecedarium Arabicum/)
|
3

|
afr-Latn
|
https://glottolog.org/resource/languoid/id/afri1274[afri1274]
+++<br>+++
https://iso639-3.sil.org/code/afr[afr]
+++<br>+++ https://www.wikidata.org/wiki/Q14196[Q14196]
|
Lingua Batava Capitensis (Abecedarium Latinum)
|
4

|
ltz-Latn
|
https://glottolog.org/resource/languoid/id/luxe1241[luxe1241]
+++<br>+++
https://iso639-3.sil.org/code/ltz[ltz]
+++<br>+++ https://www.wikidata.org/wiki/Q9051[Q9051]
|
Lingua Luxemburgensis (Abecedarium Latinum)
|
4

|
sco-Latn
|
https://glottolog.org/resource/languoid/id/scot1243[scot1243]
+++<br>+++
https://iso639-3.sil.org/code/sco[sco]
+++<br>+++ https://www.wikidata.org/wiki/Q14549[Q14549]
|
Lingua Scotica quae Teutonica (Abecedarium Latinum)
|
4

|
bar-Latn
|
https://glottolog.org/resource/languoid/id/bava1246[bava1246]
+++<br>+++
https://iso639-3.sil.org/code/bar[bar]
+++<br>+++ https://www.wikidata.org/wiki/Q29540[Q29540]
|
Lingua Bavarica (Abecedarium Latinum)
|
1

|
arg-Latn
|
https://glottolog.org/resource/languoid/id/arag1245[arag1245]
+++<br>+++
https://iso639-3.sil.org/code/arg[arg]
+++<br>+++ https://www.wikidata.org/wiki/Q8765[Q8765]
|
Lingua Aragonensis (Abecedarium Latinum)
|
1

|
zho-Hant
|

+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q18130932[Q18130932]
|
//Traditional Chinese// (/ISO 15924 Hant/)
|
12

|
gsw-Latn
|
https://glottolog.org/resource/languoid/id/swis1247[swis1247]
+++<br>+++
https://iso639-3.sil.org/code/gsw[gsw]
+++<br>+++ https://www.wikidata.org/wiki/Q131339[Q131339]
|
Dialecti Alemannicae (Abecedarium Latinum)
|
1

|
isl-Latn
|
https://glottolog.org/resource/languoid/id/icel1247[icel1247]
+++<br>+++
https://iso639-3.sil.org/code/isl[isl]
+++<br>+++ https://www.wikidata.org/wiki/Q294[Q294]
|
Lingua Islandica (Abecedarium Latinum)
|
6

|
vec-Latn
|
https://glottolog.org/resource/languoid/id/vene1258[vene1258]
+++<br>+++
https://iso639-3.sil.org/code/vec[vec]
+++<br>+++ https://www.wikidata.org/wiki/Q32724[Q32724]
|
Lingua Veneta (Abecedarium Latinum)
|
1

|
pms-Latn
|
https://glottolog.org/resource/languoid/id/piem1238[piem1238]
+++<br>+++
https://iso639-3.sil.org/code/pms[pms]
+++<br>+++ https://www.wikidata.org/wiki/Q15085[Q15085]
|
Lingua Pedemontana (Abecedarium Latinum)
|
1

|
scn-Latn
|
https://glottolog.org/resource/languoid/id/sici1248[sici1248]
+++<br>+++
https://iso639-3.sil.org/code/scn[scn]
+++<br>+++ https://www.wikidata.org/wiki/Q33973[Q33973]
|
Lingua Sicula (Abecedarium Latinum)
|
3

|
srd-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/srd[srd]
+++<br>+++ https://www.wikidata.org/wiki/Q33976[Q33976]
|
Macrolingua Sarda (Abecedarium Latinum)
|
2

|
gla-Latn
|
https://glottolog.org/resource/languoid/id/scot1245[scot1245]
+++<br>+++
https://iso639-3.sil.org/code/gla[gla]
+++<br>+++ https://www.wikidata.org/wiki/Q9314[Q9314]
|
Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum)
|
3

|
lim-Latn
|
https://glottolog.org/resource/languoid/id/limb1263[limb1263]
+++<br>+++
https://iso639-3.sil.org/code/lim[lim]
+++<br>+++ https://www.wikidata.org/wiki/Q102172[Q102172]
|
Lingua Limburgica (Abecedarium Latinum)
|
2

|
wln-Latn
|
https://glottolog.org/resource/languoid/id/wall1255[wall1255]
+++<br>+++
https://iso639-3.sil.org/code/wln[wln]
+++<br>+++ https://www.wikidata.org/wiki/Q34219[Q34219]
|
Lingua Vallonica
|
3

|
srp-Latn
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q21161949[Q21161949]
|
/Serbian/ (Abecedarium Latinum)
|
3

|
wol-Latn
|
https://glottolog.org/resource/languoid/id/nucl1347[nucl1347]
+++<br>+++
https://iso639-3.sil.org/code/wol[wol]
+++<br>+++ https://www.wikidata.org/wiki/Q34257[Q34257]
|
/Wolof language/ (Abecedarium Latinum)
|
1

|
frp-Latn
|
https://glottolog.org/resource/languoid/id/fran1260[fran1260]
+++<br>+++
https://iso639-3.sil.org/code/frp[frp]
+++<br>+++ https://www.wikidata.org/wiki/Q15087[Q15087]
|
Lingua Arpitanica
|
1

|
wuu-Zyyy
|
https://glottolog.org/resource/languoid/id/wuch1236[wuch1236]
+++<br>+++
https://iso639-3.sil.org/code/wuu[wuu]
+++<br>+++ https://www.wikidata.org/wiki/Q34290[Q34290]
|
//Macrolingua Wu// (/ISO 15924 Zyyy/)
|
5

|
srp-Cyrl
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q9299[Q9299]
|
Lingua Serbica (Abecedarium Cyrillicum)
|
13

|
urd-Arab
|
https://glottolog.org/resource/languoid/id/urdu1245[urdu1245]
+++<br>+++
https://iso639-3.sil.org/code/urd[urd]
+++<br>+++ https://www.wikidata.org/wiki/Q1617[Q1617]
|
Lingua Urdu (/Abecedarium Arabicum/)
|
11

|
gan-Zyyy
|
https://glottolog.org/resource/languoid/id/ganc1239[ganc1239]
+++<br>+++
https://iso639-3.sil.org/code/gan[gan]
+++<br>+++ https://www.wikidata.org/wiki/Q33475[Q33475]
|
Lingua Gan (/ISO 15924 Zyyy/)
|
1

|
lit-Latn
|
https://glottolog.org/resource/languoid/id/lith1251[lith1251]
+++<br>+++
https://iso639-3.sil.org/code/lit[lit]
+++<br>+++ https://www.wikidata.org/wiki/Q9083[Q9083]
|
Lingua Lithuanica (Abecedarium Latinum)
|
8

|
hbs-Latn
|
https://glottolog.org/resource/languoid/id/sout1528[sout1528]
+++<br>+++
https://iso639-3.sil.org/code/hbs[hbs]
+++<br>+++ https://www.wikidata.org/wiki/Q9301[Q9301]
|
Macrolingua Serbocroatica (Abecedarium Latinum)
|
5

|
lav-Latn
|
https://glottolog.org/resource/languoid/id/latv1249[latv1249]
+++<br>+++
https://iso639-3.sil.org/code/lav[lav]
+++<br>+++ https://www.wikidata.org/wiki/Q9078[Q9078]
|
Macrolingua Lettonica (Abecedarium Latinum)
|
6

|
bos-Latn
|
https://glottolog.org/resource/languoid/id/bosn1245[bosn1245]
+++<br>+++
https://iso639-3.sil.org/code/bos[bos]
+++<br>+++ https://www.wikidata.org/wiki/Q9303[Q9303]
|
Lingua Bosnica (Abecedarium Latinum)
|
6

|
azb-Arab
|
https://glottolog.org/resource/languoid/id/sout2697[sout2697]
+++<br>+++
https://iso639-3.sil.org/code/azb[azb]
+++<br>+++ https://www.wikidata.org/wiki/Q3449805[Q3449805]
|
/South Azerbaijani/ (/Abecedarium Arabicum/)
|
1

|
jav-Latn
|
https://glottolog.org/resource/languoid/id/java1254[java1254]
+++<br>+++
https://iso639-3.sil.org/code/jav[jav]
+++<br>+++ https://www.wikidata.org/wiki/Q33549[Q33549]
|
Lingua Iavanica (Abecedarium Latinum)
|
2

|
ell-Grek
|
https://glottolog.org/resource/languoid/id/mode1248[mode1248]
+++<br>+++
https://iso639-3.sil.org/code/ell[ell]
+++<br>+++ https://www.wikidata.org/wiki/Q36510[Q36510]
|
Lingua Neograeca (Alphabetum Graecum)
|
10

|
sun-Latn
|
https://glottolog.org/resource/languoid/id/sund1252[sund1252]
+++<br>+++
https://iso639-3.sil.org/code/sun[sun]
+++<br>+++ https://www.wikidata.org/wiki/Q34002[Q34002]
|
/Sundanese language/ (Abecedarium Latinum)
|
1

|
fry-Latn
|
https://glottolog.org/resource/languoid/id/west2354[west2354]
+++<br>+++
https://iso639-3.sil.org/code/fry[fry]
+++<br>+++ https://www.wikidata.org/wiki/Q27175[Q27175]
|
Lingua Frisice occidentalis (Abecedarium Latinum)
|
10

|
jam-Latn
|
https://glottolog.org/resource/languoid/id/jama1262[jama1262]
+++<br>+++
https://iso639-3.sil.org/code/jam[jam]
+++<br>+++ https://www.wikidata.org/wiki/Q35939[Q35939]
|
Lingua creola Iamaicana (Abecedarium Latinum)
|
1

|
che-Cyrl
|
https://glottolog.org/resource/languoid/id/chec1245[chec1245]
+++<br>+++
https://iso639-3.sil.org/code/che[che]
+++<br>+++ https://www.wikidata.org/wiki/Q33350[Q33350]
|
Lingua Tsetsenica (Abecedarium Cyrillicum)
|
2

|
bel-Cyrl
|
https://glottolog.org/resource/languoid/id/bela1254[bela1254]
+++<br>+++
https://iso639-3.sil.org/code/bel[bel]
+++<br>+++ https://www.wikidata.org/wiki/Q9091[Q9091]
|
Lingua Ruthenica Alba (Abecedarium Cyrillicum)
|
6

|
kab-Latn
|
https://glottolog.org/resource/languoid/id/kaby1243[kaby1243]
+++<br>+++
https://iso639-3.sil.org/code/kab[kab]
+++<br>+++ https://www.wikidata.org/wiki/Q35853[Q35853]
|
/Kabyle language/ (Abecedarium Latinum)
|
2

|
fao-Latn
|
https://glottolog.org/resource/languoid/id/faro1244[faro1244]
+++<br>+++
https://iso639-3.sil.org/code/fao[fao]
+++<br>+++ https://www.wikidata.org/wiki/Q25258[Q25258]
|
Lingua Faeroensis (Abecedarium Latinum)
|
1

|
mar-Deva
|
https://glottolog.org/resource/languoid/id/mara1378[mara1378]
+++<br>+++
https://iso639-3.sil.org/code/mar[mar]
+++<br>+++ https://www.wikidata.org/wiki/Q1571[Q1571]
|
Lingua Marathica (Devanāgarī)
|
5

|
ina-Latn
|
https://glottolog.org/resource/languoid/id/inte1239[inte1239]
+++<br>+++
https://iso639-3.sil.org/code/ina[ina]
+++<br>+++ https://www.wikidata.org/wiki/Q35934[Q35934]
|
Interlingua (Abecedarium Latinum)
|
1

|
ile-Latn
|
https://glottolog.org/resource/languoid/id/inte1260[inte1260]
+++<br>+++
https://iso639-3.sil.org/code/ile[ile]
+++<br>+++ https://www.wikidata.org/wiki/Q35850[Q35850]
|
Lingua Occidental (Abecedarium Latinum)
|
1

|
zul-Latn
|
https://glottolog.org/resource/languoid/id/zulu1248[zulu1248]
+++<br>+++
https://iso639-3.sil.org/code/zul[zul]
+++<br>+++ https://www.wikidata.org/wiki/Q10179[Q10179]
|
Lingua Zuluana (Abecedarium Latinum)
|
1

|===

==== Rēs interlinguālibus: 8
Rēs::
  /Wiki QID/:::
    Rēs interlinguālibus::::
      /rēgulam/;;
        Q[1-9]\d*

      ix_hxlix;;
        ix_wikiq

      ix_hxlvoc;;
        v_wiki_q

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/Wiki QID/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.</span>+++

  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wikip577

      ix_hxlvoc;;
        v_wiki_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Date or point in time when a work was first published or released</span>+++

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wikip123

      ix_hxlvoc;;
        v_wiki_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software</span>+++

  /scope and content/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P7535[P7535]

      ix_hxlix;;
        ix_wikip7535

      ix_hxlvoc;;
        v_wiki_p_7535

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/scope and content/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">a summary statement providing an overview of the archival collection</span>+++

  scrīptor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P50[P50]

      ix_hxlix;;
        ix_wikip50

      ix_hxlvoc;;
        v_wiki_p_50

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">scrīptor</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Main creator(s) of a written work (use on works, not humans)</span>+++

  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wikip393

      ix_hxlvoc;;
        v_wiki_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">number of an edition (first, second, ... as 1, 2, ...) or event</span>+++

  Numerordĭnātĭo:::
    Rēs interlinguālibus::::
      ix_hxlix;;
        ix_n1603

      ix_hxlvoc;;
        v_n1603

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">Numerordĭnātĭo</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">a generic strategy of arranging numbers in an taxonomy-like explicit way</span>+++

  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wikip2479

      ix_hxlvoc;;
        v_wiki_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">SPDX license identifier</span>+++


<<<

== Archīa

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    **Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ an static work), then the actual groundbreaking difference on the workflow used to generate every dictionaries on Cōdex such as this one are the following fact: **we provide machine readable formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with terminology translations.
    +++<br><br>+++
    **Practical implication**: the text documents on _Archīa prō cōdice_ (literal English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an impact.


=== Archīa prō dictiōnāriīs: 4


==== 1603_44_101.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_101.no1.tm.hxl.csv[1603_44_101.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container/



==== 1603_44_101.no11.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_101.no11.tm.hxl.csv[1603_44_101.no11.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container (expanded with terminology translations)/



==== 1603_44_101.wikiq.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_101.wikiq.tm.hxl.csv[1603_44_101.wikiq.tm.hxl.csv]
  /reference URL/@eng-Latn:::
    https://hxltm.etica.ai/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    HXLTM dialect of HXLStandard on CSV RFC 4180. wikiq means #item+conceptum+codicem are strictly Wikidata QIDs.



==== 1603_44_101.no11.tbx

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_101.no11.tbx[1603_44_101.no11.tbx]
  /reference URL/@eng-Latn:::
    http://www.terminorgs.net/downloads/TBX_Basic_Version_3.1.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    TBX-Basic is a terminological markup language (TML) that is a lighter version of TBX-Default, the TML that is defined in ISO 30042. TBX-Basic is designed for the localization industry and is based on information from surveys and studies that were conducted by the LISA Term SIG about the types of terminology data that the localization industry requires.



==== 1603_44_101.no11.tmx

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_101.no11.tmx[1603_44_101.no11.tmx]
  /reference URL/@eng-Latn:::
    https://www.gala-global.org/tmx-14b

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    The purpose of the Translation Memory eXchange format (TMX) format is to provide a standard method to describe translation memory data that is being exchanged among tools and/or translation vendors, while introducing little or no loss of critical data during the process



=== Archīa prō cōdice: 1


==== 1603_44_101.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_101.mul-Latn.codex.adoc[1603_44_101.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.



== Externīs
=== Dictiōnāria necessitātibus
==== [1603:44:86] //Dictiōnāria basibus dē tortūrīs//
Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:44:86

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q132781[Q132781]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria basibus dē tortūrīs//




<<<


<<<

[.text-center]

Dictiōnāria initiīs

<<<

== /Dictiōnāria basibus dē sceleribus contrā persōnam/
<<<

[id='100']
=== [`100`] /psychological, generic/@eng-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /psychological, generic/@eng-Latn





[id='100_1']
==== [`100_1`] /blackmail/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q34284[Q34284]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /blackmail || coercion based on threat of revealing information/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">ابتزاز</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Շորթագործություն</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">ব্ল্যাকমেইল</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Шантаж</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">भयदोहन</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">סחיטה</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">கப்பம்</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">การรีดเอาทรัพย์</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">勒索</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">chantagem</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">blackmail</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">chantage</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">chantage</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Chantage</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">chantaje</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">estorsione</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">utpressning</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Szantaż</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">kiristys</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Șantaj</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Tống tiền</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">xantatge</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Шантаж</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Шантаж</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Izsiljevanje</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">utpressing</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">vydírání</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">afpresning</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">ゆすり</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">pemerasan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">شانتاژ</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">zsarolás</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Xantaia</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">ĉantaĝo</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">Peras ugut</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">Šantaaž</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Şantaj</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">уцена</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">بلیک میل</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Šantažas</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">εκβιασμός</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Sjantaazje</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">Шантаж</span>+++





<<<

[id='300']
=== [`300`] Mercatus hominum

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q181784[Q181784]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /human trafficking || trade of humans for the purpose of forced labor, sexual slavery, or commercial sexual exploitation for the trafficker or others/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">الاتجار بالبشر</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">թրաֆիքինգ</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">মানব পাচার</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">торговля людьми</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">मानव तस्करी</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">인신매매</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">סחר בבני אדם</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Mercatus hominum</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">மாந்தக் கடத்துகை</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">人口贩卖</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">tráfico de pessoas</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">human trafficking</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">trafic d'êtres humains</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">mensenhandel</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Menschenhandel</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">trata de personas</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">traffico di esseri umani</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">gáinneáil ar dhaoine</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">människohandel</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">trafikim njerëzor</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">handel ludźmi</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">ihmiskauppa</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">trafic de persoane</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">buôn người</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">tràfic de persones</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">торгівля людьми</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">трафик на хора</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">trgovina z ljudmi</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">menneskehandel</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">obchod s lidmi</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">menneskehandel</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">人身売買</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">menneskehandel</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">perdagangan manusia</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">قاچاق انسان</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">emberkereskedelem</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">gizakien salerosketa</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">masnachu pobl</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">tráfico de persoas</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">obchodovanie s ľuďmi</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">homokomerco</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">pemerdagangan manusia</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">inimkaubandus</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">trgovanje ljudima</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">İnsan ticareti</span>+++

  Lingua Britonica (Abecedarium Latinum):::
    +++<span lang="br">trafikerezh tud</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">HU</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">人口販賣</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">mansal</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">trgovina ljudima</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">人口贩卖</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">трговина људима</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">انسانی بازارکاری</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">prekyba žmonėmis</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">cilvēku tirdzniecība</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">ανθρώπινη εμπορία</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">minskehannel</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">гандаль людзьмі</span>+++





<<<

[id='400']
=== [`400`] mors voluntaria

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q10737[Q10737]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /suicide || intentional act of causing one's own death/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">انتحار</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">ինքնասպանություն</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">আত্মহত্যা</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">самоубийство</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">आत्महत्या</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಆತ್ಮಹತ್ಯೆ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">자살</span>+++

  Lingua Sinica classica (/ISO 15924 Hant/):::
    +++<span lang="lzh">自殺</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">התאבדות</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">mors voluntaria</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">தற்கொலை</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">ఆత్మహత్య</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">การฆ่าตัวตาย</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">自殺</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">suicídio</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">suicide</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">suicide</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">zelfdoding</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Suizid</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">suicidio</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">suicidio</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">Féinmharú</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">självmord</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">Vetëvrasja</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">samobójstwo</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">itsemurha</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">sinucidere</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">tự sát</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">suïcidi</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">самогубство</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">самоубийство</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">samomor</span>+++

  /Waray language/ (Abecedarium Latinum):::
    +++<span lang="war">Unay</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">selvmord</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">sebevražda</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">selvmord</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">自殺</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">sjølvmord</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">ആത്മഹത്യ</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">bunuh diri</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">خودکشی</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">öngyilkosság</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">suizidio</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">hunanladdiad</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">suicidio</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">samovražda</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">sinmortigo</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">Bunuh diri</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">enesetapp</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">samoubojstvo</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">intihar</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">Suicidi</span>+++

  Lingua Britonica (Abecedarium Latinum):::
    +++<span lang="br">Emlazh</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Selfmoord</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Suizid</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">suicide</span>+++

  Lingua Bavarica (Abecedarium Latinum):::
    +++<span lang="bar">Freidoud</span>+++

  Lingua Aragonensis (Abecedarium Latinum):::
    +++<span lang="an">suicidio</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">自殺</span>+++

  Dialecti Alemannicae (Abecedarium Latinum):::
    +++<span lang="gsw">Suizid</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Sjálfsmorð</span>+++

  Lingua Veneta (Abecedarium Latinum):::
    +++<span lang="vec">suicìdio</span>+++

  Lingua Sicula (Abecedarium Latinum):::
    +++<span lang="scn">suicidiu</span>+++

  Macrolingua Sarda (Abecedarium Latinum):::
    +++<span lang="sc">Suitzìdiu</span>+++

  Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum):::
    +++<span lang="gd">fèin-mhurt</span>+++

  Lingua Limburgica (Abecedarium Latinum):::
    +++<span lang="li">Zelfmaord</span>+++

  Lingua Vallonica:::
    +++<span lang="wa">Metaedje a fén d' lu-minme</span>+++

  /Wolof language/ (Abecedarium Latinum):::
    +++<span lang="wo">Xaru</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">自杀</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">самоубиство</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">خود کشی</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Savižudybė</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Samoubistvo</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">pašnāvība</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Samoubistvo</span>+++

  /South Azerbaijani/ (/Abecedarium Arabicum/):::
    +++<span lang="azb">اینتیحار</span>+++

  Lingua Iavanica (Abecedarium Latinum):::
    +++<span lang="jv">Nglalu</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">αυτοκτονία</span>+++

  /Sundanese language/ (Abecedarium Latinum):::
    +++<span lang="su">Nelasan maneh</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Selsmoard</span>+++

  Lingua creola Iamaicana (Abecedarium Latinum):::
    +++<span lang="jam">Suisaid</span>+++

  Lingua Tsetsenica (Abecedarium Cyrillicum):::
    +++<span lang="ce">Ша-шен дер</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">самагубства</span>+++

  /Kabyle language/ (Abecedarium Latinum):::
    +++<span lang="kab">Anɣiman</span>+++

  Lingua Faeroensis (Abecedarium Latinum):::
    +++<span lang="fo">Sjálvmorð</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">आत्महत्या</span>+++

  Lingua Occidental (Abecedarium Latinum):::
    +++<span lang="ie">Suicidie</span>+++





<<<

[id='500']
=== [`500`] Homicidium

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q149086[Q149086]

  /scope and content/@eng-Latn:::
    /#TODO get more itens from https://en.wikipedia.org/wiki/Template:Homicide#/@eng-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /homicide (generic) || killing of a human being by another human being/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">جريمة قتل</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">մարդասպանություն</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">নরহত্যা</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">гомицид</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">मानव हत्या</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">살인</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">הריגה</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Homicidium</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">கொலை</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">మానవ హత్య</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">杀人</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">homicídio</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">homicide</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">homicide</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">levensberoving</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Tötung eines Menschen</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">homicidio</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">omicidio</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">dúnmharú</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">dråp</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">zabójstwo</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">henkirikos</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">omor</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">sát hại</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">homicidi</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">вбивство</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">убийство</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">umor</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">drap</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">zabití člověka člověkem</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">drab</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">殺人</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">നരഹത്യ</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">pembunuhan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">قتل</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">emberölés</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">giza hilketa</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">dynladdiad</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">homicidio</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">hommortigo</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">pembunuhan</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">mõrv</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Ubojstvo</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">cinayet</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">Omicidi</span>+++

  /Egyptian Arabic/ (/Abecedarium Arabicum/):::
    +++<span lang="arz">جريمه قتل</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Muerd</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">homicide</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">殺害</span>+++

  Lingua Sicula (Abecedarium Latinum):::
    +++<span lang="scn">ammazzatina</span>+++

  Macrolingua Sarda (Abecedarium Latinum):::
    +++<span lang="sc">mortorzu</span>+++

  Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum):::
    +++<span lang="gd">murt duine</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">homicid</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">殺人</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">хомицид</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">قتل</span>+++

  Lingua Gan (/ISO 15924 Zyyy/):::
    +++<span lang="gan">殺人</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Žmogžudys</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">cilvēka nonāvēšana</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Ubistvo</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">ανθρωποκτονία</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">забойства</span>+++

  /Kabyle language/ (Abecedarium Latinum):::
    +++<span lang="kab">Timenɣiwt</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">खून</span>+++





[id='500_1']
==== [`500_1`] Caedes

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q132821[Q132821]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /murder || unlawful killing of a human with malice aforethought/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">قتل عمد</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">սպանություն</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">খুন</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">убийство</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">हत्या</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಕೊಲೆ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">모살</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">רצח</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Caedes</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">கொலை</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">హత్య</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">การฆ่าคน</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">謀殺</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">assassínio</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">murder</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">meurtre</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">moord</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Mord</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">asesinato</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">omicidio volontario</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">dúnmharú</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">mord</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">morderstwo</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">murha</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">crimă</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">giết người</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">assassinat</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">умисне вбивство</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">убийство</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">umor</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">drap</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">vražda</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">mord</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">謀殺</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">drap</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">കൊലപാതകം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">pembunuhan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">آدمکشی</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">gyilkosság</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">erailketa</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">llofruddiaeth</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">asasinato</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">vražda</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">murdo</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">pembunuhan</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">mõrv</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Teško ubojstvo</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">cinayet</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">assassinat</span>+++

  /Egyptian Arabic/ (/Abecedarium Arabicum/):::
    +++<span lang="arz">قتل</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">moord</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Muerd</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">murther</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">謀殺</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Morð</span>+++

  Lingua Pedemontana (Abecedarium Latinum):::
    +++<span lang="pms">sassinament</span>+++

  Lingua Sicula (Abecedarium Latinum):::
    +++<span lang="scn">omicidiu</span>+++

  Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum):::
    +++<span lang="gd">murt</span>+++

  Lingua Vallonica:::
    +++<span lang="wa">moude</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">ubistvo</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">谋杀</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">убиство</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">قتل</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">nužudymas</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">ubistvo</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">slepkavība</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Ubistvo</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">δολοφονία</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">moard</span>+++

  Lingua Tsetsenica (Abecedarium Cyrillicum):::
    +++<span lang="ce">Дер</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">забойства</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">खून</span>+++

  Interlingua (Abecedarium Latinum):::
    +++<span lang="ia">assassinato</span>+++





[id='500_2']
==== [`500_2`] /manslaughter/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q3882220[Q3882220]

  /scope and content/@eng-Latn:::
    /#TODO some languages use _negligent homicide_ and _manslaughter_ as synonymous. Not ideal#/@eng-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /manslaughter || crime of killing of a human being by another human being, less serious than murder/@eng-Latn

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">непредумышленное убийство</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">맨슬로터</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">הריגה</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">การฆาตกรรม</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">誤殺</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Crime culposo</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">manslaughter</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">homicide</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">doodslag</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Totschlag</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">homicidio preterintencional</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">omicidio preterintenzionale</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">Dúnorgain</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">dråp</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">tappo</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">ngộ sát</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">homicidi preterintencional</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Uboj</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">zabití</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">manddrab</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">故殺</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Pembunuhan tidak berencana</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">قتل شبه عمد</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">hommortigo</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">一般殺人罪</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Manndráp</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">убиство</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">nogalināšana bez nodoma</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">φόνος</span>+++





[id='500_2_1']
===== [`500_2_1`] /voluntary manslaughter/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1295558[Q1295558]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /voluntary manslaughter || homicide where the offender had no prior intent to kill and acted during "the heat of passion"/@eng-Latn

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">убийство, совершённое в состоянии аффекта</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">우발적 살인</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">蓄意誤殺</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">voluntary manslaughter</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">homicide volontaire</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">vrijwillige doodslag</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Voluntary Manslaughter</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">homicidio voluntario</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">omicidio colposo</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">zabójstwo w afekcie</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">homicidi voluntari</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">frivilligt dødslag</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">故意故殺</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">vola hommortigo</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">蓄意誤殺</span>+++





[id='500_2_2']
===== [`500_2_2`] /involuntary manslaughter/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q118322[Q118322]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /involuntary manslaughter || unlawful killing of another human with no intent to kill/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">قتل خطأ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">непредумышленной убийство</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">살인</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">הריגה</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">誤殺</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">involuntary manslaughter</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">violences volontaires ayant entraîné la mort sans l'intention de la donner</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">doodslag (Engeland en Wales)</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Involuntary manslaughter</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">homicidio involuntario</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">omicidio preterintenzionale</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">Dúnorgain</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">dråp</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">Tappo</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">homicidi involuntari</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">uboj</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">zabití</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">uagtsomt manddrab</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">非故意故殺</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">قتل غیرعمد</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">emberölés</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">neintenca mortigo</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Manndráp</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">убиство</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">δολοφονία χωρίς πρόθεση</span>+++





[id='500_3']
==== [`500_3`] /negligent homicide/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q641449[Q641449]

  /scope and content/@eng-Latn:::
    /#TODO some languages use _negligent homicide_ and _manslaughter_ as synonymous. Not ideal#/@eng-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /negligent homicide || homicide caused by the negligence of another/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">قتل باهمال</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">причинение смерти по неосторожности</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">과실치사상죄</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">過失致死</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Homicídio culposo</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">negligent homicide</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">homicide involontaire</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">dood door schuld</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">fahrlässige Tötung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">homicidio negligente</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">omicidio colposo</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">vållande till annans död</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Nieumyślne spowodowanie śmierci</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">kuolemantuottamus</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">homicidi involuntari</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">uaktsomt drap</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">usmrcení z nedbalosti</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">過失致死</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">senatenta murdo</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">過失致死</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">убиство из нехата</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">ανθρωποκτονία από αμέλεια</span>+++





<<<

[id='501']
=== [`501`] /homicide (killing of family)/@eng-Latn

Rēs interlinguālibus::
  /scope and content/@eng-Latn:::
    /#TODO extract more concepts from https://en.wikipedia.org/wiki/List_of_types_of_killing#/@eng-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /homicide (killing of family)/@eng-Latn





[id='501_1']
==== [`501_1`] Homicidium honorabile

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q2691275[Q2691275]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /honor killing || homicide of a member of a family or social group by other members, due to the belief that the victim has brought dishonor upon the family or community/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">جريمة الشرف</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Պատվի սպանություն</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">সম্মান রক্ষার্থে হত্যা</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">убийство чести</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">सम्मान हत्या</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">명예살인</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">רצח על חילול כבוד המשפחה</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Homicidium honorabile</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">கெளரவக் கொலை</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">పరువు హత్యలు</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">名譽殺人</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">crime de honra</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">honor killing</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">crime d'honneur</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">eerwraak</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Ehrenmord</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">crimen de honor</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">delitto d'onore</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">marú onóra</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">hedersmord</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">zabójstwo honorowe</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">kunniamurha</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">crimă de onoare</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">giết người vì danh dự</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">crim d'honor</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">вбивство честі</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">убийство на честта</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">æresdrap</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">vražda ze cti</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">Æresdrab</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">名誉の殺人</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">അഭിമാനക്കൊല</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">pembunuhan kehormatan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">قتل ناموسی</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">becsületgyilkosság</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">crime de honra</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">honormurdo</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">pembunuhan kehormatan</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">ubojstvo zbog časti</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">töre ve namus suçları</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">名譽殺人</span>+++

  Lingua Vallonica:::
    +++<span lang="wa">moude d' oneur</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">کارو کاری</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Earwraak</span>+++





<<<

[id='503']
=== [`503`] /extra-judicial killing/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q2717573[Q2717573]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /extra-judicial killing || intentional and unlawful killings of individuals by state actors without judicial process/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">إعدام لاقضائي</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">বিচার বহির্ভূত হত্যাকাণ্ড</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">внесудебное убийство</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">초법적 살인</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">הוצאה להורג ללא משפט</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">சட்டத்துக்குப் புறம்பான கொலைகள்</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">วิสามัญฆาตกรรม</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">法外處決</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">execução extrajudicial</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">extra-judicial killing</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">exécution extrajudiciaire</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">extralegale executie</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">extralegale Hinrichtung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">ejecución extrajudicial</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">esecuzione stragiudiziale</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">execució extrajudicial</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">позасудова страта</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">zunajsodni uboj</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">udenretslig drab</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">超法規的殺人</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Pembunuhan di luar hukum</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">اعدام فراقضایی</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">eksterjura hommortigo</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">вансудско погубљење</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">ماورائے عدالت قتل</span>+++





[id='503_1']
==== [`503_1`] /targeted killing/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1642263[Q1642263]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /targeted killing || form of assassination carried by governments against their perceived enemies/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">قتل مستهدف</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Նպատակային սպանություններ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">целевое убийство</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">סיכול ממוקד</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">目標追殺</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">targeted killing</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">assassinat ciblé</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">gezielte Tötung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">asesinato selectivo</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">omicidio mirato</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Selektywna eliminacja</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">assassinat selectiu</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">Cílené zabíjení</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">標的殺害</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Pembunuhan yang ditargetkan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">قتل هدفمند</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Ciljano ubijanje</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">تہدّفی قتل</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Ciljano ubijanje</span>+++





<<<

[id='700']
=== [`700`] /sexual and gender-based violence (except killing)/@eng-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /sexual and gender-based violence (except killing)/@eng-Latn





[id='700_1']
==== [`700_1`] /sexual violence/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q558075[Q558075]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /sexual violence/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">عنف جنسي</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Սեռական բռնություն</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">যৌন সহিংসতা</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">сексуальное насилие</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">यौन हिंसा</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">성폭력</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">אלימות מינית</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">பாலியல் வன்முறை</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">性暴力</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">violência sexual</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">sexual violence</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">violence sexuelle</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">seksueel geweld</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">sexualisierte Gewalt</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">violencia sexual</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">violenza sessuale</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">foréigean gnéasach</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">sexuellt våld</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">przemoc seksualna</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">seksuaalinen väkivalta</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">violență sexuală</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Bạo lực tình dục</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">violència sexual</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">сексуальне насилля</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Сексуално насилие</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Spolno nasilje</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">seksualisert vold</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">seksuel vold</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">性的暴力</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">خشونت جنسی</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">szexuális erőszak</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Sexu indarkeria</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Violencia sexual</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">seksa violento</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">seksuaalne vägivald</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Cinsel şiddet</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">性暴力</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">Сексуално насиљe</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">جنسی تشدد</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Seksualinė prievarta</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Seksualno nasilje</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">σεξουαλική βία</span>+++





[id='700_10']
==== [`700_10`] Stuprum

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q47092[Q47092]

  /scope and content/@eng-Latn:::
    /#TODO extract more concepts from https://en.wikipedia.org/wiki/Types_of_rape#/@eng-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /rape/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">اغتصاب</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Բռնաբարություն</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">ধর্ষণ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">изнасилование</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">बलात्कार</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಬಲಾತ್ಕಾರದ ಸಂಭೋಗ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">강간</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">אונס</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Stuprum</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">வன்கலவி</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">మానభంగం</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">การข่มขืนกระทำชำเรา</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">强奸</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">violação</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">rape</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">viol</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">verkrachting</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Vergewaltigung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">violación</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">violenza sessuale</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">éigniú</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">våldtäkt</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">zgwałcenie</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">raiskaus</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">viol</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">hiếp dâm</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">violació</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">зґвалтування</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Изнасилване</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Posilstvo</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">voldtekt</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">znásilnění</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">voldtægt</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">強姦</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">valdtekt</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">ബലാത്സംഗം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">pemerkosaan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">تجاوز جنسی</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">nemi erőszak</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Bortxaketa</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">Trais rhywiol</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Violación</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">Znásilnenie</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">seksatenco</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">Rogol</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">vägistamine</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Silovanje</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">ırza geçme</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">Viòl</span>+++

  Lingua Britonica (Abecedarium Latinum):::
    +++<span lang="br">Gwallerezh</span>+++

  /Egyptian Arabic/ (/Abecedarium Arabicum/):::
    +++<span lang="arz">اغتصاب</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">verkragting</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Vergewaltegung</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">rape</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">強姦</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Nauðgun</span>+++

  Lingua Limburgica (Abecedarium Latinum):::
    +++<span lang="li">Verkrachting</span>+++

  Lingua Arpitanica:::
    +++<span lang="frp">Viol</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">强奸</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">силовање</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">عصمت دری</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Išprievartavimas</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Silovanje</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">Izvarošana</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Silovanje</span>+++

  Lingua Iavanica (Abecedarium Latinum):::
    +++<span lang="jv">Ruda peksa</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">βιασμός</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">ferkrêfting</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">Згвалтаванне</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">बलात्कार</span>+++

  Lingua Zuluana (Abecedarium Latinum):::
    +++<span lang="zu">Ukudlwengula</span>+++





[id='700_10_1']
===== [`700_10_1`] /statutory rape/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1968926[Q1968926]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /statutory rape/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">اغتصاب قانوني</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">растление</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">의제강간</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">אונס סטטוטורי</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">法定强奸</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">statutory rape</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">atteinte sexuelle sur mineur</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">sexueller Missbrauch von Jugendlichen</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">estupro</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">estupre</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">розбещення</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">seksuell omgang med midreårige</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">法定強姦</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Pemerkosaan statutori</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">تجاوز قانونی</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">Rogol statutori</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Hukuken tecavüz</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Išžaginimas</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Silovanje po slovu zakona</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Statutory rape</span>+++





[id='700_10_1_1']
====== [`700_10_1_1`] /child grooming/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1147070[Q1147070]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /child grooming/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">استمالة الأطفال</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Груминг детей</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">การเตรียมเด็กเพื่อทารุณกรรมทางเพศ</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">兒童性誘拐</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">corrupção de menores</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">child grooming</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">Sollicitation d’enfants à des fins sexuelles</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">grooming</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">child grooming</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">grooming</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">gromning</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Child grooming</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">grooming</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">ciberassetjament pedòfil</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Грумінг</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Грууминг</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">Grooming</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">grooming</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Perawatan anak</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Grooming</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Grooming</span>+++

  Macrolingua Malayana (?):::
    +++<span lang="ms">Antun kanak-kanak</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">兒童性誘拐</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">Педофилско зближавање</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Pedofilsko zbližavanje</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Child grooming</span>+++





[id='700_10_2']
===== [`700_10_2`] /unacknowledged rape/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q23807951[Q23807951]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /unacknowledged rape/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">اغتصاب غير ملحوظ</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Unacknowledged rape</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Pemerkosaan yang tak diakui</span>+++





[id='700_10_4']
===== [`700_10_4`] /corrective rape/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1135287[Q1135287]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /corrective rape || hate crime in which a person is raped because of their perceived sexual or gender orientation/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">اغتصاب تصحيحي</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">সংশোধনী ধর্ষণ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Корректирующее изнасилование</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">교간</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">אונס מתקן</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">姦改</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">estupro corretivo</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">corrective rape</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">viol correctif</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">correctieve verkrachting</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Corrective rape</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">violación correctiva</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">stupro correttivo</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Gwałt naprawczy</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Hiếp dâm trừng phạt</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">Violació correctiva</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Корекційне зґвалтування</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">nápravné znásilnění</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">矯正レイプ</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Pemerkosaan korektif</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">تجاوز اصلاحی</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Bortxaketa zuzengarri</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">korekta seksatenco</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Düzeltici tecavüz</span>+++

  Lingua Britonica (Abecedarium Latinum):::
    +++<span lang="br">Gwallerezh reizhañ</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">Корективно силовање</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">korrektive ferkrêfting</span>+++





[id='700_10_10']
===== [`700_10_10`] /gang rape/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q8192354[Q8192354]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /gang rape/@eng-Latn

  Macrolingua Arabica (/Abecedarium Arabicum/):::
    +++<span lang="ar">إغتصاب جماعي</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">গণধর্ষণ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">групповое изнасилование</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">윤간</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">אונס קבוצתי</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">குழு பாலியல் வல்லுறவு</span>+++

  /Macrolingua Sinicae (?)/:::
    +++<span lang="zh">輪姦</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">violação em grupo</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">gang rape</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">viol collectif</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">groepsverkrachting</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Gruppenvergewaltigung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">violación en grupo</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">gruppvåldtäkt</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">joukkoraiskaus</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">viol în grup</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">violació col·lectiva</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">massevoldtægt</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">輪姦</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Pemerkosaan berkelompok</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">تجاوز گروهی</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">violación en grupo</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">toplu tecavüz</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">輪姦</span>+++

  Lingua Urdu (/Abecedarium Arabicum/):::
    +++<span lang="ur">اجتماعی آبروریزی</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Groepsferkrêfting</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">सामूहिक बलात्कार</span>+++






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language. We're working on this, but we are still not perfected.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.


=== /[Book with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries. Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.


=== /[Book with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.


=== /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!


<<<

