= Cōdex [1603:1:101]: //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
:doctype: book
:title: Cōdex [1603:1:101]: //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
:lang: la
:toc: macro
:toclevels: 4
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum




{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
numerus editionis
|
2022-03-06T00:42:19

|===

<<<
toc::[]
<<<


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:1:101]**_ is the book format of the machine-readable dictionaries _**[1603:1:101] //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//**_, which are distributed for implementers on external applications. This book is intended as advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies.
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    The initiative behind this compilation is also doing other dictionaries and accepts new suggestions of relevant topics on data exchange for humanitarian use. All have in common the fact that both have human translations and (if any) external interlingual codes related to each concept while making the end result explicitly already ready to be usable on average softwares. Naturally, each book version gives extensive explanations for collaborators on how to correct itself which become part of the next weekly release.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Rēs dē factō in dictiōnāriīs
==== Concepta: 19

==== Rēs linguālibus: 2

[%header,cols="15h,25a,~,15"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
11

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
1

|===

==== Rēs interlinguālibus: 2
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
The result of this section is a preview. We're aware it is not well formatted for a book format. Sorry for the temporary inconvenience.

|===



/Wiki QID/::
#item+rem+i_qcc+is_zxxx+ix_regulam::: Q[1-9]\d*
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikiq
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_q
#item+rem+definitionem+i_eng+is_latn::: QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.


numerus editionis::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P393
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip393
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_393
#item+rem+definitionem+i_eng+is_latn::: number of an edition (first, second, ... as 1, 2, ...) or event

<<<

== Archīa


[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
**Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ an static work), then the actual groundbreaking difference on the workflow used to generate every dictionaries on Cōdex such as this one are the following fact: **we provide machine readable formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with terminology translations.

**Practical implication**: the text documents on _Archīa prō cōdice_ (literal _English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an impact.

|===

=== Archīa prō dictiōnāriīs: 1


==== 1603_1_101.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_101.no1.tm.hxl.csv[1603_1_101.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container/



=== Archīa prō cōdice: 2


==== 1603_1_101.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_101.mul-Latn.codex.adoc[1603_1_101.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.



==== 1603_1_101.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_101.mul-Latn.codex.pdf[1603_1_101.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://en.wikipedia.org/wiki/PDF

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
<<<

[id='1']
=== [`1`] //abstractum data schēmae//@lat-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //abstractum data schēmae//@lat-Latn





<<<

[id='2']
=== [`2`] //archīvum data typīs//@lat-Latn

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //archīvum data typīs//@lat-Latn





[id='2_1']
==== [`2_1`] /tabular data/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q496946[Q496946]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /tabular data/@eng-Latn





[id='2_1_1']
===== [`2_1_1`] /delimiter-separated values/

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q3021669[Q3021669]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /delimiter-separated values/





[id='2_1_1_2']
====== [`2_1_1_2`] /comma-separated values (CSV)/

Rēs interlinguālibus::
  ix_uid:::
    csv

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q935809[Q935809]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /comma-separated values (CSV)/





[id='2_1_1_3']
====== [`2_1_1_3`] /tab-separated values (TSV)/

Rēs interlinguālibus::
  ix_uid:::
    tsv

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q3513566[Q3513566]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /tab-separated values (TSV)/





<<<

[id='99']
=== [`99`] 





[id='99_1']
==== [`99_1`] 

Rēs interlinguālibus::
  ix_uid:::
    json





[id='99_2']
==== [`99_2`] 

Rēs interlinguālibus::
  ix_uid:::
    xml





[id='99_3']
==== [`99_3`] 

Rēs interlinguālibus::
  ix_uid:::
    xliff





[id='99_4']
==== [`99_4`] 

Rēs interlinguālibus::
  ix_uid:::
    tbx





[id='99_5']
==== [`99_5`] 

Rēs interlinguālibus::
  ix_uid:::
    (HXL)

  /Wiki QID/:::
    https://www.wikidata.org/wiki/https://hxlstandard.org/[https://hxlstandard.org/]





[id='99_6']
==== [`99_6`] 

Rēs interlinguālibus::
  ix_uid:::
    (HXLTM)

  /Wiki QID/:::
    https://www.wikidata.org/wiki/https://hxltm.etica.ai/[https://hxltm.etica.ai/]





[id='99_7']
==== [`99_7`] 

Rēs interlinguālibus::
  ix_uid:::
    (numerordinatio)

  /Wiki QID/:::
    https://www.wikidata.org/wiki/https://numerordinatio.etica.ai/[https://numerordinatio.etica.ai/]





[id='99_8']
==== [`99_8`] /Numerordinatio on HXLTM container/

Rēs interlinguālibus::
  ix_uid:::
    no1.tm.hxl.csv

  /Wiki QID/:::
    https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano1.tm.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano1.tm.hxl.csv&type=Code&ref=advsearch&l=&l=]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Numerordinatio on HXLTM container/





[id='99_9_2']
===== [`99_9_2`] /Numerordinatio on HXLTM container (expanded with terminology translations)/

Rēs interlinguālibus::
  ix_uid:::
    no11.tm.hxl.csv

  /Wiki QID/:::
    https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano11.tm.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano11.tm.hxl.csv&type=Code&ref=advsearch&l=&l=]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Numerordinatio on HXLTM container (expanded with terminology translations)/





[id='99_10']
==== [`99_10`] /Metadata about no1.tm.hxl.csv/

Rēs interlinguālibus::
  ix_uid:::
    meta.no1.tm.hxl.csv

  /Wiki QID/:::
    https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.hxl.csv&type=Code&ref=advsearch&l=&l=]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Metadata about no1.tm.hxl.csv/





[id='99_11']
==== [`99_11`] /Metadata about tm.hxl.csv/

Rēs interlinguālibus::
  ix_uid:::
    meta.tm.hxl.csv

  /Wiki QID/:::
    https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.tm.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.tm.hxl.csv&type=Code&ref=advsearch&l=&l=]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Metadata about tm.hxl.csv/





[id='99_12']
==== [`99_12`] /Metadata about annexes (local namespace)/

Rēs interlinguālibus::
  ix_uid:::
    nnx.tm.hxl.csv

  /Wiki QID/:::
    https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Annx.tm.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Annx.tm.hxl.csv&type=Code&ref=advsearch&l=&l=]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Metadata about annexes (local namespace)/






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language. We're working on this, but we are still not perfected.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.


=== /[Book with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries. Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.


=== /[Book with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.


=== /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!


<<<

