= Cōdex [1603:1:101]: //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
:doctype: book
:title: Cōdex [1603:1:101]: //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
:lang: la
:toc:
:toclevels: 4
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge




{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
[quote]
/_**Public domain means that each major common issue only needs to be resolved once**_/@eng-Latn

<<<
toc::[]


[id=0_999_1603_1]
== Praefātiō 

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō
|
Lingua Anglica (Abecedarium Latinum)
|
_**"Cōdex [1603:1:101]"**_ is the book format of the machine-readable dictionaries _**"[1603:1:101] //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//"**_,
which are distributed for implementers on external applications.
This book is intended as advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies.

Practical lexicography is the art or craft of compiling, writing and editing dictionaries.
The basics are not far different than a millennia ago:
it is still a very humane, creative work.
It is necessary to be humble:
most of the translator's mistakes are, in fact, not translator's fault, but methodological flaws.
Making sure of a source idea of what a concept represents,
even if it means rewrite and make simpler, annex pictures,
show examples, do whatever to make it be understood,
makes even non-professional translators that care about their own language deliver better results than any alternative.
In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.

The initiative behind this compilation is also doing other dictionaries and accepts new suggestions of relevant topics on data exchange for humanitarian use.
All have in common the fact that both have human translations and (if any) external interlingual codes related to each concept while making the end result explicitly already ready to be usable on average softwares.
Naturally, each book version gives extensive explanations for collaborators on how to correct itself which become part of the next weekly release.

|===


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
numerus editionis
|
2022-02-11T10:28:41

|===


<<<

== Methodī ex cōdice
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō
|
Lingua Anglica (Abecedarium Latinum)
|
This section explains the methodology of this book and it's machine readable formats. For your convenience the information used to explain the concepts (such as natural language and interlingual codes) which appears in this book are also summarized here. This approach is done both for reviews not needing to open other books (or deal with machine readable files) and also to spot errors on other dictionaries. +++<br><br>+++ About how the book and the dictionaries are compiled, a division of "baseline concept table" and (when relevant for a codex) "translations conciliation" is given different methodologies. +++<br><br>+++ Every book contains at minimum the baseline concept table and explanation of the used fields. This approach helps to release dictionaries faster while ensuring both humans and machines can know what to expect even when they are not ready to receive translations.

|===

=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Rēs dē factō in dictiōnāriīs

==== Rēs linguālibus: 1

[%header,cols="~,~,~,~,~"]
|===
| Cōdex linguae
| Glotto cōdicī
| ISO 639-3
| Wiki QID cōdicī
| Nōmen Latīnum

| mul-Zyyy
| 
| https://iso639-3.sil.org/code/mul[mul]
| 
| Linguae multiplīs (Scrīptum incognitō)

|===

==== Rēs interlinguālibus: 2


===== 1603:1:7:1:91 

[source,json]
----
{
    "#item+conceptum+codicem": "1_91",
    "#item+conceptum+numerordinatio": "1603:1:7:1:91",
    "#item+rem+definitionem+i_eng+is_latn": "QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter \"Q\" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.",
    "#item+rem+i_lat+is_latn": "/Wiki QID/",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikiq",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_q",
    "#item+rem+i_qcc+is_zxxx+ix_regulam": "Q[1-9]\\d*",
    "#status+conceptum+codicem": "19",
    "#status+conceptum+definitionem": "50"
}
----

===== 1603:1:7:2616:393 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_393",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:393",
    "#item+rem+definitionem+i_eng+is_latn": "number of an edition (first, second, ... as 1, 2, ...) or event",
    "#item+rem+i_lat+is_latn": "numerus editionis",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip393",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_393",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P393",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

<<<

== Archīa

=== Archīa prō dictiōnāriīs: 2
==== 1603_1_101.no1.tm.hxl.csv

* link:1603_1_101.no1.tm.hxl.csv[1603_1_101.no1.tm.hxl.csv]

==== 1603_1_101.no11.tm.hxl.csv

* link:1603_1_101.no11.tm.hxl.csv[1603_1_101.no11.tm.hxl.csv]

=== Archīa prō cōdice: 2
==== 1603_1_101.mul-Latn.codex.adoc

* link:1603_1_101.mul-Latn.codex.adoc[1603_1_101.mul-Latn.codex.adoc]

==== 1603_1_101.mul-Latn.codex.pdf

* link:1603_1_101.mul-Latn.codex.pdf[1603_1_101.mul-Latn.codex.pdf]


<<<

== //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
[id='1']
=== [`1`] //abstractum data schēmae//@lat-Latn








[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++//abstractum data schēmae//@lat-Latn+++

|===




[id='2']
=== [`2`] //archīvum data typīs//@lat-Latn








[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++//archīvum data typīs//@lat-Latn+++

|===




[id='2_1']
==== [`2_1`] /tabular data/@eng-Latn





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
Q496946

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/tabular data/@eng-Latn+++

|===




[id='2_1_1']
===== [`2_1_1`] /delimiter-separated values/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
Q3021669

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/delimiter-separated values/+++

|===




[id='2_1_1_2']
====== [`2_1_1_2`] /comma-separated values (CSV)/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
csv

|
/Wiki QID/
|
Q935809

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/comma-separated values (CSV)/+++

|===




[id='2_1_1_3']
====== [`2_1_1_3`] /tab-separated values (TSV)/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
tsv

|
/Wiki QID/
|
Q3513566

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/tab-separated values (TSV)/+++

|===




[id='99']
=== [`99`] 










[id='99_1']
==== [`99_1`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
json

|===






[id='99_2']
==== [`99_2`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
xml

|===






[id='99_3']
==== [`99_3`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
xliff

|===






[id='99_4']
==== [`99_4`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
tbx

|===






[id='99_5']
==== [`99_5`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
(HXL)

|
/Wiki QID/
|
https://hxlstandard.org/

|===






[id='99_6']
==== [`99_6`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
(HXLTM)

|
/Wiki QID/
|
https://hxltm.etica.ai/

|===






[id='99_7']
==== [`99_7`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
(numerordinatio)

|
/Wiki QID/
|
https://numerordinatio.etica.ai/

|===






[id='99_8']
==== [`99_8`] /Numerordinatio on HXLTM container/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
no1.tm.hxl.csv

|
/Wiki QID/
|
https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano1.tm.hxl.csv&type=Code&ref=advsearch&l=&l=

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Numerordinatio on HXLTM container/+++

|===




[id='99_9_2']
===== [`99_9_2`] /Numerordinatio on HXLTM container (expanded with terminology translations)/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
no11.tm.hxl.csv

|
/Wiki QID/
|
https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano11.tm.hxl.csv&type=Code&ref=advsearch&l=&l=

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Numerordinatio on HXLTM container (expanded with terminology translations)/+++

|===




[id='99_10']
==== [`99_10`] /Metadata about no1.tm.hxl.csv/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
meta.no1.tm.hxl.csv

|
/Wiki QID/
|
https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.hxl.csv&type=Code&ref=advsearch&l=&l=

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Metadata about no1.tm.hxl.csv/+++

|===




[id='99_11']
==== [`99_11`] /Metadata about tm.hxl.csv/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
meta.tm.hxl.csv

|
/Wiki QID/
|
https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.tm.hxl.csv&type=Code&ref=advsearch&l=&l=

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Metadata about tm.hxl.csv/+++

|===




[id='99_12']
==== [`99_12`] /Metadata about annexes (local namespace)/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
nnx.tm.hxl.csv

|
/Wiki QID/
|
https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Annx.tm.hxl.csv&type=Code&ref=advsearch&l=&l=

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Metadata about annexes (local namespace)/+++

|===





<<<

[appendix]
= //Open issues on exported PDF format//@eng-Latn


=== //Documentation about how to use the machine-readable dictionaries//@eng-Latn

Is necessary to give a quick introduction (or at least mention) the files generated with this implementer documentation.

=== //Missing fonts to render all term variants//@eng-Latn
The generated PDF does not include all necessary fonts.
Here potential strategy to fix it https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#custom-fonts

=== //Reliability statuses//@eng-Latn

Currently, the reliability of numeric statuses are not well explained on PDF version.
