= Cōdex [1603:1:101]: //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
:doctype: book
:title: Cōdex [1603:1:101]: //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
:lang: la
:toc:
:toclevels: 4
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum




{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

<<<
toc::[]


[id=0_999_1603_1]
== Praefātiō 

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
_**Cōdex [1603:1:101]**_ is the book format of the machine-readable dictionaries _**[1603:1:101] //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//**_, which are distributed for implementers on external applications. This book is intended as advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies.

Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.

The initiative behind this compilation is also doing other dictionaries and accepts new suggestions of relevant topics on data exchange for humanitarian use. All have in common the fact that both have human translations and (if any) external interlingual codes related to each concept while making the end result explicitly already ready to be usable on average softwares. Naturally, each book version gives extensive explanations for collaborators on how to correct itself which become part of the next weekly release.

|===


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
numerus editionis
|
2022-02-28T22:32:55

|===


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Rēs dē factō in dictiōnāriīs
==== Concepta: 19

==== Rēs linguālibus: 1

[%header,cols="15h,25a,~,15"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
11

|===

==== Rēs interlinguālibus: 3
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
The result of this section is a preview. We're aware it is not well formatted for a book format. Sorry for the temporary inconvenience.

|===



/Wiki QID/::
#item+rem+i_qcc+is_zxxx+ix_regulam::: Q[1-9]\d*
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikiq
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_q
#item+rem+definitionem+i_eng+is_latn::: QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.


numerus editionis::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P393
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip393
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_393
#item+rem+definitionem+i_eng+is_latn::: number of an edition (first, second, ... as 1, 2, ...) or event


/reference URL/@eng-Latn::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P854
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip854
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_854
#item+rem+definitionem+i_eng+is_latn::: should be used for Internet URLs as references

<<<

== Archīa


[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
Every book comes with several files both for book format (with (Abecedarium additional information) and machine-readable formats with Latinum) documentation of how to process them. If you receive this file and cannot find the alternatives, ask the human who provide this file.

|===

=== Archīa prō dictiōnāriīs: 1

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
TIP: Is recommended to use the files on this section to  generate derived works.

|===


==== 1603_1_101.no1.tm.hxl.csv

NOTE: link:1603_1_101.no1.tm.hxl.csv[1603_1_101.no1.tm.hxl.csv]

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
/Numerordinatio on HXLTM container/

|===


=== Archīa prō cōdice: 2

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
WARNING: Unless you are working with a natural language you understand it\'s letters and symbols, it is strongly advised to use automation to generate derived works. Keep manual human steps at minimum: if something goes wrong at least one or more languages can be used to verify mistakes. It's not at all necessary _know all languages_, but working with writing systems you don't understand is risky: copy and paste strategy can cause _additional_ human errors and is unlikely to get human review as fast as you would need.

|
Lingua Anglica (Abecedarium Latinum)
|
TIP: The Asciidoctor (.adoc) is better at copy and pasting! It can be converted to other text formats.

|===


==== 1603_1_101.mul-Latn.codex.adoc

NOTE: link:1603_1_101.mul-Latn.codex.adoc[1603_1_101.mul-Latn.codex.adoc]


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/reference URL/@eng-Latn
|
https://asciidoctor.org/docs/

|===


==== 1603_1_101.mul-Latn.codex.pdf

NOTE: link:1603_1_101.mul-Latn.codex.pdf[1603_1_101.mul-Latn.codex.pdf]


<<<

[.text-center]

Dictiōnāria initiīs

<<<

== //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//
<<<

[id='1']
=== [`1`] //abstractum data schēmae//@lat-Latn








[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++//abstractum data schēmae//@lat-Latn+++

|===




<<<

[id='2']
=== [`2`] //archīvum data typīs//@lat-Latn








[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++//archīvum data typīs//@lat-Latn+++

|===




[id='2_1']
==== [`2_1`] /tabular data/@eng-Latn





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q496946[Q496946]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/tabular data/@eng-Latn+++

|===




[id='2_1_1']
===== [`2_1_1`] /delimiter-separated values/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q3021669[Q3021669]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/delimiter-separated values/+++

|===




[id='2_1_1_2']
====== [`2_1_1_2`] /comma-separated values (CSV)/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
csv

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q935809[Q935809]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/comma-separated values (CSV)/+++

|===




[id='2_1_1_3']
====== [`2_1_1_3`] /tab-separated values (TSV)/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
tsv

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q3513566[Q3513566]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/tab-separated values (TSV)/+++

|===




<<<

[id='99']
=== [`99`] 










[id='99_1']
==== [`99_1`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
json

|===






[id='99_2']
==== [`99_2`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
xml

|===






[id='99_3']
==== [`99_3`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
xliff

|===






[id='99_4']
==== [`99_4`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
tbx

|===






[id='99_5']
==== [`99_5`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
(HXL)

|
/Wiki QID/
|
https://www.wikidata.org/wiki/https://hxlstandard.org/[https://hxlstandard.org/]

|===






[id='99_6']
==== [`99_6`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
(HXLTM)

|
/Wiki QID/
|
https://www.wikidata.org/wiki/https://hxltm.etica.ai/[https://hxltm.etica.ai/]

|===






[id='99_7']
==== [`99_7`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
(numerordinatio)

|
/Wiki QID/
|
https://www.wikidata.org/wiki/https://numerordinatio.etica.ai/[https://numerordinatio.etica.ai/]

|===






[id='99_8']
==== [`99_8`] /Numerordinatio on HXLTM container/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
no1.tm.hxl.csv

|
/Wiki QID/
|
https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano1.tm.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano1.tm.hxl.csv&type=Code&ref=advsearch&l=&l=]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Numerordinatio on HXLTM container/+++

|===




[id='99_9_2']
===== [`99_9_2`] /Numerordinatio on HXLTM container (expanded with terminology translations)/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
no11.tm.hxl.csv

|
/Wiki QID/
|
https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano11.tm.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ano11.tm.hxl.csv&type=Code&ref=advsearch&l=&l=]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Numerordinatio on HXLTM container (expanded with terminology translations)/+++

|===




[id='99_10']
==== [`99_10`] /Metadata about no1.tm.hxl.csv/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
meta.no1.tm.hxl.csv

|
/Wiki QID/
|
https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.hxl.csv&type=Code&ref=advsearch&l=&l=]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Metadata about no1.tm.hxl.csv/+++

|===




[id='99_11']
==== [`99_11`] /Metadata about tm.hxl.csv/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
meta.tm.hxl.csv

|
/Wiki QID/
|
https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.tm.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Ameta.tm.hxl.csv&type=Code&ref=advsearch&l=&l=]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Metadata about tm.hxl.csv/+++

|===




[id='99_12']
==== [`99_12`] /Metadata about annexes (local namespace)/





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_uid
|
nnx.tm.hxl.csv

|
/Wiki QID/
|
https://www.wikidata.org/wiki/https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Annx.tm.hxl.csv&type=Code&ref=advsearch&l=&l=[https://github.com/search?q=repo%3AEticaAI%2Fn-data+extension%3Acsv+filename%3Annx.tm.hxl.csv&type=Code&ref=advsearch&l=&l=]

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Metadata about annexes (local namespace)/+++

|===





<<<

