= Cōdex [1603:1:1]: //Numeroclatura Generālium ad MM ex Numerordĭnātĭo//@lat-Latn
:doctype: book
:title: Cōdex [1603:1:1]: //Numeroclatura Generālium ad MM ex Numerordĭnātĭo//@lat-Latn
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum




{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-01-01

|
numerus editionis
|
2022-03-12T21:03:10

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:1:1]**_ is the book format of the machine-readable dictionaries _**[1603:1:1] //Numeroclatura Generālium ad MM ex Numerordĭnātĭo//@lat-Latn**_, which are distributed for implementers on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.
    +++<br><br>+++
    **ABOUT LEXICOGRAPHY**
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    **ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**
    +++<br><br>+++
    We're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.
    +++<br><br>+++
    Since the full list of prototypal-dictionaries and dictionaries is huge, one way cited by objective audiences is the following:
    +++<br><br>+++
    ....
    1. Humanitarian aid
    2. Development aid
    3. Human rights
    4. Military relief (or conflict and conflict-resolution related concepts)
    ....
    +++<br><br>+++
    The itens 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).
    +++<br><br>+++
    Note that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    The lexicographers of this work are both volunteers, doing it for free, pro bonō publicō, and don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books. Most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.
    +++<br><br>+++
    There's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work considering it is feasible over 200 languages? The logistics to decide who should be paid, then worldwide cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither sufficient money nor humans interested in being coordinators exist.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Rēs dē factō in dictiōnāriīs
==== Concepta: 78

==== Rēs linguālibus: 5

[%header,cols="15h,25a,~,15"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
74

|
ben-Beng
|
https://glottolog.org/resource/languoid/id/beng1280[beng1280]
+++<br>+++
https://iso639-3.sil.org/code/ben[ben]
+++<br>+++ https://www.wikidata.org/wiki/Q9610[Q9610]
|
Lingua Bengali (/Bengali script/)
|
2

|
rus-Cyrl
|
https://glottolog.org/resource/languoid/id/russ1263[russ1263]
+++<br>+++
https://iso639-3.sil.org/code/rus[rus]
+++<br>+++ https://www.wikidata.org/wiki/Q7737[Q7737]
|
Lingua Russica (Abecedarium Cyrillicum)
|
3

|
lat-Latn
|
https://glottolog.org/resource/languoid/id/lati1261[lati1261]
+++<br>+++
https://iso639-3.sil.org/code/lat[lat]
+++<br>+++ https://www.wikidata.org/wiki/Q397[Q397]
|
Lingua Latina (Abecedarium Latinum)
|
28

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
2

|===

==== Rēs interlinguālibus: 8
Rēs::
  Numerordĭnātĭo:::
    Rēs interlinguālibus::::
      ix_hxlix;;
        ix_n1603

      ix_hxlvoc;;
        v_n1603

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">Numerordĭnātĭo</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">a generic strategy of arranging numbers in an taxonomy-like explicit way</span>+++

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wikip123

      ix_hxlvoc;;
        v_wiki_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software</span>+++

  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wikip2479

      ix_hxlvoc;;
        v_wiki_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">SPDX license identifier</span>+++

  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wikip577

      ix_hxlvoc;;
        v_wiki_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Date or point in time when a work was first published or released</span>+++

  scrīptor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P50[P50]

      ix_hxlix;;
        ix_wikip50

      ix_hxlvoc;;
        v_wiki_p_50

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">scrīptor</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Main creator(s) of a written work (use on works, not humans)</span>+++

  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wikip393

      ix_hxlvoc;;
        v_wiki_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">number of an edition (first, second, ... as 1, 2, ...) or event</span>+++

  /Wiki QID/:::
    Rēs interlinguālibus::::
      /rēgulam/;;
        Q[1-9]\d*

      ix_hxlix;;
        ix_wikiq

      ix_hxlvoc;;
        v_wiki_q

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/Wiki QID/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.</span>+++


<<<

== Archīa

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    **Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ an static work), then the actual groundbreaking difference on the workflow used to generate every dictionaries on Cōdex such as this one are the following fact: **we provide machine readable formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with terminology translations.
    +++<br><br>+++
    **Practical implication**: the text documents on _Archīa prō cōdice_ (literal English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an impact.


=== Archīa prō dictiōnāriīs: 1


==== 1603_1_1.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_1.no1.tm.hxl.csv[1603_1_1.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container/



=== Archīa prō cōdice: 2


==== 1603_1_1.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_1.mul-Latn.codex.adoc[1603_1_1.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.



==== 1603_1_1.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_1.mul-Latn.codex.pdf[1603_1_1.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== //Numeroclatura Generālium ad MM ex Numerordĭnātĭo//@lat-Latn
<<<

[id='1']
=== [`1`] //Meta dictiōnārium//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Meta dictiōnārium//





[id='1_1']
==== [`1_1`] //Numeroclatura Generālium ad MM ex Numerordĭnātĭo//@lat-Latn

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:1

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Numeroclatura Generālium ad MM ex Numerordĭnātĭo//@lat-Latn





[id='1_2']
==== [`1_2`] /Dictiōnāria de symbolī numerīs/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:2

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Dictiōnāria de symbolī numerīs/

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Dictiōnāria de symbolī numerīs/</span>+++





[id='1_3']
==== [`1_3`] /Dictiōnāria de symbolī ab systemata scrīpta/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:3

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Dictiōnāria de symbolī ab systemata scrīpta/

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Dictiōnāria de symbolī ab systemata scrīpta/</span>+++





[id='1_4']
==== [`1_4`] /Dictiōnāria de systemata scrīpta/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:4

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Dictiōnāria de systemata scrīpta/

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Dictiōnāria de systemata scrīpta/</span>+++





[id='1_5']
==== [`1_5`] Concept of language

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:5

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Concept of language





[id='1_6']
==== [`1_6`] /Dictiōnāria de terminī typīs/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:6

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Dictiōnāria de terminī typīs/





[id='1_7']
==== [`1_7`] //Dictiōnāria basibus dē rēs interlinguīs//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:7

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria basibus dē rēs interlinguīs//





[id='1_10']
==== [`1_10`] //(Reserved namespace to document numeric suffixes)//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:10

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //(Reserved namespace to document numeric suffixes)//





[id='1_13']
==== [`1_13`] 

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:13

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [13] 1603:13 HXL Normae





[id='1_13_22']
===== [`1_13_22`] //Pre-build list of all +v_* attributes on 1603//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:13:22

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Pre-build list of all +v_* attributes on 1603//

  Linguae multiplīs (Scrīptum incognitō):::
    [22] V





[id='1_13_24']
===== [`1_13_24`] //Pre-build list of all +ix_* attributes on 1603//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:13:24

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Pre-build list of all +ix_* attributes on 1603//

  Linguae multiplīs (Scrīptum incognitō):::
    [24] X





[id='1_20']
==== [`1_20`] Concept of number, prebuild tables

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:20

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Concept of number, prebuild tables





[id='1_51']
==== [`1_51`] //Dictiōnāria Linguārum ad MMXXII ex Numerordĭnātĭo//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:51

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria Linguārum ad MMXXII ex Numerordĭnātĭo//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Dictiōnāria Linguārum ad MMXXII ex Numerordĭnātĭo//</span>+++





[id='1_99']
==== [`1_99`] Nōtitiae temporāriōrum circā librārium

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:99

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Nōtitiae temporāriōrum circā librārium





[id='1_101']
==== [`1_101`] //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:1:101

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Dictiōnāria Archīōrum ad MMXXII ex Numerordĭnātĭo//</span>+++





<<<

[id='3']
=== [`3`] Commūnitās scientiae

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:3

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1093434[Q1093434]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Commūnitās scientiae

  Linguae multiplīs (Scrīptum incognitō):::
    [2003] Wikipedia

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Commūnitās scientiae</span>+++

  #item+rem+i_arb+is_arab:::
    بعلم المواطنين

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Гражданская наука</span>+++





[id='3_12']
==== [`3_12`] Vicidata

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:3:12

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q2013[Q2013]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Vicidata

  Linguae multiplīs (Scrīptum incognitō):::
    [2012] Wikidata

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Vicidata</span>+++





[id='3_12_6']
===== [`3_12_6`] //Speciālis collēctiōnī de Vicidata Proprietātī//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:3:12:6

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q18616576[Q18616576]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Speciālis collēctiōnī de Vicidata Proprietātī//

  Linguae multiplīs (Scrīptum incognitō):::
    [6] (16 - 10) P

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Speciālis collēctiōnī de Vicidata Proprietātī//</span>+++





[id='3_12_16']
===== [`3_12_16`] Vicidata Proprietātī

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:3:12:16

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q18616576[Q18616576]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Vicidata Proprietātī

  Linguae multiplīs (Scrīptum incognitō):::
    [16] P

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Vicidata Proprietātī</span>+++





[id='3_12_17']
===== [`3_12_17`] Vicidata rēs identitāte

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:3:12:17

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q43649390[Q43649390]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Vicidata rēs identitāte

  Linguae multiplīs (Scrīptum incognitō):::
    [17] Q

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Vicidata rēs identitāte</span>+++





[id='3_1603']
==== [`3_1603`] /Communitary translations via Wikidata/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:3:1603

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Communitary translations via Wikidata/





[id='3_1603_45']
===== [`3_1603_45`] 

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:3:1603:45





[id='3_1603_45_1']
====== [`3_1603_45_1`] 

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:3:1603:45:1





<<<

[id='13']
=== [`13`] HXL Normae

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:13

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    HXL Normae

  Linguae multiplīs (Scrīptum incognitō):::
    [2013-12-01] HXL Standard

  Linguae multiplīs (Scrīptum incognitō):::
    https://www.elrha.org/wp-content/uploads/2017/05/hif-alnap-unocha-exchange-language-case-study-2016-1.pdf

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">HXL Normae</span>+++





<<<

[id='14']
=== [`14`] //Librārium mīlitārī//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:14

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Librārium mīlitārī//

  Linguae multiplīs (Scrīptum incognitō):::
    [14] 1914, Primum bellum mundanum





[id='14_997']
==== [`14_997`] //Dictiōnāria dē relevāminibus per bellīs//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:14:997

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria dē relevāminibus per bellīs//





[id='13_1603']
==== [`13_1603`] /HXL replacement maps to other namespaces/@eng-Latn

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:13:1603

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /HXL replacement maps to other namespaces/@eng-Latn





[id='13_1603_49']
===== [`13_1603_49`] /HXL replacement maps to UN m49 from other namespaces/@eng-Latn

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:13:1603:49

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /HXL replacement maps to UN m49 from other namespaces/@eng-Latn





<<<

[id='23']
=== [`23`] //Librārium lēgī//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:23

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Librārium lēgī//





[id='23_21']
==== [`23_21`] //Dictiōnāria dē Iurum humanorum defensor//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:23:21

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria dē Iurum humanorum defensor//





[id='23_36']
==== [`23_36`] //Dictiōnāria dē intraimperiīs lēgisperītīs per lēgēs certiōrātū//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:23:36

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria dē intraimperiīs lēgisperītīs per lēgēs certiōrātū//





<<<

[id='25']
=== [`25`] Mīlitāris scientiae

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:25

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q11190[Q11190]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Medicina

  Linguae multiplīs (Scrīptum incognitō):::
    [1025] قانون در طب

  Linguae multiplīs (Scrīptum incognitō):::
    https://archive.org/details/AlQaawnoonFiTTwibb/Al-Qaawnoon%20fi-t-Twibb/mode/2up

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Mīlitāris scientiae</span>+++

  #item+rem+i_arb+is_arab:::
    علوم عسكرية

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Военная наука</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">সামরিক বিজ্ঞান</span>+++





[id='25_1']
==== [`25_1`] /dictiōnāria de partes corporis humani/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:25:1

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //dictiōnāria de partes corporis humani//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/dictiōnāria de partes corporis humani/</span>+++





<<<

[id='32']
=== [`32`] /Translitteratio librāriīs/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:32

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Translitteratio librāriīs/

  Linguae multiplīs (Scrīptum incognitō):::
    [32] Translitteratio; T=20, L=12; 20 + 12 = 32





<<<

[id='42']
=== [`42`] Forēnsis scientiae

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:42

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q192386[Q192386]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Mīlitāris scientiae

  Linguae multiplīs (Scrīptum incognitō):::
    [142] (142 -100) 魏伯陽 

  Linguae multiplīs (Scrīptum incognitō):::
    https://archive.org/search.php?query=title%3A%28%E6%AD%A6%E7%B6%93%E7%B8%BD%E8%A6%81%29

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Forēnsis scientiae</span>+++

  #item+rem+i_arb+is_arab:::
    علم الأدلة الجنائية

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Криминалистическая экспертиза</span>+++

  Lingua Bengali (/Bengali script/):::
    +++<span lang="bn">ফরেনসিক বিজ্ঞান</span>+++





<<<

[id='44']
=== [`44`] Forēnsis scientiae

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:44

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q495304[Q495304]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Forēnsis scientiae

  Linguae multiplīs (Scrīptum incognitō):::
    [42] Antistius ex Caesar post mortī, circa 42-03-15 BC





[id='44_1']
==== [`44_1`] //dictiōnāria de post mortis condici//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:44:1

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q99312209[Q99312209]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //dictiōnāria de post mortis condici//





[id='44_142']
==== [`44_142`] //dictiōnāria de vulnera ab arma ignifera//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:44:142

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //dictiōnāria de vulnera ab arma ignifera//

  Linguae multiplīs (Scrīptum incognitō):::
    [142] 魏伯陽 





<<<

[id='45']
=== [`45`] (Interimperia) Locus cōdicī

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Normās interimperia

  Linguae multiplīs (Scrīptum incognitō):::
    [1945-10-24] Fundatio de Nationes Unitae

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">(Interimperia) Locus cōdicī</span>+++





[id='45_1']
==== [`45_1`] //dictiōnāria de hūmānitātēs interimperia//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:1

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //dictiōnāria de hūmānitātēs interimperia//





[id='45_16']
==== [`45_16`] (Interimperia) Locus cōdicī

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q7200235[Q7200235]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    (Interimperia) Locus cōdicī

  Linguae multiplīs (Scrīptum incognitō):::
    [16] P

  Linguae multiplīs (Scrīptum incognitō):::
    https://en.wikipedia.org/wiki/Common_Operational_Datasets#P-codes





[id='45_16_?']
===== [`45_16_?`] 

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?

  ix_regex:::
    \1=[1603:45:49]





[id='45_16_?_0']
====== [`45_16_?_0`] //imperium territōrium//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?:0

  ix_regex:::
    \1=[1603:45:49]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //imperium territōrium//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//imperium territōrium//</span>+++





[id='45_16_?_1']
====== [`45_16_?_1`] //Infraimperium territōria ōrdō 1//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?:1

  ix_regex:::
    \1=[1603:45:49]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Infraimperium territōria ōrdō 1//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Infraimperium territōria ōrdō 1//</span>+++





[id='45_16_?_2']
====== [`45_16_?_2`] //Infraimperium territōria ōrdō 2//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?:2

  ix_regex:::
    \1=[1603:45:49]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Infraimperium territōria ōrdō 2//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Infraimperium territōria ōrdō 2//</span>+++





[id='45_16_?_3']
====== [`45_16_?_3`] //Infraimperium territōria ōrdō 3//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?:3

  ix_regex:::
    \1=[1603:45:49]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Infraimperium territōria ōrdō 3//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Infraimperium territōria ōrdō 3//</span>+++





[id='45_16_?_4']
====== [`45_16_?_4`] //Infraimperium territōria ōrdō 4//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?:4

  ix_regex:::
    \1=[1603:45:49]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Infraimperium territōria ōrdō 4//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Infraimperium territōria ōrdō 4//</span>+++





[id='45_16_?_5']
====== [`45_16_?_5`] //Infraimperium territōria ōrdō 5//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?:5

  ix_regex:::
    \1=[1603:45:49]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Infraimperium territōria ōrdō 5//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Infraimperium territōria ōrdō 5//</span>+++





[id='45_16_?_6']
====== [`45_16_?_6`] //Infraimperium territōria ōrdō 6//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?:6

  ix_regex:::
    \1=[1603:45:49]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Infraimperium territōria ōrdō 6//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Infraimperium territōria ōrdō 6//</span>+++





[id='45_16_?_21_?']
======= [`45_16_?_21_?`] (Interimperia) Locus cōdicī; exāctō (A1...A6)

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:?:21:?

  ix_regex:::
    \1=[1603:45:49] \2=[1603:45:16:916] 

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    (Interimperia) Locus cōdicī; exāctō (A1...A6)

  Linguae multiplīs (Scrīptum incognitō):::
    [21] (0 + 1 + 2 + 3 + 4 + 5 + 6)

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">(Interimperia) Locus cōdicī; exāctō (A1...A6)</span>+++





[id='45_16_900']
===== [`45_16_900`] [private use] Entire world public P-Codes Adm 0 (>110)

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:900

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [private use] Entire world public P-Codes Adm 0 (>110)





[id='45_16_901']
===== [`45_16_901`] [private use] Entire world public P-Codes A.1 (>2500)

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:901

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [private use] Entire world public P-Codes A.1 (>2500)





[id='45_16_902']
===== [`45_16_902`] [private use] Entire world public P-Codes A.2 (>33700)

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:902

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [private use] Entire world public P-Codes A.2 (>33700)





[id='45_16_903']
===== [`45_16_903`] [private use] Entire world public P-Codes A.3 (>130500)

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:903

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [private use] Entire world public P-Codes A.3 (>130500)





[id='45_16_904']
===== [`45_16_904`] [private use] Entire world public P-Codes A.4 (>265000)

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:904

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [private use] Entire world public P-Codes A.4 (>265000)





[id='45_16_905']
===== [`45_16_905`] [private use] Entire world public P-Codes A.5

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:905

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [private use] Entire world public P-Codes A.5





[id='45_16_906']
===== [`45_16_906`] [private use] Entire world public P-Codes A.6

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:906

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [private use] Entire world public P-Codes A.6





[id='45_16_916']
===== [`45_16_916`] [meta] UN OCHA P-Code *WITHOUT* ISO 3166-1 prefix

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:916

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [meta] UN OCHA P-Code *WITHOUT* ISO 3166-1 prefix





[id='45_16_921']
===== [`45_16_921`] [private use] Entire world public P-Codes A.0 + A1, +A.2 + A.3 + A.4 + A5 + A.6 (> 430000)

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:16:921

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    [private use] Entire world public P-Codes A.0 + A1, +A.2 + A.3 + A.4 + A5 + A.6 (> 430000)

  Linguae multiplīs (Scrīptum incognitō):::
    [921] (0 + 1 + 2 + 3 + 4 + 5 + 6 + 900)





[id='45_19']
==== [`45_19`] Dictiōnāria dē locī generibus

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:19

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Dictiōnāria dē locī generibus





[id='45_31']
==== [`45_31`] Dictiōnāria de calamitātibus

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:31

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Dictiōnāria de calamitātibus





[id='45_49']
==== [`45_49`] //Imperia et regiōnēs territōria cōdicēs//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:49

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Imperia et regiōnēs territōria cōdicēs//

  Linguae multiplīs (Scrīptum incognitō):::
    [49] UN M49

  Linguae multiplīs (Scrīptum incognitō):::
    https://unstats.un.org/unsd/publication/SeriesM/Series_M49_(1970)_en-fr.pdf

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Imperia et regiōnēs territōria cōdicēs//</span>+++





[id='45_95']
==== [`45_95`] //Dictiōnāria dē abūsīs interimperiīs contrā cīvēs ex auxiliātiō//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:95

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria dē abūsīs interimperiīs contrā cīvēs ex auxiliātiō//





[id='45_994']
==== [`45_994`] //Dictiōnāria dē Development aid//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:45:994

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria dē Development aid//





<<<

[id='47']
=== [`47`] Normās interindustriās

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:47

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1334738[Q1334738]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Normās interindustriās

  Linguae multiplīs (Scrīptum incognitō):::
    [1947-02-23] ISO

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Normās interindustriās</span>+++

  #item+rem+i_arb+is_arab:::
    /معايير دولية/





<<<

[id='63']
=== [`63`] //Librārium hūmānitātī strictae//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:63

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Librārium hūmānitātī strictae//





[id='63_1']
==== [`63_1`] //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:63:1

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//





[id='63_101']
==== [`63_101`] //Dictiōnāria basibus dē rēbus vītālibus necessāriīs//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:63:101

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria basibus dē rēbus vītālibus necessāriīs//





<<<

[id='64']
=== [`64`] /Dictiōnāria de aquīs et aliae/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:64

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Dictiōnāria de aquīs et aliae/





[id='64_41']
==== [`64_41`] //Dictiōnāria basibus dē perītiae per susurrōs vītālēs//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:64:41

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria basibus dē perītiae per susurrōs vītālēs//





[id='64_604']
==== [`64_604`] //Dictiōnāria de aquīs et sānātiōnibus ex līmpidīs//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:64:604

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q2552246[Q2552246]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Dictiōnāria de aquīs et sānātiōnibus ex līmpidīs//





<<<

[id='84']
=== [`84`] Dentālis scientiae

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:84

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Dentālis scientiae

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Dentālis scientiae</span>+++

  #item+rem+i_arb+is_arab:::
    طب الأسنان





[id='84_1']
==== [`84_1`] /Dictiōnāria dentālium/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:84:1

  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q10627714[Q10627714]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Dictiōnāria dentālium/

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Dictiōnāria dentālium/</span>+++





<<<

[id='99']
=== [`99`] /Temporary public numeric namespace/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:99

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Temporary public numeric namespace/





[id='99_987']
==== [`99_987`] //Personal name nomenclature//

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:99:987

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //Personal name nomenclature//





<<<

[id='999999']
=== [`999999`] Data temporāriīs

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:999999

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    Data temporāriīs

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Data temporāriīs</span>+++





<<<

[id='999999999']
=== [`999999999`] /Non data files (used for software which generate data)/

Rēs interlinguālibus::
  Numerordĭnātĭo:::
    1603:999999999

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Non data files (used for software which generate data)/






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language. We're working on this, but we are still not perfected.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.


=== /[Book with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries. Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.


=== /[Book with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.


=== /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!


<<<

