= Cōdex [1603:84:1]: /Dictiōnāria dentālium/
:doctype: book
:title: Cōdex [1603:84:1]: /Dictiōnāria dentālium/
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum
:front-cover-image: image:1603_84_1.mul-Latn.codex.svg["Cōdex [1603_84_1]: /Dictiōnāria dentālium/",1050,1600]




{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
Multiplicēs scrīptōribus

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-01-16

|
numerus editionis
|
2022-04-17T14:40:54

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|
/reference URL/@eng-Latn
|
https://github.com/EticaAI/multilingual-lexicography/issues/8

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:84:1]**_ is the book format of the machine-readable dictionaries _**[1603:84:1] /Dictiōnāria dentālium/**_, which are distributed for implementers on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.
    +++<br><br>+++
    **ABOUT LEXICOGRAPHY**
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    **ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**
    +++<br><br>+++
    We're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.
    +++<br><br>+++
    Since the full list of prototypal-dictionaries and dictionaries is huge, one way cited by objective audiences is the following:
    +++<br><br>+++
    . Humanitarian aid
    . Development aid
    . Human rights
    . Military relief (or conflict and conflict-resolution related concepts)
    +++<br><br>+++
    The itens 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).
    +++<br><br>+++
    Note that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    The lexicographers of this work are both volunteers, doing it for free, pro bonō publicō, and don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books. Most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.
    +++<br><br>+++
    There's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work considering it is feasible over 200 languages? The logistics to decide who should be paid, then worldwide cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither sufficient money nor humans interested in being coordinators exist.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Methodī ex verbīs in dictiōnāriīs
NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    The ***[1603:84:1] /Dictiōnāria dentālium/*** uses Wikidata as one strategy to conciliate language terms for one or more of it's concepts.
    +++<br><br>+++
    This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up to date translations.
    +++<br><br>+++
    **How reliable are the community translations (Wikidata source)?**
    +++<br><br>+++
    The short, default answer is: **they are reliable**, even in cases of no authoritative translations for each subject.
    +++<br><br>+++
    As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).
    +++<br><br>+++
    However, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.
    +++<br><br>+++
    **Major reasons for "wrong translations" are not translators fault**
    +++<br><br>+++
    TIP: As a rule of thumb, for already very defined concepts where you, as human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.
    +++<br><br>+++
    The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.
    +++<br><br>+++
    It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.
    +++<br><br>+++
    From the point of view of data conciliation, the following methodology is used to release the terminology translations with the main concept table.
    +++<br><br>+++
    . The main handcrafted lexicographical table (explained on previous topic), also provided on `1603_84_1.no1.tm.hxl.csv`, may reference Wiki QID.
    . Every unique QID of  `1603_84_1.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!
    .. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares then for general use.
    . The query result, with all QIDs and term labels, is shared as `1603_84_1.wikiq.tm.hxl.csv`
    . The community reviewed translations of each singular QID is pre-compiled on an individual file `1603_84_1.wikiq.tm.hxl.csv`
    . `1603_84_1.no1.tm.hxl.csv` plus `1603_84_1.wikiq.tm.hxl.csv` created `1603_84_1.no11.tm.hxl.csv`


=== Rēs dē factō in dictiōnāriīs
==== Concepta: 60

==== Rēs linguālibus: 2

[%header,cols="15h,25a,~,17"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
7

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
3

|===

==== Rēs interlinguālibus: 9
Rēs::
  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wikip2479

      ix_hxlvoc;;
        v_wiki_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">SPDX license identifier</span>+++

  /reference URL/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P854[P854]

      ix_hxlix;;
        ix_wikip854

      ix_hxlvoc;;
        v_wiki_p_854

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/reference URL/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">should be used for Internet URLs as references</span>+++

  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wikip577

      ix_hxlvoc;;
        v_wiki_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Date or point in time when a work was first published or released</span>+++

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wikip123

      ix_hxlvoc;;
        v_wiki_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software</span>+++

  scrīptor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P50[P50]

      ix_hxlix;;
        ix_wikip50

      ix_hxlvoc;;
        v_wiki_p_50

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">scrīptor</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Main creator(s) of a written work (use on works, not humans)</span>+++

  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wikip393

      ix_hxlvoc;;
        v_wiki_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">number of an edition (first, second, ... as 1, 2, ...) or event</span>+++


<<<

== Archīa

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    **Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ an static work), then the actual groundbreaking difference on the workflow used to generate every dictionaries on Cōdex such as this one are the following fact: **we provide machine readable formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with terminology translations.
    +++<br><br>+++
    **Practical implication**: the text documents on _Archīa prō cōdice_ (literal English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an impact.


=== Archīa prō dictiōnāriīs: 4


==== 1603_84_1.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_84_1.no1.tm.hxl.csv[1603_84_1.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container/



==== 1603_84_1.no11.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_84_1.no11.tm.hxl.csv[1603_84_1.no11.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container (expanded with terminology translations)/



==== 1603_84_1.wikiq.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_84_1.wikiq.tm.hxl.csv[1603_84_1.wikiq.tm.hxl.csv]
  /reference URL/@eng-Latn:::
    https://hxltm.etica.ai/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    HXLTM dialect of HXLStandard on CSV RFC 4180. wikiq means #item+conceptum+codicem are strictly Wikidata QIDs.



==== 1603_84_1.no11.tbx

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_84_1.no11.tbx[1603_84_1.no11.tbx]
  /reference URL/@eng-Latn:::
    http://www.terminorgs.net/downloads/TBX_Basic_Version_3.1.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    TBX-Basic is a terminological markup language (TML) that is a lighter version of TBX-Default, the TML that is defined in ISO 30042. TBX-Basic is designed for the localization industry and is based on information from surveys and studies that were conducted by the LISA Term SIG about the types of terminology data that the localization industry requires.



==== 1603_84_1.no11.tmx

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_84_1.no11.tmx[1603_84_1.no11.tmx]
  /reference URL/@eng-Latn:::
    https://www.gala-global.org/tmx-14b

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    The purpose of the Translation Memory eXchange format (TMX) format is to provide a standard method to describe translation memory data that is being exchanged among tools and/or translation vendors, while introducing little or no loss of critical data during the process



=== Archīa prō cōdice: 2


==== 1603_84_1.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_84_1.mul-Latn.codex.adoc[1603_84_1.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.



==== 1603_84_1.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_84_1.mul-Latn.codex.pdf[1603_84_1.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== /Dictiōnāria dentālium/
image::1603_84_1.~1/0~0.svg[title="++Sine nomine++"]

Sine nomine

<<<

[id='1']
=== [`1`] /Quadrant codes - upper right permanent teeth/

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Quadrant codes - upper right permanent teeth/





[id='1_1']
==== [`1_1`] 

Rēs interlinguālibus::
  ix_iso3950:::
    11

  ix_hxlix:::
    ix_iso3950q1d1

  ix_hxlvoc:::
    v_iso3950q1d1





[id='1_2']
==== [`1_2`] 

Rēs interlinguālibus::
  ix_iso3950:::
    12

  ix_hxlix:::
    ix_iso3950q1d2

  ix_hxlvoc:::
    v_iso3950q1d2





[id='1_3']
==== [`1_3`] 

Rēs interlinguālibus::
  ix_iso3950:::
    13

  ix_hxlix:::
    ix_iso3950q1d3

  ix_hxlvoc:::
    v_iso3950q1d3





[id='1_4']
==== [`1_4`] 

Rēs interlinguālibus::
  ix_iso3950:::
    14

  ix_hxlix:::
    ix_iso3950q1d4

  ix_hxlvoc:::
    v_iso3950q1d4





[id='1_5']
==== [`1_5`] 

Rēs interlinguālibus::
  ix_iso3950:::
    15

  ix_hxlix:::
    ix_iso3950q1d5

  ix_hxlvoc:::
    v_iso3950q1d5





[id='1_6']
==== [`1_6`] 

Rēs interlinguālibus::
  ix_iso3950:::
    16

  ix_hxlix:::
    ix_iso3950q1d6

  ix_hxlvoc:::
    v_iso3950q1d6





[id='1_7']
==== [`1_7`] 

Rēs interlinguālibus::
  ix_iso3950:::
    17

  ix_hxlix:::
    ix_iso3950q1d7

  ix_hxlvoc:::
    v_iso3950q1d7





[id='1_8']
==== [`1_8`] 

Rēs interlinguālibus::
  ix_iso3950:::
    18

  ix_hxlix:::
    ix_iso3950q1d8

  ix_hxlvoc:::
    v_iso3950q1d8





<<<

[id='2']
=== [`2`] /Quadrant codes - upper left permanent teeth/

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Quadrant codes - upper left permanent teeth/





[id='2_1']
==== [`2_1`] 

Rēs interlinguālibus::
  ix_iso3950:::
    21

  ix_hxlix:::
    ix_iso3950q2d1

  ix_hxlvoc:::
    v_iso3950q2d1





[id='2_2']
==== [`2_2`] 

Rēs interlinguālibus::
  ix_iso3950:::
    22

  ix_hxlix:::
    ix_iso3950q2d2

  ix_hxlvoc:::
    v_iso3950q2d2





[id='2_3']
==== [`2_3`] 

Rēs interlinguālibus::
  ix_iso3950:::
    23

  ix_hxlix:::
    ix_iso3950q2d3

  ix_hxlvoc:::
    v_iso3950q2d3





[id='2_4']
==== [`2_4`] 

Rēs interlinguālibus::
  ix_iso3950:::
    24

  ix_hxlix:::
    ix_iso3950q2d4

  ix_hxlvoc:::
    v_iso3950q2d4





[id='2_5']
==== [`2_5`] 

Rēs interlinguālibus::
  ix_iso3950:::
    25

  ix_hxlix:::
    ix_iso3950q2d5

  ix_hxlvoc:::
    v_iso3950q2d5





[id='2_6']
==== [`2_6`] 

Rēs interlinguālibus::
  ix_iso3950:::
    26

  ix_hxlix:::
    ix_iso3950q2d6

  ix_hxlvoc:::
    v_iso3950q2d6





[id='2_7']
==== [`2_7`] 

Rēs interlinguālibus::
  ix_iso3950:::
    27

  ix_hxlix:::
    ix_iso3950q2d7

  ix_hxlvoc:::
    v_iso3950q2d7





[id='2_8']
==== [`2_8`] 

Rēs interlinguālibus::
  ix_iso3950:::
    28

  ix_hxlix:::
    ix_iso3950q2d8

  ix_hxlvoc:::
    v_iso3950q2d8





<<<

[id='3']
=== [`3`] /Quadrant codes - lower left permanent teeth/

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Quadrant codes - lower left permanent teeth/





[id='3_1']
==== [`3_1`] 

Rēs interlinguālibus::
  ix_iso3950:::
    31

  ix_hxlix:::
    ix_iso3950q3d1

  ix_hxlvoc:::
    v_iso3950q3d1





[id='3_2']
==== [`3_2`] 

Rēs interlinguālibus::
  ix_iso3950:::
    32

  ix_hxlix:::
    ix_iso3950q3d2

  ix_hxlvoc:::
    v_iso3950q3d2





[id='3_3']
==== [`3_3`] 

Rēs interlinguālibus::
  ix_iso3950:::
    33

  ix_hxlix:::
    ix_iso3950q3d3

  ix_hxlvoc:::
    v_iso3950q3d3





[id='3_4']
==== [`3_4`] 

Rēs interlinguālibus::
  ix_iso3950:::
    34

  ix_hxlix:::
    ix_iso3950q3d4

  ix_hxlvoc:::
    v_iso3950q3d4





[id='3_5']
==== [`3_5`] 

Rēs interlinguālibus::
  ix_iso3950:::
    35

  ix_hxlix:::
    ix_iso3950q3d5

  ix_hxlvoc:::
    v_iso3950q3d5





[id='3_6']
==== [`3_6`] 

Rēs interlinguālibus::
  ix_iso3950:::
    36

  ix_hxlix:::
    ix_iso3950q3d6

  ix_hxlvoc:::
    v_iso3950q3d6





[id='3_7']
==== [`3_7`] 

Rēs interlinguālibus::
  ix_iso3950:::
    37

  ix_hxlix:::
    ix_iso3950q3d7

  ix_hxlvoc:::
    v_iso3950q3d7





[id='3_8']
==== [`3_8`] 

Rēs interlinguālibus::
  ix_iso3950:::
    38

  ix_hxlix:::
    ix_iso3950q3d8

  ix_hxlvoc:::
    v_iso3950q3d8





<<<

[id='4']
=== [`4`] /Quadrant codes - lower right permanent teeth/

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Quadrant codes - lower right permanent teeth/





[id='4_1']
==== [`4_1`] 

Rēs interlinguālibus::
  ix_iso3950:::
    41

  ix_hxlix:::
    ix_iso3950q4d1

  ix_hxlvoc:::
    v_iso3950q4d1





[id='4_2']
==== [`4_2`] 

Rēs interlinguālibus::
  ix_iso3950:::
    42

  ix_hxlix:::
    ix_iso3950q4d2

  ix_hxlvoc:::
    v_iso3950q4d2





[id='4_3']
==== [`4_3`] 

Rēs interlinguālibus::
  ix_iso3950:::
    43

  ix_hxlix:::
    ix_iso3950q4d3

  ix_hxlvoc:::
    v_iso3950q4d3





[id='4_4']
==== [`4_4`] 

Rēs interlinguālibus::
  ix_iso3950:::
    44

  ix_hxlix:::
    ix_iso3950q4d4

  ix_hxlvoc:::
    v_iso3950q4d4





[id='4_5']
==== [`4_5`] 

Rēs interlinguālibus::
  ix_iso3950:::
    45

  ix_hxlix:::
    ix_iso3950q4d5

  ix_hxlvoc:::
    v_iso3950q4d5





[id='4_6']
==== [`4_6`] 

Rēs interlinguālibus::
  ix_iso3950:::
    46

  ix_hxlix:::
    ix_iso3950q4d6

  ix_hxlvoc:::
    v_iso3950q4d6





[id='4_7']
==== [`4_7`] 

Rēs interlinguālibus::
  ix_iso3950:::
    47

  ix_hxlix:::
    ix_iso3950q4d7

  ix_hxlvoc:::
    v_iso3950q4d7





[id='4_8']
==== [`4_8`] 

Rēs interlinguālibus::
  ix_iso3950:::
    48

  ix_hxlix:::
    ix_iso3950q4d8

  ix_hxlvoc:::
    v_iso3950q4d8





<<<

[id='5']
=== [`5`] /Quadrant codes - upper right deciduous teeth/

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Quadrant codes - upper right deciduous teeth/





[id='5_1']
==== [`5_1`] 

Rēs interlinguālibus::
  ix_iso3950:::
    51

  ix_hxlix:::
    ix_iso3950q5d1

  ix_hxlvoc:::
    v_iso3950q5d1





[id='5_2']
==== [`5_2`] 

Rēs interlinguālibus::
  ix_iso3950:::
    52

  ix_hxlix:::
    ix_iso3950q5d2

  ix_hxlvoc:::
    v_iso3950q5d2





[id='5_3']
==== [`5_3`] 

Rēs interlinguālibus::
  ix_iso3950:::
    53

  ix_hxlix:::
    ix_iso3950q5d3

  ix_hxlvoc:::
    v_iso3950q5d3





[id='5_4']
==== [`5_4`] 

Rēs interlinguālibus::
  ix_iso3950:::
    54

  ix_hxlix:::
    ix_iso3950q5d4

  ix_hxlvoc:::
    v_iso3950q5d4





[id='5_5']
==== [`5_5`] 

Rēs interlinguālibus::
  ix_iso3950:::
    55

  ix_hxlix:::
    ix_iso3950q5d5

  ix_hxlvoc:::
    v_iso3950q5d5





<<<

[id='6']
=== [`6`] /Quadrant codes - upper left deciduous teeth/

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Quadrant codes - upper left deciduous teeth/





[id='6_1']
==== [`6_1`] 

Rēs interlinguālibus::
  ix_iso3950:::
    61

  ix_hxlix:::
    ix_iso3950q6d1

  ix_hxlvoc:::
    v_iso3950q6d1





[id='6_2']
==== [`6_2`] 

Rēs interlinguālibus::
  ix_iso3950:::
    62

  ix_hxlix:::
    ix_iso3950q6d2

  ix_hxlvoc:::
    v_iso3950q6d2





[id='6_3']
==== [`6_3`] 

Rēs interlinguālibus::
  ix_iso3950:::
    63

  ix_hxlix:::
    ix_iso3950q6d3

  ix_hxlvoc:::
    v_iso3950q6d3





[id='6_4']
==== [`6_4`] 

Rēs interlinguālibus::
  ix_iso3950:::
    64

  ix_hxlix:::
    ix_iso3950q6d4

  ix_hxlvoc:::
    v_iso3950q6d4





[id='6_5']
==== [`6_5`] 

Rēs interlinguālibus::
  ix_iso3950:::
    65

  ix_hxlix:::
    ix_iso3950q6d5

  ix_hxlvoc:::
    v_iso3950q6d5





<<<

[id='7']
=== [`7`] /Quadrant codes - lower left deciduous teeth/

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Quadrant codes - lower left deciduous teeth/





[id='7_1']
==== [`7_1`] 

Rēs interlinguālibus::
  ix_iso3950:::
    71

  ix_hxlix:::
    ix_iso3950q7d1

  ix_hxlvoc:::
    v_iso3950q7d1





[id='7_2']
==== [`7_2`] 

Rēs interlinguālibus::
  ix_iso3950:::
    72

  ix_hxlix:::
    ix_iso3950q7d2

  ix_hxlvoc:::
    v_iso3950q7d2





[id='7_3']
==== [`7_3`] 

Rēs interlinguālibus::
  ix_iso3950:::
    73

  ix_hxlix:::
    ix_iso3950q7d3

  ix_hxlvoc:::
    v_iso3950q7d3





[id='7_4']
==== [`7_4`] 

Rēs interlinguālibus::
  ix_iso3950:::
    74

  ix_hxlix:::
    ix_iso3950q7d4

  ix_hxlvoc:::
    v_iso3950q7d4





[id='7_5']
==== [`7_5`] 

Rēs interlinguālibus::
  ix_iso3950:::
    75

  ix_hxlix:::
    ix_iso3950q7d5

  ix_hxlvoc:::
    v_iso3950q7d5





<<<

[id='8']
=== [`8`] 





[id='8_1']
==== [`8_1`] 

Rēs interlinguālibus::
  ix_iso3950:::
    81

  ix_hxlix:::
    ix_iso3950q8d1

  ix_hxlvoc:::
    v_iso3950q8d1





[id='8_2']
==== [`8_2`] 

Rēs interlinguālibus::
  ix_iso3950:::
    82

  ix_hxlix:::
    ix_iso3950q8d2

  ix_hxlvoc:::
    v_iso3950q8d2





[id='8_3']
==== [`8_3`] 

Rēs interlinguālibus::
  ix_iso3950:::
    83

  ix_hxlix:::
    ix_iso3950q8d3

  ix_hxlvoc:::
    v_iso3950q8d3





[id='8_4']
==== [`8_4`] 

Rēs interlinguālibus::
  ix_iso3950:::
    84

  ix_hxlix:::
    ix_iso3950q8d4

  ix_hxlvoc:::
    v_iso3950q8d4





[id='8_5']
==== [`8_5`] 

Rēs interlinguālibus::
  ix_iso3950:::
    85

  ix_hxlix:::
    ix_iso3950q8d5

  ix_hxlvoc:::
    v_iso3950q8d5






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language. We're working on this, but we are still not perfected.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.


=== /[Book with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries. Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.


=== /[Book with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.


=== /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!


<<<

