= Cōdex [1603:23:21]: //Dictiōnāria dē Iurum humanorum defensor//
:doctype: book
:title: Cōdex [1603:23:21]: //Dictiōnāria dē Iurum humanorum defensor//
:lang: la
:toc:
:toclevels: 4
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum




{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

<<<
toc::[]


[id=0_999_1603_1]
== Praefātiō 

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
_**Cōdex [1603:23:21]**_ is the book format of the machine-readable dictionaries _**[1603:23:21] //Dictiōnāria dē Iurum humanorum defensor//**_, which are distributed for implementers on external applications. This book is intended as advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies.

Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.

The initiative behind this compilation is also doing other dictionaries and accepts new suggestions of relevant topics on data exchange for humanitarian use. All have in common the fact that both have human translations and (if any) external interlingual codes related to each concept while making the end result explicitly already ready to be usable on average softwares. Naturally, each book version gives extensive explanations for collaborators on how to correct itself which become part of the next weekly release.

|===


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-04-20

|
numerus editionis
|
2022-03-05T01:05:07

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|===


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/scope and content/@eng-Latn
|
This is the most generic type of human rights defender. In addition to defend some type of human rights, MUST not cause intentional harm to other human beings unless in self defense and not disproportional immediate to the danger.

**RELATED DICTIONARIES**


This namespace of dictionaries have related (but not equal) actors which may _help_ other humans using different strategies. The differentiation between then is **very** relevant as this affects perception of neutrality when _help_ is done.


**1603:63:1** //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//

This is stricter and more well know type of humanitarian aid. It MUST focus on immediate needs, which differentiate them from development aid.


**[1603:26:21]** //Dictiōnāria dē Iurum humanorum defensor//

This is the most generic type of human rights defender. In addition to defend some type of human rights, MUST not cause intentional harm to other human beings unless in self defense and not disproportional immediate to the danger.


**[1603:26:36]** //Dictiōnāria dē intraimperiīs lēgisperītīs per lēgēs certiōrātū//

This is a very strict type of **1603:26:21**. The main difference are the modi operandi : uses own country laws or it's signed international treaties to defend specific cases or reforms on country judicial system.

**[1603:45:997]** //(needs be boostrapped)//

Development aid, while may be practiced as part of humanitarian operations to reduce likelihood of future need from foreigner help to do humanitarian aid, is not the same as humanitarian aid. 


**[1603:14:997]** //Dictiōnāria dē relevāminibus per bellīs//

Military relief is a type of intervention on a foreign country justified on reduce individual human suffering which already is not considered a formal peacekeeping operation.

|===


=== Methodī ex verbīs in dictiōnāriīs
NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
The ***[1603:23:21] //Dictiōnāria dē Iurum humanorum defensor//*** uses Wikidata as one strategy to conciliate language terms for one or more of it's concepts.

This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up to date translations.

|
Lingua Anglica (Abecedarium Latinum)
|
**How reliable are the community translations (Wikidata source)?**

The short, default answer is: **they are reliable**, even in cases of no authoritative translations for each subject.

As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).

However, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.

|
Lingua Anglica (Abecedarium Latinum)
|
**Major reasons for "wrong translations" are not translators fault**

TIP: As a rule of thumb, for already very defined concepts where you, as human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.

The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.

It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.

|
Lingua Anglica (Abecedarium Latinum)
|
From the point of view of data conciliation, the following methodology is used to release the terminology translations with the main concept table.

. The main handcrafted lexicographical table (explained on previous topic), also provided on `1603_23_21.no1.tm.hxl.csv`, may reference Wiki QID.
. Every unique QID of  `1603_23_21.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!
.. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares then for general use.
. The query result, with all QIDs and term labels, is shared as `1603_23_21.wikiq.tm.hxl.csv`
. The community reviewed translations of each singular QID is pre-compiled on an individual file `1603_23_21.wikiq.tm.hxl.csv`
. `1603_23_21.no1.tm.hxl.csv` plus `1603_23_21.wikiq.tm.hxl.csv` created `1603_23_21.no11.tm.hxl.csv`

|===

=== Rēs dē factō in dictiōnāriīs
==== Concepta: 1

==== Rēs linguālibus: 1

[%header,cols="15h,25a,~,15"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
1

|===

==== Rēs interlinguālibus: 6
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
The result of this section is a preview. We're aware it is not well formatted for a book format. Sorry for the temporary inconvenience.

|===



scrīptor::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P50
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip50
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_50
#item+rem+definitionem+i_eng+is_latn::: Main creator(s) of a written work (use on works, not humans)


/cōdex pūblicandī/::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P123
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip123
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_123
#item+rem+definitionem+i_eng+is_latn::: organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software


numerus editionis::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P393
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip393
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_393
#item+rem+definitionem+i_eng+is_latn::: number of an edition (first, second, ... as 1, 2, ...) or event


/publication date/@eng-Latn::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P577
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip577
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_577
#item+rem+definitionem+i_eng+is_latn::: Date or point in time when a work was first published or released


/SPDX license ID/@eng-Latn::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P2479
#item+rem+i_qcc+is_zxxx+ix_regulam::: [0-9A-Za-z\.\-]{3,36}[+]?
#item+rem+i_qcc+is_zxxx+ix_wikip1630::: https://spdx.org/licenses/$1.html
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip2479
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_2479
#item+rem+definitionem+i_eng+is_latn::: SPDX license identifier


/scope and content/@eng-Latn::
#item+rem+i_qcc+is_zxxx+ix_wikip::: P7535
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip7535
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_7535
#item+rem+definitionem+i_eng+is_latn::: a summary statement providing an overview of the archival collection

<<<

== Archīa


[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
**Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ an static work), then the actual groundbreaking difference on the workflow used to generate every dictionaries on Cōdex such as this one are the following fact: **we provide machine readable formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with terminology translations.

**Practical implication**: the text documents on _Archīa prō cōdice_ (literal _English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an impact.

|===

=== Archīa prō dictiōnāriīs: 3


==== 1603_23_21.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_23_21.no1.tm.hxl.csv[1603_23_21.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container/



==== 1603_23_21.no11.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_23_21.no11.tm.hxl.csv[1603_23_21.no11.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container (expanded with terminology translations)/



==== 1603_23_21.wikiq.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_23_21.wikiq.tm.hxl.csv[1603_23_21.wikiq.tm.hxl.csv]
  /reference URL/@eng-Latn:::
    https://hxltm.etica.ai/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    HXLTM dialect of HXLStandard on CSV RFC 4180. wikiq means #item+conceptum+codicem are strictly Wikidata QIDs.



=== Archīa prō cōdice: 2


==== 1603_23_21.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_23_21.mul-Latn.codex.adoc[1603_23_21.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.



==== 1603_23_21.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_23_21.mul-Latn.codex.pdf[1603_23_21.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://en.wikipedia.org/wiki/PDF

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== //Dictiōnāria dē Iurum humanorum defensor//
<<<

[id='17']
=== [`17`] /Wikidata QIDs/








[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++/Wikidata QIDs/+++

|===





<<<

== Notā bene

=== /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language. We're working on this, but we are still not perfected.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.


=== /[Book with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries. Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.


=== /[Book with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.


=== /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!


<<<

