= Cōdex [1603:1:6]: /Dictiōnāria de terminī typīs/
:doctype: book
:title: Cōdex [1603:1:6]: /Dictiōnāria de terminī typīs/
:lang: la
:toc:
:toclevels: 4
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge




{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
[quote]
/_**Public domain means that each major common issue only needs to be resolved once**_/@eng-Latn

<<<
toc::[]


[id=0_999_1603_1]
== Praefātiō 

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō
|
Lingua Anglica (Abecedarium Latinum)
|
_**"Cōdex [1603:1:6]"**_ is the book format of the machine-readable dictionaries _**"[1603:1:6] /Dictiōnāria de terminī typīs/"**_,
which are distributed for implementers on external applications.
This book is intended as advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies.

Practical lexicography is the art or craft of compiling, writing and editing dictionaries.
The basics are not far different than a millennia ago:
it is still a very humane, creative work.
It is necessary to be humble:
most of the translator's mistakes are, in fact, not translator's fault, but methodological flaws.
Making sure of a source idea of what a concept represents,
even if it means rewrite and make simpler, annex pictures,
show examples, do whatever to make it be understood,
makes even non-professional translators that care about their own language deliver better results than any alternative.
In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.

The initiative behind this compilation is also doing other dictionaries and accepts new suggestions of relevant topics on data exchange for humanitarian use.
All have in common the fact that both have human translations and (if any) external interlingual codes related to each concept while making the end result explicitly already ready to be usable on average softwares.
Naturally, each book version gives extensive explanations for collaborators on how to correct itself which become part of the next weekly release.

|===


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-01-01

|
numerus editionis
|
2022-02-09T12:08:18

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|
/reference URL/@eng-Latn
|
https://github.com/EticaAI/multilingual-lexicography/issues/16

|===


<<<

== Methodī ex cōdice
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō
|
Lingua Anglica (Abecedarium Latinum)
|
This section explains the methodology of this book and it's machine readable formats. For your convenience the information used to explain the concepts (such as natural language and interlingual codes) which appears in this book are also summarized here. This approach is done both for reviews not needing to open other books (or deal with machine readable files) and also to spot errors on other dictionaries. +++<br><br>+++ About how the book and the dictionaries are compiled, a division of "baseline concept table" and (when relevant for a codex) "translations conciliation" is given different methodologies. +++<br><br>+++ Every book contains at minimum the baseline concept table and explanation of the used fields. This approach helps to release dictionaries faster while ensuring both humans and machines can know what to expect even when they are not ready to receive translations.

|===

=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Rēs dē factō in dictiōnāriīs

==== Rēs linguālibus: 1

[%header,cols="~,~,~,~,~"]
|===
| Cōdex linguae
| Glotto cōdicī
| ISO 639-3
| Wiki QID cōdicī
| Nōmen Latīnum

| mul-Zyyy
| 
| https://iso639-3.sil.org/code/mul[mul]
| 
| Linguae multiplīs (Scrīptum incognitō)

|===

==== Rēs interlinguālibus: 8


===== 1603:1:7:1:91 

[source,json]
----
{
    "#item+conceptum+codicem": "1_91",
    "#item+conceptum+numerordinatio": "1603:1:7:1:91",
    "#item+rem+definitionem+i_eng+is_latn": "QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter \"Q\" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.",
    "#item+rem+i_lat+is_latn": "/Wiki QID/",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikiq",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_q",
    "#item+rem+i_qcc+is_zxxx+ix_regulam": "Q[1-9]\\d*",
    "#status+conceptum+codicem": "19",
    "#status+conceptum+definitionem": "50"
}
----

===== 1603:1:7:2616:50 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_50",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:50",
    "#item+rem+definitionem+i_eng+is_latn": "Main creator(s) of a written work (use on works, not humans)",
    "#item+rem+i_lat+is_latn": "scrīptor",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip50",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_50",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P50",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:123 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_123",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:123",
    "#item+rem+definitionem+i_eng+is_latn": "organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software",
    "#item+rem+i_lat+is_latn": "/cōdex pūblicandī/",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip123",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_123",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P123",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:393 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_393",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:393",
    "#item+rem+definitionem+i_eng+is_latn": "number of an edition (first, second, ... as 1, 2, ...) or event",
    "#item+rem+i_lat+is_latn": "numerus editionis",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip393",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_393",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P393",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:577 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_577",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:577",
    "#item+rem+definitionem+i_eng+is_latn": "Date or point in time when a work was first published or released",
    "#item+rem+i_lat+is_latn": "/publication date/@eng-Latn",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip577",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_577",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P577",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:854 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_854",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:854",
    "#item+rem+definitionem+i_eng+is_latn": "should be used for Internet URLs as references",
    "#item+rem+i_lat+is_latn": "/reference URL/@eng-Latn",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip854",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_854",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P854",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:2479 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_2479",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:2479",
    "#item+rem+definitionem+i_eng+is_latn": "SPDX license identifier",
    "#item+rem+i_lat+is_latn": "/SPDX license ID/@eng-Latn",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip2479",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_2479",
    "#item+rem+i_qcc+is_zxxx+ix_regulam": "[0-9A-Za-z\\.\\-]{3,36}[+]?",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P2479",
    "#item+rem+i_qcc+is_zxxx+ix_wikip1630": "https://spdx.org/licenses/$1.html",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:3916 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_3916",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:3916",
    "#item+rem+definitionem+i_eng+is_latn": "The UNESCO Thesaurus is a controlled and structured list of terms used in subject analysis and retrieval of documents and publications in the fields of education, culture, natural sciences, social and human sciences, communication and information. Continuously enriched and updated, its multidisciplinary terminology reflects the evolution of UNESCO's programmes and activities.",
    "#item+rem+i_lat+is_latn": "UNESCO thēsaurus",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip3916",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_3916",
    "#item+rem+i_qcc+is_zxxx+ix_regulam": "concept[1-9]\\d*",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P3916",
    "#item+rem+i_qcc+is_zxxx+ix_wikip1630": "http://vocabularies.unesco.org/thesaurus/$1",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

<<<

== /Dictiōnāria de terminī typīs/
[id='102786']
=== [`102786`] abbreviātiō





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
Q102786

|
UNESCO thēsaurus
|
concept988

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++abbreviātiō+++

|===




[id='101244']
=== [`101244`] //acronymum//





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
Q101244

|
UNESCO thēsaurus
|
concept989

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++//acronymum//+++

|===




[id='1']
=== [`1`] dēfīnītiō








[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Linguae multiplīs (Scrīptum incognitō)
| +++dēfīnītiō+++

| Linguae multiplīs (Scrīptum incognitō)
| +++https://en.wiktionary.org/wiki/definitio#Latin+++

|===





<<<

[appendix]
= //Open issues on exported PDF format//@eng-Latn


=== //Documentation about how to use the machine-readable dictionaries//@eng-Latn

Is necessary to give a quick introduction (or at least mention) the files generated with this implementer documentation.

=== //Missing fonts to render all term variants//@eng-Latn
The generated PDF does not include all necessary fonts.
Here potential strategy to fix it https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#custom-fonts

=== //Reliability statuses//@eng-Latn

Currently, the reliability of numeric statuses are not well explained on PDF version.
