= Cōdex [1603:1:6]: /Dictiōnāria de terminī typīs/
:doctype: book
:title: Cōdex [1603:1:6]: /Dictiōnāria de terminī typīs/
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum
:front-cover-image: image:1603_1_6.mul-Latn.codex.svg["Cōdex [1603_1_6]: /Dictiōnāria de terminī typīs/",1050,1600]




{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-01-01

|
numerus editionis
|
2022-04-17T20:01:16

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|
/reference URL/@eng-Latn
|
https://github.com/EticaAI/multilingual-lexicography/issues/16

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:1:6]**_ is the book format of the machine-readable dictionaries _**[1603:1:6] /Dictiōnāria de terminī typīs/**_, which are distributed for implementers on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.
    +++<br><br>+++
    **ABOUT LEXICOGRAPHY**
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    **ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**
    +++<br><br>+++
    We're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.
    +++<br><br>+++
    Since the full list of prototypal-dictionaries and dictionaries is huge, one way cited by objective audiences is the following:
    +++<br><br>+++
    . Humanitarian aid
    . Development aid
    . Human rights
    . Military relief (or conflict and conflict-resolution related concepts)
    +++<br><br>+++
    The itens 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).
    +++<br><br>+++
    Note that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    The lexicographers of this work are both volunteers, doing it for free, pro bonō publicō, and don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books. Most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.
    +++<br><br>+++
    There's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work considering it is feasible over 200 languages? The logistics to decide who should be paid, then worldwide cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither sufficient money nor humans interested in being coordinators exist.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Methodī ex verbīs in dictiōnāriīs
NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    The ***[1603:1:6] /Dictiōnāria de terminī typīs/*** uses Wikidata as one strategy to conciliate language terms for one or more of it's concepts.
    +++<br><br>+++
    This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up to date translations.
    +++<br><br>+++
    **How reliable are the community translations (Wikidata source)?**
    +++<br><br>+++
    The short, default answer is: **they are reliable**, even in cases of no authoritative translations for each subject.
    +++<br><br>+++
    As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).
    +++<br><br>+++
    However, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.
    +++<br><br>+++
    **Major reasons for "wrong translations" are not translators fault**
    +++<br><br>+++
    TIP: As a rule of thumb, for already very defined concepts where you, as human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.
    +++<br><br>+++
    The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.
    +++<br><br>+++
    It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.
    +++<br><br>+++
    From the point of view of data conciliation, the following methodology is used to release the terminology translations with the main concept table.
    +++<br><br>+++
    . The main handcrafted lexicographical table (explained on previous topic), also provided on `1603_1_6.no1.tm.hxl.csv`, may reference Wiki QID.
    . Every unique QID of  `1603_1_6.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!
    .. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares then for general use.
    . The query result, with all QIDs and term labels, is shared as `1603_1_6.wikiq.tm.hxl.csv`
    . The community reviewed translations of each singular QID is pre-compiled on an individual file `1603_1_6.wikiq.tm.hxl.csv`
    . `1603_1_6.no1.tm.hxl.csv` plus `1603_1_6.wikiq.tm.hxl.csv` created `1603_1_6.no11.tm.hxl.csv`


=== Rēs dē factō in dictiōnāriīs
==== Concepta: 3

==== Rēs linguālibus: 114

[%header,cols="15h,25a,~,17"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
3

|
ara-Arab
|
https://glottolog.org/resource/languoid/id/arab1395[arab1395]
+++<br>+++
https://iso639-3.sil.org/code/ara[ara]
+++<br>+++ https://www.wikidata.org/wiki/Q13955[Q13955]
|
Macrolingua Arabica (Abecedarium Arabicum)
|
2

|
hye-Armn
|
https://glottolog.org/resource/languoid/id/nucl1235[nucl1235]
+++<br>+++
https://iso639-3.sil.org/code/hye[hye]
+++<br>+++ https://www.wikidata.org/wiki/Q8785[Q8785]
|
Lingua Armenia (Alphabetum Armenium)
|
1

|
ben-Beng
|
https://glottolog.org/resource/languoid/id/beng1280[beng1280]
+++<br>+++
https://iso639-3.sil.org/code/ben[ben]
+++<br>+++ https://www.wikidata.org/wiki/Q9610[Q9610]
|
Lingua Bengali (/ISO 15924 Beng/)
|
2

|
rus-Cyrl
|
https://glottolog.org/resource/languoid/id/russ1263[russ1263]
+++<br>+++
https://iso639-3.sil.org/code/rus[rus]
+++<br>+++ https://www.wikidata.org/wiki/Q7737[Q7737]
|
Lingua Russica (Abecedarium Cyrillicum)
|
2

|
hin-Deva
|
https://glottolog.org/resource/languoid/id/hind1269[hind1269]
+++<br>+++
https://iso639-3.sil.org/code/hin[hin]
+++<br>+++ https://www.wikidata.org/wiki/Q1568[Q1568]
|
Lingua Hindica (Devanāgarī)
|
2

|
kat-Geor
|
https://glottolog.org/resource/languoid/id/nucl1302[nucl1302]
+++<br>+++
https://iso639-3.sil.org/code/kat[kat]
+++<br>+++ https://www.wikidata.org/wiki/Q8108[Q8108]
|
Lingua Georgiana (Abecedarium Georgianum)
|
2

|
guj-Gujr
|
https://glottolog.org/resource/languoid/id/guja1252[guja1252]
+++<br>+++
https://iso639-3.sil.org/code/guj[guj]
+++<br>+++ https://www.wikidata.org/wiki/Q5137[Q5137]
|
Lingua Gujaratensis (/ISO 15924 Gujr/)
|
1

|
pan-Guru
|
https://glottolog.org/resource/languoid/id/panj1256[panj1256]
+++<br>+++
https://iso639-3.sil.org/code/pan[pan]
+++<br>+++ https://www.wikidata.org/wiki/Q58635[Q58635]
|
Lingua Paniabica (/ISO 15924 Guru/)
|
1

|
kan-Knda
|
https://glottolog.org/resource/languoid/id/nucl1305[nucl1305]
+++<br>+++
https://iso639-3.sil.org/code/kan[kan]
+++<br>+++ https://www.wikidata.org/wiki/Q33673[Q33673]
|
Lingua Cannadica (/ISO 15924 Knda/)
|
1

|
kor-Hang
|
https://glottolog.org/resource/languoid/id/kore1280[kore1280]
+++<br>+++
https://iso639-3.sil.org/code/kor[kor]
+++<br>+++ https://www.wikidata.org/wiki/Q9176[Q9176]
|
Lingua Coreana (Abecedarium Coreanum)
|
2

|
heb-Hebr
|
https://glottolog.org/resource/languoid/id/hebr1245[hebr1245]
+++<br>+++
https://iso639-3.sil.org/code/heb[heb]
+++<br>+++ https://www.wikidata.org/wiki/Q9288[Q9288]
|
Lingua Hebraica (Alphabetum Hebraicum)
|
2

|
lat-Latn
|
https://glottolog.org/resource/languoid/id/lati1261[lati1261]
+++<br>+++
https://iso639-3.sil.org/code/lat[lat]
+++<br>+++ https://www.wikidata.org/wiki/Q397[Q397]
|
Lingua Latina (Abecedarium Latinum)
|
2

|
sat-Olck
|
https://glottolog.org/resource/languoid/id/sant1410[sant1410]
+++<br>+++
https://iso639-3.sil.org/code/sat[sat]
+++<br>+++ https://www.wikidata.org/wiki/Q33965[Q33965]
|
Lingua Santali (/ISO 15924 Olck/)
|
1

|
tam-Taml
|
https://glottolog.org/resource/languoid/id/tami1289[tami1289]
+++<br>+++
https://iso639-3.sil.org/code/tam[tam]
+++<br>+++ https://www.wikidata.org/wiki/Q5885[Q5885]
|
Lingua Tamulica (/ISO 15924 Taml/)
|
1

|
tel-Telu
|
https://glottolog.org/resource/languoid/id/telu1262[telu1262]
+++<br>+++
https://iso639-3.sil.org/code/tel[tel]
+++<br>+++ https://www.wikidata.org/wiki/Q8097[Q8097]
|
Lingua Telingana (/ISO 15924 Telu/)
|
1

|
tha-Thai
|
https://glottolog.org/resource/languoid/id/thai1261[thai1261]
+++<br>+++
https://iso639-3.sil.org/code/tha[tha]
+++<br>+++ https://www.wikidata.org/wiki/Q9217[Q9217]
|
Lingua Thai (/ISO 15924 Thai/)
|
1

|
zho-Zyyy
|
https://glottolog.org/resource/languoid/id/sini1245[sini1245]
+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q7850[Q7850]
|
/Macrolingua Sinicae (/ISO 15924 Zyyy/)/
|
2

|
por-Latn
|
https://glottolog.org/resource/languoid/id/port1283[port1283]
+++<br>+++
https://iso639-3.sil.org/code/por[por]
+++<br>+++ https://www.wikidata.org/wiki/Q5146[Q5146]
|
Lingua Lusitana (Abecedarium Latinum)
|
2

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
5

|
fra-Latn
|
https://glottolog.org/resource/languoid/id/stan1290[stan1290]
+++<br>+++
https://iso639-3.sil.org/code/fra[fra]
+++<br>+++ https://www.wikidata.org/wiki/Q150[Q150]
|
Lingua Francogallica (Abecedarium Latinum)
|
2

|
nld-Latn
|
https://glottolog.org/resource/languoid/id/mode1257[mode1257]
+++<br>+++
https://iso639-3.sil.org/code/nld[nld]
+++<br>+++ https://www.wikidata.org/wiki/Q7411[Q7411]
|
Lingua Batavica (Abecedarium Latinum)
|
2

|
deu-Latn
|
https://glottolog.org/resource/languoid/id/stan1295[stan1295]
+++<br>+++
https://iso639-3.sil.org/code/deu[deu]
+++<br>+++ https://www.wikidata.org/wiki/Q188[Q188]
|
Lingua Germanica (Abecedarium Latinum)
|
2

|
spa-Latn
|
https://glottolog.org/resource/languoid/id/stan1288[stan1288]
+++<br>+++
https://iso639-3.sil.org/code/spa[spa]
+++<br>+++ https://www.wikidata.org/wiki/Q1321[Q1321]
|
Lingua Hispanica (Abecedarium Latinum)
|
2

|
ita-Latn
|
https://glottolog.org/resource/languoid/id/ital1282[ital1282]
+++<br>+++
https://iso639-3.sil.org/code/ita[ita]
+++<br>+++ https://www.wikidata.org/wiki/Q652[Q652]
|
Lingua Italiana (Abecedarium Latinum)
|
2

|
gle-Latn
|
https://glottolog.org/resource/languoid/id/iris1253[iris1253]
+++<br>+++
https://iso639-3.sil.org/code/gle[gle]
+++<br>+++ https://www.wikidata.org/wiki/Q9142[Q9142]
|
Lingua Hibernica (Abecedarium Latinum)
|
2

|
swe-Latn
|
https://glottolog.org/resource/languoid/id/swed1254[swed1254]
+++<br>+++
https://iso639-3.sil.org/code/swe[swe]
+++<br>+++ https://www.wikidata.org/wiki/Q9027[Q9027]
|
Lingua Suecica (Abecedarium Latinum)
|
2

|
sqi-Latn
|
https://glottolog.org/resource/languoid/id/alba1267[alba1267]
+++<br>+++
https://iso639-3.sil.org/code/sqi[sqi]
+++<br>+++ https://www.wikidata.org/wiki/Q8748[Q8748]
|
Macrolingua Albanica (/Abecedarium Latinum/)
|
1

|
pol-Latn
|
https://glottolog.org/resource/languoid/id/poli1260[poli1260]
+++<br>+++
https://iso639-3.sil.org/code/pol[pol]
+++<br>+++ https://www.wikidata.org/wiki/Q809[Q809]
|
Lingua Polonica (Abecedarium Latinum)
|
2

|
fin-Latn
|
https://glottolog.org/resource/languoid/id/finn1318[finn1318]
+++<br>+++
https://iso639-3.sil.org/code/fin[fin]
+++<br>+++ https://www.wikidata.org/wiki/Q1412[Q1412]
|
Lingua Finnica (Abecedarium Latinum)
|
2

|
ron-Latn
|
https://glottolog.org/resource/languoid/id/roma1327[roma1327]
+++<br>+++
https://iso639-3.sil.org/code/ron[ron]
+++<br>+++ https://www.wikidata.org/wiki/Q7913[Q7913]
|
Lingua Dacoromanica (Abecedarium Latinum)
|
2

|
vie-Latn
|
https://glottolog.org/resource/languoid/id/viet1252[viet1252]
+++<br>+++
https://iso639-3.sil.org/code/vie[vie]
+++<br>+++ https://www.wikidata.org/wiki/Q9199[Q9199]
|
Lingua Vietnamensis (Abecedarium Latinum)
|
2

|
cat-Latn
|
https://glottolog.org/resource/languoid/id/stan1289[stan1289]
+++<br>+++
https://iso639-3.sil.org/code/cat[cat]
+++<br>+++ https://www.wikidata.org/wiki/Q7026[Q7026]
|
Lingua Catalana (Abecedarium Latinum)
|
2

|
ukr-Cyrl
|
https://glottolog.org/resource/languoid/id/ukra1253[ukra1253]
+++<br>+++
https://iso639-3.sil.org/code/ukr[ukr]
+++<br>+++ https://www.wikidata.org/wiki/Q8798[Q8798]
|
Lingua Ucrainica (Abecedarium Cyrillicum)
|
2

|
bul-Cyrl
|
https://glottolog.org/resource/languoid/id/bulg1262[bulg1262]
+++<br>+++
https://iso639-3.sil.org/code/bul[bul]
+++<br>+++ https://www.wikidata.org/wiki/Q7918[Q7918]
|
Lingua Bulgarica (Abecedarium Cyrillicum)
|
2

|
slv-Latn
|
https://glottolog.org/resource/languoid/id/slov1268[slov1268]
+++<br>+++
https://iso639-3.sil.org/code/slv[slv]
+++<br>+++ https://www.wikidata.org/wiki/Q9063[Q9063]
|
Lingua Slovena (Abecedarium Latinum)
|
2

|
nob-Latn
|
https://glottolog.org/resource/languoid/id/norw1259[norw1259]
+++<br>+++
https://iso639-3.sil.org/code/nob[nob]
+++<br>+++ https://www.wikidata.org/wiki/Q25167[Q25167]
|
/Bokmål/ (Abecedarium Latinum)
|
2

|
ces-Latn
|
https://glottolog.org/resource/languoid/id/czec1258[czec1258]
+++<br>+++
https://iso639-3.sil.org/code/ces[ces]
+++<br>+++ https://www.wikidata.org/wiki/Q9056[Q9056]
|
Lingua Bohemica (Abecedarium Latinum)
|
2

|
dan-Latn
|
https://glottolog.org/resource/languoid/id/dani1285[dani1285]
+++<br>+++
https://iso639-3.sil.org/code/dan[dan]
+++<br>+++ https://www.wikidata.org/wiki/Q9035[Q9035]
|
Lingua Danica (Abecedarium Latinum)
|
2

|
jpn-Jpan
|
https://glottolog.org/resource/languoid/id/nucl1643[nucl1643]
+++<br>+++
https://iso639-3.sil.org/code/jpn[jpn]
+++<br>+++ https://www.wikidata.org/wiki/Q5287[Q5287]
|
Lingua Iaponica (Scriptura Iaponica)
|
2

|
nno-Latn
|
https://glottolog.org/resource/languoid/id/norw1262[norw1262]
+++<br>+++
https://iso639-3.sil.org/code/nno[nno]
+++<br>+++ https://www.wikidata.org/wiki/Q25164[Q25164]
|
/Nynorsk/ (Abecedarium Latinum)
|
2

|
mal-Mlym
|
https://glottolog.org/resource/languoid/id/mala1464[mala1464]
+++<br>+++
https://iso639-3.sil.org/code/mal[mal]
+++<br>+++ https://www.wikidata.org/wiki/Q36236[Q36236]
|
Lingua Malabarica (/Malayalam script/)
|
1

|
ind-Latn
|
https://glottolog.org/resource/languoid/id/indo1316[indo1316]
+++<br>+++
https://iso639-3.sil.org/code/ind[ind]
+++<br>+++ https://www.wikidata.org/wiki/Q9240[Q9240]
|
Lingua Indonesiana (Abecedarium Latinum)
|
2

|
fas-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/fas[fas]
+++<br>+++ https://www.wikidata.org/wiki/Q9168[Q9168]
|
Macrolingua Persica (//Abecedarium Arabicum//)
|
2

|
hun-Latn
|
https://glottolog.org/resource/languoid/id/hung1274[hung1274]
+++<br>+++
https://iso639-3.sil.org/code/hun[hun]
+++<br>+++ https://www.wikidata.org/wiki/Q9067[Q9067]
|
Lingua Hungarica (Abecedarium Latinum)
|
2

|
eus-Latn
|
https://glottolog.org/resource/languoid/id/basq1248[basq1248]
+++<br>+++
https://iso639-3.sil.org/code/eus[eus]
+++<br>+++ https://www.wikidata.org/wiki/Q8752[Q8752]
|
Lingua Vasconica (Abecedarium Latinum)
|
2

|
cym-Latn
|
https://glottolog.org/resource/languoid/id/wels1247[wels1247]
+++<br>+++
https://iso639-3.sil.org/code/cym[cym]
+++<br>+++ https://www.wikidata.org/wiki/Q9309[Q9309]
|
Lingua Cambrica (Abecedarium Latinum)
|
2

|
glg-Latn
|
https://glottolog.org/resource/languoid/id/gali1258[gali1258]
+++<br>+++
https://iso639-3.sil.org/code/glg[glg]
+++<br>+++ https://www.wikidata.org/wiki/Q9307[Q9307]
|
Lingua Gallaica (Abecedarium Latinum)
|
2

|
slk-Latn
|
https://glottolog.org/resource/languoid/id/slov1269[slov1269]
+++<br>+++
https://iso639-3.sil.org/code/slk[slk]
+++<br>+++ https://www.wikidata.org/wiki/Q9058[Q9058]
|
Lingua Slovaca (Abecedarium Latinum)
|
2

|
epo-Latn
|
https://glottolog.org/resource/languoid/id/espe1235[espe1235]
+++<br>+++
https://iso639-3.sil.org/code/epo[epo]
+++<br>+++ https://www.wikidata.org/wiki/Q143[Q143]
|
Lingua Esperantica (Abecedarium Latinum)
|
2

|
msa-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/msa[msa]
+++<br>+++ https://www.wikidata.org/wiki/Q9237[Q9237]
|
Macrolingua Malayana (/ISO 15924 Zyyy/)
|
2

|
est-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/est[est]
+++<br>+++ https://www.wikidata.org/wiki/Q9072[Q9072]
|
Macrolingua Estonica (Abecedarium Latinum)
|
2

|
hrv-Latn
|
https://glottolog.org/resource/languoid/id/croa1245[croa1245]
+++<br>+++
https://iso639-3.sil.org/code/hrv[hrv]
+++<br>+++ https://www.wikidata.org/wiki/Q6654[Q6654]
|
Lingua Croatica (Abecedarium Latinum)
|
2

|
tur-Latn
|
https://glottolog.org/resource/languoid/id/nucl1301[nucl1301]
+++<br>+++
https://iso639-3.sil.org/code/tur[tur]
+++<br>+++ https://www.wikidata.org/wiki/Q256[Q256]
|
Lingua Turcica (Abecedarium Latinum)
|
2

|
nds-Latn
|
https://glottolog.org/resource/languoid/id/lowg1239[lowg1239]
+++<br>+++
https://iso639-3.sil.org/code/nds[nds]
+++<br>+++ https://www.wikidata.org/wiki/Q25433[Q25433]
|
Lingua Saxonica (Abecedarium Latinum)
|
2

|
oci-Latn
|
https://glottolog.org/resource/languoid/id/occi1239[occi1239]
+++<br>+++
https://iso639-3.sil.org/code/oci[oci]
+++<br>+++ https://www.wikidata.org/wiki/Q14185[Q14185]
|
Lingua Occitana (Abecedarium Latinum)
|
1

|
bre-Latn
|
https://glottolog.org/resource/languoid/id/bret1244[bret1244]
+++<br>+++
https://iso639-3.sil.org/code/bre[bre]
+++<br>+++ https://www.wikidata.org/wiki/Q12107[Q12107]
|
Lingua Britonica (Abecedarium Latinum)
|
1

|
afr-Latn
|
https://glottolog.org/resource/languoid/id/afri1274[afri1274]
+++<br>+++
https://iso639-3.sil.org/code/afr[afr]
+++<br>+++ https://www.wikidata.org/wiki/Q14196[Q14196]
|
Lingua Batava Capitensis (Abecedarium Latinum)
|
2

|
ltz-Latn
|
https://glottolog.org/resource/languoid/id/luxe1241[luxe1241]
+++<br>+++
https://iso639-3.sil.org/code/ltz[ltz]
+++<br>+++ https://www.wikidata.org/wiki/Q9051[Q9051]
|
Lingua Luxemburgensis (Abecedarium Latinum)
|
2

|
sco-Latn
|
https://glottolog.org/resource/languoid/id/scot1243[scot1243]
+++<br>+++
https://iso639-3.sil.org/code/sco[sco]
+++<br>+++ https://www.wikidata.org/wiki/Q14549[Q14549]
|
Lingua Scotica quae Teutonica (Abecedarium Latinum)
|
1

|
arg-Latn
|
https://glottolog.org/resource/languoid/id/arag1245[arag1245]
+++<br>+++
https://iso639-3.sil.org/code/arg[arg]
+++<br>+++ https://www.wikidata.org/wiki/Q8765[Q8765]
|
Lingua Aragonensis (Abecedarium Latinum)
|
1

|
zho-Hant
|

+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q18130932[Q18130932]
|
//Traditional Chinese// (/ISO 15924 Hant/)
|
2

|
gsw-Latn
|
https://glottolog.org/resource/languoid/id/swis1247[swis1247]
+++<br>+++
https://iso639-3.sil.org/code/gsw[gsw]
+++<br>+++ https://www.wikidata.org/wiki/Q131339[Q131339]
|
Dialecti Alemannicae (Abecedarium Latinum)
|
1

|
isl-Latn
|
https://glottolog.org/resource/languoid/id/icel1247[icel1247]
+++<br>+++
https://iso639-3.sil.org/code/isl[isl]
+++<br>+++ https://www.wikidata.org/wiki/Q294[Q294]
|
Lingua Islandica (Abecedarium Latinum)
|
2

|
vec-Latn
|
https://glottolog.org/resource/languoid/id/vene1258[vene1258]
+++<br>+++
https://iso639-3.sil.org/code/vec[vec]
+++<br>+++ https://www.wikidata.org/wiki/Q32724[Q32724]
|
Lingua Veneta (Abecedarium Latinum)
|
2

|
scn-Latn
|
https://glottolog.org/resource/languoid/id/sici1248[sici1248]
+++<br>+++
https://iso639-3.sil.org/code/scn[scn]
+++<br>+++ https://www.wikidata.org/wiki/Q33973[Q33973]
|
Lingua Sicula (Abecedarium Latinum)
|
1

|
srd-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/srd[srd]
+++<br>+++ https://www.wikidata.org/wiki/Q33976[Q33976]
|
Macrolingua Sarda (Abecedarium Latinum)
|
1

|
gla-Latn
|
https://glottolog.org/resource/languoid/id/scot1245[scot1245]
+++<br>+++
https://iso639-3.sil.org/code/gla[gla]
+++<br>+++ https://www.wikidata.org/wiki/Q9314[Q9314]
|
Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum)
|
1

|
srp-Latn
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q21161949[Q21161949]
|
/Serbian/ (Abecedarium Latinum)
|
2

|
wuu-Zyyy
|
https://glottolog.org/resource/languoid/id/wuch1236[wuch1236]
+++<br>+++
https://iso639-3.sil.org/code/wuu[wuu]
+++<br>+++ https://www.wikidata.org/wiki/Q34290[Q34290]
|
//Macrolingua Wu// (/ISO 15924 Zyyy/)
|
2

|
srp-Cyrl
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q9299[Q9299]
|
Lingua Serbica (Abecedarium Cyrillicum)
|
2

|
urd-Arab
|
https://glottolog.org/resource/languoid/id/urdu1245[urdu1245]
+++<br>+++
https://iso639-3.sil.org/code/urd[urd]
+++<br>+++ https://www.wikidata.org/wiki/Q1617[Q1617]
|
Lingua Urdu (Abecedarium Arabicum)
|
2

|
lit-Latn
|
https://glottolog.org/resource/languoid/id/lith1251[lith1251]
+++<br>+++
https://iso639-3.sil.org/code/lit[lit]
+++<br>+++ https://www.wikidata.org/wiki/Q9083[Q9083]
|
Lingua Lithuanica (Abecedarium Latinum)
|
1

|
hbs-Latn
|
https://glottolog.org/resource/languoid/id/sout1528[sout1528]
+++<br>+++
https://iso639-3.sil.org/code/hbs[hbs]
+++<br>+++ https://www.wikidata.org/wiki/Q9301[Q9301]
|
Macrolingua Serbocroatica (Abecedarium Latinum)
|
2

|
lav-Latn
|
https://glottolog.org/resource/languoid/id/latv1249[latv1249]
+++<br>+++
https://iso639-3.sil.org/code/lav[lav]
+++<br>+++ https://www.wikidata.org/wiki/Q9078[Q9078]
|
Macrolingua Lettonica (Abecedarium Latinum)
|
2

|
bos-Latn
|
https://glottolog.org/resource/languoid/id/bosn1245[bosn1245]
+++<br>+++
https://iso639-3.sil.org/code/bos[bos]
+++<br>+++ https://www.wikidata.org/wiki/Q9303[Q9303]
|
Lingua Bosnica (Abecedarium Latinum)
|
1

|
ell-Grek
|
https://glottolog.org/resource/languoid/id/mode1248[mode1248]
+++<br>+++
https://iso639-3.sil.org/code/ell[ell]
+++<br>+++ https://www.wikidata.org/wiki/Q36510[Q36510]
|
Lingua Neograeca (Alphabetum Graecum)
|
2

|
fry-Latn
|
https://glottolog.org/resource/languoid/id/west2354[west2354]
+++<br>+++
https://iso639-3.sil.org/code/fry[fry]
+++<br>+++ https://www.wikidata.org/wiki/Q27175[Q27175]
|
Lingua Frisice occidentalis (Abecedarium Latinum)
|
1

|
che-Cyrl
|
https://glottolog.org/resource/languoid/id/chec1245[chec1245]
+++<br>+++
https://iso639-3.sil.org/code/che[che]
+++<br>+++ https://www.wikidata.org/wiki/Q33350[Q33350]
|
Lingua Tsetsenica (Abecedarium Cyrillicum)
|
1

|
bel-Cyrl
|
https://glottolog.org/resource/languoid/id/bela1254[bela1254]
+++<br>+++
https://iso639-3.sil.org/code/bel[bel]
+++<br>+++ https://www.wikidata.org/wiki/Q9091[Q9091]
|
Lingua Ruthenica Alba (Abecedarium Cyrillicum)
|
2

|
kab-Latn
|
https://glottolog.org/resource/languoid/id/kaby1243[kaby1243]
+++<br>+++
https://iso639-3.sil.org/code/kab[kab]
+++<br>+++ https://www.wikidata.org/wiki/Q35853[Q35853]
|
/Kabyle language/ (Abecedarium Latinum)
|
1

|
mar-Deva
|
https://glottolog.org/resource/languoid/id/mara1378[mara1378]
+++<br>+++
https://iso639-3.sil.org/code/mar[mar]
+++<br>+++ https://www.wikidata.org/wiki/Q1571[Q1571]
|
Lingua Marathica (Devanāgarī)
|
1

|
ban-Latn
|
https://glottolog.org/resource/languoid/id/bali1278[bali1278]
+++<br>+++
https://iso639-3.sil.org/code/ban[ban]
+++<br>+++ https://www.wikidata.org/wiki/Q33070[Q33070]
|
/Balinese/ (Abecedarium Latinum)
|
1

|
ast-Latn
|
https://glottolog.org/resource/languoid/id/astu1245[astu1245]
+++<br>+++
https://iso639-3.sil.org/code/ast[ast]
+++<br>+++ https://www.wikidata.org/wiki/Q29507[Q29507]
|
Lingua Asturiana (Abecedarium Latinum)
|
2

|
diq-Latn
|
https://glottolog.org/resource/languoid/id/diml1238[diml1238]
+++<br>+++
https://iso639-3.sil.org/code/diq[diq]
+++<br>+++ https://www.wikidata.org/wiki/Q10199[Q10199]
|
Lingua Zazaca (Abecedarium Latinum)
|
1

|
hak-Zyyy
|
https://glottolog.org/resource/languoid/id/hakk1236[hakk1236]
+++<br>+++
https://iso639-3.sil.org/code/hak[hak]
+++<br>+++ https://www.wikidata.org/wiki/Q33375[Q33375]
|
/Hakka Chinese/ (/ISO 15924 Zyyy/)
|
1

|
nan-Latn
|
https://glottolog.org/resource/languoid/id/minn1241[minn1241]
+++<br>+++
https://iso639-3.sil.org/code/nan[nan]
+++<br>+++ https://www.wikidata.org/wiki/Q36495[Q36495]
|
/Min Nan Chinese/ (Abecedarium Latinum)
|
1

|
pnb-Arab
|
https://glottolog.org/resource/languoid/id/west2386[west2386]
+++<br>+++
https://iso639-3.sil.org/code/pnb[pnb]
+++<br>+++ https://www.wikidata.org/wiki/Q1389492[Q1389492]
|
Lingua Paniabica occidentalis (Abecedarium Arabicum)
|
2

|
smn-Latn
|
https://glottolog.org/resource/languoid/id/inar1241[inar1241]
+++<br>+++
https://iso639-3.sil.org/code/smn[smn]
+++<br>+++ https://www.wikidata.org/wiki/Q33462[Q33462]
|
/Inari Sami/ (Abecedarium Latinum)
|
1

|
yue-Zyyy
|
https://glottolog.org/resource/languoid/id/yuec1235[yuec1235]
+++<br>+++
https://iso639-3.sil.org/code/yue[yue]
+++<br>+++ https://www.wikidata.org/wiki/Q7033959[Q7033959]
|
Lingua Yue (/ISO 15924 Zyyy/)
|
1

|
swa-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/swa[swa]
+++<br>+++ https://www.wikidata.org/wiki/Q7838[Q7838]
|
Macrolingua Suahelica (Abecedarium Latinum)
|
2

|
yor-Latn
|
https://glottolog.org/resource/languoid/id/yoru1245[yoru1245]
+++<br>+++
https://iso639-3.sil.org/code/yor[yor]
+++<br>+++ https://www.wikidata.org/wiki/Q34311[Q34311]
|
Lingua yoruba (Abecedarium Latinum)
|
1

|
yid-Hebr
|
https://glottolog.org/resource/languoid/id/yidd1255[yidd1255]
+++<br>+++
https://iso639-3.sil.org/code/yid[yid]
+++<br>+++ https://www.wikidata.org/wiki/Q8641[Q8641]
|
Macrolingua Iudaeo-Germanica (Alphabetum Hebraicum)
|
2

|
uzb-Latn
|
https://glottolog.org/resource/languoid/id/uzbe1247[uzbe1247]
+++<br>+++
https://iso639-3.sil.org/code/uzb[uzb]
+++<br>+++ https://www.wikidata.org/wiki/Q9264[Q9264]
|
Macrolingua Uzbecica (Abecedarium Latinum)
|
1

|
tat-Zyyy
|
https://glottolog.org/resource/languoid/id/tata1255[tata1255]
+++<br>+++
https://iso639-3.sil.org/code/tat[tat]
+++<br>+++ https://www.wikidata.org/wiki/Q25285[Q25285]
|
Lingua Tatarica (/ISO 15924 Zyyy/)
|
1

|
tuk-Latn
|
https://glottolog.org/resource/languoid/id/turk1304[turk1304]
+++<br>+++
https://iso639-3.sil.org/code/tuk[tuk]
+++<br>+++ https://www.wikidata.org/wiki/Q9267[Q9267]
|
Lingua Turcomannica (Abecedarium Latinum)
|
1

|
abk-Cyrl
|
https://glottolog.org/resource/languoid/id/abkh1244[abkh1244]
+++<br>+++
https://iso639-3.sil.org/code/abk[abk]
+++<br>+++ https://www.wikidata.org/wiki/Q5111[Q5111]
|
Lingua Abasgica (Abecedarium Cyrillicum)
|
1

|
aze-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/aze[aze]
+++<br>+++ https://www.wikidata.org/wiki/Q9292[Q9292]
|
Macrolingua Atropatenica (Abecedarium Latinum)
|
1

|
bak-Cyrl
|
https://glottolog.org/resource/languoid/id/bash1264[bash1264]
+++<br>+++
https://iso639-3.sil.org/code/bak[bak]
+++<br>+++ https://www.wikidata.org/wiki/Q13389[Q13389]
|
Lingua Baschkirica (Abecedarium Cyrillicum)
|
1

|
chv-Cyrl
|
https://glottolog.org/resource/languoid/id/chuv1255[chuv1255]
+++<br>+++
https://iso639-3.sil.org/code/chv[chv]
+++<br>+++ https://www.wikidata.org/wiki/Q33348[Q33348]
|
Lingua Tschuvaschica (Abecedarium Cyrillicum)
|
1

|
hat-Latn
|
https://glottolog.org/resource/languoid/id/hait1244[hait1244]
+++<br>+++
https://iso639-3.sil.org/code/hat[hat]
+++<br>+++ https://www.wikidata.org/wiki/Q33491[Q33491]
|
Lingua creola Haitiana (Abecedarium Latinum)
|
1

|
kaz-Zyyy
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q9252[Q9252]
|
Lingua Kazachica (/ISO 15924 Zyyy/)
|
2

|
kaz-Arab
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362991[Q64362991]
|
Lingua Kazachica (Abecedarium Arabicum)
|
1

|
kaz-Cyrl
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362992[Q64362992]
|
Lingua Kazachica (Abecedarium Cyrillicum)
|
1

|
kaz-Latn
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362993[Q64362993]
|
Lingua Kazachica (Abecedarium Latinum)
|
1

|
kir-Zyyy
|
https://glottolog.org/resource/languoid/id/kirg1245[kirg1245]
+++<br>+++
https://iso639-3.sil.org/code/kir[kir]
+++<br>+++ https://www.wikidata.org/wiki/Q9255[Q9255]
|
Lingua Kyrgyzensis (/ISO 15924 Zyyy/)
|
1

|
mkd-Cyrl
|
https://glottolog.org/resource/languoid/id/mace1250[mace1250]
+++<br>+++
https://iso639-3.sil.org/code/mkd[mkd]
+++<br>+++ https://www.wikidata.org/wiki/Q9296[Q9296]
|
Lingua Macedonica (Abecedarium Cyrillicum)
|
2

|
mon-Cyrl
|
https://glottolog.org/resource/languoid/id/mong1331[mong1331]
+++<br>+++
https://iso639-3.sil.org/code/mon[mon]
+++<br>+++ https://www.wikidata.org/wiki/Q9246[Q9246]
|
Macrolingua Mongolica (Abecedarium Cyrillicum)
|
1

|
kin-Latn
|
https://glottolog.org/resource/languoid/id/kiny1244[kiny1244]
+++<br>+++
https://iso639-3.sil.org/code/kin[kin]
+++<br>+++ https://www.wikidata.org/wiki/Q33573[Q33573]
|
/Kinyarwanda/ (Abecedarium Latinum)
|
1

|
snd-Arab
|
https://glottolog.org/resource/languoid/id/sind1272[sind1272]
+++<br>+++
https://iso639-3.sil.org/code/snd[snd]
+++<br>+++ https://www.wikidata.org/wiki/Q33997[Q33997]
|
Lingua Sindhuica (Abecedarium Arabicum)
|
1

|
sme-Latn
|
https://glottolog.org/resource/languoid/id/nort2671[nort2671]
+++<br>+++
https://iso639-3.sil.org/code/sme[sme]
+++<br>+++ https://www.wikidata.org/wiki/Q33947[Q33947]
|
Lingua Samica septentrionalis (Abecedarium Latinum)
|
1

|
tgk-Zyyy
|
https://glottolog.org/resource/languoid/id/taji1245[taji1245]
+++<br>+++
https://iso639-3.sil.org/code/tgk[tgk]
+++<br>+++ https://www.wikidata.org/wiki/Q9260[Q9260]
|
Lingua Tadzikica (/ISO 15924 Zyyy/)
|
2

|
ina-Latn
|
https://glottolog.org/resource/languoid/id/inte1239[inte1239]
+++<br>+++
https://iso639-3.sil.org/code/ina[ina]
+++<br>+++ https://www.wikidata.org/wiki/Q35934[Q35934]
|
Interlingua (Abecedarium Latinum)
|
1

|
ido-Latn
|
https://glottolog.org/resource/languoid/id/idoo1234[idoo1234]
+++<br>+++
https://iso639-3.sil.org/code/ido[ido]
+++<br>+++ https://www.wikidata.org/wiki/Q35224[Q35224]
|
Ido (Abecedarium Latinum)
|
2

|===

==== Rēs interlinguālibus: 8
Rēs::
  /Wiki QID/:::
    Rēs interlinguālibus::::
      /rēgulam/;;
        Q[1-9]\d*

      ix_hxlix;;
        ix_wikiq

      ix_hxlvoc;;
        v_wiki_q

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/Wiki QID/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.</span>+++

  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wikip2479

      ix_hxlvoc;;
        v_wiki_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">SPDX license identifier</span>+++

  scrīptor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P50[P50]

      ix_hxlix;;
        ix_wikip50

      ix_hxlvoc;;
        v_wiki_p_50

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">scrīptor</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Main creator(s) of a written work (use on works, not humans)</span>+++

  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wikip577

      ix_hxlvoc;;
        v_wiki_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Date or point in time when a work was first published or released</span>+++

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wikip123

      ix_hxlvoc;;
        v_wiki_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software</span>+++

  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wikip393

      ix_hxlvoc;;
        v_wiki_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">number of an edition (first, second, ... as 1, 2, ...) or event</span>+++

  UNESCO thēsaurus:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P3916[P3916]

      /rēgulam/;;
        concept[1-9]\d*

      /formatter URL/@eng-Latn;;
        http://vocabularies.unesco.org/thesaurus/$1

      ix_hxlix;;
        ix_wikip3916

      ix_hxlvoc;;
        v_wiki_p_3916

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">UNESCO thēsaurus</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">The UNESCO Thesaurus is a controlled and structured list of terms used in subject analysis and retrieval of documents and publications in the fields of education, culture, natural sciences, social and human sciences, communication and information. Continuously enriched and updated, its multidisciplinary terminology reflects the evolution of UNESCO's programmes and activities.</span>+++

  /reference URL/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P854[P854]

      ix_hxlix;;
        ix_wikip854

      ix_hxlvoc;;
        v_wiki_p_854

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/reference URL/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">should be used for Internet URLs as references</span>+++


<<<

== Archīa

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    **Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ an static work), then the actual groundbreaking difference on the workflow used to generate every dictionaries on Cōdex such as this one are the following fact: **we provide machine readable formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with terminology translations.
    +++<br><br>+++
    **Practical implication**: the text documents on _Archīa prō cōdice_ (literal English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an impact.


=== Archīa prō dictiōnāriīs: 4


==== 1603_1_6.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_6.no1.tm.hxl.csv[1603_1_6.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container/



==== 1603_1_6.no11.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_6.no11.tm.hxl.csv[1603_1_6.no11.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container (expanded with terminology translations)/



==== 1603_1_6.wikiq.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_6.wikiq.tm.hxl.csv[1603_1_6.wikiq.tm.hxl.csv]
  /reference URL/@eng-Latn:::
    https://hxltm.etica.ai/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    HXLTM dialect of HXLStandard on CSV RFC 4180. wikiq means #item+conceptum+codicem are strictly Wikidata QIDs.



==== 1603_1_6.no11.tbx

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_6.no11.tbx[1603_1_6.no11.tbx]
  /reference URL/@eng-Latn:::
    http://www.terminorgs.net/downloads/TBX_Basic_Version_3.1.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    TBX-Basic is a terminological markup language (TML) that is a lighter version of TBX-Default, the TML that is defined in ISO 30042. TBX-Basic is designed for the localization industry and is based on information from surveys and studies that were conducted by the LISA Term SIG about the types of terminology data that the localization industry requires.



==== 1603_1_6.no11.tmx

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_6.no11.tmx[1603_1_6.no11.tmx]
  /reference URL/@eng-Latn:::
    https://www.gala-global.org/tmx-14b

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    The purpose of the Translation Memory eXchange format (TMX) format is to provide a standard method to describe translation memory data that is being exchanged among tools and/or translation vendors, while introducing little or no loss of critical data during the process



=== Archīa prō cōdice: 2


==== 1603_1_6.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_6.mul-Latn.codex.adoc[1603_1_6.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.



==== 1603_1_6.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_6.mul-Latn.codex.pdf[1603_1_6.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== /Dictiōnāria de terminī typīs/
<<<

[id='102786']
=== [`102786`] abbreviatio

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q102786[Q102786]

  UNESCO thēsaurus:::
    http://vocabularies.unesco.org/thesaurus/concept988[concept988]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    abbreviātiō

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">abbreviatio</span>+++

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">اختصار</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Հապավում</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">সংক্ষেপন</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">аббревиатура</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">सूचकाक्षर</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">აბრევიატურა</span>+++

  Lingua Gujaratensis (/ISO 15924 Gujr/):::
    +++<span lang="gu">સંક્ષિપ્ત શબ્દ</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಸಂಕ್ಷೇಪಣ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">준말</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">שם קצר</span>+++

  Lingua Santali (/ISO 15924 Olck/):::
    +++<span lang="sat">ᱠᱷᱟᱴᱚᱛ</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">அஃகுப்பெயர்</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">縮寫</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">abreviatura</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">abbreviation</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">abréviation</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">afkorting</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Abkürzung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">abreviatura</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">abbreviazione</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">Giorrúchán (teanga)</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">förkortning</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">shkurtesë</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">skrót</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">lyhenne</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Abreviere</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">viết tắt</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">abreviatura</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">абревіатура</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Абревиатура</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Kratica</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">forkortelse</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">zkratka</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">forkortelse</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">略語</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">forkorting</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">ചുരുക്കെഴുത്ത്</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">singkatan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">کوتهنوشت</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">rövidítés</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Laburdura</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">Byrfodd</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Abreviatura</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">skratka</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">mallongigo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">Singkatan kata</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">lühend</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Kratica</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">kısaltmalar</span>+++

  Lingua Saxonica (Abecedarium Latinum):::
    +++<span lang="nds">Afkörten</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Afkorting</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Ofkierzung</span>+++

  Lingua Aragonensis (Abecedarium Latinum):::
    +++<span lang="an">Abreviadura</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">縮寫</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Skammstöfun</span>+++

  Lingua Veneta (Abecedarium Latinum):::
    +++<span lang="vec">scursamento</span>+++

  Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum):::
    +++<span lang="gd">Giorrachadh</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">Abrevijatura</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">缩写</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">абревијатура</span>+++

  Lingua Urdu (Abecedarium Arabicum):::
    +++<span lang="ur">مخفف</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Kratica</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">abreviatūra</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">Συντομογραφία</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Ofkoarting</span>+++

  Lingua Tsetsenica (Abecedarium Cyrillicum):::
    +++<span lang="ce">Аббревиатура</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">абрэвіятура</span>+++

  /Kabyle language/ (Abecedarium Latinum):::
    +++<span lang="kab">Asegzel (tutlayt)</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">संक्षिप्त रूप</span>+++

  /Balinese/ (Abecedarium Latinum):::
    +++<span lang="ban">Aksara anceng</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">abreviatura</span>+++

  Lingua Zazaca (Abecedarium Latinum):::
    +++<span lang="diq">Kılmkerdış</span>+++

  /Hakka Chinese/ (/ISO 15924 Zyyy/):::
    +++<span lang="hak">Suk-siá</span>+++

  Lingua Paniabica occidentalis (Abecedarium Arabicum):::
    +++<span lang="pnb">مخفف</span>+++

  /Inari Sami/ (Abecedarium Latinum):::
    +++<span lang="smn">uánádâs</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">減筆</span>+++

  Macrolingua Suahelica (Abecedarium Latinum):::
    +++<span lang="sw">Kifupi</span>+++

  Lingua yoruba (Abecedarium Latinum):::
    +++<span lang="yo">Àkọ̀mọ̀nà</span>+++

  Macrolingua Iudaeo-Germanica (Alphabetum Hebraicum):::
    +++<span lang="yi">קורץ ווארט</span>+++

  Macrolingua Uzbecica (Abecedarium Latinum):::
    +++<span lang="uz">Abbreviatura</span>+++

  Lingua Tatarica (/ISO 15924 Zyyy/):::
    +++<span lang="tt">Аббревиатура</span>+++

  Lingua Turcomannica (Abecedarium Latinum):::
    +++<span lang="tk">Abbrewiatura</span>+++

  Lingua Abasgica (Abecedarium Cyrillicum):::
    +++<span lang="ab">аббревиатура</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">abreviatur</span>+++

  Lingua Baschkirica (Abecedarium Cyrillicum):::
    +++<span lang="ba">аббревиатура</span>+++

  Lingua Tschuvaschica (Abecedarium Cyrillicum):::
    +++<span lang="cv">Аббревиатура</span>+++

  Lingua creola Haitiana (Abecedarium Latinum):::
    +++<span lang="ht">Abreviyasyon</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Қысқарған сөз</span>+++

  Lingua Kazachica (Abecedarium Arabicum):::
    +++<span lang="kk-arab">قىسقارعان ٴسوز</span>+++

  Lingua Kazachica (Abecedarium Cyrillicum):::
    +++<span lang="kk-cyrl">Қысқарған сөз</span>+++

  Lingua Kazachica (Abecedarium Latinum):::
    +++<span lang="kk-latn">Qısqarğan söz</span>+++

  Lingua Kyrgyzensis (/ISO 15924 Zyyy/):::
    +++<span lang="ky">Аббревиатура</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">кратенка</span>+++

  Macrolingua Mongolica (Abecedarium Cyrillicum):::
    +++<span lang="mn">Товчлол</span>+++

  /Kinyarwanda/ (Abecedarium Latinum):::
    +++<span lang="rw">Amagambo ahinnye</span>+++

  Lingua Sindhuica (Abecedarium Arabicum):::
    +++<span lang="sd">مخفف</span>+++

  Lingua Samica septentrionalis (Abecedarium Latinum):::
    +++<span lang="se">oanádus</span>+++

  Lingua Tadzikica (/ISO 15924 Zyyy/):::
    +++<span lang="tg">Аббревиатура</span>+++

  Ido (Abecedarium Latinum):::
    +++<span lang="io">Abreviuro</span>+++





<<<

[id='101244']
=== [`101244`] Acronymum

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q101244[Q101244]

  UNESCO thēsaurus:::
    http://vocabularies.unesco.org/thesaurus/concept989[concept989]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    //acronymum//

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Acronymum</span>+++

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">لفظ اختصار</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">সংক্ষিপ্ত রূপ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">акроним</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">परिवर्णी शब्द</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">აკრონიმია</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਸੰਖੇਪ ਰੂਪ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">두문자어</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">ראשי תיבות</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">ఇతర పదాల మొదటి అక్షరాల నుండి పుట్టిన పదం (ఏక్రానిం) మరియు ఇనీష్యలిజం</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">อักษรย่อ</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">首字母縮略字</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">acrónimo</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">acronym</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">acronyme</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">acroniem</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Akronym</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">acrónimo</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">acronimo</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">acrainm</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">akronym</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">skrótowiec</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">akronyymi ja kirjainlyhenne</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Acronim</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">từ viết tắt từ chữ đầu</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">acrònim</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">акронім</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Акроним</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Akronim</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">akronym</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">akronym</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">akronym</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">頭字語</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">akronym</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Akronim</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">سرنام</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">mozaikszó</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Akronimo</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">Llythrenw</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Acrónimo</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">Akronym</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">akronimo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">akronim</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">Akronüüm</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Akronim</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">akronim</span>+++

  Lingua Saxonica (Abecedarium Latinum):::
    +++<span lang="nds">Akronym</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">Acronim</span>+++

  Lingua Britonica (Abecedarium Latinum):::
    +++<span lang="br">Gwreskanv</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Akroniem</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Akronym</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">acronym</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">首字母縮略字</span>+++

  Dialecti Alemannicae (Abecedarium Latinum):::
    +++<span lang="gsw">Akronym</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Upphafsstafaheiti</span>+++

  Lingua Veneta (Abecedarium Latinum):::
    +++<span lang="vec">acrònemo</span>+++

  Lingua Sicula (Abecedarium Latinum):::
    +++<span lang="scn">Acrònimu</span>+++

  Macrolingua Sarda (Abecedarium Latinum):::
    +++<span lang="sc">Acrònimu</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">akronim</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">首字母缩略字</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">акроним</span>+++

  Lingua Urdu (Abecedarium Arabicum):::
    +++<span lang="ur">ترخیمہ</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Akronimas</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Akronim</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">Akronīms</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Akronim</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">Αρκτικόλεξο</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">Акронім</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">acrónimu</span>+++

  /Min Nan Chinese/ (Abecedarium Latinum):::
    +++<span lang="nan">Thâu-jī-gí</span>+++

  Lingua Paniabica occidentalis (Abecedarium Arabicum):::
    +++<span lang="pnb">ترخیمہ</span>+++

  Macrolingua Suahelica (Abecedarium Latinum):::
    +++<span lang="sw">Akronimu</span>+++

  Macrolingua Iudaeo-Germanica (Alphabetum Hebraicum):::
    +++<span lang="yi">ראשי תיבות</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Шартты белгі</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">акроним</span>+++

  Lingua Tadzikica (/ISO 15924 Zyyy/):::
    +++<span lang="tg">ихтисорот</span>+++

  Interlingua (Abecedarium Latinum):::
    +++<span lang="ia">Acronymo</span>+++

  Ido (Abecedarium Latinum):::
    +++<span lang="io">Akronimo</span>+++





<<<

[id='1']
=== [`1`] dēfīnītiō

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    dēfīnītiō

  Linguae multiplīs (Scrīptum incognitō):::
    https://en.wiktionary.org/wiki/definitio#Latin






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language. We're working on this, but we are still not perfected.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.


=== /[Book with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries. Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.


=== /[Book with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.


=== /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!


<<<

