= Cōdex [1603:63:1]: //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//
:doctype: book
:title: Cōdex [1603:63:1]: //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum




{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-04-20

|
numerus editionis
|
2022-03-16T07:51:22

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:63:1]**_ is the book format of the machine-readable dictionaries _**[1603:63:1] //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//**_, which are distributed for implementers on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.
    +++<br><br>+++
    **ABOUT LEXICOGRAPHY**
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    **ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**
    +++<br><br>+++
    We're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.
    +++<br><br>+++
    Since the full list of prototypal-dictionaries and dictionaries is huge, one way cited by objective audiences is the following:
    +++<br><br>+++
    ....
    1. Humanitarian aid
    2. Development aid
    3. Human rights
    4. Military relief (or conflict and conflict-resolution related concepts)
    ....
    +++<br><br>+++
    The itens 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).
    +++<br><br>+++
    Note that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    The lexicographers of this work are both volunteers, doing it for free, pro bonō publicō, and don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books. Most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.
    +++<br><br>+++
    There's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work considering it is feasible over 200 languages? The logistics to decide who should be paid, then worldwide cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither sufficient money nor humans interested in being coordinators exist.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
Rēs interlinguālibus::
  /scope and content/@eng-Latn:::
    This group contains concepts related to humanitarian relief when done by individuais. It is REQUIRED that the individual is from an organization, either as volunteer or as part of the job, which has a code or conduct compatible with Red Cross and Red Crescent Movement. This is the more generic type of what is considered _humanitarian_, but still an _strict_ type of humanitarian. This differentiation is likely to be more clear as more dictionaries for individuais are created.



=== Methodī ex verbīs in dictiōnāriīs
NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    The ***[1603:63:1] //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//*** uses Wikidata as one strategy to conciliate language terms for one or more of it's concepts.
    +++<br><br>+++
    This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up to date translations.
    +++<br><br>+++
    **How reliable are the community translations (Wikidata source)?**
    +++<br><br>+++
    The short, default answer is: **they are reliable**, even in cases of no authoritative translations for each subject.
    +++<br><br>+++
    As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).
    +++<br><br>+++
    However, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.
    +++<br><br>+++
    **Major reasons for "wrong translations" are not translators fault**
    +++<br><br>+++
    TIP: As a rule of thumb, for already very defined concepts where you, as human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.
    +++<br><br>+++
    The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.
    +++<br><br>+++
    It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.
    +++<br><br>+++
    From the point of view of data conciliation, the following methodology is used to release the terminology translations with the main concept table.
    +++<br><br>+++
    . The main handcrafted lexicographical table (explained on previous topic), also provided on `1603_63_1.no1.tm.hxl.csv`, may reference Wiki QID.
    . Every unique QID of  `1603_63_1.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!
    .. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares then for general use.
    . The query result, with all QIDs and term labels, is shared as `1603_63_1.wikiq.tm.hxl.csv`
    . The community reviewed translations of each singular QID is pre-compiled on an individual file `1603_63_1.wikiq.tm.hxl.csv`
    . `1603_63_1.no1.tm.hxl.csv` plus `1603_63_1.wikiq.tm.hxl.csv` created `1603_63_1.no11.tm.hxl.csv`


=== Rēs dē factō in dictiōnāriīs
==== Concepta: 4

==== Rēs linguālibus: 64

[%header,cols="15h,25a,~,17"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
4

|
ara-Arab
|
https://glottolog.org/resource/languoid/id/arab1395[arab1395]
+++<br>+++
https://iso639-3.sil.org/code/ara[ara]
+++<br>+++ https://www.wikidata.org/wiki/Q13955[Q13955]
|
Macrolingua Arabica (Abecedarium Arabicum)
|
3

|
hye-Armn
|
https://glottolog.org/resource/languoid/id/nucl1235[nucl1235]
+++<br>+++
https://iso639-3.sil.org/code/hye[hye]
+++<br>+++ https://www.wikidata.org/wiki/Q8785[Q8785]
|
Lingua Armenia (Alphabetum Armenium)
|
2

|
ben-Beng
|
https://glottolog.org/resource/languoid/id/beng1280[beng1280]
+++<br>+++
https://iso639-3.sil.org/code/ben[ben]
+++<br>+++ https://www.wikidata.org/wiki/Q9610[Q9610]
|
Lingua Bengali (/ISO 15924 Beng/)
|
3

|
rus-Cyrl
|
https://glottolog.org/resource/languoid/id/russ1263[russ1263]
+++<br>+++
https://iso639-3.sil.org/code/rus[rus]
+++<br>+++ https://www.wikidata.org/wiki/Q7737[Q7737]
|
Lingua Russica (Abecedarium Cyrillicum)
|
2

|
hin-Deva
|
https://glottolog.org/resource/languoid/id/hind1269[hind1269]
+++<br>+++
https://iso639-3.sil.org/code/hin[hin]
+++<br>+++ https://www.wikidata.org/wiki/Q1568[Q1568]
|
Lingua Hindica (Devanāgarī)
|
1

|
kor-Hang
|
https://glottolog.org/resource/languoid/id/kore1280[kore1280]
+++<br>+++
https://iso639-3.sil.org/code/kor[kor]
+++<br>+++ https://www.wikidata.org/wiki/Q9176[Q9176]
|
Lingua Coreana (Abecedarium Coreanum)
|
3

|
heb-Hebr
|
https://glottolog.org/resource/languoid/id/hebr1245[hebr1245]
+++<br>+++
https://iso639-3.sil.org/code/heb[heb]
+++<br>+++ https://www.wikidata.org/wiki/Q9288[Q9288]
|
Lingua Hebraica (Alphabetum Hebraicum)
|
3

|
lat-Latn
|
https://glottolog.org/resource/languoid/id/lati1261[lati1261]
+++<br>+++
https://iso639-3.sil.org/code/lat[lat]
+++<br>+++ https://www.wikidata.org/wiki/Q397[Q397]
|
Lingua Latina (Abecedarium Latinum)
|
3

|
tam-Taml
|
https://glottolog.org/resource/languoid/id/tami1289[tami1289]
+++<br>+++
https://iso639-3.sil.org/code/tam[tam]
+++<br>+++ https://www.wikidata.org/wiki/Q5885[Q5885]
|
Lingua Tamulica (/ISO 15924 Taml/)
|
1

|
tha-Thai
|
https://glottolog.org/resource/languoid/id/thai1261[thai1261]
+++<br>+++
https://iso639-3.sil.org/code/tha[tha]
+++<br>+++ https://www.wikidata.org/wiki/Q9217[Q9217]
|
Lingua Thai (/ISO 15924 Thai/)
|
2

|
zho-Zyyy
|
https://glottolog.org/resource/languoid/id/sini1245[sini1245]
+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q7850[Q7850]
|
/Macrolingua Sinicae (/ISO 15924 Zyyy/)/
|
3

|
por-Latn
|
https://glottolog.org/resource/languoid/id/port1283[port1283]
+++<br>+++
https://iso639-3.sil.org/code/por[por]
+++<br>+++ https://www.wikidata.org/wiki/Q5146[Q5146]
|
Lingua Lusitana (Abecedarium Latinum)
|
3

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
6

|
fra-Latn
|
https://glottolog.org/resource/languoid/id/stan1290[stan1290]
+++<br>+++
https://iso639-3.sil.org/code/fra[fra]
+++<br>+++ https://www.wikidata.org/wiki/Q150[Q150]
|
Lingua Francogallica (Abecedarium Latinum)
|
3

|
nld-Latn
|
https://glottolog.org/resource/languoid/id/mode1257[mode1257]
+++<br>+++
https://iso639-3.sil.org/code/nld[nld]
+++<br>+++ https://www.wikidata.org/wiki/Q7411[Q7411]
|
Lingua Batavica (Abecedarium Latinum)
|
3

|
deu-Latn
|
https://glottolog.org/resource/languoid/id/stan1295[stan1295]
+++<br>+++
https://iso639-3.sil.org/code/deu[deu]
+++<br>+++ https://www.wikidata.org/wiki/Q188[Q188]
|
Lingua Germanica (Abecedarium Latinum)
|
3

|
spa-Latn
|
https://glottolog.org/resource/languoid/id/stan1288[stan1288]
+++<br>+++
https://iso639-3.sil.org/code/spa[spa]
+++<br>+++ https://www.wikidata.org/wiki/Q1321[Q1321]
|
Lingua Hispanica (Abecedarium Latinum)
|
3

|
ita-Latn
|
https://glottolog.org/resource/languoid/id/ital1282[ital1282]
+++<br>+++
https://iso639-3.sil.org/code/ita[ita]
+++<br>+++ https://www.wikidata.org/wiki/Q652[Q652]
|
Lingua Italiana (Abecedarium Latinum)
|
3

|
swe-Latn
|
https://glottolog.org/resource/languoid/id/swed1254[swed1254]
+++<br>+++
https://iso639-3.sil.org/code/swe[swe]
+++<br>+++ https://www.wikidata.org/wiki/Q9027[Q9027]
|
Lingua Suecica (Abecedarium Latinum)
|
2

|
sqi-Latn
|
https://glottolog.org/resource/languoid/id/alba1267[alba1267]
+++<br>+++
https://iso639-3.sil.org/code/sqi[sqi]
+++<br>+++ https://www.wikidata.org/wiki/Q8748[Q8748]
|
Macrolingua Albanica (/Abecedarium Latinum/)
|
3

|
pol-Latn
|
https://glottolog.org/resource/languoid/id/poli1260[poli1260]
+++<br>+++
https://iso639-3.sil.org/code/pol[pol]
+++<br>+++ https://www.wikidata.org/wiki/Q809[Q809]
|
Lingua Polonica (Abecedarium Latinum)
|
3

|
fin-Latn
|
https://glottolog.org/resource/languoid/id/finn1318[finn1318]
+++<br>+++
https://iso639-3.sil.org/code/fin[fin]
+++<br>+++ https://www.wikidata.org/wiki/Q1412[Q1412]
|
Lingua Finnica (Abecedarium Latinum)
|
2

|
ron-Latn
|
https://glottolog.org/resource/languoid/id/roma1327[roma1327]
+++<br>+++
https://iso639-3.sil.org/code/ron[ron]
+++<br>+++ https://www.wikidata.org/wiki/Q7913[Q7913]
|
Lingua Dacoromanica (Abecedarium Latinum)
|
3

|
vie-Latn
|
https://glottolog.org/resource/languoid/id/viet1252[viet1252]
+++<br>+++
https://iso639-3.sil.org/code/vie[vie]
+++<br>+++ https://www.wikidata.org/wiki/Q9199[Q9199]
|
Lingua Vietnamensis (Abecedarium Latinum)
|
3

|
cat-Latn
|
https://glottolog.org/resource/languoid/id/stan1289[stan1289]
+++<br>+++
https://iso639-3.sil.org/code/cat[cat]
+++<br>+++ https://www.wikidata.org/wiki/Q7026[Q7026]
|
Lingua Catalana (Abecedarium Latinum)
|
3

|
ukr-Cyrl
|
https://glottolog.org/resource/languoid/id/ukra1253[ukra1253]
+++<br>+++
https://iso639-3.sil.org/code/ukr[ukr]
+++<br>+++ https://www.wikidata.org/wiki/Q8798[Q8798]
|
Lingua Ucrainica (Abecedarium Cyrillicum)
|
2

|
bul-Cyrl
|
https://glottolog.org/resource/languoid/id/bulg1262[bulg1262]
+++<br>+++
https://iso639-3.sil.org/code/bul[bul]
+++<br>+++ https://www.wikidata.org/wiki/Q7918[Q7918]
|
Lingua Bulgarica (Abecedarium Cyrillicum)
|
3

|
nob-Latn
|
https://glottolog.org/resource/languoid/id/norw1259[norw1259]
+++<br>+++
https://iso639-3.sil.org/code/nob[nob]
+++<br>+++ https://www.wikidata.org/wiki/Q25167[Q25167]
|
/Bokmål/ (Abecedarium Latinum)
|
2

|
ces-Latn
|
https://glottolog.org/resource/languoid/id/czec1258[czec1258]
+++<br>+++
https://iso639-3.sil.org/code/ces[ces]
+++<br>+++ https://www.wikidata.org/wiki/Q9056[Q9056]
|
Lingua Bohemica (Abecedarium Latinum)
|
2

|
dan-Latn
|
https://glottolog.org/resource/languoid/id/dani1285[dani1285]
+++<br>+++
https://iso639-3.sil.org/code/dan[dan]
+++<br>+++ https://www.wikidata.org/wiki/Q9035[Q9035]
|
Lingua Danica (Abecedarium Latinum)
|
3

|
jpn-Jpan
|
https://glottolog.org/resource/languoid/id/nucl1643[nucl1643]
+++<br>+++
https://iso639-3.sil.org/code/jpn[jpn]
+++<br>+++ https://www.wikidata.org/wiki/Q5287[Q5287]
|
Lingua Iaponica (Scriptura Iaponica)
|
3

|
ind-Latn
|
https://glottolog.org/resource/languoid/id/indo1316[indo1316]
+++<br>+++
https://iso639-3.sil.org/code/ind[ind]
+++<br>+++ https://www.wikidata.org/wiki/Q9240[Q9240]
|
Lingua Indonesiana (Abecedarium Latinum)
|
3

|
fas-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/fas[fas]
+++<br>+++ https://www.wikidata.org/wiki/Q9168[Q9168]
|
Macrolingua Persica (//Abecedarium Arabicum//)
|
3

|
eus-Latn
|
https://glottolog.org/resource/languoid/id/basq1248[basq1248]
+++<br>+++
https://iso639-3.sil.org/code/eus[eus]
+++<br>+++ https://www.wikidata.org/wiki/Q8752[Q8752]
|
Lingua Vasconica (Abecedarium Latinum)
|
2

|
epo-Latn
|
https://glottolog.org/resource/languoid/id/espe1235[espe1235]
+++<br>+++
https://iso639-3.sil.org/code/epo[epo]
+++<br>+++ https://www.wikidata.org/wiki/Q143[Q143]
|
Lingua Esperantica (Abecedarium Latinum)
|
3

|
msa-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/msa[msa]
+++<br>+++ https://www.wikidata.org/wiki/Q9237[Q9237]
|
Macrolingua Malayana (/ISO 15924 Zyyy/)
|
3

|
est-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/est[est]
+++<br>+++ https://www.wikidata.org/wiki/Q9072[Q9072]
|
Macrolingua Estonica (Abecedarium Latinum)
|
2

|
hrv-Latn
|
https://glottolog.org/resource/languoid/id/croa1245[croa1245]
+++<br>+++
https://iso639-3.sil.org/code/hrv[hrv]
+++<br>+++ https://www.wikidata.org/wiki/Q6654[Q6654]
|
Lingua Croatica (Abecedarium Latinum)
|
2

|
tur-Latn
|
https://glottolog.org/resource/languoid/id/nucl1301[nucl1301]
+++<br>+++
https://iso639-3.sil.org/code/tur[tur]
+++<br>+++ https://www.wikidata.org/wiki/Q256[Q256]
|
Lingua Turcica (Abecedarium Latinum)
|
1

|
ltz-Latn
|
https://glottolog.org/resource/languoid/id/luxe1241[luxe1241]
+++<br>+++
https://iso639-3.sil.org/code/ltz[ltz]
+++<br>+++ https://www.wikidata.org/wiki/Q9051[Q9051]
|
Lingua Luxemburgensis (Abecedarium Latinum)
|
2

|
zho-Hant
|

+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q18130932[Q18130932]
|
//Traditional Chinese// (/ISO 15924 Hant/)
|
2

|
vec-Latn
|
https://glottolog.org/resource/languoid/id/vene1258[vene1258]
+++<br>+++
https://iso639-3.sil.org/code/vec[vec]
+++<br>+++ https://www.wikidata.org/wiki/Q32724[Q32724]
|
Lingua Veneta (Abecedarium Latinum)
|
2

|
srp-Latn
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q21161949[Q21161949]
|
/Serbian/ (Abecedarium Latinum)
|
2

|
wuu-Zyyy
|
https://glottolog.org/resource/languoid/id/wuch1236[wuch1236]
+++<br>+++
https://iso639-3.sil.org/code/wuu[wuu]
+++<br>+++ https://www.wikidata.org/wiki/Q34290[Q34290]
|
//Macrolingua Wu// (/ISO 15924 Zyyy/)
|
1

|
srp-Cyrl
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q9299[Q9299]
|
Lingua Serbica (Abecedarium Cyrillicum)
|
3

|
lit-Latn
|
https://glottolog.org/resource/languoid/id/lith1251[lith1251]
+++<br>+++
https://iso639-3.sil.org/code/lit[lit]
+++<br>+++ https://www.wikidata.org/wiki/Q9083[Q9083]
|
Lingua Lithuanica (Abecedarium Latinum)
|
3

|
hbs-Latn
|
https://glottolog.org/resource/languoid/id/sout1528[sout1528]
+++<br>+++
https://iso639-3.sil.org/code/hbs[hbs]
+++<br>+++ https://www.wikidata.org/wiki/Q9301[Q9301]
|
Macrolingua Serbocroatica (Abecedarium Latinum)
|
2

|
lav-Latn
|
https://glottolog.org/resource/languoid/id/latv1249[latv1249]
+++<br>+++
https://iso639-3.sil.org/code/lav[lav]
+++<br>+++ https://www.wikidata.org/wiki/Q9078[Q9078]
|
Macrolingua Lettonica (Abecedarium Latinum)
|
2

|
bos-Latn
|
https://glottolog.org/resource/languoid/id/bosn1245[bosn1245]
+++<br>+++
https://iso639-3.sil.org/code/bos[bos]
+++<br>+++ https://www.wikidata.org/wiki/Q9303[Q9303]
|
Lingua Bosnica (Abecedarium Latinum)
|
2

|
ell-Grek
|
https://glottolog.org/resource/languoid/id/mode1248[mode1248]
+++<br>+++
https://iso639-3.sil.org/code/ell[ell]
+++<br>+++ https://www.wikidata.org/wiki/Q36510[Q36510]
|
Lingua Neograeca (Alphabetum Graecum)
|
3

|
bel-Cyrl
|
https://glottolog.org/resource/languoid/id/bela1254[bela1254]
+++<br>+++
https://iso639-3.sil.org/code/bel[bel]
+++<br>+++ https://www.wikidata.org/wiki/Q9091[Q9091]
|
Lingua Ruthenica Alba (Abecedarium Cyrillicum)
|
1

|
bho-Deva
|
https://glottolog.org/resource/languoid/id/bhoj1244[bhoj1244]
+++<br>+++
https://iso639-3.sil.org/code/bho[bho]
+++<br>+++ https://www.wikidata.org/wiki/Q33268[Q33268]
|
Lingua Bhojpuri (Devanāgarī)
|
1

|
gcr-Latn
|
https://glottolog.org/resource/languoid/id/guia1246[guia1246]
+++<br>+++
https://iso639-3.sil.org/code/gcr[gcr]
+++<br>+++ https://www.wikidata.org/wiki/Q1363072[Q1363072]
|
/Guianese Creole French/ (Abecedarium Latinum)
|
2

|
gom-Zyyy
|
https://glottolog.org/resource/languoid/id/goan1235[goan1235]
+++<br>+++
https://iso639-3.sil.org/code/gom[gom]
+++<br>+++ https://www.wikidata.org/wiki/Q5575236[Q5575236]
|
/Goan Konkani/ (/ISO 15924 Zyyy/)
|
1

|
nan-Latn
|
https://glottolog.org/resource/languoid/id/minn1241[minn1241]
+++<br>+++
https://iso639-3.sil.org/code/nan[nan]
+++<br>+++ https://www.wikidata.org/wiki/Q36495[Q36495]
|
/Min Nan Chinese/ (Abecedarium Latinum)
|
1

|
yue-Zyyy
|
https://glottolog.org/resource/languoid/id/yuec1235[yuec1235]
+++<br>+++
https://iso639-3.sil.org/code/yue[yue]
+++<br>+++ https://www.wikidata.org/wiki/Q7033959[Q7033959]
|
Lingua Yue (/ISO 15924 Zyyy/)
|
1

|
aze-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/aze[aze]
+++<br>+++ https://www.wikidata.org/wiki/Q9292[Q9292]
|
Macrolingua Atropatenica (Abecedarium Latinum)
|
2

|
kaz-Zyyy
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q9252[Q9252]
|
Lingua Kazachica (/ISO 15924 Zyyy/)
|
2

|
kaz-Arab
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362991[Q64362991]
|
Lingua Kazachica (Abecedarium Arabicum)
|
2

|
kaz-Cyrl
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362992[Q64362992]
|
Lingua Kazachica (Abecedarium Cyrillicum)
|
2

|
kaz-Latn
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362993[Q64362993]
|
Lingua Kazachica (Abecedarium Latinum)
|
2

|
nep-Deva
|
https://glottolog.org/resource/languoid/id/east1436[east1436]
+++<br>+++
https://iso639-3.sil.org/code/nep[nep]
+++<br>+++ https://www.wikidata.org/wiki/Q33823[Q33823]
|
Macrolingua Nepalensis (Devanāgarī)
|
2

|
ina-Latn
|
https://glottolog.org/resource/languoid/id/inte1239[inte1239]
+++<br>+++
https://iso639-3.sil.org/code/ina[ina]
+++<br>+++ https://www.wikidata.org/wiki/Q35934[Q35934]
|
Interlingua (Abecedarium Latinum)
|
2

|===

==== Rēs interlinguālibus: 7
Rēs::
  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wikip393

      ix_hxlvoc;;
        v_wiki_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">number of an edition (first, second, ... as 1, 2, ...) or event</span>+++

  /Wiki QID/:::
    Rēs interlinguālibus::::
      /rēgulam/;;
        Q[1-9]\d*

      ix_hxlix;;
        ix_wikiq

      ix_hxlvoc;;
        v_wiki_q

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/Wiki QID/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.</span>+++

  /scope and content/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P7535[P7535]

      ix_hxlix;;
        ix_wikip7535

      ix_hxlvoc;;
        v_wiki_p_7535

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/scope and content/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">a summary statement providing an overview of the archival collection</span>+++

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wikip123

      ix_hxlvoc;;
        v_wiki_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software</span>+++

  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wikip577

      ix_hxlvoc;;
        v_wiki_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Date or point in time when a work was first published or released</span>+++

  scrīptor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P50[P50]

      ix_hxlix;;
        ix_wikip50

      ix_hxlvoc;;
        v_wiki_p_50

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">scrīptor</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Main creator(s) of a written work (use on works, not humans)</span>+++

  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wikip2479

      ix_hxlvoc;;
        v_wiki_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">SPDX license identifier</span>+++


<<<

== Archīa

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    **Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ an static work), then the actual groundbreaking difference on the workflow used to generate every dictionaries on Cōdex such as this one are the following fact: **we provide machine readable formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with terminology translations.
    +++<br><br>+++
    **Practical implication**: the text documents on _Archīa prō cōdice_ (literal English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an impact.


=== Archīa prō dictiōnāriīs: 3


==== 1603_63_1.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_63_1.no1.tm.hxl.csv[1603_63_1.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container/



==== 1603_63_1.no11.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_63_1.no11.tm.hxl.csv[1603_63_1.no11.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container (expanded with terminology translations)/



==== 1603_63_1.wikiq.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_63_1.wikiq.tm.hxl.csv[1603_63_1.wikiq.tm.hxl.csv]
  /reference URL/@eng-Latn:::
    https://hxltm.etica.ai/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    HXLTM dialect of HXLStandard on CSV RFC 4180. wikiq means #item+conceptum+codicem are strictly Wikidata QIDs.



=== Archīa prō cōdice: 2


==== 1603_63_1.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_63_1.mul-Latn.codex.adoc[1603_63_1.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.



==== 1603_63_1.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_63_1.mul-Latn.codex.pdf[1603_63_1.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//
<<<

[id='1']
=== [`1`] Auxilium humanitarium

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q826745[Q826745]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    fiat lux, 1603_63_1!

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">مساعدات إنسانية</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">հումանիտար օգնություն</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">মানবহিতৈষী সাহায্য</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">гуманитарная помощь</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">인도주의적 지원</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">סיוע הומניטרי</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Auxilium humanitarium</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">ความช่วยเหลือด้านมนุษยธรรม</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">人道援助</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">ajuda humanitária</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">humanitarian aid</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">aide humanitaire</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">noodhulp</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">humanitäre Hilfe</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">ayuda humanitaria</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">aiuto umanitario</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">humanitärt bistånd</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">Ndihma humanitare</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">pomoc humanitarna</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">humanitaarinen apu</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">ajutor umanitar</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Viện trợ nhân đạo</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">ajuda humanitària</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">гуманітарна допомога</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Хуманитарна помощ</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">hjelpearbeid</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">humanitární pomoc</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">nødhjælp</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">人道援助</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Bantuan kemanusiaan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">کمکهای بشردوستانه</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Gizaldeko laguntza</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">Humanitara helpo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">bantuan kemanusiaan</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">Humanitaarabi</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Humanitarna pomoć</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Humanitär Hëllef</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">人道援助</span>+++

  Lingua Veneta (Abecedarium Latinum):::
    +++<span lang="vec">juto umanitàrio</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">humanitarna pomoć</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">хуманитарна помоћ</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Humanitarinė pagalba</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Humanitarna pomoć</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">humānā palīdzība</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Humanitarna pomoć</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">ανθρωπιστική βοήθεια</span>+++

  /Guianese Creole French/ (Abecedarium Latinum):::
    +++<span lang="gcr">Èd mounitèr</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">Humanitar yardım</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Ізгілік көмек</span>+++

  Lingua Kazachica (Abecedarium Arabicum):::
    +++<span lang="kk-arab">ىزگىلىك كومەك</span>+++

  Lingua Kazachica (Abecedarium Cyrillicum):::
    +++<span lang="kk-cyrl">Ізгілік көмек</span>+++

  Lingua Kazachica (Abecedarium Latinum):::
    +++<span lang="kk-latn">İzgilik kömek</span>+++

  Macrolingua Nepalensis (Devanāgarī):::
    +++<span lang="ne">मानवीय सहायता</span>+++

  Interlingua (Abecedarium Latinum):::
    +++<span lang="ia">adjuta humanitari</span>+++





<<<

[id='17']
=== [`17`] /Wikidata QIDs/

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /Wikidata QIDs/





[id='17_775858']
==== [`17_775858`] Humanitarismus

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q775858[Q775858]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /humanitarianism/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">أعمال خيرية</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">মানবহিতৈষণা</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">मानवतावाद</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">인도주의</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">הומניטרית</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Humanitarismus</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">மனித நேயம்</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">人道主义</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">humanitarismo</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">humanitarianism</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">humanitarisme</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">humanitarisme</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Humanitarismus</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">humanitarismo</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">umanitarismo</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">Humanitarizmi</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Humanitaryzm</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">umanitarism</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">chủ nghĩa nhân đạo</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">humanitarisme</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Хуманитаризъм</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">humanitarianisme</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">人道主義</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Humanitarianisme</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">بشردوستی</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">Humanitarismo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">faham kemanusiaan</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Hümaniteryenizm</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">人道主义</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">Хуманитарност</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Humanitarizmas</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">Ανθρωπισμός</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">гуманітарызм</span>+++

  Lingua Bhojpuri (Devanāgarī):::
    +++<span lang="bho">मानवतावाद</span>+++

  /Goan Konkani/ (/ISO 15924 Zyyy/):::
    +++<span lang="gom">मानवतावाद</span>+++

  /Min Nan Chinese/ (Abecedarium Latinum):::
    +++<span lang="nan">Jîn-tō-chú-gī</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">人道主義</span>+++





[id='17_826745']
==== [`17_826745`] Auxilium humanitarium

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q826745[Q826745]

Rēs linguālibus::
  Linguae multiplīs (Scrīptum incognitō):::
    /humanitarian aid/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">مساعدات إنسانية</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">հումանիտար օգնություն</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">মানবহিতৈষী সাহায্য</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">гуманитарная помощь</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">인도주의적 지원</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">סיוע הומניטרי</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Auxilium humanitarium</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">ความช่วยเหลือด้านมนุษยธรรม</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">人道援助</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">ajuda humanitária</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">humanitarian aid</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">aide humanitaire</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">noodhulp</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">humanitäre Hilfe</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">ayuda humanitaria</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">aiuto umanitario</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">humanitärt bistånd</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">Ndihma humanitare</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">pomoc humanitarna</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">humanitaarinen apu</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">ajutor umanitar</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Viện trợ nhân đạo</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">ajuda humanitària</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">гуманітарна допомога</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Хуманитарна помощ</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">hjelpearbeid</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">humanitární pomoc</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">nødhjælp</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">人道援助</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Bantuan kemanusiaan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">کمکهای بشردوستانه</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Gizaldeko laguntza</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">Humanitara helpo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">bantuan kemanusiaan</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">Humanitaarabi</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Humanitarna pomoć</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Humanitär Hëllef</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">人道援助</span>+++

  Lingua Veneta (Abecedarium Latinum):::
    +++<span lang="vec">juto umanitàrio</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">humanitarna pomoć</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">хуманитарна помоћ</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Humanitarinė pagalba</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Humanitarna pomoć</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">humānā palīdzība</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Humanitarna pomoć</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">ανθρωπιστική βοήθεια</span>+++

  /Guianese Creole French/ (Abecedarium Latinum):::
    +++<span lang="gcr">Èd mounitèr</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">Humanitar yardım</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Ізгілік көмек</span>+++

  Lingua Kazachica (Abecedarium Arabicum):::
    +++<span lang="kk-arab">ىزگىلىك كومەك</span>+++

  Lingua Kazachica (Abecedarium Cyrillicum):::
    +++<span lang="kk-cyrl">Ізгілік көмек</span>+++

  Lingua Kazachica (Abecedarium Latinum):::
    +++<span lang="kk-latn">İzgilik kömek</span>+++

  Macrolingua Nepalensis (Devanāgarī):::
    +++<span lang="ne">मानवीय सहायता</span>+++

  Interlingua (Abecedarium Latinum):::
    +++<span lang="ia">adjuta humanitari</span>+++






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language. We're working on this, but we are still not perfected.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.


=== /[Book with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries. Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.


=== /[Book with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.


=== /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!


<<<

