= Cōdex [1603:1:99]: Nōtitiae temporāriōrum circā librārium
:doctype: book
:title: Cōdex [1603:1:99]: Nōtitiae temporāriōrum circā librārium
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum
:front-cover-image: image:1603_1_99.mul-Latn.codex.svg["Cōdex [1603_1_99]: Nōtitiae temporāriōrum circā librārium",1050,1600]




{nbsp} +
{nbsp} +
[quote]
**Dedicação ao Domínio Público significa que cada grande problema comum só precisa ser resolvido uma vez**

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-04-14

|
numerus editionis
|
2022-04-24T11:04:11

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:1:99]**_ é o formato de livro dos dados estruturados legíveis por máquina do grupo de dicionários _**[1603:1:99] Nōtitiae temporāriōrum circā librārium**_, que são distribuídos para os implementadores usarem em aplicativos externos. Este livro pretende ser um recurso avançado para outros lexicógrafos e tradutores de terminologia, inclusive para detectar e relatar inconsistências. Ele pode, no entanto, ser usado como um dicionário ad hoc se não houver trabalho derivado focado em suas necessidades específicas.
    +++<br><br>+++
    **SOBRE LEXICOGRAFIA**
    +++<br><br>+++
    A lexicografia prática é a arte ou ofício de compilar, escrever e editar dicionários. O básico não é muito diferente de um milênio atrás: ainda é um trabalho muito humano e criativo. É preciso ser humilde: a maioria dos erros de tradutores, na verdade, não é culpa do tradutor, mas falhas metodológicas. Certificar-se de uma ideia de origem do que um conceito representa, mesmo que signifique reescrever e simplificar, anexar fotos, mostrar exemplos, fazer o que for para que seja entendido, faz com que até mesmo tradutores não profissionais que se preocupam com sua própria língua entreguem melhor resultados do que qualquer alternativa. Em outras palavras: mesmo as chamadas melhores práticas da indústria de pagar tradutores e revisores profissionais não podem superar termos de origem já mal explicados.
    +++<br><br>+++
    **SOBRE TIPOS DE DICIONÁRIOS QUE ESTAMOS COMPILANDO**
    +++<br><br>+++
    Estamos preocupados com um grupo de idéias (chamamos isso de grupo de dicionários de conceitos) que podem ser divididos em partes menores, revisados quanto a inconsistências, aprimorados para definições e depois traduzidos por voluntários. Códigos interlinguais, como o que poderia ser usado na troca de dados real, também são adicionados a cada conceito. Ambos os glossários, interfaces de usuário (como rótulos na coleta de dados) e, em alguns casos, até códigos padrão para o que iria em um campo de dados podem ser compilados dessa maneira.
    +++<br><br>+++
    Como a lista completa de dicionários-prototípicos e dicionários minimamente utilizáveis é enorme, um modo de citar público-alvos típicos é o seguinte:
    +++<br><br>+++
    . Ajuda humanitária
    . Ajuda ao desenvolvimento
    . Direitos humanos
    . Socorro militar (ou conceitos relacionados a conflitos e resolução de conflitos)
    +++<br><br>+++
    Os itens 1, 2 e 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[são algumas vezes referidos como _nexus_] e são frequentemente encontrados ajudando _crise humanitária_. Já que a maioria dos colaboradores cujas ideias e críticas válidas são voluntárias, então 3 (direitos humanos, como na Anistia Internacional) para diferenciar do humanitarismo (como o Movimento da Cruz Vermelha é referência).
    +++<br><br>+++
    Observe que **dicionários não são guias de uso**. As instruções, quando existem, são principalmente dedicadas a lexicógrafos e tradutores.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    As pessoas lexicógrafas deste trabalho são voluntárias, fazendo-o gratuitamente, pro bonō publicō, e não aceitam doações por causa dos dicionários reutilizáveis ​​de todos. O trabalho anterior existente muitas vezes é baseado em livros antigos de domínio público. A maioria dos tradutores de terminologia já seriam voluntários porque acreditam em uma causa. A melhor maneira de inspirar a colaboração é sermos nós mesmos exemplos.
    +++<br><br>+++
    Há um aspecto não moralista, bastante simples de entender: quão caro seria pagar pelo trabalho de todos considerando que é viável em mais de 200 idiomas? A logística para decidir quem deve ser pago, depois a transferência de dinheiro em todo o mundo (pode incluir pessoas de países embargados), depois os mecanismos tradicionais de auditoria para verificar o uso indevido que os doadores esperam, existe? Em terminologia especial (os próprios termos do dicionário) e tantas línguas, não existe dinheiro suficiente nem humanos interessados ​​em ser coordenadores.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
Rēs interlinguālibus (1)::
  /scope and content/@eng-Latn:::
    /Temporary information about the library. Used to store on spreadsheets (not on code) messages not translated yet on dedicated dictionaries. Not intented for external use/@eng-Latn



=== Rēs dē factō in dictiōnāriīs
==== Concepta: 51

==== Rēs linguālibus: 3

[%header,cols="15h,25a,~,17"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
1

|
por-Latn
|
https://glottolog.org/resource/languoid/id/port1283[port1283]
+++<br>+++
https://iso639-3.sil.org/code/por[por]
+++<br>+++ https://www.wikidata.org/wiki/Q5146[Q5146]
|
Lingua Lusitana (Abecedarium Latinum)
|
31

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
53

|===

==== Rēs interlinguālibus: 6
Rēs::
  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wikip577

      ix_hxlvoc;;
        v_wiki_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Date or point in time when a work was first published or released</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">Data ou ponto no tempo em que um trabalho foi publicado ou lançado pela primeira vez</span>+++

  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wikip2479

      ix_hxlvoc;;
        v_wiki_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">SPDX license identifier</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">identificador de licença SPDX</span>+++

  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wikip393

      ix_hxlvoc;;
        v_wiki_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">number of an edition (first, second, ... as 1, 2, ...) or event</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">número de uma edição (primeira, segunda, ... como 1, 2, ...) ou evento</span>+++

  /scope and content/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P7535[P7535]

      ix_hxlix;;
        ix_wikip7535

      ix_hxlvoc;;
        v_wiki_p_7535

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/scope and content/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">a summary statement providing an overview of the archival collection</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">uma declaração resumida fornecendo uma visão geral da coleção de arquivo</span>+++

  scrīptor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P50[P50]

      ix_hxlix;;
        ix_wikip50

      ix_hxlvoc;;
        v_wiki_p_50

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">scrīptor</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Main creator(s) of a written work (use on works, not humans)</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">Principais criadores de uma obra escrita (uso em obras, não em humanos)</span>+++

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wikip123

      ix_hxlvoc;;
        v_wiki_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">organização ou pessoa responsável pela publicação de livros, periódicos, música impressa, podcasts, jogos ou software</span>+++


<<<

== Archīa

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    **Informações de contexto**: ignorando por um momento o fato de ter várias traduções (e otimizadas para receber contribuições regularmente, não _apenas_ um trabalho estático), então a diferença real no fluxo de trabalho usado para gerar cada grupo de dicionários em um Cōdex como este é o seguinte fato: **fornecemos formatos de arquivos estruturados legíveis por máquina mesmo quando os equivalentes em _idiomas internacionais_, como o inglês, não possuem para áreas como ajuda humanitária, ajuda ao desenvolvimento e direitos humanos**. Os mais próximos desse multilinguismo (fora da Wikimedia) são o SEMIeu da União Europeia (até 24 idiomas), mas mesmo assim têm problemas ao compartilhar traduções em todos os idiomas. As traduções das Nações Unidas (até 6 idiomas, raramente mais) não estão disponíveis por agências humanitárias para ajudar nas traduções de terminologia.
    +++<br><br>+++
    **Implicação prática**: os documentos de texto em _Archīa prō cōdice_ (tradução literal em inglês: _File for book_) são alternativas a este formato de livro que são altamente automatizados usando apenas o formato de dados. No entanto, os formatos legíveis por máquina em _Archīa prō dictiōnāriīs_ (tradução literal em inglês: _Arquivos para dicionários_) são o foco e recomendados para trabalhos derivados e destinados a mitigar erros humanos adicionais. Podemos até criar novos formatos a pedido! O objetivo aqui é permitir tradutores de terminologia e uso de produção onde isso tenha um impacto positivo.


=== Archīa prō dictiōnāriīs: 1


==== 1603_1_99.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_99.no1.tm.hxl.csv[1603_1_99.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio no contêiner HXLTM/



=== Archīa prō cōdice: 2


==== 1603_1_99.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_99.mul-Latn.codex.adoc[1603_1_99.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc é um formato de autoria de texto simples (ou seja, linguagem de marcação leve) para escrever conteúdo técnico, como documentação, artigos e livros.



==== 1603_1_99.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_99.mul-Latn.codex.pdf[1603_1_99.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), padronizado como ISO 32000, é um formato de arquivo desenvolvido pela Adobe em 1992 para apresentar documentos, incluindo formatação de texto e imagens, de maneira independente do software aplicativo, hardware e sistemas operacionais.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== Nōtitiae temporāriōrum circā librārium
<<<

[id='1']
=== [`1`] fīat lūx!

Rēs linguālibus (2)::
  Linguae multiplīs (Scrīptum incognitō):::
    fīat lūx!

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">fīat lūx!</span>+++





<<<

[id='2']
=== [`2`] /{% _🗣️ 1603_1_99_1 🗣️_ %}/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">{% _🗣️ 1603_1_99_1 🗣️_ %}</span>+++





<<<

[id='3']
=== [`3`] /The result of this section is a preview. We're aware it is not well (Abecedarium formatted for a book format. Sorry for the temporary inconvenience./@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">The result of this section is a preview. We're aware it is not well (Abecedarium formatted for a book format. Sorry for the temporary inconvenience.</span>+++





<<<

[id='10']
=== [`10`] //General text hardcoded on the 1603_1.py//@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">/General text hardcoded on the 1603_1.py/</span>+++





[id='10_1']
==== [`10_1`] /_**Cōdex [{0}]**_ is the book format of the machine-readable structured data of the group of dictionaries _**[{0}] {1}**_, which are distributed for implementers to use on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including to detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.\n\n**ABOUT LEXICOGRAPHY**\n\nPractical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different from a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means to rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.\n\n**ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**\n\nWe're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.\n\nSince the full list of prototypal-dictionaries and minimally usable dictionaries is huge, one mode to cite typical objective audiences is the following:\n\n. Humanitarian aid\n. Development aid\n. Human rights\n. Military relief (or conflict and conflict-resolution related concepts)\n\nThe items 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred to as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).\n\nNote that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.\n\n**/PRO BONŌ PUBLICŌ/@lat-Latn**\n\nThe lexicographers of this work are both volunteers, doing it for free, pro bonō publicō, and don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books. Most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.\n\nThere's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work, considering it is feasible over 200 languages? The logistics to decide who should be paid, then worldwide cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither sufficient money nor humans interested in being coordinators exist./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [{0}]**_ is the book format of the machine-readable structured data of the group of dictionaries _**[{0}] {1}**_, which are distributed for implementers to use on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including to detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.
    +++<br><br>+++
    **ABOUT LEXICOGRAPHY**
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different from a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means to rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    **ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**
    +++<br><br>+++
    We're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.
    +++<br><br>+++
    Since the full list of prototypal-dictionaries and minimally usable dictionaries is huge, one mode to cite typical objective audiences is the following:
    +++<br><br>+++
    . Humanitarian aid
    . Development aid
    . Human rights
    . Military relief (or conflict and conflict-resolution related concepts)
    +++<br><br>+++
    The items 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred to as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).
    +++<br><br>+++
    Note that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    The lexicographers of this work are both volunteers, doing it for free, pro bonō publicō, and don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books. Most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.
    +++<br><br>+++
    There's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work, considering it is feasible over 200 languages? The logistics to decide who should be paid, then worldwide cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither sufficient money nor humans interested in being coordinators exist.

  Lingua Lusitana (Abecedarium Latinum):::
    _**Cōdex [{0}]**_ é o formato de livro dos dados estruturados legíveis por máquina do grupo de dicionários _**[{0}] {1}**_, que são distribuídos para os implementadores usarem em aplicativos externos. Este livro pretende ser um recurso avançado para outros lexicógrafos e tradutores de terminologia, inclusive para detectar e relatar inconsistências. Ele pode, no entanto, ser usado como um dicionário ad hoc se não houver trabalho derivado focado em suas necessidades específicas.
    +++<br><br>+++
    **SOBRE LEXICOGRAFIA**
    +++<br><br>+++
    A lexicografia prática é a arte ou ofício de compilar, escrever e editar dicionários. O básico não é muito diferente de um milênio atrás: ainda é um trabalho muito humano e criativo. É preciso ser humilde: a maioria dos erros de tradutores, na verdade, não é culpa do tradutor, mas falhas metodológicas. Certificar-se de uma ideia de origem do que um conceito representa, mesmo que signifique reescrever e simplificar, anexar fotos, mostrar exemplos, fazer o que for para que seja entendido, faz com que até mesmo tradutores não profissionais que se preocupam com sua própria língua entreguem melhor resultados do que qualquer alternativa. Em outras palavras: mesmo as chamadas melhores práticas da indústria de pagar tradutores e revisores profissionais não podem superar termos de origem já mal explicados.
    +++<br><br>+++
    **SOBRE TIPOS DE DICIONÁRIOS QUE ESTAMOS COMPILANDO**
    +++<br><br>+++
    Estamos preocupados com um grupo de idéias (chamamos isso de grupo de dicionários de conceitos) que podem ser divididos em partes menores, revisados quanto a inconsistências, aprimorados para definições e depois traduzidos por voluntários. Códigos interlinguais, como o que poderia ser usado na troca de dados real, também são adicionados a cada conceito. Ambos os glossários, interfaces de usuário (como rótulos na coleta de dados) e, em alguns casos, até códigos padrão para o que iria em um campo de dados podem ser compilados dessa maneira.
    +++<br><br>+++
    Como a lista completa de dicionários-prototípicos e dicionários minimamente utilizáveis é enorme, um modo de citar público-alvos típicos é o seguinte:
    +++<br><br>+++
    . Ajuda humanitária
    . Ajuda ao desenvolvimento
    . Direitos humanos
    . Socorro militar (ou conceitos relacionados a conflitos e resolução de conflitos)
    +++<br><br>+++
    Os itens 1, 2 e 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[são algumas vezes referidos como _nexus_] e são frequentemente encontrados ajudando _crise humanitária_. Já que a maioria dos colaboradores cujas ideias e críticas válidas são voluntárias, então 3 (direitos humanos, como na Anistia Internacional) para diferenciar do humanitarismo (como o Movimento da Cruz Vermelha é referência).
    +++<br><br>+++
    Observe que **dicionários não são guias de uso**. As instruções, quando existem, são principalmente dedicadas a lexicógrafos e tradutores.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    As pessoas lexicógrafas deste trabalho são voluntárias, fazendo-o gratuitamente, pro bonō publicō, e não aceitam doações por causa dos dicionários reutilizáveis ​​de todos. O trabalho anterior existente muitas vezes é baseado em livros antigos de domínio público. A maioria dos tradutores de terminologia já seriam voluntários porque acreditam em uma causa. A melhor maneira de inspirar a colaboração é sermos nós mesmos exemplos.
    +++<br><br>+++
    Há um aspecto não moralista, bastante simples de entender: quão caro seria pagar pelo trabalho de todos considerando que é viável em mais de 200 idiomas? A logística para decidir quem deve ser pago, depois a transferência de dinheiro em todo o mundo (pode incluir pessoas de países embargados), depois os mecanismos tradicionais de auditoria para verificar o uso indevido que os doadores esperam, existe? Em terminologia especial (os próprios termos do dicionário) e tantas línguas, não existe dinheiro suficiente nem humanos interessados ​​em ser coordenadores.





[id='10_1_0']
===== [`10_1_0`] /_**Cōdex [{0}]**_ is the book format of the machine-readable dictionaries _**[{0}] {1}**_, which are distributed for implementers on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.\n\n**ABOUT LEXICOGRAPHY**\n\nPractical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.\n\n**ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**\n\nWe're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.\n\nSince the full list of prototypal-dictionaries and dictionaries is huge, one way cited by objective audiences is the following:\n\n1. Humanitarian aid2. Development aid\n3. Human rights\n4. Military relief (or conflict and conflict-resolution related concepts)\n\n// -\n\nThe itens 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).\n\nNote that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.\n\n///\n**BUT ARE SPECIALIZED DICTIONARIES NECESSARY AT ALL?**\n\nThis preface text is generated with every Cōdex version, so this may be a prototype/draft one (which means not a good example), but the answer is: yes. But a _very boring yes_. References about decision making on dictionaries are very scarce through centuries, but a quick summary on this topic: **any dictionary compilation to be useful should be based on _de facto_ users needs, which is different from typical validation**.\n\nOur dictionaries are strongly focused on multilingualism but as 2022, maybe the close discussion at international level would be https://en.m.wikipedia.org/wiki/Localisation_(humanitarian_practice)[Localisation (humanitarian practice)]. However, _localisation_ on these discussions is a different sense than https://en.m.wikipedia.org/wiki/Internationalization_and_localization[Internationalization and localization], which is more aligned with use of these works on software.\n///\n**/PRO BONŌ PUBLICŌ/@lat-Latn**\n\nThe lexicographers of this work not only are volunteers doing it for free but they don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books and most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.\n\nThere's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work considering it is feasible over 200 languages? The logistics to decide who should be paid, then **worldwide** cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither money nor humans interested in being coordinators exist.\n\nResuming: don't worth the trouble to be paid for this on such scale languages./@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [{0}]**_ is the book format of the machine-readable dictionaries _**[{0}] {1}**_, which are distributed for implementers on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.
    +++<br><br>+++
    **ABOUT LEXICOGRAPHY**
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    **ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**
    +++<br><br>+++
    We're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.
    +++<br><br>+++
    Since the full list of prototypal-dictionaries and dictionaries is huge, one way cited by objective audiences is the following:
    +++<br><br>+++
    1. Humanitarian aid2. Development aid
    3. Human rights
    4. Military relief (or conflict and conflict-resolution related concepts)
    +++<br><br>+++
    // -
    +++<br><br>+++
    The itens 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).
    +++<br><br>+++
    Note that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.
    +++<br><br>+++
    ////
    **BUT ARE SPECIALIZED DICTIONARIES NECESSARY AT ALL?**
    +++<br><br>+++
    This preface text is generated with every Cōdex version, so this may be a prototype/draft one (which means not a good example), but the answer is: yes. But a _very boring yes_. References about decision making on dictionaries are very scarce through centuries, but a quick summary on this topic: **any dictionary compilation to be useful should be based on _de facto_ users needs, which is different from typical validation**.
    +++<br><br>+++
    Our dictionaries are strongly focused on multilingualism but as 2022, maybe the close discussion at international level would be https://en.m.wikipedia.org/wiki/Localisation_(humanitarian_practice)[Localisation (humanitarian practice)]. However, _localisation_ on these discussions is a different sense than https://en.m.wikipedia.org/wiki/Internationalization_and_localization[Internationalization and localization], which is more aligned with use of these works on software.
    ////
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    The lexicographers of this work not only are volunteers doing it for free but they don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books and most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.
    +++<br><br>+++
    There's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work considering it is feasible over 200 languages? The logistics to decide who should be paid, then **worldwide** cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither money nor humans interested in being coordinators exist.
    +++<br><br>+++
    Resuming: don't worth the trouble to be paid for this on such scale languages.





[id='10_2']
==== [`10_2`] /**Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ a static work), then the actual groundbreaking difference on the workflow used to generate every group of dictionaries on a Cōdex such as this one is the following fact: **we provide machine-readable structured file formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with use cases such, for example, the need to collect and exchange data accurately.\n\n**Practical implication**: the text documents on _Archīa prō cōdice_ (literal English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an positive impact./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    **Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ a static work), then the actual groundbreaking difference on the workflow used to generate every group of dictionaries on a Cōdex such as this one is the following fact: **we provide machine-readable structured file formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with use cases such, for example, the need to collect and exchange data accurately.
    +++<br><br>+++
    **Practical implication**: the text documents on _Archīa prō cōdice_ (literal English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an positive impact.

  Lingua Lusitana (Abecedarium Latinum):::
    **Informações de contexto**: ignorando por um momento o fato de ter várias traduções (e otimizadas para receber contribuições regularmente, não _apenas_ um trabalho estático), então a diferença real no fluxo de trabalho usado para gerar cada grupo de dicionários em um Cōdex como este é o seguinte fato: **fornecemos formatos de arquivos estruturados legíveis por máquina mesmo quando os equivalentes em _idiomas internacionais_, como o inglês, não possuem para áreas como ajuda humanitária, ajuda ao desenvolvimento e direitos humanos**. Os mais próximos desse multilinguismo (fora da Wikimedia) são o SEMIeu da União Europeia (até 24 idiomas), mas mesmo assim têm problemas ao compartilhar traduções em todos os idiomas. As traduções das Nações Unidas (até 6 idiomas, raramente mais) não estão disponíveis por agências humanitárias para ajudar nas traduções de terminologia.
    +++<br><br>+++
    **Implicação prática**: os documentos de texto em _Archīa prō cōdice_ (tradução literal em inglês: _File for book_) são alternativas a este formato de livro que são altamente automatizados usando apenas o formato de dados. No entanto, os formatos legíveis por máquina em _Archīa prō dictiōnāriīs_ (tradução literal em inglês: _Arquivos para dicionários_) são o foco e recomendados para trabalhos derivados e destinados a mitigar erros humanos adicionais. Podemos até criar novos formatos a pedido! O objetivo aqui é permitir tradutores de terminologia e uso de produção onde isso tenha um impacto positivo.





[id='10_2_0']
===== [`10_2_0`] /Every book comes with several files both for book format (with (Abecedarium additional information) and machine-readable formats with Latinum) documentation of how to process them. If you receive this file and cannot find the alternatives, ask the human who provide this file./@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Every book comes with several files both for book format (with (Abecedarium additional information) and machine-readable formats with Latinum) documentation of how to process them. If you receive this file and cannot find the alternatives, ask the human who provide this file.</span>+++





[id='10_3']
==== [`10_3`] /WARNING: Unless you are working with a natural language you understand it\'s letters and symbols, it is strongly advised to use automation to generate derived works. Keep manual human steps at minimum: if something goes wrong at least one or more languages can be used to verify mistakes. It's not at all necessary _know all languages_, but working with writing systems you don't understand is risky: copy and paste strategy can cause _additional_ human errors and is unlikely to get human review as fast as you would need./@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">WARNING: Unless you are working with a natural language you understand it\'s letters and symbols, it is strongly advised to use automation to generate derived works. Keep manual human steps at minimum: if something goes wrong at least one or more languages can be used to verify mistakes. It's not at all necessary _know all languages_, but working with writing systems you don't understand is risky: copy and paste strategy can cause _additional_ human errors and is unlikely to get human review as fast as you would need.</span>+++





[id='10_4']
==== [`10_4`] /TIP: The Asciidoctor (.adoc) is better at copy and pasting! It can be converted to other text formats./@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">TIP: The Asciidoctor (.adoc) is better at copy and pasting! It can be converted to other text formats.</span>+++





[id='10_5']
==== [`10_5`] /NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">NOTE: /No momento, não há fluxo de trabalho para usar https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], que na verdade poderia ser usado como armazenamento para nomenclatura mais rigorosa. As implementações atuais usam apenas conceitos do Wikidata, os Q-items./@eng-Latn</span>+++





[id='10_6']
==== [`10_6`] /The ***[{1}] {2}*** uses Wikidata as one strategy to conciliate language terms for one or more of its concepts.\n\nThis means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up-to-date translations./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    The ***[{1}] {2}*** uses Wikidata as one strategy to conciliate language terms for one or more of its concepts.
    +++<br><br>+++
    This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up-to-date translations.

  Lingua Lusitana (Abecedarium Latinum):::
    O ***[{1}] {2}*** usa o Wikidata como uma estratégia para conciliar termos linguísticos para um ou mais de seus conceitos.
    +++<br><br>+++
    Isso significa que este livro e os arquivos de dados de dicionários relacionados requerem atualizações periódicas para , no mínimo, sincronize e compartilhe novamente as traduções atualizadas.





[id='10_7']
==== [`10_7`] /**How reliable are the community translations (Wikidata source)?**\n\nThe short, default answer is: **they are reliable**, even in cases of no official translations for each subject.\n\nAs reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).\n\nHowever, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    **How reliable are the community translations (Wikidata source)?**
    +++<br><br>+++
    The short, default answer is: **they are reliable**, even in cases of no official translations for each subject.
    +++<br><br>+++
    As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).
    +++<br><br>+++
    However, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.

  Lingua Lusitana (Abecedarium Latinum):::
    **Qual a confiabilidade das traduções da comunidade (fonte Wikidata)?**
    +++<br><br>+++
    A resposta curta padrão é: **elas são confiáveis**, mesmo nos casos de não haver traduções oficiais para cada assunto.
    +++<br><br>+++
    Como referência, é provável que um tradutor profissional (sem acesso à Wikipedia ou bases de terminologia interna das organizações de controle) forneça resultados de qualidade inferior se você fizer testes cegos. Isso é possível porque não apenas o público médio, mas também terminólogos e tradutores profissionais ajudam a Wikipédia (e implicitamente o Wikidata).
    +++<br><br>+++
    No entanto, mesmo quando o resultado está correto, a versão atual precisa de diferenciação aprimorada, no mínimo, sigla e forma longa . Para grandes organizações, existem recursos como __P1813 nomes curtos__, mas ainda não foram compilados com o conjunto de dados atual.





[id='10_8']
==== [`10_8`] /**Major reasons for "wrong translations" are not translators fault**\n\nTIP: As a rule of thumb, for already very defined concepts where you, as a human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.\n\nThe main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.\n\nIt is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    **Major reasons for "wrong translations" are not translators fault**
    +++<br><br>+++
    TIP: As a rule of thumb, for already very defined concepts where you, as a human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.
    +++<br><br>+++
    The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.
    +++<br><br>+++
    It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.

  Lingua Lusitana (Abecedarium Latinum):::
    **Os principais motivos para "traduções erradas" não são culpa dos tradutores**
    +++<br><br>+++
    DICA: Como regra geral, para conceitos já muito definidos em que você, como humano, pode verificar manualmente um ou mais termos traduzidos como um resultado decente, as outras traduções provavelmente serão aceitáveis. Dicionários com casos extremos (como nomes de territórios em disputa) teriam mais explicações.
    +++<br><br>+++
    A principal razão para "traduções erradas" são conceitos mal definidos usados ​​para explicar aos tradutores da comunidade como gerar traduções de terminologia. Isso tornaria as traduções existentes do Wikidata (usadas não apenas por nós) inconsistentes. A segunda razão é se os dicionários usam traduções para conceitos sem uma correspondência estrita; em outras palavras, se fizermos definições mais estritas do que significa conceito, mas reutilizarmos termos menos exatos da Wikidada. Também há problemas quando idiomas inteiros são codificados com códigos errados. Observe que todos esses casos **traduções erradas NÃO são estritamente culpa do tradutor, mas sim da lexicografia**.
    +++<br><br>+++
    Ainda é possível ter erros estritos no nível de tradução. Mas mesmo que indiquemos aos usuários como corrigir o Wikidata/Wikipedia (com base na melhor explicação contextual de um conceito, como este livro), os requisitos para dizer que o termo anterior foi objetivamente um erro de tradução humana errado (se seguir nossa seriedade na construção de dicionário) são muito elevados.





[id='10_9']
==== [`10_9`] /From the point of view of data conciliation, the following methodology is used to publish the terminology translations with the main concept table.\n\n. The main handcrafted lexicographical table (explained on previous topic), also provided on `{0}.no1.tm.hxl.csv`, may reference Wiki QID.\n. Every unique QID of  `{0}.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!\n.. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares than for general use.\n. The query result, with all QIDs and term labels, is shared as `{0}.wikiq.tm.hxl.csv`\n. The community reviewed translations of each singular QID is pre-compiled on an individual file `{0}.wikiq.tm.hxl.csv`\n. `{0}.no1.tm.hxl.csv` plus `{0}.wikiq.tm.hxl.csv` created `{0}.no11.tm.hxl.csv`/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    From the point of view of data conciliation, the following methodology is used to publish the terminology translations with the main concept table.
    +++<br><br>+++
    . The main handcrafted lexicographical table (explained on previous topic), also provided on `{0}.no1.tm.hxl.csv`, may reference Wiki QID.
    . Every unique QID of  `{0}.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!
    .. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares than for general use.
    . The query result, with all QIDs and term labels, is shared as `{0}.wikiq.tm.hxl.csv`
    . The community reviewed translations of each singular QID is pre-compiled on an individual file `{0}.wikiq.tm.hxl.csv`
    . `{0}.no1.tm.hxl.csv` plus `{0}.wikiq.tm.hxl.csv` created `{0}.no11.tm.hxl.csv`

  Lingua Lusitana (Abecedarium Latinum):::
    Do ponto de vista da conciliação de dados, a seguinte metodologia é utilizada para publicar as traduções da terminologia com a tabela de conceitos principais.
    +++<br><br>+++
    . A principal tabela lexicográfica artesanal (explicada no tópico anterior), também fornecida em `{0}.no1.tm.hxl.csv`, pode fazer referência ao Wiki QID.
    . Cada QID exclusivo de `{0}.no1.tm.hxl.csv`, juntamente com códigos de idioma de [`1603:1:51`] (que requer conhecimento de idiomas humanos), é usado para preparar uma consulta SPARQL otimizada para execução em https://query.wikidata.org/[Wikidata Query Service]. A consulta é tão grande que não é viável para links "Try it" (URL longo), como https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[como o que você encontraria nos Tutoriais Wikidata ], ***mas*** funciona!
    .. Note que o conhecimento é gratuito, as traduções estão lá, mas as necessidades humanitárias multilíngues podem faltar pessoas para preparar os arquivos e compartilhar do que para uso geral.
    . O resultado da consulta, com todos os QIDs e rótulos de termos, é compartilhado como `{0}.wikiq.tm.hxl.csv`
    . As traduções revisadas pela comunidade de cada QID singular são pré-compiladas em um arquivo individual `{0}.wikiq.tm.hxl.csv`
    . `{0}.no1.tm.hxl.csv` mais `{0}.wikiq.tm.hxl.csv` criado `{0}.no11.tm.hxl.csv`





[id='10_10']
==== [`10_10`] /This section explains the methodology of this book, and its machine-readable structured data formats. For your convenience, the information used to explain the concepts (such as natural language and interlingual codes) which appears in this book are also summarized here. This approach is done both for reviews not needing to open other books (or deal with machine-readable files) and also to spot errors on other dictionaries. +++<br><br>+++ About how the book and the dictionaries are compiled, a division of "baseline concept table" and (when relevant for a codex) "translations conciliation" is given different methodologies. +++<br><br>+++ Every book contains at minimum the baseline concept table and explanation of the used fields. This approach helps to release dictionaries faster while ensuring both humans and machines can know what to expect even when they are not ready to receive translations./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    This section explains the methodology of this book, and its machine-readable structured data formats. For your convenience, the information used to explain the concepts (such as natural language and interlingual codes) which appears in this book are also summarized here. This approach is done both for reviews not needing to open other books (or deal with machine-readable files) and also to spot errors on other dictionaries. +++<br><br>+++ About how the book and the dictionaries are compiled, a division of "baseline concept table" and (when relevant for a codex) "translations conciliation" is given different methodologies. +++<br><br>+++ Every book contains at minimum the baseline concept table and explanation of the used fields. This approach helps to release dictionaries faster while ensuring both humans and machines can know what to expect even when they are not ready to receive translations.

  Lingua Lusitana (Abecedarium Latinum):::
    Esta seção explica a metodologia deste livro e seus formatos de dados estruturados legíveis por máquina. Para sua conveniência, as informações usadas para explicar os conceitos (como linguagem natural e códigos interlinguais) que aparecem neste livro também estão resumidas aqui. Essa abordagem é feita tanto para revisões que não precisam abrir outros livros (ou lidar com arquivos legíveis por máquina) quanto para detectar erros em outros dicionários. +++<br><br>+++ Sobre como o livro e os dicionários são compilados, uma divisão de "quadro de conceitos básicos" e (quando relevante para um códice) "conciliação de traduções" é dada por diferentes metodologias. +++<br><br>+++ Todo livro contém no mínimo a tabela de conceitos básicos e a explicação dos campos usados. Essa abordagem ajuda a liberar dicionários mais rapidamente, garantindo que humanos e máquinas saibam o que esperar, mesmo quando não estiverem prontos para receber traduções.





[id='10_11']
==== [`10_11`] /While the previous section presented the linguistic information (e.g. natural languages list) from [[1603:1:51]] restricted to what this book edition de facto has, this section gives a quick summary of Interlinguistic Information of [[1603:1:7]]. By Interlinguistic, it can be either true, language neutral codes (such as numbers) or computer codes which actually are mnemonics using some non-neutral writing system. Interlinguistic, in the worst case, means some sort of _external identifier_ likely to be usable as a machine-readable identifier.\n\nThe next section, **Archīa** (literal English translation: Files) will only show [[{0}]] direct related files. But the complete [[1603:1:51]] and [[1603:1:7]] are available and licensed under public domain, which makes them very friendly to derived works while mitigating implementers _additional_ errors./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    While the previous section presented the linguistic information (e.g. natural languages list) from [[1603:1:51]] restricted to what this book edition de facto has, this section gives a quick summary of Interlinguistic Information of [[1603:1:7]]. By Interlinguistic, it can be either true, language neutral codes (such as numbers) or computer codes which actually are mnemonics using some non-neutral writing system. Interlinguistic, in the worst case, means some sort of _external identifier_ likely to be usable as a machine-readable identifier.
    +++<br><br>+++
    The next section, **Archīa** (literal English translation: Files) will only show [[{0}]] direct related files. But the complete [[1603:1:51]] and [[1603:1:7]] are available and licensed under public domain, which makes them very friendly to derived works while mitigating implementers _additional_ errors.

  Lingua Lusitana (Abecedarium Latinum):::
    Enquanto a seção anterior apresentou a informação linguística (por exemplo, lista de línguas naturais) de [[1603:1:51]] restrita ao que esta edição do livro de fato tem, esta seção fornece um rápido resumo da Informação Interlinguística de [[1603:1:7]]. Por interlinguística, pode ser verdadeiro, códigos neutros de linguagem (como números) ou códigos de computador que na verdade são mnemônicos usando algum sistema de escrita não neutro. Interlinguístico, na pior das hipóteses, significa algum tipo de _identificador externo_ provavelmente utilizável como um identificador legível por máquina.
    +++<br><br>+++
    A próxima seção, **Archīa** (tradução literal em inglês: Arquivos) mostrará apenas [[{0 }]] arquivos relacionados diretos. Mas os [[1603:1:51]] e [[1603:1:7]] completos estão disponíveis e licenciados sob domínio público, o que os torna muito amigáveis para trabalhos derivados enquanto mitiga erros _adicionais_ dos implementadores.





[id='10_12']
==== [`10_12`] /Ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis), then the actual groundbreaking difference to every dictionary on Cōdex such as this one is the following fact: **we provide well documented machine-readable formats** even when the equivalents in English don't have./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis), then the actual groundbreaking difference to every dictionary on Cōdex such as this one is the following fact: **we provide well documented machine-readable formats** even when the equivalents in English don't have.</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Ignorando por um momento o fato de ter várias traduções (e otimizadas para receber contribuições regularmente), então a verdadeira diferença inovadora para cada dicionário no Cōdex como este é o seguinte fato: **fornecemos documentos legíveis por máquina bem documentados formatos** mesmo quando os equivalentes em inglês não possuem.</span>+++





<<<

[id='20']
=== [`20`] /Disambiguation between dictionaries/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Disambiguation between dictionaries</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Desambiguação entre dicionários</span>+++





[id='20_1']
==== [`20_1`] /\n\n**RELATED DICTIONARIES**\n\n\nThis namespace of dictionaries have related (but not equal) actors which may _help_ other humans using different strategies. The differentiation between then is **very** relevant as this affects perception of neutrality when _help_ is done.\n\n\n**1603:63:1** //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//\n\nThis is stricter and more well know type of humanitarian aid. It MUST focus on immediate needs, which differentiate them from development aid.\n\n\n**[1603:26:21]** //Dictiōnāria dē Iurum humanorum defensor//\n\nThis is the most generic type of human rights defender. In addition to defend some type of human rights, MUST not cause intentional harm to other human beings unless in self defense and not disproportional immediate to the danger.\n\n\n**[1603:26:36]** //Dictiōnāria dē intraimperiīs lēgisperītīs per lēgēs certiōrātū//\n\nThis is a very strict type of **1603:26:21**. The main difference are the modi operandi : uses own country laws or it's signed international treaties to defend specific cases or reforms on country judicial system.\n\n**[1603:45:997]** //(needs be boostrapped)//\n\nDevelopment aid, while may be practiced as part of humanitarian operations to reduce likelihood of future need from foreigner help to do humanitarian aid, is not the same as humanitarian aid. \n\n\n**[1603:14:997]** //Dictiōnāria dē relevāminibus per bellīs//\n\nMilitary relief is a type of intervention on a foreign country justified on reduce individual human suffering which already is not considered a formal peacekeeping operation./@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    
    +++<br><br>+++
    **RELATED DICTIONARIES**
    +++<br><br>+++
    
    This namespace of dictionaries have related (but not equal) actors which may _help_ other humans using different strategies. The differentiation between then is **very** relevant as this affects perception of neutrality when _help_ is done.
    +++<br><br>+++
    
    **1603:63:1** //Dictiōnāria basibus dē auxiliīs hūmānitātibus strictīs//
    +++<br><br>+++
    This is stricter and more well know type of humanitarian aid. It MUST focus on immediate needs, which differentiate them from development aid.
    +++<br><br>+++
    
    **[1603:26:21]** //Dictiōnāria dē Iurum humanorum defensor//
    +++<br><br>+++
    This is the most generic type of human rights defender. In addition to defend some type of human rights, MUST not cause intentional harm to other human beings unless in self defense and not disproportional immediate to the danger.
    +++<br><br>+++
    
    **[1603:26:36]** //Dictiōnāria dē intraimperiīs lēgisperītīs per lēgēs certiōrātū//
    +++<br><br>+++
    This is a very strict type of **1603:26:21**. The main difference are the modi operandi : uses own country laws or it's signed international treaties to defend specific cases or reforms on country judicial system.
    +++<br><br>+++
    **[1603:45:997]** //(needs be boostrapped)//
    +++<br><br>+++
    Development aid, while may be practiced as part of humanitarian operations to reduce likelihood of future need from foreigner help to do humanitarian aid, is not the same as humanitarian aid. 
    +++<br><br>+++
    
    **[1603:14:997]** //Dictiōnāria dē relevāminibus per bellīs//
    +++<br><br>+++
    Military relief is a type of intervention on a foreign country justified on reduce individual human suffering which already is not considered a formal peacekeeping operation.





<<<

[id='50']
=== [`50`] /Quotes and other messages/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Quotes and other messages</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Citações e outras mensagens</span>+++





[id='50_1']
==== [`50_1`] /**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">**Public domain means that each major common issue only needs to be resolved once**</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">**Dedicação ao Domínio Público significa que cada grande problema comum só precisa ser resolvido uma vez**</span>+++





<<<

[id='100']
=== [`100`] /Notāte bene/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Notāte bene</span>+++





[id='100_1']
==== [`100_1`] /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">[HELP WANTED] Generated PDF don't have right fonts for all languages</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">[PRECISAMOS DE AJUDA] O PDF gerado não tem as fontes corretas para todos os idiomas</span>+++





[id='100_1_1']
===== [`100_1_1`] /First, sorry if this affects your loved language :(. We're working on this, but we are still not perfected book generation in so many languages at same time.\nIf you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.\nPlease note that all formats intended for machine processing will work fine./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language :(. We're working on this, but we are still not perfected book generation in so many languages at same time.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.

  Lingua Lusitana (Abecedarium Latinum):::
    Primeiro, desculpe se isso afeta seu idioma favorito :(. Estamos trabalhando nisso, mas ainda não estamos aperfeiçoando a geração de livros em tantos idiomas ao mesmo tempo.
    Se você tiver fontes instaladas em seu computador, provavelmente ainda poderá copiar e colar da versão eBook.
    Observe que todos os formatos destinados ao processamento de máquina funcionarão bem.





[id='100_2']
==== [`100_2`] /[eBook with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">[eBook with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">[eBook com Wikidata Q] Quero ajudar! Alguma tradução está faltando ou está errada! Como muda-la?</span>+++





[id='100_2_1']
===== [`100_2_1`] /Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries! Please check if the exact concept you want have a Q ID then click. There you can add translations.\nThe next release (likely weekly) will have your submissions without need to contact us directly./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries! Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.

  Lingua Lusitana (Abecedarium Latinum):::
    A maioria (mas não todos) os conceitos estão usando o Wikidata Q. Na verdade, na maioria das vezes melhoramos o Wikidata enquanto preparamos os dicionários! Verifique se o conceito exato que você deseja tem um Q ID e clique nele. Lá você pode adicionar traduções.
    A próxima versão (provavelmente semanal) terá seus envios sem a necessidade de nos contatar diretamente.





[id='100_3']
==== [`100_3`] /[eBook with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">[eBook with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">[eBook com Wikidata Q] Posso encontrar o conceito Wikidata, mas não consigo editar!</span>+++





[id='100_3_1']
===== [`100_3_1`] /While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.\nHowever, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.

  Lingua Lusitana (Abecedarium Latinum):::
    Embora o Wikidata seja mais flexível do que o da Wikipedia (por exemplo, permite conceitos sem a necessidade de criar páginas da Wikipedia), mesmo o Wikidata pode ter conceitos que exigem a criação de uma conta e não permitem edição anônima. Criar tal conta e confirmar e-mail é mais rápido do que pedir que outra pessoa faça isso por você.
    No entanto, embora o vandalismo no Wikidata seja raro, muito poucos conceitos exigirão uma conta com mais contribuições e não criada muito recentemente. Se este for o seu caso, ajude com os que você pode fazer sozinho e o resto peça para outra pessoa adicionar a você.





[id='100_4']
==== [`100_4`] /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">I heard there is an interest in having Cōdex beyond Latin language! How to do it?!</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Ouvi dizer que há interesse em ter o Cōdex além da língua latina! Como fazer?!</span>+++





[id='100_4_1']
===== [`100_4_1`] /Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Por favor, entre em contato conosco. Este livro usa latim (às vezes _latim macarrónico_) para documentar todos os outros idiomas, mas obviamente podemos automatizar a geração de livros para outros usando outros sistemas de escrita e algum idioma de referência. Precisamos de ajuda especial com sistemas de escrita como Bengali, Devanagari e Tamil. Para scripts da direita para a esquerda, apesar de poder renderizar o texto, a impressão do livro exigirá um modelo diferente. Apenas substituir o latim não funcionará, por isso estamos abertos a ideias para proporcionar uma ótima experiência ao usuário!</span>+++





<<<

[id='101']
=== [`101`] /TODO move to 1603_1_101 (archives) here temporary/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">TODO move to 1603_1_101 (archives) here temporary</span>+++





[id='101_1']
==== [`101_1`] //Numerordinatio on HXLTM container//@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">/Numerordinatio on HXLTM container/</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">/Numerordinatio no contêiner HXLTM/</span>+++





[id='101_2']
==== [`101_2`] //Numerordinatio on HXLTM container (expanded with terminology translations)//@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">/Numerordinatio on HXLTM container (expanded with terminology translations)/</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">/Numerordinatio no contêiner HXLTM (expandido com traduções de terminologia)/</span>+++





[id='101_3']
==== [`101_3`] //Metadata about no1.tm.hxl.csv//@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">/Metadata about no1.tm.hxl.csv/</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">/Metadados sobre no1.tm.hxl.csv/</span>+++





[id='101_4']
==== [`101_4`] //Metadata about tm.hxl.csv//@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">/Metadata about tm.hxl.csv/</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">/Metadados sobre tm.hxl.csv/</span>+++





[id='101_5']
==== [`101_5`] //Metadata about annexes (local namespace)//@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">/Metadata about annexes (local namespace)/</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">/Metadados sobre anexos (espaço de nomes local)/</span>+++





[id='101_6']
==== [`101_6`] /HXLTM dialect of HXLStandard on CSV RFC 4180. TL;DR: wikiq means #item+conceptum+codicem are strictly Wikidata QIDs./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">HXLTM dialect of HXLStandard on CSV RFC 4180. TL;DR: wikiq means #item+conceptum+codicem are strictly Wikidata QIDs.</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Dialeto HXLTM do Padrão HXL em CSV RFC 4180. Resumidamente: wikiq significa que #item+conceptum+codicem são estritamente Wikidata QIDs.</span>+++





[id='101_6_854']
===== [`101_6_854`] /https://hxltm.etica.ai//@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">https://hxltm.etica.ai/</span>+++





[id='101_7']
==== [`101_7`] /TODO no11.xml/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">TODO no11.xml</span>+++





[id='101_7_854']
===== [`101_7_854`] /https://hxltm.etica.ai//@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">https://hxltm.etica.ai/</span>+++





[id='101_8']
==== [`101_8`] /TBX-Basic is a terminological markup language (TML) that is a lighter version of TBX-Default, the TML that is defined in ISO 30042. TBX-Basic is designed for the localization industry and is based on information from surveys and studies that were conducted by the LISA Term SIG about the types of terminology data that the localization industry requires./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">TBX-Basic is a terminological markup language (TML) that is a lighter version of TBX-Default, the TML that is defined in ISO 30042. TBX-Basic is designed for the localization industry and is based on information from surveys and studies that were conducted by the LISA Term SIG about the types of terminology data that the localization industry requires.</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">TBX-Basic é uma linguagem de marcação terminológica (TML) que é uma versão mais leve de TBX-Default, a TML que é definida na ISO 30042. TBX-Basic é projetada para o setor de localização e é baseada em informações de pesquisas e estudos que foram conduzida pelo LISA Term SIG sobre os tipos de dados de terminologia que o setor de localização exige.</span>+++





[id='101_8_854']
===== [`101_8_854`] /http://www.terminorgs.net/downloads/TBX_Basic_Version_3.1.pdf/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">http://www.terminorgs.net/downloads/TBX_Basic_Version_3.1.pdf</span>+++





[id='101_9']
==== [`101_9`] /The purpose of the Translation Memory eXchange format (TMX) format is to provide a standard method to describe translation memory data that is being exchanged among tools and/or translation vendors, while introducing little or no loss of critical data during the process/@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">The purpose of the Translation Memory eXchange format (TMX) format is to provide a standard method to describe translation memory data that is being exchanged among tools and/or translation vendors, while introducing little or no loss of critical data during the process</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">O objetivo do formato Translation Memory eXchange (TMX) é fornecer um método padrão para descrever dados de memória de tradução que estão sendo trocados entre ferramentas e/ou fornecedores de tradução, ao mesmo tempo em que introduz pouca ou nenhuma perda de dados críticos durante o processo</span>+++





[id='101_9_854']
===== [`101_9_854`] /https://www.gala-global.org/tmx-14b/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">https://www.gala-global.org/tmx-14b</span>+++





[id='101_10']
==== [`101_10`] /AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">AsciiDoc é um formato de autoria de texto simples (ou seja, linguagem de marcação leve) para escrever conteúdo técnico, como documentação, artigos e livros.</span>+++





[id='101_10_854']
===== [`101_10_854`] /https://docs.asciidoctor.org//@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">https://docs.asciidoctor.org/</span>+++





[id='101_11']
==== [`101_11`] /Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems./@eng-Latn

Rēs linguālibus (2)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems.</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Portable Document Format (PDF), padronizado como ISO 32000, é um formato de arquivo desenvolvido pela Adobe em 1992 para apresentar documentos, incluindo formatação de texto e imagens, de maneira independente do software aplicativo, hardware e sistemas operacionais.</span>+++





[id='101_11_854']
===== [`101_11_854`] /https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf</span>+++





<<<

[id='999']
=== [`999`] /@TODOs/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">@TODOs</span>+++





[id='999_1']
==== [`999_1`] /Add links to codex to search by last edits on Q itens on the current book. See https://wikidata-todo.toolforge.org/sparql_rc.php?/@eng-Latn

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Add links to codex to search by last edits on Q itens on the current book. See https://wikidata-todo.toolforge.org/sparql_rc.php?</span>+++






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== [PRECISAMOS DE AJUDA] O PDF gerado não tem as fontes corretas para todos os idiomas

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Primeiro, desculpe se isso afeta seu idioma favorito :(. Estamos trabalhando nisso, mas ainda não estamos aperfeiçoando a geração de livros em tantos idiomas ao mesmo tempo.
    Se você tiver fontes instaladas em seu computador, provavelmente ainda poderá copiar e colar da versão eBook.
    Observe que todos os formatos destinados ao processamento de máquina funcionarão bem.


=== [eBook com Wikidata Q] Quero ajudar! Alguma tradução está faltando ou está errada! Como muda-la?

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    A maioria (mas não todos) os conceitos estão usando o Wikidata Q. Na verdade, na maioria das vezes melhoramos o Wikidata enquanto preparamos os dicionários! Verifique se o conceito exato que você deseja tem um Q ID e clique nele. Lá você pode adicionar traduções.
    A próxima versão (provavelmente semanal) terá seus envios sem a necessidade de nos contatar diretamente.


=== [eBook com Wikidata Q] Posso encontrar o conceito Wikidata, mas não consigo editar!

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Embora o Wikidata seja mais flexível do que o da Wikipedia (por exemplo, permite conceitos sem a necessidade de criar páginas da Wikipedia), mesmo o Wikidata pode ter conceitos que exigem a criação de uma conta e não permitem edição anônima. Criar tal conta e confirmar e-mail é mais rápido do que pedir que outra pessoa faça isso por você.
    No entanto, embora o vandalismo no Wikidata seja raro, muito poucos conceitos exigirão uma conta com mais contribuições e não criada muito recentemente. Se este for o seu caso, ajude com os que você pode fazer sozinho e o resto peça para outra pessoa adicionar a você.


=== Ouvi dizer que há interesse em ter o Cōdex além da língua latina! Como fazer?!

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Por favor, entre em contato conosco. Este livro usa latim (às vezes _latim macarrónico_) para documentar todos os outros idiomas, mas obviamente podemos automatizar a geração de livros para outros usando outros sistemas de escrita e algum idioma de referência. Precisamos de ajuda especial com sistemas de escrita como Bengali, Devanagari e Tamil. Para scripts da direita para a esquerda, apesar de poder renderizar o texto, a impressão do livro exigirá um modelo diferente. Apenas substituir o latim não funcionará, por isso estamos abertos a ideias para proporcionar uma ótima experiência ao usuário!


<<<

