= Cōdex [1603:64:604]: //Dictiōnāria dē aquīs et sānātiōnibus ex līmpidīs//
:doctype: book
:title: Cōdex [1603:64:604]: //Dictiōnāria dē aquīs et sānātiōnibus ex līmpidīs//
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum
:front-cover-image: image:1603_64_604.mul-Latn.codex.svg["Cōdex [1603_64_604]: //Dictiōnāria dē aquīs et sānātiōnibus ex līmpidīs//",1050,1600]




{nbsp} +
{nbsp} +
[quote]
**Dedicação ao Domínio Público significa que cada grande problema comum só precisa ser resolvido uma vez**

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-04-14

|
numerus editionis
|
2022-04-29T02:06:07

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:64:604]**_ é o formato de livro dos dados estruturados legíveis por máquina do grupo de dicionários _**[1603:64:604] //Dictiōnāria dē aquīs et sānātiōnibus ex līmpidīs//**_, que são distribuídos para os implementadores usarem em aplicativos externos. Este livro pretende ser um recurso avançado para outros lexicógrafos e tradutores de terminologia, inclusive para detectar e relatar inconsistências. Ele pode, no entanto, ser usado como um dicionário ad hoc se não houver trabalho derivado focado em suas necessidades específicas.
    +++<br><br>+++
    **SOBRE LEXICOGRAFIA**
    +++<br><br>+++
    A lexicografia prática é a arte ou ofício de compilar, escrever e editar dicionários. O básico não é muito diferente de um milênio atrás: ainda é um trabalho muito humano e criativo. É preciso ser humilde: a maioria dos erros de tradutores, na verdade, não é culpa do tradutor, mas falhas metodológicas. Certificar-se de uma ideia de origem do que um conceito representa, mesmo que signifique reescrever e simplificar, anexar fotos, mostrar exemplos, fazer o que for para que seja entendido, faz com que até mesmo tradutores não profissionais que se preocupam com sua própria língua entreguem melhor resultados do que qualquer alternativa. Em outras palavras: mesmo as chamadas melhores práticas da indústria de pagar tradutores e revisores profissionais não podem superar termos de origem já mal explicados.
    +++<br><br>+++
    **SOBRE TIPOS DE DICIONÁRIOS QUE ESTAMOS COMPILANDO**
    +++<br><br>+++
    Estamos preocupados com um grupo de idéias (chamamos isso de grupo de dicionários de conceitos) que podem ser divididos em partes menores, revisados quanto a inconsistências, aprimorados para definições e depois traduzidos por voluntários. Códigos interlinguais, como o que poderia ser usado na troca de dados real, também são adicionados a cada conceito. Ambos os glossários, interfaces de usuário (como rótulos na coleta de dados) e, em alguns casos, até códigos padrão para o que iria em um campo de dados podem ser compilados dessa maneira.
    +++<br><br>+++
    Como a lista completa de dicionários-prototípicos e dicionários minimamente utilizáveis é enorme, um modo de citar público-alvos típicos é o seguinte:
    +++<br><br>+++
    . Ajuda humanitária
    . Ajuda ao desenvolvimento
    . Direitos humanos
    . Socorro militar (ou conceitos relacionados a conflitos e resolução de conflitos)
    +++<br><br>+++
    Os itens 1, 2 e 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[são algumas vezes referidos como _nexus_] e são frequentemente encontrados ajudando _crise humanitária_. Já que a maioria dos colaboradores cujas ideias e críticas válidas são voluntárias, então 3 (direitos humanos, como na Anistia Internacional) para diferenciar do humanitarismo (como o Movimento da Cruz Vermelha é referência).
    +++<br><br>+++
    Observe que **dicionários não são guias de uso**. As instruções, quando existem, são principalmente dedicadas a lexicógrafos e tradutores.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    As pessoas lexicógrafas deste trabalho são voluntárias, fazendo-o gratuitamente, pro bonō publicō, e não aceitam doações por causa dos dicionários reutilizáveis ​​de todos. O trabalho anterior existente muitas vezes é baseado em livros antigos de domínio público. A maioria dos tradutores de terminologia já seriam voluntários porque acreditam em uma causa. A melhor maneira de inspirar a colaboração é sermos nós mesmos exemplos.
    +++<br><br>+++
    Há um aspecto não moralista, bastante simples de entender: quão caro seria pagar pelo trabalho de todos considerando que é viável em mais de 200 idiomas? A logística para decidir quem deve ser pago, depois a transferência de dinheiro em todo o mundo (pode incluir pessoas de países embargados), depois os mecanismos tradicionais de auditoria para verificar o uso indevido que os doadores esperam, existe? Em terminologia especial (os próprios termos do dicionário) e tantas línguas, não existe dinheiro suficiente nem humanos interessados ​​em ser coordenadores.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
Rēs interlinguālibus (1)::
  /scope and content/@eng-Latn:::
    The decision making behind these dictionaries are general terminology related to water and improving human health through cleanliness.
    +++<br><br>+++
    In English, in the humanitarian sector the typical term used is WaSH: Water, Sanitation and Hygiene. The Latin term we use is not a direct literal translation from the English term, but the idea behind the concept. Add to this that /sanitation/@lat-Latn is somewhat redundant with /hygiene/@fra-Latn, which would generate a nonsensical Latin term in this context.
    +++<br><br>+++
    Another relevant topic which these dictionaries would contain terminology is the Sustainable Development Goal 6 (SDG 6 or Global Goal 6) about _clean water and sanitation for all_ (which is a concept much newer than the idea of WaSH on humanitarian sector). In English _hygiene_ is mentioned, but not as part of title or short descriptions.
    +++<br><br>+++
    **How complete are these dictionaries?**
    The concepts here are incomplete and the current state is more focused on available translations we can compile. The ideal would be to prepare the definitions and start to add them on Wikipedia, which in turn would allow us to start having very well defined QIDs to scale translations.
    +++<br><br>+++
    **Know issues**
    As 2022-04-19 the concept Q5893646 is an example of generating wrong translations. /Bucket toilet/@eng-Latn is linked to /Goldeimer/@deu-Latn (use of human excrementa exchanged for money). Ideally **before** asking for translation Initiatives we should review /Bucket toilet/@eng-Latn for a term easier to translate, not just create literal translations for other languages.



=== Methodī ex verbīs in dictiōnāriīs
NOTE: /No momento, não há fluxo de trabalho para usar https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], que na verdade poderia ser usado como armazenamento para nomenclatura mais rigorosa. As implementações atuais usam apenas conceitos do Wikidata, os Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    O ***[1603:64:604] //Dictiōnāria dē aquīs et sānātiōnibus ex līmpidīs//*** usa o Wikidata como uma estratégia para conciliar termos linguísticos para um ou mais de seus conceitos.
    +++<br><br>+++
    Isso significa que este livro e os arquivos de dados de dicionários relacionados requerem atualizações periódicas para , no mínimo, sincronize e compartilhe novamente as traduções atualizadas.
    +++<br><br>+++
    **Qual a confiabilidade das traduções da comunidade (fonte Wikidata)?**
    +++<br><br>+++
    A resposta curta padrão é: **elas são confiáveis**, mesmo nos casos de não haver traduções oficiais para cada assunto.
    +++<br><br>+++
    Como referência, é provável que um tradutor profissional (sem acesso à Wikipedia ou bases de terminologia interna das organizações de controle) forneça resultados de qualidade inferior se você fizer testes cegos. Isso é possível porque não apenas o público médio, mas também terminólogos e tradutores profissionais ajudam a Wikipédia (e implicitamente o Wikidata).
    +++<br><br>+++
    No entanto, mesmo quando o resultado está correto, a versão atual precisa de diferenciação aprimorada, no mínimo, sigla e forma longa . Para grandes organizações, existem recursos como __P1813 nomes curtos__, mas ainda não foram compilados com o conjunto de dados atual.
    +++<br><br>+++
    **Os principais motivos para "traduções erradas" não são culpa dos tradutores**
    +++<br><br>+++
    DICA: Como regra geral, para conceitos já muito definidos em que você, como humano, pode verificar manualmente um ou mais termos traduzidos como um resultado decente, as outras traduções provavelmente serão aceitáveis. Dicionários com casos extremos (como nomes de territórios em disputa) teriam mais explicações.
    +++<br><br>+++
    A principal razão para "traduções erradas" são conceitos mal definidos usados ​​para explicar aos tradutores da comunidade como gerar traduções de terminologia. Isso tornaria as traduções existentes do Wikidata (usadas não apenas por nós) inconsistentes. A segunda razão é se os dicionários usam traduções para conceitos sem uma correspondência estrita; em outras palavras, se fizermos definições mais estritas do que significa conceito, mas reutilizarmos termos menos exatos da Wikidada. Também há problemas quando idiomas inteiros são codificados com códigos errados. Observe que todos esses casos **traduções erradas NÃO são estritamente culpa do tradutor, mas sim da lexicografia**.
    +++<br><br>+++
    Ainda é possível ter erros estritos no nível de tradução. Mas mesmo que indiquemos aos usuários como corrigir o Wikidata/Wikipedia (com base na melhor explicação contextual de um conceito, como este livro), os requisitos para dizer que o termo anterior foi objetivamente um erro de tradução humana errado (se seguir nossa seriedade na construção de dicionário) são muito elevados.
    +++<br><br>+++
    Do ponto de vista da conciliação de dados, a seguinte metodologia é utilizada para publicar as traduções da terminologia com a tabela de conceitos principais.
    +++<br><br>+++
    . A principal tabela lexicográfica artesanal (explicada no tópico anterior), também fornecida em `1603_64_604.no1.tm.hxl.csv`, pode fazer referência ao Wiki QID.
    . Cada QID exclusivo de `1603_64_604.no1.tm.hxl.csv`, juntamente com códigos de idioma de [`1603:1:51`] (que requer conhecimento de idiomas humanos), é usado para preparar uma consulta SPARQL otimizada para execução em https://query.wikidata.org/[Wikidata Query Service]. A consulta é tão grande que não é viável para links "Try it" (URL longo), como https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[como o que você encontraria nos Tutoriais Wikidata ], ***mas*** funciona!
    .. Note que o conhecimento é gratuito, as traduções estão lá, mas as necessidades humanitárias multilíngues podem faltar pessoas para preparar os arquivos e compartilhar do que para uso geral.
    . O resultado da consulta, com todos os QIDs e rótulos de termos, é compartilhado como `1603_64_604.wikiq.tm.hxl.csv`
    . As traduções revisadas pela comunidade de cada QID singular são pré-compiladas em um arquivo individual `1603_64_604.wikiq.tm.hxl.csv`
    . `1603_64_604.no1.tm.hxl.csv` mais `1603_64_604.wikiq.tm.hxl.csv` criado `1603_64_604.no11.tm.hxl.csv`


=== Rēs dē factō in dictiōnāriīs
==== Concepta: 28

==== Rēs linguālibus: 226

[%header,cols="15h,25a,~,17"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
mul-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/mul[mul]
+++<br>+++ 
|
Linguae multiplīs (Scrīptum incognitō)
|
27

|
ara-Arab
|
https://glottolog.org/resource/languoid/id/arab1395[arab1395]
+++<br>+++
https://iso639-3.sil.org/code/ara[ara]
+++<br>+++ https://www.wikidata.org/wiki/Q13955[Q13955]
|
Macrolingua Arabica (Abecedarium Arabicum)
|
22

|
hye-Armn
|
https://glottolog.org/resource/languoid/id/nucl1235[nucl1235]
+++<br>+++
https://iso639-3.sil.org/code/hye[hye]
+++<br>+++ https://www.wikidata.org/wiki/Q8785[Q8785]
|
Lingua Armenia (Alphabetum Armenium)
|
8

|
ben-Beng
|
https://glottolog.org/resource/languoid/id/beng1280[beng1280]
+++<br>+++
https://iso639-3.sil.org/code/ben[ben]
+++<br>+++ https://www.wikidata.org/wiki/Q9610[Q9610]
|
Lingua Bengali (/ISO 15924 Beng/)
|
14

|
rus-Cyrl
|
https://glottolog.org/resource/languoid/id/russ1263[russ1263]
+++<br>+++
https://iso639-3.sil.org/code/rus[rus]
+++<br>+++ https://www.wikidata.org/wiki/Q7737[Q7737]
|
Lingua Russica (Abecedarium Cyrillicum)
|
17

|
hin-Deva
|
https://glottolog.org/resource/languoid/id/hind1269[hind1269]
+++<br>+++
https://iso639-3.sil.org/code/hin[hin]
+++<br>+++ https://www.wikidata.org/wiki/Q1568[Q1568]
|
Lingua Hindica (Devanāgarī)
|
14

|
amh-Ethi
|
https://glottolog.org/resource/languoid/id/amha1245[amha1245]
+++<br>+++
https://iso639-3.sil.org/code/amh[amh]
+++<br>+++ https://www.wikidata.org/wiki/Q28244[Q28244]
|
Lingua Amharica (/ISO 15924 Ethi/)
|
2

|
kat-Geor
|
https://glottolog.org/resource/languoid/id/nucl1302[nucl1302]
+++<br>+++
https://iso639-3.sil.org/code/kat[kat]
+++<br>+++ https://www.wikidata.org/wiki/Q8108[Q8108]
|
Lingua Georgiana (Abecedarium Georgianum)
|
8

|
guj-Gujr
|
https://glottolog.org/resource/languoid/id/guja1252[guja1252]
+++<br>+++
https://iso639-3.sil.org/code/guj[guj]
+++<br>+++ https://www.wikidata.org/wiki/Q5137[Q5137]
|
Lingua Gujaratensis (/ISO 15924 Gujr/)
|
5

|
pan-Guru
|
https://glottolog.org/resource/languoid/id/panj1256[panj1256]
+++<br>+++
https://iso639-3.sil.org/code/pan[pan]
+++<br>+++ https://www.wikidata.org/wiki/Q58635[Q58635]
|
Lingua Paniabica (/ISO 15924 Guru/)
|
4

|
kan-Knda
|
https://glottolog.org/resource/languoid/id/nucl1305[nucl1305]
+++<br>+++
https://iso639-3.sil.org/code/kan[kan]
+++<br>+++ https://www.wikidata.org/wiki/Q33673[Q33673]
|
Lingua Cannadica (/ISO 15924 Knda/)
|
7

|
kor-Hang
|
https://glottolog.org/resource/languoid/id/kore1280[kore1280]
+++<br>+++
https://iso639-3.sil.org/code/kor[kor]
+++<br>+++ https://www.wikidata.org/wiki/Q9176[Q9176]
|
Lingua Coreana (Abecedarium Coreanum)
|
14

|
lzh-Hant
|
https://glottolog.org/resource/languoid/id/lite1248[lite1248]
+++<br>+++
https://iso639-3.sil.org/code/lzh[lzh]
+++<br>+++ https://www.wikidata.org/wiki/Q37041[Q37041]
|
Lingua Sinica classica (/ISO 15924 Hant/)
|
1

|
heb-Hebr
|
https://glottolog.org/resource/languoid/id/hebr1245[hebr1245]
+++<br>+++
https://iso639-3.sil.org/code/heb[heb]
+++<br>+++ https://www.wikidata.org/wiki/Q9288[Q9288]
|
Lingua Hebraica (Alphabetum Hebraicum)
|
13

|
khm-Khmr
|
https://glottolog.org/resource/languoid/id/cent1989[cent1989]
+++<br>+++
https://iso639-3.sil.org/code/khm[khm]
+++<br>+++ https://www.wikidata.org/wiki/Q9205[Q9205]
|
Lingua Khmer (/ISO 15924 Khmr/)
|
1

|
lao-Laoo
|
https://glottolog.org/resource/languoid/id/laoo1244[laoo1244]
+++<br>+++
https://iso639-3.sil.org/code/lao[lao]
+++<br>+++ https://www.wikidata.org/wiki/Q9211[Q9211]
|
/Lao language/ (/ISO 15924 Laoo/)
|
1

|
lat-Latn
|
https://glottolog.org/resource/languoid/id/lati1261[lati1261]
+++<br>+++
https://iso639-3.sil.org/code/lat[lat]
+++<br>+++ https://www.wikidata.org/wiki/Q397[Q397]
|
Lingua Latina (Abecedarium Latinum)
|
4

|
mni-Mtei
|
https://glottolog.org/resource/languoid/id/mani1292[mani1292]
+++<br>+++
https://iso639-3.sil.org/code/mni[mni]
+++<br>+++ https://www.wikidata.org/wiki/Q33868[Q33868]
|
Lingua Meitei (/ISO 15924 Mtei/)
|
1

|
nqo-Nkoo
|
https://glottolog.org/resource/languoid/id/nkoa1234[nkoa1234]
+++<br>+++
https://iso639-3.sil.org/code/nqo[nqo]
+++<br>+++ https://www.wikidata.org/wiki/Q18546266[Q18546266]
|
/N'Ko/ (/ISO 15924 Nkoo/)
|
1

|
sat-Olck
|
https://glottolog.org/resource/languoid/id/sant1410[sant1410]
+++<br>+++
https://iso639-3.sil.org/code/sat[sat]
+++<br>+++ https://www.wikidata.org/wiki/Q33965[Q33965]
|
Lingua Santali (/ISO 15924 Olck/)
|
2

|
ori-Orya
|

+++<br>+++
https://iso639-3.sil.org/code/ori[ori]
+++<br>+++ https://www.wikidata.org/wiki/Q33810[Q33810]
|
Macrolingua Orissensis (/ISO 15924 Orya/)
|
2

|
sin-Sinh
|
https://glottolog.org/resource/languoid/id/sinh1246[sinh1246]
+++<br>+++
https://iso639-3.sil.org/code/sin[sin]
+++<br>+++ https://www.wikidata.org/wiki/Q13267[Q13267]
|
Lingua Singhalensis (/ISO 15924 Sinh/)
|
3

|
tam-Taml
|
https://glottolog.org/resource/languoid/id/tami1289[tami1289]
+++<br>+++
https://iso639-3.sil.org/code/tam[tam]
+++<br>+++ https://www.wikidata.org/wiki/Q5885[Q5885]
|
Lingua Tamulica (/ISO 15924 Taml/)
|
15

|
tel-Telu
|
https://glottolog.org/resource/languoid/id/telu1262[telu1262]
+++<br>+++
https://iso639-3.sil.org/code/tel[tel]
+++<br>+++ https://www.wikidata.org/wiki/Q8097[Q8097]
|
Lingua Telingana (/ISO 15924 Telu/)
|
9

|
div-Thaa
|
https://glottolog.org/resource/languoid/id/dhiv1236[dhiv1236]
+++<br>+++
https://iso639-3.sil.org/code/div[div]
+++<br>+++ https://www.wikidata.org/wiki/Q32656[Q32656]
|
Lingua Dhivehi (/ISO 15924 Thaa/)
|
1

|
tha-Thai
|
https://glottolog.org/resource/languoid/id/thai1261[thai1261]
+++<br>+++
https://iso639-3.sil.org/code/tha[tha]
+++<br>+++ https://www.wikidata.org/wiki/Q9217[Q9217]
|
Lingua Thai (/ISO 15924 Thai/)
|
8

|
bod-Tibt
|
https://glottolog.org/resource/languoid/id/tibe1272[tibe1272]
+++<br>+++
https://iso639-3.sil.org/code/bod[bod]
+++<br>+++ https://www.wikidata.org/wiki/Q34271[Q34271]
|
Lingua Tibetana (Scriptura Tibetana)
|
2

|
san-Zyyy
|
https://glottolog.org/resource/languoid/id/sans1269[sans1269]
+++<br>+++
https://iso639-3.sil.org/code/san[san]
+++<br>+++ https://www.wikidata.org/wiki/Q11059[Q11059]
|
Lingua Sanscrita (/ISO 15924 Zyyy/)
|
2

|
zho-Zyyy
|
https://glottolog.org/resource/languoid/id/sini1245[sini1245]
+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q7850[Q7850]
|
/Macrolingua Sinicae (/ISO 15924 Zyyy/)/
|
24

|
por-Latn
|
https://glottolog.org/resource/languoid/id/port1283[port1283]
+++<br>+++
https://iso639-3.sil.org/code/por[por]
+++<br>+++ https://www.wikidata.org/wiki/Q5146[Q5146]
|
Lingua Lusitana (Abecedarium Latinum)
|
17

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
29

|
fra-Latn
|
https://glottolog.org/resource/languoid/id/stan1290[stan1290]
+++<br>+++
https://iso639-3.sil.org/code/fra[fra]
+++<br>+++ https://www.wikidata.org/wiki/Q150[Q150]
|
Lingua Francogallica (Abecedarium Latinum)
|
22

|
nld-Latn
|
https://glottolog.org/resource/languoid/id/mode1257[mode1257]
+++<br>+++
https://iso639-3.sil.org/code/nld[nld]
+++<br>+++ https://www.wikidata.org/wiki/Q7411[Q7411]
|
Lingua Batavica (Abecedarium Latinum)
|
18

|
deu-Latn
|
https://glottolog.org/resource/languoid/id/stan1295[stan1295]
+++<br>+++
https://iso639-3.sil.org/code/deu[deu]
+++<br>+++ https://www.wikidata.org/wiki/Q188[Q188]
|
Lingua Germanica (Abecedarium Latinum)
|
19

|
spa-Latn
|
https://glottolog.org/resource/languoid/id/stan1288[stan1288]
+++<br>+++
https://iso639-3.sil.org/code/spa[spa]
+++<br>+++ https://www.wikidata.org/wiki/Q1321[Q1321]
|
Lingua Hispanica (Abecedarium Latinum)
|
21

|
ita-Latn
|
https://glottolog.org/resource/languoid/id/ital1282[ital1282]
+++<br>+++
https://iso639-3.sil.org/code/ita[ita]
+++<br>+++ https://www.wikidata.org/wiki/Q652[Q652]
|
Lingua Italiana (Abecedarium Latinum)
|
14

|
gle-Latn
|
https://glottolog.org/resource/languoid/id/iris1253[iris1253]
+++<br>+++
https://iso639-3.sil.org/code/gle[gle]
+++<br>+++ https://www.wikidata.org/wiki/Q9142[Q9142]
|
Lingua Hibernica (Abecedarium Latinum)
|
4

|
swe-Latn
|
https://glottolog.org/resource/languoid/id/swed1254[swed1254]
+++<br>+++
https://iso639-3.sil.org/code/swe[swe]
+++<br>+++ https://www.wikidata.org/wiki/Q9027[Q9027]
|
Lingua Suecica (Abecedarium Latinum)
|
16

|
ceb-Latn
|
https://glottolog.org/resource/languoid/id/cebu1242[cebu1242]
+++<br>+++
https://iso639-3.sil.org/code/ceb[ceb]
+++<br>+++ https://www.wikidata.org/wiki/Q33239[Q33239]
|
Lingua Caebuana (Abecedarium Latinum)
|
1

|
sqi-Latn
|
https://glottolog.org/resource/languoid/id/alba1267[alba1267]
+++<br>+++
https://iso639-3.sil.org/code/sqi[sqi]
+++<br>+++ https://www.wikidata.org/wiki/Q8748[Q8748]
|
Macrolingua Albanica (/Abecedarium Latinum/)
|
5

|
pol-Latn
|
https://glottolog.org/resource/languoid/id/poli1260[poli1260]
+++<br>+++
https://iso639-3.sil.org/code/pol[pol]
+++<br>+++ https://www.wikidata.org/wiki/Q809[Q809]
|
Lingua Polonica (Abecedarium Latinum)
|
14

|
fin-Latn
|
https://glottolog.org/resource/languoid/id/finn1318[finn1318]
+++<br>+++
https://iso639-3.sil.org/code/fin[fin]
+++<br>+++ https://www.wikidata.org/wiki/Q1412[Q1412]
|
Lingua Finnica (Abecedarium Latinum)
|
14

|
ron-Latn
|
https://glottolog.org/resource/languoid/id/roma1327[roma1327]
+++<br>+++
https://iso639-3.sil.org/code/ron[ron]
+++<br>+++ https://www.wikidata.org/wiki/Q7913[Q7913]
|
Lingua Dacoromanica (Abecedarium Latinum)
|
11

|
vie-Latn
|
https://glottolog.org/resource/languoid/id/viet1252[viet1252]
+++<br>+++
https://iso639-3.sil.org/code/vie[vie]
+++<br>+++ https://www.wikidata.org/wiki/Q9199[Q9199]
|
Lingua Vietnamensis (Abecedarium Latinum)
|
14

|
cat-Latn
|
https://glottolog.org/resource/languoid/id/stan1289[stan1289]
+++<br>+++
https://iso639-3.sil.org/code/cat[cat]
+++<br>+++ https://www.wikidata.org/wiki/Q7026[Q7026]
|
Lingua Catalana (Abecedarium Latinum)
|
16

|
ukr-Cyrl
|
https://glottolog.org/resource/languoid/id/ukra1253[ukra1253]
+++<br>+++
https://iso639-3.sil.org/code/ukr[ukr]
+++<br>+++ https://www.wikidata.org/wiki/Q8798[Q8798]
|
Lingua Ucrainica (Abecedarium Cyrillicum)
|
15

|
bul-Cyrl
|
https://glottolog.org/resource/languoid/id/bulg1262[bulg1262]
+++<br>+++
https://iso639-3.sil.org/code/bul[bul]
+++<br>+++ https://www.wikidata.org/wiki/Q7918[Q7918]
|
Lingua Bulgarica (Abecedarium Cyrillicum)
|
8

|
slv-Latn
|
https://glottolog.org/resource/languoid/id/slov1268[slov1268]
+++<br>+++
https://iso639-3.sil.org/code/slv[slv]
+++<br>+++ https://www.wikidata.org/wiki/Q9063[Q9063]
|
Lingua Slovena (Abecedarium Latinum)
|
8

|
war-Latn
|
https://glottolog.org/resource/languoid/id/wara1300[wara1300]
+++<br>+++
https://iso639-3.sil.org/code/war[war]
+++<br>+++ https://www.wikidata.org/wiki/Q34279[Q34279]
|
/Waray language/ (Abecedarium Latinum)
|
4

|
nob-Latn
|
https://glottolog.org/resource/languoid/id/norw1259[norw1259]
+++<br>+++
https://iso639-3.sil.org/code/nob[nob]
+++<br>+++ https://www.wikidata.org/wiki/Q25167[Q25167]
|
/Bokmål/ (Abecedarium Latinum)
|
13

|
ces-Latn
|
https://glottolog.org/resource/languoid/id/czec1258[czec1258]
+++<br>+++
https://iso639-3.sil.org/code/ces[ces]
+++<br>+++ https://www.wikidata.org/wiki/Q9056[Q9056]
|
Lingua Bohemica (Abecedarium Latinum)
|
13

|
dan-Latn
|
https://glottolog.org/resource/languoid/id/dani1285[dani1285]
+++<br>+++
https://iso639-3.sil.org/code/dan[dan]
+++<br>+++ https://www.wikidata.org/wiki/Q9035[Q9035]
|
Lingua Danica (Abecedarium Latinum)
|
11

|
jpn-Jpan
|
https://glottolog.org/resource/languoid/id/nucl1643[nucl1643]
+++<br>+++
https://iso639-3.sil.org/code/jpn[jpn]
+++<br>+++ https://www.wikidata.org/wiki/Q5287[Q5287]
|
Lingua Iaponica (Scriptura Iaponica)
|
20

|
nno-Latn
|
https://glottolog.org/resource/languoid/id/norw1262[norw1262]
+++<br>+++
https://iso639-3.sil.org/code/nno[nno]
+++<br>+++ https://www.wikidata.org/wiki/Q25164[Q25164]
|
/Nynorsk/ (Abecedarium Latinum)
|
10

|
mal-Mlym
|
https://glottolog.org/resource/languoid/id/mala1464[mala1464]
+++<br>+++
https://iso639-3.sil.org/code/mal[mal]
+++<br>+++ https://www.wikidata.org/wiki/Q36236[Q36236]
|
Lingua Malabarica (/Malayalam script/)
|
11

|
ind-Latn
|
https://glottolog.org/resource/languoid/id/indo1316[indo1316]
+++<br>+++
https://iso639-3.sil.org/code/ind[ind]
+++<br>+++ https://www.wikidata.org/wiki/Q9240[Q9240]
|
Lingua Indonesiana (Abecedarium Latinum)
|
18

|
fas-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/fas[fas]
+++<br>+++ https://www.wikidata.org/wiki/Q9168[Q9168]
|
Macrolingua Persica (//Abecedarium Arabicum//)
|
16

|
hun-Latn
|
https://glottolog.org/resource/languoid/id/hung1274[hung1274]
+++<br>+++
https://iso639-3.sil.org/code/hun[hun]
+++<br>+++ https://www.wikidata.org/wiki/Q9067[Q9067]
|
Lingua Hungarica (Abecedarium Latinum)
|
10

|
eus-Latn
|
https://glottolog.org/resource/languoid/id/basq1248[basq1248]
+++<br>+++
https://iso639-3.sil.org/code/eus[eus]
+++<br>+++ https://www.wikidata.org/wiki/Q8752[Q8752]
|
Lingua Vasconica (Abecedarium Latinum)
|
12

|
cym-Latn
|
https://glottolog.org/resource/languoid/id/wels1247[wels1247]
+++<br>+++
https://iso639-3.sil.org/code/cym[cym]
+++<br>+++ https://www.wikidata.org/wiki/Q9309[Q9309]
|
Lingua Cambrica (Abecedarium Latinum)
|
5

|
glg-Latn
|
https://glottolog.org/resource/languoid/id/gali1258[gali1258]
+++<br>+++
https://iso639-3.sil.org/code/glg[glg]
+++<br>+++ https://www.wikidata.org/wiki/Q9307[Q9307]
|
Lingua Gallaica (Abecedarium Latinum)
|
8

|
slk-Latn
|
https://glottolog.org/resource/languoid/id/slov1269[slov1269]
+++<br>+++
https://iso639-3.sil.org/code/slk[slk]
+++<br>+++ https://www.wikidata.org/wiki/Q9058[Q9058]
|
Lingua Slovaca (Abecedarium Latinum)
|
7

|
epo-Latn
|
https://glottolog.org/resource/languoid/id/espe1235[espe1235]
+++<br>+++
https://iso639-3.sil.org/code/epo[epo]
+++<br>+++ https://www.wikidata.org/wiki/Q143[Q143]
|
Lingua Esperantica (Abecedarium Latinum)
|
14

|
msa-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/msa[msa]
+++<br>+++ https://www.wikidata.org/wiki/Q9237[Q9237]
|
Macrolingua Malayana (/ISO 15924 Zyyy/)
|
10

|
est-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/est[est]
+++<br>+++ https://www.wikidata.org/wiki/Q9072[Q9072]
|
Macrolingua Estonica (Abecedarium Latinum)
|
11

|
hrv-Latn
|
https://glottolog.org/resource/languoid/id/croa1245[croa1245]
+++<br>+++
https://iso639-3.sil.org/code/hrv[hrv]
+++<br>+++ https://www.wikidata.org/wiki/Q6654[Q6654]
|
Lingua Croatica (Abecedarium Latinum)
|
8

|
tur-Latn
|
https://glottolog.org/resource/languoid/id/nucl1301[nucl1301]
+++<br>+++
https://iso639-3.sil.org/code/tur[tur]
+++<br>+++ https://www.wikidata.org/wiki/Q256[Q256]
|
Lingua Turcica (Abecedarium Latinum)
|
14

|
nds-Latn
|
https://glottolog.org/resource/languoid/id/lowg1239[lowg1239]
+++<br>+++
https://iso639-3.sil.org/code/nds[nds]
+++<br>+++ https://www.wikidata.org/wiki/Q25433[Q25433]
|
Lingua Saxonica (Abecedarium Latinum)
|
4

|
oci-Latn
|
https://glottolog.org/resource/languoid/id/occi1239[occi1239]
+++<br>+++
https://iso639-3.sil.org/code/oci[oci]
+++<br>+++ https://www.wikidata.org/wiki/Q14185[Q14185]
|
Lingua Occitana (Abecedarium Latinum)
|
6

|
bre-Latn
|
https://glottolog.org/resource/languoid/id/bret1244[bret1244]
+++<br>+++
https://iso639-3.sil.org/code/bre[bre]
+++<br>+++ https://www.wikidata.org/wiki/Q12107[Q12107]
|
Lingua Britonica (Abecedarium Latinum)
|
3

|
arz-Latn
|
https://glottolog.org/resource/languoid/id/egyp1253[egyp1253]
+++<br>+++
https://iso639-3.sil.org/code/arz[arz]
+++<br>+++ https://www.wikidata.org/wiki/Q29919[Q29919]
|
/Egyptian Arabic/ (Abecedarium Arabicum)
|
2

|
afr-Latn
|
https://glottolog.org/resource/languoid/id/afri1274[afri1274]
+++<br>+++
https://iso639-3.sil.org/code/afr[afr]
+++<br>+++ https://www.wikidata.org/wiki/Q14196[Q14196]
|
Lingua Batava Capitensis (Abecedarium Latinum)
|
7

|
ltz-Latn
|
https://glottolog.org/resource/languoid/id/luxe1241[luxe1241]
+++<br>+++
https://iso639-3.sil.org/code/ltz[ltz]
+++<br>+++ https://www.wikidata.org/wiki/Q9051[Q9051]
|
Lingua Luxemburgensis (Abecedarium Latinum)
|
5

|
sco-Latn
|
https://glottolog.org/resource/languoid/id/scot1243[scot1243]
+++<br>+++
https://iso639-3.sil.org/code/sco[sco]
+++<br>+++ https://www.wikidata.org/wiki/Q14549[Q14549]
|
Lingua Scotica quae Teutonica (Abecedarium Latinum)
|
4

|
bar-Latn
|
https://glottolog.org/resource/languoid/id/bava1246[bava1246]
+++<br>+++
https://iso639-3.sil.org/code/bar[bar]
+++<br>+++ https://www.wikidata.org/wiki/Q29540[Q29540]
|
Lingua Bavarica (Abecedarium Latinum)
|
3

|
arg-Latn
|
https://glottolog.org/resource/languoid/id/arag1245[arag1245]
+++<br>+++
https://iso639-3.sil.org/code/arg[arg]
+++<br>+++ https://www.wikidata.org/wiki/Q8765[Q8765]
|
Lingua Aragonensis (Abecedarium Latinum)
|
2

|
zho-Hant
|

+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q18130932[Q18130932]
|
//Traditional Chinese// (/ISO 15924 Hant/)
|
16

|
pap-Latn
|
https://glottolog.org/resource/languoid/id/papi1253[papi1253]
+++<br>+++
https://iso639-3.sil.org/code/pap[pap]
+++<br>+++ https://www.wikidata.org/wiki/Q33856[Q33856]
|
/lingua Papiamentica/ (Abecedarium Latinum)
|
1

|
cos-Latn
|
https://glottolog.org/resource/languoid/id/cors1241[cors1241]
+++<br>+++
https://iso639-3.sil.org/code/cos[cos]
+++<br>+++ https://www.wikidata.org/wiki/Q33111[Q33111]
|
Lingua Corsica (Abecedarium Latinum)
|
1

|
gsw-Latn
|
https://glottolog.org/resource/languoid/id/swis1247[swis1247]
+++<br>+++
https://iso639-3.sil.org/code/gsw[gsw]
+++<br>+++ https://www.wikidata.org/wiki/Q131339[Q131339]
|
Dialecti Alemannicae (Abecedarium Latinum)
|
2

|
isl-Latn
|
https://glottolog.org/resource/languoid/id/icel1247[icel1247]
+++<br>+++
https://iso639-3.sil.org/code/isl[isl]
+++<br>+++ https://www.wikidata.org/wiki/Q294[Q294]
|
Lingua Islandica (Abecedarium Latinum)
|
8

|
min-Latn
|
https://glottolog.org/resource/languoid/id/mina1268[mina1268]
+++<br>+++
https://iso639-3.sil.org/code/min[min]
+++<br>+++ https://www.wikidata.org/wiki/Q13324[Q13324]
|
/Minangkabau language/ (Abecedarium Latinum)
|
1

|
vec-Latn
|
https://glottolog.org/resource/languoid/id/vene1258[vene1258]
+++<br>+++
https://iso639-3.sil.org/code/vec[vec]
+++<br>+++ https://www.wikidata.org/wiki/Q32724[Q32724]
|
Lingua Veneta (Abecedarium Latinum)
|
3

|
pms-Latn
|
https://glottolog.org/resource/languoid/id/piem1238[piem1238]
+++<br>+++
https://iso639-3.sil.org/code/pms[pms]
+++<br>+++ https://www.wikidata.org/wiki/Q15085[Q15085]
|
Lingua Pedemontana (Abecedarium Latinum)
|
1

|
scn-Latn
|
https://glottolog.org/resource/languoid/id/sici1248[sici1248]
+++<br>+++
https://iso639-3.sil.org/code/scn[scn]
+++<br>+++ https://www.wikidata.org/wiki/Q33973[Q33973]
|
Lingua Sicula (Abecedarium Latinum)
|
3

|
srd-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/srd[srd]
+++<br>+++ https://www.wikidata.org/wiki/Q33976[Q33976]
|
Macrolingua Sarda (Abecedarium Latinum)
|
3

|
gla-Latn
|
https://glottolog.org/resource/languoid/id/scot1245[scot1245]
+++<br>+++
https://iso639-3.sil.org/code/gla[gla]
+++<br>+++ https://www.wikidata.org/wiki/Q9314[Q9314]
|
Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum)
|
2

|
lim-Latn
|
https://glottolog.org/resource/languoid/id/limb1263[limb1263]
+++<br>+++
https://iso639-3.sil.org/code/lim[lim]
+++<br>+++ https://www.wikidata.org/wiki/Q102172[Q102172]
|
Lingua Limburgica (Abecedarium Latinum)
|
2

|
wln-Latn
|
https://glottolog.org/resource/languoid/id/wall1255[wall1255]
+++<br>+++
https://iso639-3.sil.org/code/wln[wln]
+++<br>+++ https://www.wikidata.org/wiki/Q34219[Q34219]
|
Lingua Vallonica (Abecedarium Latinum)
|
2

|
srp-Latn
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q21161949[Q21161949]
|
/Serbian/ (Abecedarium Latinum)
|
1

|
vls-Latn
|
https://glottolog.org/resource/languoid/id/vlaa1240[vlaa1240]
+++<br>+++
https://iso639-3.sil.org/code/vls[vls]
+++<br>+++ https://www.wikidata.org/wiki/Q100103[Q100103]
|
/West Flemish/ (Abecedarium Latinum)
|
1

|
nap-Latn
|
https://glottolog.org/resource/languoid/id/neap1235[neap1235]
+++<br>+++
https://iso639-3.sil.org/code/nap[nap]
+++<br>+++ https://www.wikidata.org/wiki/Q33845[Q33845]
|
Lingua Neapolitana (Abecedarium Latinum)
|
1

|
lij-Latn
|
https://glottolog.org/resource/languoid/id/ligu1248[ligu1248]
+++<br>+++
https://iso639-3.sil.org/code/lij[lij]
+++<br>+++ https://www.wikidata.org/wiki/Q36106[Q36106]
|
Lingua Ligustica (Abecedarium Latinum)
|
1

|
fur-Latn
|
https://glottolog.org/resource/languoid/id/friu1240[friu1240]
+++<br>+++
https://iso639-3.sil.org/code/fur[fur]
+++<br>+++ https://www.wikidata.org/wiki/Q33441[Q33441]
|
Lingua Foroiuliensis (Abecedarium Latinum)
|
1

|
pcd-Latn
|
https://glottolog.org/resource/languoid/id/pica1241[pica1241]
+++<br>+++
https://iso639-3.sil.org/code/pcd[pcd]
+++<br>+++ https://www.wikidata.org/wiki/Q34024[Q34024]
|
Lingua Picardica (Abecedarium Latinum)
|
1

|
wol-Latn
|
https://glottolog.org/resource/languoid/id/nucl1347[nucl1347]
+++<br>+++
https://iso639-3.sil.org/code/wol[wol]
+++<br>+++ https://www.wikidata.org/wiki/Q34257[Q34257]
|
/Wolof language/ (Abecedarium Latinum)
|
1

|
kon-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/kon[kon]
+++<br>+++ https://www.wikidata.org/wiki/Q33702[Q33702]
|
/Kongo macrolanguage/ (Abecedarium Latinum)
|
1

|
frp-Latn
|
https://glottolog.org/resource/languoid/id/fran1260[fran1260]
+++<br>+++
https://iso639-3.sil.org/code/frp[frp]
+++<br>+++ https://www.wikidata.org/wiki/Q15087[Q15087]
|
Lingua Arpitanica (Abecedarium Latinum)
|
1

|
wuu-Zyyy
|
https://glottolog.org/resource/languoid/id/wuch1236[wuch1236]
+++<br>+++
https://iso639-3.sil.org/code/wuu[wuu]
+++<br>+++ https://www.wikidata.org/wiki/Q34290[Q34290]
|
//Macrolingua Wu// (/ISO 15924 Zyyy/)
|
7

|
srp-Cyrl
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q9299[Q9299]
|
Lingua Serbica (Abecedarium Cyrillicum)
|
13

|
urd-Arab
|
https://glottolog.org/resource/languoid/id/urdu1245[urdu1245]
+++<br>+++
https://iso639-3.sil.org/code/urd[urd]
+++<br>+++ https://www.wikidata.org/wiki/Q1617[Q1617]
|
Lingua Urdu (Abecedarium Arabicum)
|
3

|
gan-Zyyy
|
https://glottolog.org/resource/languoid/id/ganc1239[ganc1239]
+++<br>+++
https://iso639-3.sil.org/code/gan[gan]
+++<br>+++ https://www.wikidata.org/wiki/Q33475[Q33475]
|
Lingua Gan (/ISO 15924 Zyyy/)
|
2

|
lit-Latn
|
https://glottolog.org/resource/languoid/id/lith1251[lith1251]
+++<br>+++
https://iso639-3.sil.org/code/lit[lit]
+++<br>+++ https://www.wikidata.org/wiki/Q9083[Q9083]
|
Lingua Lithuanica (Abecedarium Latinum)
|
5

|
hbs-Latn
|
https://glottolog.org/resource/languoid/id/sout1528[sout1528]
+++<br>+++
https://iso639-3.sil.org/code/hbs[hbs]
+++<br>+++ https://www.wikidata.org/wiki/Q9301[Q9301]
|
Macrolingua Serbocroatica (Abecedarium Latinum)
|
9

|
lav-Latn
|
https://glottolog.org/resource/languoid/id/latv1249[latv1249]
+++<br>+++
https://iso639-3.sil.org/code/lav[lav]
+++<br>+++ https://www.wikidata.org/wiki/Q9078[Q9078]
|
Macrolingua Lettonica (Abecedarium Latinum)
|
8

|
bos-Latn
|
https://glottolog.org/resource/languoid/id/bosn1245[bosn1245]
+++<br>+++
https://iso639-3.sil.org/code/bos[bos]
+++<br>+++ https://www.wikidata.org/wiki/Q9303[Q9303]
|
Lingua Bosnica (Abecedarium Latinum)
|
5

|
azb-Arab
|
https://glottolog.org/resource/languoid/id/sout2697[sout2697]
+++<br>+++
https://iso639-3.sil.org/code/azb[azb]
+++<br>+++ https://www.wikidata.org/wiki/Q3449805[Q3449805]
|
/South Azerbaijani/ (Abecedarium Arabicum)
|
2

|
jav-Latn
|
https://glottolog.org/resource/languoid/id/java1254[java1254]
+++<br>+++
https://iso639-3.sil.org/code/jav[jav]
+++<br>+++ https://www.wikidata.org/wiki/Q33549[Q33549]
|
Lingua Iavanica (Abecedarium Latinum)
|
4

|
ell-Grek
|
https://glottolog.org/resource/languoid/id/mode1248[mode1248]
+++<br>+++
https://iso639-3.sil.org/code/ell[ell]
+++<br>+++ https://www.wikidata.org/wiki/Q36510[Q36510]
|
Lingua Neograeca (Alphabetum Graecum)
|
10

|
sun-Latn
|
https://glottolog.org/resource/languoid/id/sund1252[sund1252]
+++<br>+++
https://iso639-3.sil.org/code/sun[sun]
+++<br>+++ https://www.wikidata.org/wiki/Q34002[Q34002]
|
/Sundanese language/ (Abecedarium Latinum)
|
3

|
fry-Latn
|
https://glottolog.org/resource/languoid/id/west2354[west2354]
+++<br>+++
https://iso639-3.sil.org/code/fry[fry]
+++<br>+++ https://www.wikidata.org/wiki/Q27175[Q27175]
|
Lingua Frisice occidentalis (Abecedarium Latinum)
|
4

|
ace-Latn
|
https://glottolog.org/resource/languoid/id/achi1257[achi1257]
+++<br>+++
https://iso639-3.sil.org/code/ace[ace]
+++<br>+++ https://www.wikidata.org/wiki/Q27683[Q27683]
|
/Acehnese language/ (Abecedarium Latinum)
|
1

|
jam-Latn
|
https://glottolog.org/resource/languoid/id/jama1262[jama1262]
+++<br>+++
https://iso639-3.sil.org/code/jam[jam]
+++<br>+++ https://www.wikidata.org/wiki/Q35939[Q35939]
|
Lingua creola Iamaicana (Abecedarium Latinum)
|
2

|
che-Cyrl
|
https://glottolog.org/resource/languoid/id/chec1245[chec1245]
+++<br>+++
https://iso639-3.sil.org/code/che[che]
+++<br>+++ https://www.wikidata.org/wiki/Q33350[Q33350]
|
Lingua Tsetsenica (Abecedarium Cyrillicum)
|
2

|
bel-Cyrl
|
https://glottolog.org/resource/languoid/id/bela1254[bela1254]
+++<br>+++
https://iso639-3.sil.org/code/bel[bel]
+++<br>+++ https://www.wikidata.org/wiki/Q9091[Q9091]
|
Lingua Ruthenica Alba (Abecedarium Cyrillicum)
|
6

|
kab-Latn
|
https://glottolog.org/resource/languoid/id/kaby1243[kaby1243]
+++<br>+++
https://iso639-3.sil.org/code/kab[kab]
+++<br>+++ https://www.wikidata.org/wiki/Q35853[Q35853]
|
/Kabyle language/ (Abecedarium Latinum)
|
1

|
fao-Latn
|
https://glottolog.org/resource/languoid/id/faro1244[faro1244]
+++<br>+++
https://iso639-3.sil.org/code/fao[fao]
+++<br>+++ https://www.wikidata.org/wiki/Q25258[Q25258]
|
Lingua Faeroensis (Abecedarium Latinum)
|
1

|
bam-Zyyy
|
https://glottolog.org/resource/languoid/id/bamb1269[bamb1269]
+++<br>+++
https://iso639-3.sil.org/code/bam[bam]
+++<br>+++ https://www.wikidata.org/wiki/Q33243[Q33243]
|
/Bambara language/ (/ISO 15924 Zyyy/)
|
1

|
lmo-Latn
|
https://glottolog.org/resource/languoid/id/lomb1257[lomb1257]
+++<br>+++
https://iso639-3.sil.org/code/lmo[lmo]
+++<br>+++ https://www.wikidata.org/wiki/Q33754[Q33754]
|
Langobardus sermo (Abecedarium Latinum)
|
2

|
mar-Deva
|
https://glottolog.org/resource/languoid/id/mara1378[mara1378]
+++<br>+++
https://iso639-3.sil.org/code/mar[mar]
+++<br>+++ https://www.wikidata.org/wiki/Q1571[Q1571]
|
Lingua Marathica (Devanāgarī)
|
9

|
ary-Arab
|
https://glottolog.org/resource/languoid/id/moro1292[moro1292]
+++<br>+++
https://iso639-3.sil.org/code/ary[ary]
+++<br>+++ https://www.wikidata.org/wiki/Q56426[Q56426]
|
/Moroccan Arabic/ (Abecedarium Arabicum)
|
1

|
awa-Deva
|
https://glottolog.org/resource/languoid/id/awad1243[awad1243]
+++<br>+++
https://iso639-3.sil.org/code/awa[awa]
+++<br>+++ https://www.wikidata.org/wiki/Q29579[Q29579]
|
/Awadhi/ (Devanāgarī)
|
1

|
ban-Latn
|
https://glottolog.org/resource/languoid/id/bali1278[bali1278]
+++<br>+++
https://iso639-3.sil.org/code/ban[ban]
+++<br>+++ https://www.wikidata.org/wiki/Q33070[Q33070]
|
/Balinese/ (Abecedarium Latinum)
|
1

|
ast-Latn
|
https://glottolog.org/resource/languoid/id/astu1245[astu1245]
+++<br>+++
https://iso639-3.sil.org/code/ast[ast]
+++<br>+++ https://www.wikidata.org/wiki/Q29507[Q29507]
|
Lingua Asturiana (Abecedarium Latinum)
|
7

|
bcl-Latn
|
https://glottolog.org/resource/languoid/id/cent2087[cent2087]
+++<br>+++
https://iso639-3.sil.org/code/bcl[bcl]
+++<br>+++ https://www.wikidata.org/wiki/Q33284[Q33284]
|
/Central Bikol/  (Abecedarium Latinum)
|
1

|
bho-Deva
|
https://glottolog.org/resource/languoid/id/bhoj1244[bhoj1244]
+++<br>+++
https://iso639-3.sil.org/code/bho[bho]
+++<br>+++ https://www.wikidata.org/wiki/Q33268[Q33268]
|
Lingua Bhojpuri (Devanāgarī)
|
4

|
bxr-Cyrl
|
https://glottolog.org/resource/languoid/id/russ1264[russ1264]
+++<br>+++
https://iso639-3.sil.org/code/bxr[bxr]
+++<br>+++ https://www.wikidata.org/wiki/Q33120[Q33120]
|
Lingua Buriatica (Abecedarium Cyrillicum)
|
1

|
cdo-Zyyy
|
https://glottolog.org/resource/languoid/id/mind1253[mind1253]
+++<br>+++
https://iso639-3.sil.org/code/cdo[cdo]
+++<br>+++ https://www.wikidata.org/wiki/Q36455[Q36455]
|
/Min Dong Chinese/ (/ISO 15924 Zyyy/)
|
1

|
diq-Latn
|
https://glottolog.org/resource/languoid/id/diml1238[diml1238]
+++<br>+++
https://iso639-3.sil.org/code/diq[diq]
+++<br>+++ https://www.wikidata.org/wiki/Q10199[Q10199]
|
Lingua Zazaca (Abecedarium Latinum)
|
3

|
dsb-Latn
|
https://glottolog.org/resource/languoid/id/lowe1385[lowe1385]
+++<br>+++
https://iso639-3.sil.org/code/dsb[dsb]
+++<br>+++ https://www.wikidata.org/wiki/Q13286[Q13286]
|
/Lower Sorbian/ (Abecedarium Latinum)
|
2

|
ext-Latn
|
https://glottolog.org/resource/languoid/id/extr1243[extr1243]
+++<br>+++
https://iso639-3.sil.org/code/ext[ext]
+++<br>+++ https://www.wikidata.org/wiki/Q30007[Q30007]
|
Lingua Extremadurensis (Abecedarium Latinum)
|
1

|
gcr-Latn
|
https://glottolog.org/resource/languoid/id/guia1246[guia1246]
+++<br>+++
https://iso639-3.sil.org/code/gcr[gcr]
+++<br>+++ https://www.wikidata.org/wiki/Q1363072[Q1363072]
|
/Guianese Creole French/ (Abecedarium Latinum)
|
2

|
gom-Zyyy
|
https://glottolog.org/resource/languoid/id/goan1235[goan1235]
+++<br>+++
https://iso639-3.sil.org/code/gom[gom]
+++<br>+++ https://www.wikidata.org/wiki/Q5575236[Q5575236]
|
/Goan Konkani/ (/ISO 15924 Zyyy/)
|
1

|
frr-latn
|
https://glottolog.org/resource/languoid/id/nort2626[nort2626]
+++<br>+++
https://iso639-3.sil.org/code/frr[frr]
+++<br>+++ https://www.wikidata.org/wiki/Q28224[Q28224]
|
/Northern Frisian/ (Abecedarium Latinum)
|
0

|
hak-Zyyy
|
https://glottolog.org/resource/languoid/id/hakk1236[hakk1236]
+++<br>+++
https://iso639-3.sil.org/code/hak[hak]
+++<br>+++ https://www.wikidata.org/wiki/Q33375[Q33375]
|
/Hakka Chinese/ (/ISO 15924 Zyyy/)
|
2

|
hif-Zyyy
|
https://glottolog.org/resource/languoid/id/fiji1242[fiji1242]
+++<br>+++
https://iso639-3.sil.org/code/hif[hif]
+++<br>+++ https://www.wikidata.org/wiki/Q46728[Q46728]
|
Lingua Hindi Vitiensis (/ISO 15924 Zyyy/)
|
1

|
hsb-Latn
|
https://glottolog.org/resource/languoid/id/uppe1395[uppe1395]
+++<br>+++
https://iso639-3.sil.org/code/hsb[hsb]
+++<br>+++ https://www.wikidata.org/wiki/Q13248[Q13248]
|
/Upper Sorbian/ (Abecedarium Latinum)
|
3

|
hyw-Armn
|
https://glottolog.org/resource/languoid/id/homs1234[homs1234]
+++<br>+++
https://iso639-3.sil.org/code/hyw[hyw]
+++<br>+++ https://www.wikidata.org/wiki/Q180945[Q180945]
|
/Western Armenian/ (Alphabetum Armenium)
|
1

|
ilo-Latn
|
https://glottolog.org/resource/languoid/id/ilok1237[ilok1237]
+++<br>+++
https://iso639-3.sil.org/code/ilo[ilo]
+++<br>+++ https://www.wikidata.org/wiki/Q35936[Q35936]
|
Lingua Ilocana (Abecedarium Latinum)
|
2

|
inh-Cyrl
|
https://glottolog.org/resource/languoid/id/ingu1240[ingu1240]
+++<br>+++
https://iso639-3.sil.org/code/inh[inh]
+++<br>+++ https://www.wikidata.org/wiki/Q33509[Q33509]
|
Lingua Ingussica (Abecedarium Cyrillicum)
|
1

|
kaa-Latn
|
https://glottolog.org/resource/languoid/id/kara1467[kara1467]
+++<br>+++
https://iso639-3.sil.org/code/kaa[kaa]
+++<br>+++ https://www.wikidata.org/wiki/Q33541[Q33541]
|
Lingua Karakalpakensis (Abecedarium Latinum)
|
1

|
kbp-Latn
|
https://glottolog.org/resource/languoid/id/kabi1261[kabi1261]
+++<br>+++
https://iso639-3.sil.org/code/kbp[kbp]
+++<br>+++ https://www.wikidata.org/wiki/Q35475[Q35475]
|
/Kabiye language/ (Abecedarium Latinum)
|
1

|
mai-Deva
|
https://glottolog.org/resource/languoid/id/mait1250[mait1250]
+++<br>+++
https://iso639-3.sil.org/code/mai[mai]
+++<br>+++ https://www.wikidata.org/wiki/Q36109[Q36109]
|
Lingua Maithili (Devanāgarī)
|
1

|
mwl-Latn
|
https://glottolog.org/resource/languoid/id/mira1251[mira1251]
+++<br>+++
https://iso639-3.sil.org/code/mwl[mwl]
+++<br>+++ https://www.wikidata.org/wiki/Q13330[Q13330]
|
Lingua Mirandica (Abecedarium Latinum)
|
1

|
mzn-Arab
|
https://glottolog.org/resource/languoid/id/maza1291[maza1291]
+++<br>+++
https://iso639-3.sil.org/code/mzn[mzn]
+++<br>+++ https://www.wikidata.org/wiki/Q13356[Q13356]
|
/Mazanderani language/ (Abecedarium Arabicum)
|
1

|
nah-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/nah[nah]
+++<br>+++ https://www.wikidata.org/wiki/Q13300[Q13300]
|
Lingua Navatlaca (Abecedarium Latinum)
|
1

|
nan-Latn
|
https://glottolog.org/resource/languoid/id/minn1241[minn1241]
+++<br>+++
https://iso639-3.sil.org/code/nan[nan]
+++<br>+++ https://www.wikidata.org/wiki/Q36495[Q36495]
|
/Min Nan Chinese/ (Abecedarium Latinum)
|
6

|
new-Deva
|
https://glottolog.org/resource/languoid/id/newa1246[newa1246]
+++<br>+++
https://iso639-3.sil.org/code/new[new]
+++<br>+++ https://www.wikidata.org/wiki/Q33979[Q33979]
|
Lingua Newari (Devanāgarī)
|
1

|
pam-Latn
|
https://glottolog.org/resource/languoid/id/pamp1243[pamp1243]
+++<br>+++
https://iso639-3.sil.org/code/pam[pam]
+++<br>+++ https://www.wikidata.org/wiki/Q36121[Q36121]
|
/Kapampangan language/ (Abecedarium Latinum)
|
1

|
pfl-Latn
|
https://glottolog.org/resource/languoid/id/pala1330[pala1330]
+++<br>+++
https://iso639-3.sil.org/code/pfl[pfl]
+++<br>+++ https://www.wikidata.org/wiki/Q23014[Q23014]
|
/Palatine German language/ (Abecedarium Latinum)
|
1

|
pnb-Arab
|
https://glottolog.org/resource/languoid/id/west2386[west2386]
+++<br>+++
https://iso639-3.sil.org/code/pnb[pnb]
+++<br>+++ https://www.wikidata.org/wiki/Q1389492[Q1389492]
|
Lingua Paniabica occidentalis (Abecedarium Arabicum)
|
1

|
rue-Cyrl
|
https://glottolog.org/resource/languoid/id/rusy1239[rusy1239]
+++<br>+++
https://iso639-3.sil.org/code/rue[rue]
+++<br>+++ https://www.wikidata.org/wiki/Q26245[Q26245]
|
Lingua Rusinica (Abecedarium Cyrillicum)
|
1

|
rup-Latn
|
https://glottolog.org/resource/languoid/id/arom1237[arom1237]
+++<br>+++
https://iso639-3.sil.org/code/rup[rup]
+++<br>+++ https://www.wikidata.org/wiki/Q29316[Q29316]
|
Lingua aromanian (Abecedarium Latinum)
|
1

|
sah-Cyrl
|
https://glottolog.org/resource/languoid/id/yaku1245[yaku1245]
+++<br>+++
https://iso639-3.sil.org/code/sah[sah]
+++<br>+++ https://www.wikidata.org/wiki/Q34299[Q34299]
|
Lingua Iacutica (Abecedarium Cyrillicum)
|
2

|
sgs-Latn
|
https://glottolog.org/resource/languoid/id/samo1265[samo1265]
+++<br>+++
https://iso639-3.sil.org/code/sgs[sgs]
+++<br>+++ https://www.wikidata.org/wiki/Q213434[Q213434]
|
Lingua Samogitica (Abecedarium Latinum)
|
2

|
shi-Zyyy
|
https://glottolog.org/resource/languoid/id/tach1250[tach1250]
+++<br>+++
https://iso639-3.sil.org/code/shi[shi]
+++<br>+++ https://www.wikidata.org/wiki/Q34152[Q34152]
|
Shilha language (/ISO 15924 Zyyy/)
|
1

|
shn-Mymr
|
https://glottolog.org/resource/languoid/id/shan1277[shan1277]
+++<br>+++
https://iso639-3.sil.org/code/shn[shn]
+++<br>+++ https://www.wikidata.org/wiki/Q56482[Q56482]
|
Lingua Shan (/ISO 15924 Mymr/)
|
1

|
smn-Latn
|
https://glottolog.org/resource/languoid/id/inar1241[inar1241]
+++<br>+++
https://iso639-3.sil.org/code/smn[smn]
+++<br>+++ https://www.wikidata.org/wiki/Q33462[Q33462]
|
/Inari Sami/ (Abecedarium Latinum)
|
4

|
stq-Latn
|
https://glottolog.org/resource/languoid/id/sate1242[sate1242]
+++<br>+++
https://iso639-3.sil.org/code/stq[stq]
+++<br>+++ https://www.wikidata.org/wiki/Q27154[Q27154]
|
/Saterland Frisian language/ (Abecedarium Latinum)
|
1

|
szl-Latn
|
https://glottolog.org/resource/languoid/id/sile1253[sile1253]
+++<br>+++
https://iso639-3.sil.org/code/szl[szl]
+++<br>+++ https://www.wikidata.org/wiki/Q30319[Q30319]
|
Lingua Silesica (Abecedarium Latinum)
|
1

|
tcy-Zyyy
|
https://glottolog.org/resource/languoid/id/tulu1258[tulu1258]
+++<br>+++
https://iso639-3.sil.org/code/tcy[tcy]
+++<br>+++ https://www.wikidata.org/wiki/Q34251[Q34251]
|
Lingua Tuluva (/ISO 15924 Zyyy/)
|
2

|
udm-Cyrl
|
https://glottolog.org/resource/languoid/id/udmu1245[udmu1245]
+++<br>+++
https://iso639-3.sil.org/code/udm[udm]
+++<br>+++ https://www.wikidata.org/wiki/Q13238[Q13238]
|
Lingua Udmurtica (Abecedarium Cyrillicum)
|
2

|
vep-Latn
|
https://glottolog.org/resource/languoid/id/veps1250[veps1250]
+++<br>+++
https://iso639-3.sil.org/code/vep[vep]
+++<br>+++ https://www.wikidata.org/wiki/Q32747[Q32747]
|
Lingua Vepsica (Abecedarium Latinum)
|
1

|
vro-Latn
|
https://glottolog.org/resource/languoid/id/sout2679[sout2679]
+++<br>+++
https://iso639-3.sil.org/code/vro[vro]
+++<br>+++ https://www.wikidata.org/wiki/Q32762[Q32762]
|
Lingua Voruvica (Abecedarium Latinum)
|
2

|
yue-Zyyy
|
https://glottolog.org/resource/languoid/id/yuec1235[yuec1235]
+++<br>+++
https://iso639-3.sil.org/code/yue[yue]
+++<br>+++ https://www.wikidata.org/wiki/Q7033959[Q7033959]
|
Lingua Yue (/ISO 15924 Zyyy/)
|
10

|
crh-Latn
|
https://glottolog.org/resource/languoid/id/crim1257[crim1257]
+++<br>+++
https://iso639-3.sil.org/code/crh[crh]
+++<br>+++ https://www.wikidata.org/wiki/Q107557485[Q107557485]
|
Lingua Tatarica Crimensis (Abecedarium Latinum)
|
1

|
lad-Zyyy
|
https://glottolog.org/resource/languoid/id/ladi1251[ladi1251]
+++<br>+++
https://iso639-3.sil.org/code/lad[lad]
+++<br>+++ https://www.wikidata.org/wiki/Q36196[Q36196]
|
Lingua Iudaeo-Hispanica (/ISO 15924 Zyyy/)
|
1

|
lez-Cyrl
|
https://glottolog.org/resource/languoid/id/lezg1247[lezg1247]
+++<br>+++
https://iso639-3.sil.org/code/lez[lez]
+++<br>+++ https://www.wikidata.org/wiki/Q31746[Q31746]
|
Lingua Lesghica (Abecedarium Cyrillicum)
|
1

|
swa-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/swa[swa]
+++<br>+++ https://www.wikidata.org/wiki/Q7838[Q7838]
|
Macrolingua Suahelica (Abecedarium Latinum)
|
5

|
zha-Zyyy
|
https://glottolog.org/resource/languoid/id/nort3180[nort3180]
+++<br>+++
https://iso639-3.sil.org/code/zha[zha]
+++<br>+++ https://www.wikidata.org/wiki/Q13216[Q13216]
|
/Zhuang languages/ (/ISO 15924 Zyyy/)
|
1

|
yor-Latn
|
https://glottolog.org/resource/languoid/id/yoru1245[yoru1245]
+++<br>+++
https://iso639-3.sil.org/code/yor[yor]
+++<br>+++ https://www.wikidata.org/wiki/Q34311[Q34311]
|
Lingua yoruba (Abecedarium Latinum)
|
1

|
yid-Hebr
|
https://glottolog.org/resource/languoid/id/yidd1255[yidd1255]
+++<br>+++
https://iso639-3.sil.org/code/yid[yid]
+++<br>+++ https://www.wikidata.org/wiki/Q8641[Q8641]
|
Macrolingua Iudaeo-Germanica (Alphabetum Hebraicum)
|
3

|
xho-Latn
|
https://glottolog.org/resource/languoid/id/xhos1239[xhos1239]
+++<br>+++
https://iso639-3.sil.org/code/xho[xho]
+++<br>+++ https://www.wikidata.org/wiki/Q13218[Q13218]
|
Lingua Xosana (Abecedarium Latinum)
|
1

|
uzb-Latn
|
https://glottolog.org/resource/languoid/id/uzbe1247[uzbe1247]
+++<br>+++
https://iso639-3.sil.org/code/uzb[uzb]
+++<br>+++ https://www.wikidata.org/wiki/Q9264[Q9264]
|
Macrolingua Uzbecica (Abecedarium Latinum)
|
1

|
uig-Zyyy
|
https://glottolog.org/resource/languoid/id/uigh1240[uigh1240]
+++<br>+++
https://iso639-3.sil.org/code/uig[uig]
+++<br>+++ https://www.wikidata.org/wiki/Q13263[Q13263]
|
Lingua Uigurica (/ISO 15924 Zyyy/)
|
1

|
tat-Zyyy
|
https://glottolog.org/resource/languoid/id/tata1255[tata1255]
+++<br>+++
https://iso639-3.sil.org/code/tat[tat]
+++<br>+++ https://www.wikidata.org/wiki/Q25285[Q25285]
|
Lingua Tatarica (/ISO 15924 Zyyy/)
|
5

|
tat-Cyrl
|
https://glottolog.org/resource/languoid/id/tata1255[tata1255]
+++<br>+++
https://iso639-3.sil.org/code/tat[tat]
+++<br>+++ https://www.wikidata.org/wiki/Q39132549[Q39132549]
|
Lingua Tatarica (Abecedarium Cyrillicum)
|
2

|
tat-Latn
|
https://glottolog.org/resource/languoid/id/tata1255[tata1255]
+++<br>+++
https://iso639-3.sil.org/code/tat[tat]
+++<br>+++ https://www.wikidata.org/wiki/Q39134544[Q39134544]
|
Lingua Tatarica (Abecedarium Latinum)
|
2

|
tso-Latn
|
https://glottolog.org/resource/languoid/id/tson1249[tson1249]
+++<br>+++
https://iso639-3.sil.org/code/tso[tso]
+++<br>+++ https://www.wikidata.org/wiki/Q34327[Q34327]
|
/Tsonga language/ (Abecedarium Latinum)
|
1

|
tgl-Latn
|
https://glottolog.org/resource/languoid/id/taga1270[taga1270]
+++<br>+++
https://iso639-3.sil.org/code/tgl[tgl]
+++<br>+++ https://www.wikidata.org/wiki/Q34057[Q34057]
|
Lingua Tagalog (Abecedarium Latinum)
|
4

|
tuk-Latn
|
https://glottolog.org/resource/languoid/id/turk1304[turk1304]
+++<br>+++
https://iso639-3.sil.org/code/tuk[tuk]
+++<br>+++ https://www.wikidata.org/wiki/Q9267[Q9267]
|
Lingua Turcomannica (Abecedarium Latinum)
|
2

|
abk-Cyrl
|
https://glottolog.org/resource/languoid/id/abkh1244[abkh1244]
+++<br>+++
https://iso639-3.sil.org/code/abk[abk]
+++<br>+++ https://www.wikidata.org/wiki/Q5111[Q5111]
|
Lingua Abasgica (Abecedarium Cyrillicum)
|
1

|
asm-Beng
|
https://glottolog.org/resource/languoid/id/assa1263[assa1263]
+++<br>+++
https://iso639-3.sil.org/code/asm[asm]
+++<br>+++ https://www.wikidata.org/wiki/Q29401[Q29401]
|
Lingua Assamica (/ISO 15924 Beng/)
|
2

|
ava-Cyrl
|
https://glottolog.org/resource/languoid/id/avar1256[avar1256]
+++<br>+++
https://iso639-3.sil.org/code/ava[ava]
+++<br>+++ https://www.wikidata.org/wiki/Q29561[Q29561]
|
Lingua Avarica (Abecedarium Cyrillicum)
|
1

|
aze-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/aze[aze]
+++<br>+++ https://www.wikidata.org/wiki/Q9292[Q9292]
|
Macrolingua Atropatenica (Abecedarium Latinum)
|
6

|
bak-Cyrl
|
https://glottolog.org/resource/languoid/id/bash1264[bash1264]
+++<br>+++
https://iso639-3.sil.org/code/bak[bak]
+++<br>+++ https://www.wikidata.org/wiki/Q13389[Q13389]
|
Lingua Baschkirica (Abecedarium Cyrillicum)
|
3

|
bis-Latn
|
https://glottolog.org/resource/languoid/id/bisl1239[bisl1239]
+++<br>+++
https://iso639-3.sil.org/code/bis[bis]
+++<br>+++ https://www.wikidata.org/wiki/Q35452[Q35452]
|
Lingua Bislama (Abecedarium Latinum)
|
1

|
chv-Cyrl
|
https://glottolog.org/resource/languoid/id/chuv1255[chuv1255]
+++<br>+++
https://iso639-3.sil.org/code/chv[chv]
+++<br>+++ https://www.wikidata.org/wiki/Q33348[Q33348]
|
Lingua Tschuvaschica (Abecedarium Cyrillicum)
|
5

|
grn-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/grn[grn]
+++<br>+++ https://www.wikidata.org/wiki/Q35876[Q35876]
|
Macrolingua Guaranica (Abecedarium Latinum)
|
1

|
glv-Latn
|
https://glottolog.org/resource/languoid/id/manx1243[manx1243]
+++<br>+++
https://iso639-3.sil.org/code/glv[glv]
+++<br>+++ https://www.wikidata.org/wiki/Q12175[Q12175]
|
Lingua Monensis (Abecedarium Latinum)
|
1

|
hau-Latn
|
https://glottolog.org/resource/languoid/id/haus1257[haus1257]
+++<br>+++
https://iso639-3.sil.org/code/hau[hau]
+++<br>+++ https://www.wikidata.org/wiki/Q56475[Q56475]
|
Lingua Haussana (Abecedarium Latinum)
|
4

|
hat-Latn
|
https://glottolog.org/resource/languoid/id/hait1244[hait1244]
+++<br>+++
https://iso639-3.sil.org/code/hat[hat]
+++<br>+++ https://www.wikidata.org/wiki/Q33491[Q33491]
|
Lingua creola Haitiana (Abecedarium Latinum)
|
4

|
xmf-Geor
|
https://glottolog.org/resource/languoid/id/ming1252[ming1252]
+++<br>+++
https://iso639-3.sil.org/code/xmf[xmf]
+++<br>+++ https://www.wikidata.org/wiki/Q13359[Q13359]
|
Lingua Mingrelica (Abecedarium Georgianum)
|
1

|
kaz-Zyyy
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q9252[Q9252]
|
Lingua Kazachica (/ISO 15924 Zyyy/)
|
7

|
kaz-Arab
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362991[Q64362991]
|
Lingua Kazachica (Abecedarium Arabicum)
|
2

|
kaz-Cyrl
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362992[Q64362992]
|
Lingua Kazachica (Abecedarium Cyrillicum)
|
3

|
kaz-Latn
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362993[Q64362993]
|
Lingua Kazachica (Abecedarium Latinum)
|
2

|
kur-Zyyy
|
https://glottolog.org/resource/languoid/id/kurd1259[kurd1259]
+++<br>+++
https://iso639-3.sil.org/code/kur[kur]
+++<br>+++ https://www.wikidata.org/wiki/Q36368[Q36368]
|
Macrolingua Curdica (/ISO 15924 Zyyy/)
|
1

|
ckb-Arab
|
https://glottolog.org/resource/languoid/id/cent1972[cent1972]
+++<br>+++
https://iso639-3.sil.org/code/ckb[ckb]
+++<br>+++ https://www.wikidata.org/wiki/Q36811[Q36811]
|
/Central Kurdish/ (Abecedarium Arabicum)
|
4

|
cor-Latn
|
https://glottolog.org/resource/languoid/id/corn1251[corn1251]
+++<br>+++
https://iso639-3.sil.org/code/cor[cor]
+++<br>+++ https://www.wikidata.org/wiki/Q25289[Q25289]
|
Lingua Cornubica (Abecedarium Latinum)
|
3

|
kir-Zyyy
|
https://glottolog.org/resource/languoid/id/kirg1245[kirg1245]
+++<br>+++
https://iso639-3.sil.org/code/kir[kir]
+++<br>+++ https://www.wikidata.org/wiki/Q9255[Q9255]
|
Lingua Kyrgyzensis (/ISO 15924 Zyyy/)
|
3

|
lld-Latn
|
https://glottolog.org/resource/languoid/id/ladi1250[ladi1250]
+++<br>+++
https://iso639-3.sil.org/code/lld[lld]
+++<br>+++ https://www.wikidata.org/wiki/Q36202[Q36202]
|
/Lingua Ladina-Dolomiana/ (Abecedarium Latinum)
|
1

|
lin-Latn
|
https://glottolog.org/resource/languoid/id/ling1263[ling1263]
+++<br>+++
https://iso639-3.sil.org/code/lin[lin]
+++<br>+++ https://www.wikidata.org/wiki/Q36217[Q36217]
|
/Lingala/ (Abecedarium Latinum)
|
1

|
mlg-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/mlg[mlg]
+++<br>+++ https://www.wikidata.org/wiki/Q7930[Q7930]
|
Macrolingua Malagasiensis (Abecedarium Latinum)
|
1

|
mkd-Cyrl
|
https://glottolog.org/resource/languoid/id/mace1250[mace1250]
+++<br>+++
https://iso639-3.sil.org/code/mkd[mkd]
+++<br>+++ https://www.wikidata.org/wiki/Q9296[Q9296]
|
Lingua Macedonica (Abecedarium Cyrillicum)
|
13

|
mon-Cyrl
|
https://glottolog.org/resource/languoid/id/mong1331[mong1331]
+++<br>+++
https://iso639-3.sil.org/code/mon[mon]
+++<br>+++ https://www.wikidata.org/wiki/Q9246[Q9246]
|
Macrolingua Mongolica (Abecedarium Cyrillicum)
|
2

|
mya-Mymr
|
https://glottolog.org/resource/languoid/id/nucl1310[nucl1310]
+++<br>+++
https://iso639-3.sil.org/code/mya[mya]
+++<br>+++ https://www.wikidata.org/wiki/Q9228[Q9228]
|
Lingua Birmanica (/ISO 15924 Mymr/)
|
3

|
nep-Deva
|
https://glottolog.org/resource/languoid/id/east1436[east1436]
+++<br>+++
https://iso639-3.sil.org/code/nep[nep]
+++<br>+++ https://www.wikidata.org/wiki/Q33823[Q33823]
|
Macrolingua Nepalensis (Devanāgarī)
|
3

|
dty-Deva
|
https://glottolog.org/resource/languoid/id/doty1234[doty1234]
+++<br>+++
https://iso639-3.sil.org/code/dty[dty]
+++<br>+++ https://www.wikidata.org/wiki/Q18415595[Q18415595]
|
/Dotyali/ (Devanāgarī)
|
1

|
nav-Latn
|
https://glottolog.org/resource/languoid/id/nava1243[nava1243]
+++<br>+++
https://iso639-3.sil.org/code/nav[nav]
+++<br>+++ https://www.wikidata.org/wiki/Q13310[Q13310]
|
/Navajo/ (Abecedarium Arabicum)
|
1

|
oss-Cyrl
|
https://glottolog.org/resource/languoid/id/iron1242[iron1242]
+++<br>+++
https://iso639-3.sil.org/code/oss[oss]
+++<br>+++ https://www.wikidata.org/wiki/Q33968[Q33968]
|
Lingua Ossetica (Abecedarium Cyrillicum)
|
1

|
pus-Arab
|
https://glottolog.org/resource/languoid/id/nucl1276[nucl1276]
+++<br>+++
https://iso639-3.sil.org/code/pus[pus]
+++<br>+++ https://www.wikidata.org/wiki/Q58680[Q58680]
|
Macrolingua Afganica (Abecedarium Arabicum)
|
5

|
que-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/que[que]
+++<br>+++ https://www.wikidata.org/wiki/Q5218[Q5218]
|
Macrolinguae Quechuae (Abecedarium Latinum)
|
4

|
snd-Arab
|
https://glottolog.org/resource/languoid/id/sind1272[sind1272]
+++<br>+++
https://iso639-3.sil.org/code/snd[snd]
+++<br>+++ https://www.wikidata.org/wiki/Q33997[Q33997]
|
Lingua Sindhuica (Abecedarium Arabicum)
|
4

|
sme-Latn
|
https://glottolog.org/resource/languoid/id/nort2671[nort2671]
+++<br>+++
https://iso639-3.sil.org/code/sme[sme]
+++<br>+++ https://www.wikidata.org/wiki/Q33947[Q33947]
|
Lingua Samica septentrionalis (Abecedarium Latinum)
|
6

|
smo-Latn
|
https://glottolog.org/resource/languoid/id/samo1305[samo1305]
+++<br>+++
https://iso639-3.sil.org/code/smo[smo]
+++<br>+++ https://www.wikidata.org/wiki/Q34011[Q34011]
|
Lingua Samoana (Abecedarium Latinum)
|
1

|
sna-Latn
|
https://glottolog.org/resource/languoid/id/shon1251[shon1251]
+++<br>+++
https://iso639-3.sil.org/code/sna[sna]
+++<br>+++ https://www.wikidata.org/wiki/Q34004[Q34004]
|
/Shona/ (Abecedarium Latinum)
|
2

|
som-Latn
|
https://glottolog.org/resource/languoid/id/soma1255[soma1255]
+++<br>+++
https://iso639-3.sil.org/code/som[som]
+++<br>+++ https://www.wikidata.org/wiki/Q13275[Q13275]
|
Lingua Somalica (Abecedarium Latinum)
|
2

|
tgk-Zyyy
|
https://glottolog.org/resource/languoid/id/taji1245[taji1245]
+++<br>+++
https://iso639-3.sil.org/code/tgk[tgk]
+++<br>+++ https://www.wikidata.org/wiki/Q9260[Q9260]
|
Lingua Tadzikica (/ISO 15924 Zyyy/)
|
2

|
zul-Latn
|
https://glottolog.org/resource/languoid/id/zulu1248[zulu1248]
+++<br>+++
https://iso639-3.sil.org/code/zul[zul]
+++<br>+++ https://www.wikidata.org/wiki/Q10179[Q10179]
|
Lingua Zuluana (Abecedarium Latinum)
|
1

|
vol-Latn
|
https://glottolog.org/resource/languoid/id/vola1234[vola1234]
+++<br>+++
https://iso639-3.sil.org/code/vol[vol]
+++<br>+++ https://www.wikidata.org/wiki/Q36986[Q36986]
|
Volapük (Abecedarium Latinum)
|
1

|
ina-Latn
|
https://glottolog.org/resource/languoid/id/inte1239[inte1239]
+++<br>+++
https://iso639-3.sil.org/code/ina[ina]
+++<br>+++ https://www.wikidata.org/wiki/Q35934[Q35934]
|
Interlingua (Abecedarium Latinum)
|
1

|
ile-Latn
|
https://glottolog.org/resource/languoid/id/inte1260[inte1260]
+++<br>+++
https://iso639-3.sil.org/code/ile[ile]
+++<br>+++ https://www.wikidata.org/wiki/Q35850[Q35850]
|
Lingua Occidental (Abecedarium Latinum)
|
1

|
jbo-Latn
|
https://glottolog.org/resource/languoid/id/lojb1234[lojb1234]
+++<br>+++
https://iso639-3.sil.org/code/jbo[jbo]
+++<br>+++ https://www.wikidata.org/wiki/Q36350[Q36350]
|
Lojban (Abecedarium Latinum)
|
1

|
ido-Latn
|
https://glottolog.org/resource/languoid/id/idoo1234[idoo1234]
+++<br>+++
https://iso639-3.sil.org/code/ido[ido]
+++<br>+++ https://www.wikidata.org/wiki/Q35224[Q35224]
|
Ido (Abecedarium Latinum)
|
1

|
lfn-Latn
|
https://glottolog.org/resource/languoid/id/ling1267[ling1267]
+++<br>+++
https://iso639-3.sil.org/code/lfn[lfn]
+++<br>+++ https://www.wikidata.org/wiki/Q146803[Q146803]
|
Lingua Franca Nova (Abecedarium Latinum)
|
1

|===

==== Rēs interlinguālibus: 7
Rēs::
  /Wiki QID/:::
    Rēs interlinguālibus::::
      /rēgulam/;;
        Q[1-9]\d*

      ix_hxlix;;
        ix_wikiq

      ix_hxlvoc;;
        v_wiki_q

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/Wiki QID/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">QID (ou número Q) é o identificador único de um item de dados no Wikidata, composto pela letra "Q" seguida por um ou mais dígitos. Ele é usado para ajudar pessoas e máquinas a entender a diferença entre itens com nomes iguais ou semelhantes, por exemplo, existem vários lugares no mundo chamados Londres e muitas pessoas chamadas James Smith. Este número aparece ao lado do nome na parte superior de cada item do Wikidata.</span>+++

  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wikip2479

      ix_hxlvoc;;
        v_wiki_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">SPDX license identifier</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">identificador de licença SPDX</span>+++

  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wikip577

      ix_hxlvoc;;
        v_wiki_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Date or point in time when a work was first published or released</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">Data ou ponto no tempo em que um trabalho foi publicado ou lançado pela primeira vez</span>+++

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wikip123

      ix_hxlvoc;;
        v_wiki_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">organização ou pessoa responsável pela publicação de livros, periódicos, música impressa, podcasts, jogos ou software</span>+++

  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wikip393

      ix_hxlvoc;;
        v_wiki_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">number of an edition (first, second, ... as 1, 2, ...) or event</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">número de uma edição (primeira, segunda, ... como 1, 2, ...) ou evento</span>+++

  /scope and content/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P7535[P7535]

      ix_hxlix;;
        ix_wikip7535

      ix_hxlvoc;;
        v_wiki_p_7535

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/scope and content/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">a summary statement providing an overview of the archival collection</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">uma declaração resumida fornecendo uma visão geral da coleção de arquivo</span>+++

  scrīptor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P50[P50]

      ix_hxlix;;
        ix_wikip50

      ix_hxlvoc;;
        v_wiki_p_50

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">scrīptor</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Main creator(s) of a written work (use on works, not humans)</span>+++

      Lingua Lusitana (Abecedarium Latinum);;
        +++<span lang="pt">Principais criadores de uma obra escrita (uso em obras, não em humanos)</span>+++


<<<

== Archīa

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    **Informações de contexto**: ignorando por um momento o fato de ter várias traduções (e otimizadas para receber contribuições regularmente, não _apenas_ um trabalho estático), então a diferença real no fluxo de trabalho usado para gerar cada grupo de dicionários em um Cōdex como este é o seguinte fato: **fornecemos formatos de arquivos estruturados legíveis por máquina mesmo quando os equivalentes em _idiomas internacionais_, como o inglês, não possuem para áreas como ajuda humanitária, ajuda ao desenvolvimento e direitos humanos**. Os mais próximos desse multilinguismo (fora da Wikimedia) são o SEMIeu da União Europeia (até 24 idiomas), mas mesmo assim têm problemas ao compartilhar traduções em todos os idiomas. As traduções das Nações Unidas (até 6 idiomas, raramente mais) não estão disponíveis por agências humanitárias para ajudar nas traduções de terminologia.
    +++<br><br>+++
    **Implicação prática**: os documentos de texto em _Archīa prō cōdice_ (tradução literal em inglês: _File for book_) são alternativas a este formato de livro que são altamente automatizados usando apenas o formato de dados. No entanto, os formatos legíveis por máquina em _Archīa prō dictiōnāriīs_ (tradução literal em inglês: _Arquivos para dicionários_) são o foco e recomendados para trabalhos derivados e destinados a mitigar erros humanos adicionais. Podemos até criar novos formatos a pedido! O objetivo aqui é permitir tradutores de terminologia e uso de produção onde isso tenha um impacto positivo.


=== Archīa prō dictiōnāriīs: 4


==== 1603_64_604.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_64_604.no1.tm.hxl.csv[1603_64_604.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio no contêiner HXLTM/



==== 1603_64_604.no11.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_64_604.no11.tm.hxl.csv[1603_64_604.no11.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio no contêiner HXLTM (expandido com traduções de terminologia)/



==== 1603_64_604.wikiq.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_64_604.wikiq.tm.hxl.csv[1603_64_604.wikiq.tm.hxl.csv]
  /reference URL/@eng-Latn:::
    https://hxltm.etica.ai/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Dialeto HXLTM do Padrão HXL em CSV RFC 4180. Resumidamente: wikiq significa que #item+conceptum+codicem são estritamente Wikidata QIDs.



==== 1603_64_604.no11.tbx

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_64_604.no11.tbx[1603_64_604.no11.tbx]
  /reference URL/@eng-Latn:::
    http://www.terminorgs.net/downloads/TBX_Basic_Version_3.1.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    TBX-Basic é uma linguagem de marcação terminológica (TML) que é uma versão mais leve de TBX-Default, a TML que é definida na ISO 30042. TBX-Basic é projetada para o setor de localização e é baseada em informações de pesquisas e estudos que foram conduzida pelo LISA Term SIG sobre os tipos de dados de terminologia que o setor de localização exige.



==== 1603_64_604.no11.tmx

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_64_604.no11.tmx[1603_64_604.no11.tmx]
  /reference URL/@eng-Latn:::
    https://www.gala-global.org/tmx-14b

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    O objetivo do formato Translation Memory eXchange (TMX) é fornecer um método padrão para descrever dados de memória de tradução que estão sendo trocados entre ferramentas e/ou fornecedores de tradução, ao mesmo tempo em que introduz pouca ou nenhuma perda de dados críticos durante o processo



=== Archīa prō cōdice: 2


==== 1603_64_604.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_64_604.mul-Latn.codex.adoc[1603_64_604.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc é um formato de autoria de texto simples (ou seja, linguagem de marcação leve) para escrever conteúdo técnico, como documentação, artigos e livros.



==== 1603_64_604.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_64_604.mul-Latn.codex.pdf[1603_64_604.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), padronizado como ISO 32000, é um formato de arquivo desenvolvido pela Adobe em 1992 para apresentar documentos, incluindo formatação de texto e imagens, de maneira independente do software aplicativo, hardware e sistemas operacionais.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== //Dictiōnāria dē aquīs et sānātiōnibus ex līmpidīs//
<<<

[id='1']
=== [`1`] 





[id='1_283']
==== [`1_283`] aqua

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q283[Q283]

Rēs linguālibus (219)::
  Linguae multiplīs (Scrīptum incognitō):::
    /water/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">ماء</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">ջուր</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">পানি</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">вода</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">जल</span>+++

  Lingua Amharica (/ISO 15924 Ethi/):::
    +++<span lang="am">ውሃ</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">წყალი</span>+++

  Lingua Gujaratensis (/ISO 15924 Gujr/):::
    +++<span lang="gu">પાણી</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਪਾਣੀ</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ನೀರು</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">물</span>+++

  Lingua Sinica classica (/ISO 15924 Hant/):::
    +++<span lang="lzh">水</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">מים</span>+++

  Lingua Khmer (/ISO 15924 Khmr/):::
    +++<span lang="km">ទឹក</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">aqua</span>+++

  Lingua Meitei (/ISO 15924 Mtei/):::
    +++<span lang="mni">ꯏꯁꯤꯡ</span>+++

  /N'Ko/ (/ISO 15924 Nkoo/):::
    +++<span lang="nqo">ߖߌ</span>+++

  Lingua Santali (/ISO 15924 Olck/):::
    +++<span lang="sat">ᱫᱟᱜ</span>+++

  Macrolingua Orissensis (/ISO 15924 Orya/):::
    +++<span lang="or">ଜଳ</span>+++

  Lingua Singhalensis (/ISO 15924 Sinh/):::
    +++<span lang="si">ජලය</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">நீர்</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">నీరు</span>+++

  Lingua Dhivehi (/ISO 15924 Thaa/):::
    +++<span lang="dv">ފެން</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">น้ำ</span>+++

  Lingua Tibetana (Scriptura Tibetana):::
    +++<span lang="bo">ཆུ།</span>+++

  Lingua Sanscrita (/ISO 15924 Zyyy/):::
    +++<span lang="sa">जलम्</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">水</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">água</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">water</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">eau</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">water</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Wasser</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">agua</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">acqua</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">uisce</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">vatten</span>+++

  Lingua Caebuana (Abecedarium Latinum):::
    +++<span lang="ceb">tubig</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">uji</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">woda</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">vesi</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">apă</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">nước</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">aigua</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">вода</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">вода</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">voda</span>+++

  /Waray language/ (Abecedarium Latinum):::
    +++<span lang="war">tubig</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">vann</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">voda</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">vand</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">vatn</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">ജലം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">air</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">آب</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">víz</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">ura</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">dŵr</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">auga</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">voda</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">akvo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">air</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">vesi</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">voda</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">su</span>+++

  Lingua Saxonica (Abecedarium Latinum):::
    +++<span lang="nds">Water</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">aiga</span>+++

  Lingua Britonica (Abecedarium Latinum):::
    +++<span lang="br">dour</span>+++

  /Egyptian Arabic/ (Abecedarium Arabicum):::
    +++<span lang="arz">ميه</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">water</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Waasser</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">watter</span>+++

  Lingua Bavarica (Abecedarium Latinum):::
    +++<span lang="bar">Wossa</span>+++

  Lingua Aragonensis (Abecedarium Latinum):::
    +++<span lang="an">augua</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">水</span>+++

  /lingua Papiamentica/ (Abecedarium Latinum):::
    +++<span lang="pap">awa</span>+++

  Lingua Corsica (Abecedarium Latinum):::
    +++<span lang="co">acqua</span>+++

  Dialecti Alemannicae (Abecedarium Latinum):::
    +++<span lang="gsw">Wasser</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">vatn</span>+++

  /Minangkabau language/ (Abecedarium Latinum):::
    +++<span lang="min">aia</span>+++

  Lingua Veneta (Abecedarium Latinum):::
    +++<span lang="vec">àcua</span>+++

  Lingua Pedemontana (Abecedarium Latinum):::
    +++<span lang="pms">eva</span>+++

  Lingua Sicula (Abecedarium Latinum):::
    +++<span lang="scn">acqua</span>+++

  Macrolingua Sarda (Abecedarium Latinum):::
    +++<span lang="sc">aba</span>+++

  Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum):::
    +++<span lang="gd">uisge</span>+++

  Lingua Limburgica (Abecedarium Latinum):::
    +++<span lang="li">water</span>+++

  /West Flemish/ (Abecedarium Latinum):::
    +++<span lang="vls">woater</span>+++

  Lingua Neapolitana (Abecedarium Latinum):::
    +++<span lang="nap">acqua</span>+++

  Lingua Ligustica (Abecedarium Latinum):::
    +++<span lang="lij">ægoa</span>+++

  Lingua Foroiuliensis (Abecedarium Latinum):::
    +++<span lang="fur">aghe</span>+++

  Lingua Picardica (Abecedarium Latinum):::
    +++<span lang="pcd">Ieu</span>+++

  /Wolof language/ (Abecedarium Latinum):::
    +++<span lang="wo">ndox</span>+++

  /Kongo macrolanguage/ (Abecedarium Latinum):::
    +++<span lang="kg">maza</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">水</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">вода</span>+++

  Lingua Urdu (Abecedarium Arabicum):::
    +++<span lang="ur">پانی</span>+++

  Lingua Gan (/ISO 15924 Zyyy/):::
    +++<span lang="gan">水</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">vanduo</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">voda</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">ūdens</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">voda</span>+++

  /South Azerbaijani/ (Abecedarium Arabicum):::
    +++<span lang="azb">سو</span>+++

  Lingua Iavanica (Abecedarium Latinum):::
    +++<span lang="jv">banyu</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">νερό</span>+++

  /Sundanese language/ (Abecedarium Latinum):::
    +++<span lang="su">cai</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">wetter</span>+++

  /Acehnese language/ (Abecedarium Latinum):::
    +++<span lang="ace">ie</span>+++

  Lingua creola Iamaicana (Abecedarium Latinum):::
    +++<span lang="jam">waata</span>+++

  Lingua Tsetsenica (Abecedarium Cyrillicum):::
    +++<span lang="ce">хи</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">вада</span>+++

  /Kabyle language/ (Abecedarium Latinum):::
    +++<span lang="kab">aman</span>+++

  Lingua Faeroensis (Abecedarium Latinum):::
    +++<span lang="fo">vatn</span>+++

  /Bambara language/ (/ISO 15924 Zyyy/):::
    +++<span lang="bm">Ji</span>+++

  Langobardus sermo (Abecedarium Latinum):::
    +++<span lang="lmo">aqua</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">पाणी</span>+++

  /Moroccan Arabic/ (Abecedarium Arabicum):::
    +++<span lang="ary">ما</span>+++

  /Awadhi/ (Devanāgarī):::
    +++<span lang="awa">पानी</span>+++

  /Balinese/ (Abecedarium Latinum):::
    +++<span lang="ban">toya</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">agua</span>+++

  /Central Bikol/  (Abecedarium Latinum):::
    +++<span lang="bcl">Tubig</span>+++

  Lingua Bhojpuri (Devanāgarī):::
    +++<span lang="bho">पानी</span>+++

  Lingua Buriatica (Abecedarium Cyrillicum):::
    +++<span lang="bxr">уһан</span>+++

  /Min Dong Chinese/ (/ISO 15924 Zyyy/):::
    +++<span lang="cdo">cūi</span>+++

  Lingua Zazaca (Abecedarium Latinum):::
    +++<span lang="diq">Awe</span>+++

  /Lower Sorbian/ (Abecedarium Latinum):::
    +++<span lang="dsb">wóda</span>+++

  Lingua Extremadurensis (Abecedarium Latinum):::
    +++<span lang="ext">augua</span>+++

  /Guianese Creole French/ (Abecedarium Latinum):::
    +++<span lang="gcr">dilo</span>+++

  /Goan Konkani/ (/ISO 15924 Zyyy/):::
    +++<span lang="gom">udok</span>+++

  /Northern Frisian/ (Abecedarium Latinum):::
    +++<span lang="frr">Weeder</span>+++

  /Hakka Chinese/ (/ISO 15924 Zyyy/):::
    +++<span lang="hak">súi</span>+++

  Lingua Hindi Vitiensis (/ISO 15924 Zyyy/):::
    +++<span lang="hif">paani</span>+++

  /Upper Sorbian/ (Abecedarium Latinum):::
    +++<span lang="hsb">woda</span>+++

  /Western Armenian/ (Alphabetum Armenium):::
    +++<span lang="hyw">ջուր</span>+++

  Lingua Ilocana (Abecedarium Latinum):::
    +++<span lang="ilo">danum</span>+++

  Lingua Ingussica (Abecedarium Cyrillicum):::
    +++<span lang="inh">Хий</span>+++

  Lingua Karakalpakensis (Abecedarium Latinum):::
    +++<span lang="kaa">suw</span>+++

  /Kabiye language/ (Abecedarium Latinum):::
    +++<span lang="kbp">lɩm</span>+++

  Lingua Maithili (Devanāgarī):::
    +++<span lang="mai">पानी</span>+++

  Lingua Mirandica (Abecedarium Latinum):::
    +++<span lang="mwl">auga</span>+++

  /Mazanderani language/ (Abecedarium Arabicum):::
    +++<span lang="mzn">ئو</span>+++

  Lingua Navatlaca (Abecedarium Latinum):::
    +++<span lang="nah">ātl</span>+++

  /Min Nan Chinese/ (Abecedarium Latinum):::
    +++<span lang="nan">Chúi</span>+++

  Lingua Newari (Devanāgarī):::
    +++<span lang="new">लः</span>+++

  /Kapampangan language/ (Abecedarium Latinum):::
    +++<span lang="pam">danum</span>+++

  /Palatine German language/ (Abecedarium Latinum):::
    +++<span lang="pfl">Wassa</span>+++

  Lingua Paniabica occidentalis (Abecedarium Arabicum):::
    +++<span lang="pnb">پانی</span>+++

  Lingua Rusinica (Abecedarium Cyrillicum):::
    +++<span lang="rue">вода</span>+++

  Lingua aromanian (Abecedarium Latinum):::
    +++<span lang="rup">Apâ</span>+++

  Lingua Iacutica (Abecedarium Cyrillicum):::
    +++<span lang="sah">уу</span>+++

  Lingua Samogitica (Abecedarium Latinum):::
    +++<span lang="sgs">Ondou</span>+++

  Shilha language (/ISO 15924 Zyyy/):::
    +++<span lang="shi">Aman</span>+++

  Lingua Shan (/ISO 15924 Mymr/):::
    +++<span lang="shn">ၼမ်ႉ</span>+++

  /Inari Sami/ (Abecedarium Latinum):::
    +++<span lang="smn">čääci</span>+++

  /Saterland Frisian language/ (Abecedarium Latinum):::
    +++<span lang="stq">Woater</span>+++

  Lingua Silesica (Abecedarium Latinum):::
    +++<span lang="szl">woda</span>+++

  Lingua Tuluva (/ISO 15924 Zyyy/):::
    +++<span lang="tcy">ನೀರ್</span>+++

  Lingua Udmurtica (Abecedarium Cyrillicum):::
    +++<span lang="udm">ву</span>+++

  Lingua Vepsica (Abecedarium Latinum):::
    +++<span lang="vep">vezi</span>+++

  Lingua Voruvica (Abecedarium Latinum):::
    +++<span lang="vro">Vesi</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">水</span>+++

  Lingua Tatarica Crimensis (Abecedarium Latinum):::
    +++<span lang="crh-latn">Suv</span>+++

  Lingua Iudaeo-Hispanica (/ISO 15924 Zyyy/):::
    +++<span lang="lad">agua</span>+++

  Lingua Lesghica (Abecedarium Cyrillicum):::
    +++<span lang="lez">яд</span>+++

  Macrolingua Suahelica (Abecedarium Latinum):::
    +++<span lang="sw">maji</span>+++

  /Zhuang languages/ (/ISO 15924 Zyyy/):::
    +++<span lang="za">raemx</span>+++

  Lingua yoruba (Abecedarium Latinum):::
    +++<span lang="yo">omi</span>+++

  Macrolingua Iudaeo-Germanica (Alphabetum Hebraicum):::
    +++<span lang="yi">װאַסער</span>+++

  Lingua Xosana (Abecedarium Latinum):::
    +++<span lang="xh">amanzi</span>+++

  Macrolingua Uzbecica (Abecedarium Latinum):::
    +++<span lang="uz">suv</span>+++

  Lingua Uigurica (/ISO 15924 Zyyy/):::
    +++<span lang="ug">سۇ</span>+++

  Lingua Tatarica (/ISO 15924 Zyyy/):::
    +++<span lang="tt">су</span>+++

  Lingua Tatarica (Abecedarium Cyrillicum):::
    +++<span lang="tt-cyrl">су</span>+++

  Lingua Tatarica (Abecedarium Latinum):::
    +++<span lang="tt-latn">su</span>+++

  /Tsonga language/ (Abecedarium Latinum):::
    +++<span lang="ts">mati</span>+++

  Lingua Tagalog (Abecedarium Latinum):::
    +++<span lang="tl">tubig</span>+++

  Lingua Turcomannica (Abecedarium Latinum):::
    +++<span lang="tk">suw</span>+++

  Lingua Abasgica (Abecedarium Cyrillicum):::
    +++<span lang="ab">аӡы</span>+++

  Lingua Assamica (/ISO 15924 Beng/):::
    +++<span lang="as">পানী</span>+++

  Lingua Avarica (Abecedarium Cyrillicum):::
    +++<span lang="av">лъим</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">su</span>+++

  Lingua Baschkirica (Abecedarium Cyrillicum):::
    +++<span lang="ba">Һыу</span>+++

  Lingua Bislama (Abecedarium Latinum):::
    +++<span lang="bi">wota</span>+++

  Lingua Tschuvaschica (Abecedarium Cyrillicum):::
    +++<span lang="cv">шыв</span>+++

  Macrolingua Guaranica (Abecedarium Latinum):::
    +++<span lang="gn">y</span>+++

  Lingua Monensis (Abecedarium Latinum):::
    +++<span lang="gv">ushtey</span>+++

  Lingua Haussana (Abecedarium Latinum):::
    +++<span lang="ha">ruwa</span>+++

  Lingua creola Haitiana (Abecedarium Latinum):::
    +++<span lang="ht">dlo</span>+++

  Lingua Mingrelica (Abecedarium Georgianum):::
    +++<span lang="xmf">წყარი</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">су</span>+++

  Macrolingua Curdica (/ISO 15924 Zyyy/):::
    +++<span lang="ku">av</span>+++

  /Central Kurdish/ (Abecedarium Arabicum):::
    +++<span lang="ckb">ئاو</span>+++

  Lingua Cornubica (Abecedarium Latinum):::
    +++<span lang="kw">Dowr</span>+++

  Lingua Kyrgyzensis (/ISO 15924 Zyyy/):::
    +++<span lang="ky">суу</span>+++

  /Lingua Ladina-Dolomiana/ (Abecedarium Latinum):::
    +++<span lang="lld">Èga</span>+++

  /Lingala/ (Abecedarium Latinum):::
    +++<span lang="ln">mái</span>+++

  Macrolingua Malagasiensis (Abecedarium Latinum):::
    +++<span lang="mg">rano</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">вода</span>+++

  Macrolingua Mongolica (Abecedarium Cyrillicum):::
    +++<span lang="mn">Ус</span>+++

  Lingua Birmanica (/ISO 15924 Mymr/):::
    +++<span lang="my">ရေ</span>+++

  Macrolingua Nepalensis (Devanāgarī):::
    +++<span lang="ne">पानी</span>+++

  /Dotyali/ (Devanāgarī):::
    +++<span lang="dty">पानी</span>+++

  /Navajo/ (Abecedarium Arabicum):::
    +++<span lang="nv">tó</span>+++

  Lingua Ossetica (Abecedarium Cyrillicum):::
    +++<span lang="os">дон</span>+++

  Macrolingua Afganica (Abecedarium Arabicum):::
    +++<span lang="ps">اوبه</span>+++

  Macrolinguae Quechuae (Abecedarium Latinum):::
    +++<span lang="qu">yaku</span>+++

  Lingua Sindhuica (Abecedarium Arabicum):::
    +++<span lang="sd">پاڻي</span>+++

  Lingua Samica septentrionalis (Abecedarium Latinum):::
    +++<span lang="se">čáhci</span>+++

  Lingua Samoana (Abecedarium Latinum):::
    +++<span lang="sm">vai</span>+++

  /Shona/ (Abecedarium Latinum):::
    +++<span lang="sn">mvura</span>+++

  Lingua Somalica (Abecedarium Latinum):::
    +++<span lang="so">biyo</span>+++

  Lingua Tadzikica (/ISO 15924 Zyyy/):::
    +++<span lang="tg">об</span>+++

  Lingua Zuluana (Abecedarium Latinum):::
    +++<span lang="zu">amanzi</span>+++

  Volapük (Abecedarium Latinum):::
    +++<span lang="vo">vat</span>+++

  Interlingua (Abecedarium Latinum):::
    +++<span lang="ia">aqua</span>+++

  Lingua Occidental (Abecedarium Latinum):::
    +++<span lang="ie">aqua</span>+++

  Lojban (Abecedarium Latinum):::
    +++<span lang="jbo">djacu</span>+++

  Ido (Abecedarium Latinum):::
    +++<span lang="io">aquo</span>+++

  Lingua Franca Nova (Abecedarium Latinum):::
    +++<span lang="lfn">acua</span>+++





[id='1_7892']
==== [`1_7892`] /drinking water/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q7892[Q7892]

Rēs linguālibus (87)::
  Linguae multiplīs (Scrīptum incognitō):::
    /drinking water/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">ماء الشرب</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Խմելու ջուր</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">পানীয় জল</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">питьевая вода</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">पीने का पानी</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">სასმელი წყალი</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਪੀਣ ਵਾਲਾ ਪਾਣੀ</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಕುಡಿಯುವ ನೀರು</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">식수</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">מי שתייה</span>+++

  /Lao language/ (/ISO 15924 Laoo/):::
    +++<span lang="lo">ນ້ຳດື່ມ</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">குடி நீர்</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">తాగునీరు</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">น้ำดื่ม</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">饮用水</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">água potável</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">drinking water</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">eau potable</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">drinkwater</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Trinkwasser</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">agua potable</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">acqua potabile</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">dricksvatten</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">Uji i Pijshëm</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">woda pitna</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">juomavesi</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Apă potabilă</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">nước uống</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">aigua potable</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">питна вода</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Питейна вода</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Pitna voda</span>+++

  /Waray language/ (Abecedarium Latinum):::
    +++<span lang="war">Irimnon nga tubig</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">drikkevann</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">pitná voda</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">drikkevand</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">飲料水</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">drikkevatn</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">കുടിവെള്ളം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">air minum</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">آب آشامیدنی</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">ivóvíz</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Edateko ur</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">auga potable</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">Pitná voda</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">trinkakvo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">air minuman</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">joogivesi</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Pitka voda</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">İçme suyu</span>+++

  Lingua Saxonica (Abecedarium Latinum):::
    +++<span lang="nds">Drinkwater</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">Aiga potabla</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Drinkwater</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Drénkwaasser</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Neysluvatn</span>+++

  Lingua Sicula (Abecedarium Latinum):::
    +++<span lang="scn">acqua pi bìviri</span>+++

  Macrolingua Sarda (Abecedarium Latinum):::
    +++<span lang="sc">Aba potàbile</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">饮用水</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">пијаћа вода</span>+++

  Lingua Gan (/ISO 15924 Zyyy/):::
    +++<span lang="gan">白開水</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">pitka voda</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">dzeramais ūdens</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Vodovod</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">Πόσιμο νερό</span>+++

  Lingua creola Iamaicana (Abecedarium Latinum):::
    +++<span lang="jam">Jingkin waata</span>+++

  Lingua Tsetsenica (Abecedarium Cyrillicum):::
    +++<span lang="ce">молу хи</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">піццёвая вада</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">पिण्याचे पाणी</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">agua potable</span>+++

  Lingua Zazaca (Abecedarium Latinum):::
    +++<span lang="diq">Awa şımıtışi</span>+++

  /Guianese Creole French/ (Abecedarium Latinum):::
    +++<span lang="gcr">Dilo potab</span>+++

  /Upper Sorbian/ (Abecedarium Latinum):::
    +++<span lang="hsb">pitna woda</span>+++

  /Min Nan Chinese/ (Abecedarium Latinum):::
    +++<span lang="nan">Ím-iōng-chúi</span>+++

  /Inari Sami/ (Abecedarium Latinum):::
    +++<span lang="smn">juuhâmčääci</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">食水</span>+++

  Macrolingua Suahelica (Abecedarium Latinum):::
    +++<span lang="sw">Maji salama</span>+++

  Macrolingua Iudaeo-Germanica (Alphabetum Hebraicum):::
    +++<span lang="yi">טרינקוואסער</span>+++

  Lingua Haussana (Abecedarium Latinum):::
    +++<span lang="ha">Ruwa</span>+++

  Lingua creola Haitiana (Abecedarium Latinum):::
    +++<span lang="ht">Dlo pou bwè pwòp</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Ауыз су</span>+++

  Lingua Kyrgyzensis (/ISO 15924 Zyyy/):::
    +++<span lang="ky">Ичилчү суу</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">пивка вода</span>+++

  Lingua Birmanica (/ISO 15924 Mymr/):::
    +++<span lang="my">သန့်ရှင်းသော သောက်သုံးရေ</span>+++

  Macrolingua Nepalensis (Devanāgarī):::
    +++<span lang="ne">पिउने पानी</span>+++

  Macrolinguae Quechuae (Abecedarium Latinum):::
    +++<span lang="qu">Upyana yaku</span>+++

  Lingua Samica septentrionalis (Abecedarium Latinum):::
    +++<span lang="se">juhkančáhci</span>+++





[id='1_15324']
==== [`1_15324`] Corpus aquae

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q15324[Q15324]

Rēs linguālibus (92)::
  Linguae multiplīs (Scrīptum incognitō):::
    /body of water/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">مسطح مائي</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">ջրային օբյեկտ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">водный объект</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">जल निकाय</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">წყალსატევი</span>+++

  Lingua Gujaratensis (/ISO 15924 Gujr/):::
    +++<span lang="gu">જળાશય</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">수역</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">גוף מים</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Corpus aquae</span>+++

  Lingua Singhalensis (/ISO 15924 Sinh/):::
    +++<span lang="si">Body of water</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">நீர்நிலைகள்</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">నీటి రాశి</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">แหล่งน้ำ</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">水體</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">corpo de água</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">body of water</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">étendue d'eau</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">waterlichaam</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Gewässer</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">cuerpo de agua</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">massa d'acqua</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">limistéar uisce</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">vattensamling</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">trup ujor</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">akwen</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">vesimuodostuma</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">întindere de apă</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">vùng nước</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">cos d'aigua</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">водний об'єкт</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Воден басейн</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Vodno telo</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">vannmasse</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">vodstvo</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">vandområde</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水域</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">vassførekomst</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">ജലാശയം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">perairan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">بدنه آبی</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">felszíni víz</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">ur gorputza</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">corff o ddŵr</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">corpo de auga</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">akvejo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">jasad air</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">veekogu</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">vodena površina</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">su kütlesi</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">espandida d'aiga</span>+++

  Lingua Britonica (Abecedarium Latinum):::
    +++<span lang="br">Ledennad dour</span>+++

  /Egyptian Arabic/ (Abecedarium Arabicum):::
    +++<span lang="arz">مسطح مائى</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Gewässer</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">body o watter</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">水體</span>+++

  Dialecti Alemannicae (Abecedarium Latinum):::
    +++<span lang="gsw">Gewässer</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Vatnshlot</span>+++

  Lingua Veneta (Abecedarium Latinum):::
    +++<span lang="vec">corpo de àcua</span>+++

  Lingua Sicula (Abecedarium Latinum):::
    +++<span lang="scn">corpu ìdricu</span>+++

  Lingua Vallonica (Abecedarium Latinum):::
    +++<span lang="wa">Aiwe</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">vodena površina</span>+++

  Lingua Arpitanica (Abecedarium Latinum):::
    +++<span lang="frp">ètendua d’égoua</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">水体</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">водена површина</span>+++

  Lingua Urdu (Abecedarium Arabicum):::
    +++<span lang="ur">جسم آب</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Vandens telkinys</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">vodena masa</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">ūdenstilpe</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">υδάτινο σώμα</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">водны аб’ект</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">जलसाठा</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">cuerpu d'agua</span>+++

  Lingua Bhojpuri (Devanāgarī):::
    +++<span lang="bho">जलभंडार</span>+++

  Lingua Zazaca (Abecedarium Latinum):::
    +++<span lang="diq">Kutleyê awer</span>+++

  /Lower Sorbian/ (Abecedarium Latinum):::
    +++<span lang="dsb">Wódy</span>+++

  /Upper Sorbian/ (Abecedarium Latinum):::
    +++<span lang="hsb">wodźizna</span>+++

  Lingua Ilocana (Abecedarium Latinum):::
    +++<span lang="ilo">bagi ti danum</span>+++

  Lingua Samogitica (Abecedarium Latinum):::
    +++<span lang="sgs">Ondens telkėnīs</span>+++

  Lingua Voruvica (Abecedarium Latinum):::
    +++<span lang="vro">Viikogo</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">水體</span>+++

  Lingua Tatarica (/ISO 15924 Zyyy/):::
    +++<span lang="tt">сулык</span>+++

  Lingua Tatarica (Abecedarium Cyrillicum):::
    +++<span lang="tt-cyrl">сулык</span>+++

  Lingua Tatarica (Abecedarium Latinum):::
    +++<span lang="tt-latn">sulıq</span>+++

  Lingua Tagalog (Abecedarium Latinum):::
    +++<span lang="tl">Anyong tubig</span>+++

  Lingua Baschkirica (Abecedarium Cyrillicum):::
    +++<span lang="ba">һыу объекты</span>+++

  Lingua Tschuvaschica (Abecedarium Cyrillicum):::
    +++<span lang="cv">Шывлăх</span>+++

  Lingua Kazachica (Abecedarium Cyrillicum):::
    +++<span lang="kk-cyrl">Бөген</span>+++

  /Central Kurdish/ (Abecedarium Arabicum):::
    +++<span lang="ckb">کۆمای ئاوی</span>+++

  Lingua Cornubica (Abecedarium Latinum):::
    +++<span lang="kw">korf dowr</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">водна површина</span>+++

  Lingua Tadzikica (/ISO 15924 Zyyy/):::
    +++<span lang="tg">Объекти обӣ</span>+++





[id='1_81041']
==== [`1_81041`] Circulus aquae

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q81041[Q81041]

Rēs linguālibus (97)::
  Linguae multiplīs (Scrīptum incognitō):::
    /earth water cycle/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">دورة الماء</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Ջրի շրջապտույտը բնության մեջ</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">পানিচক্র</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Круговорот воды в природе</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">जल चक्र</span>+++

  Lingua Amharica (/ISO 15924 Ethi/):::
    +++<span lang="am">የውሃ ኡደት</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">წყლის წრებრუნვა</span>+++

  Lingua Gujaratensis (/ISO 15924 Gujr/):::
    +++<span lang="gu">જળ ચક્ર</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਜਲ ਚੱਕਰ</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಜಲ ಚಕ್ರ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">물의 순환</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">מחזור המים</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Circulus aquae</span>+++

  Lingua Singhalensis (/ISO 15924 Sinh/):::
    +++<span lang="si">ජල චක්රය</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">நீர் சுழற்சி</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">జలచక్రం</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">วัฏจักรของน้ำ</span>+++

  Lingua Tibetana (Scriptura Tibetana):::
    +++<span lang="bo">ཆུ་ཁམས་འཁོར་སྐྱོད།</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">水循环</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">ciclo hidrológico</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Earth water cycle</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">cycle de l'eau</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">waterkringloop</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Wasserkreislauf</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">ciclo hidrológico</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">ciclo dell'acqua</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">vattnets kretslopp</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">Cikli i Ujit</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">cykl hydrologiczny</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">Veden kiertokulku</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Circuitul apei în natură</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Vòng tuần hoàn nước</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">cicle hidrològic</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">кругообіг води</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Кръговрат на водата</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Kroženje vode</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">vannets kretsløp</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">koloběh vody</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">Vandets kredsløb</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水循環</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">Vasskrinslaupet</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">ജലചംക്രമണം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Siklus air</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">چرخه آب</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">Vízkörforgás</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Uraren zikloa</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">cylchred ddŵr</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Ciclo hidrolóxico</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">Kolobeh vody</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">akva ciklo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">Kitaran air</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">veeringe</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Hidrološki ciklus</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Su döngüsü</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">Cicle de l'aiga</span>+++

  Lingua Britonica (Abecedarium Latinum):::
    +++<span lang="br">Kelc'hiad an dour</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Waterkringloop</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">watter cycle</span>+++

  Lingua Aragonensis (Abecedarium Latinum):::
    +++<span lang="an">Ciclo hidrolochico</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Hringrás vatns</span>+++

  Lingua Limburgica (Abecedarium Latinum):::
    +++<span lang="li">Waterkringloup</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">水循环</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">хидролошки циклус</span>+++

  Lingua Urdu (Abecedarium Arabicum):::
    +++<span lang="ur">آبی چکر</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Hidrologinis ciklas</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Hidrološki ciklus</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">Ūdens cikls</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">hidrološki ciklus</span>+++

  /South Azerbaijani/ (Abecedarium Arabicum):::
    +++<span lang="azb">سو دؤورانی</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">κύκλος του νερού</span>+++

  /Sundanese language/ (Abecedarium Latinum):::
    +++<span lang="su">Daur cai</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">Кругазварот вады</span>+++

  Langobardus sermo (Abecedarium Latinum):::
    +++<span lang="lmo">Ciclo de l'acqua</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">जलचक्र</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">Ciclu hidrolóxicu</span>+++

  /Hakka Chinese/ (/ISO 15924 Zyyy/):::
    +++<span lang="hak">Súi-sùn-fàn</span>+++

  /Min Nan Chinese/ (Abecedarium Latinum):::
    +++<span lang="nan">Chúi sûn-khoân</span>+++

  Lingua Tuluva (/ISO 15924 Zyyy/):::
    +++<span lang="tcy">ಜಲಚಕ್ರ</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">水循環</span>+++

  Macrolingua Suahelica (Abecedarium Latinum):::
    +++<span lang="sw">Dura ya maji</span>+++

  Macrolingua Iudaeo-Germanica (Alphabetum Hebraicum):::
    +++<span lang="yi">וואסער-ציקל</span>+++

  Lingua Tagalog (Abecedarium Latinum):::
    +++<span lang="tl">Pagpapaulit-ulit ng tubig</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">Su dövranı</span>+++

  Lingua Baschkirica (Abecedarium Cyrillicum):::
    +++<span lang="ba">Тәбиғәттә һыу әйләнеше</span>+++

  Lingua Tschuvaschica (Abecedarium Cyrillicum):::
    +++<span lang="cv">Çутçанталăри шыв çаврăмĕ</span>+++

  Lingua creola Haitiana (Abecedarium Latinum):::
    +++<span lang="ht">Sik dlo</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Табиғаттағы су айналымы</span>+++

  /Central Kurdish/ (Abecedarium Arabicum):::
    +++<span lang="ckb">سووڕی ئاو</span>+++

  Lingua Cornubica (Abecedarium Latinum):::
    +++<span lang="kw">Tro Dowroniethel</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">Кружење на водата</span>+++

  Lingua Birmanica (/ISO 15924 Mymr/):::
    +++<span lang="my">ရေ သံသရာလည်ခြင်း</span>+++

  Macrolingua Nepalensis (Devanāgarī):::
    +++<span lang="ne">जलचक्र</span>+++

  Macrolingua Afganica (Abecedarium Arabicum):::
    +++<span lang="ps">د اوبو جريان (د ابو څرخ)</span>+++

  Macrolinguae Quechuae (Abecedarium Latinum):::
    +++<span lang="qu">Yaku muyuriy</span>+++

  Lingua Sindhuica (Abecedarium Arabicum):::
    +++<span lang="sd">آبِي چَڪَرُ</span>+++

  /Shona/ (Abecedarium Latinum):::
    +++<span lang="sn">Nhevedzwa dzeMvura</span>+++





[id='1_102192']
==== [`1_102192`] Aqua dulcis

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q102192[Q102192]

Rēs linguālibus (76)::
  Linguae multiplīs (Scrīptum incognitō):::
    /fresh water/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">ماء عذب</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">স্বাদু পানি</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">пресная вода</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">मीठा जल</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">მტკნარი წყალი</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">민물</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">מים מתוקים</span>+++

  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Aqua dulcis</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">நன்னீர்</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">น้ำจืด</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">淡水</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">água doce</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">fresh water</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">eau douce</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">zoet water</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Süßwasser</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">agua dulce</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">acqua dolce</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">Fionnuisce</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">sötvatten</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Woda słodka</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">Makea vesi</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Apă dulce</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">nước ngọt</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">aigua dolça</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">прісна вода</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Прясна вода</span>+++

  /Waray language/ (Abecedarium Latinum):::
    +++<span lang="war">Tab-áng</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">ferskvann</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">sladká voda</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">Ferskvand</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">淡水</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">ferskvatn</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">air tawar</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">آب شیرین</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">édesvíz</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Ur geza</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Auga doce</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">sladká voda</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">nesala akvo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">Air tawar</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">Magevesi</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Slatka voda</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">tatlı su</span>+++

  Lingua Saxonica (Abecedarium Latinum):::
    +++<span lang="nds">Söötwater</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">Aiga doça</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Varswater</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Séisswaasser</span>+++

  Lingua Scotica quae Teutonica (Abecedarium Latinum):::
    +++<span lang="sco">Fresh watter</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">淡水</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Ferskvatn</span>+++

  Lingua Veneta (Abecedarium Latinum):::
    +++<span lang="vec">àcua dolse</span>+++

  Lingua Scotica seu Scotica Gadelica (Abecedarium Latinum):::
    +++<span lang="gd">fìor-uisge</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">淡水</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">Свјежа вода</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Slatka voda</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">Saldūdens</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Slatka voda</span>+++

  Lingua Iavanica (Abecedarium Latinum):::
    +++<span lang="jv">Banyu tawa</span>+++

  /Sundanese language/ (Abecedarium Latinum):::
    +++<span lang="su">Cai tawar</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Swietwetter</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">Прэсная вада</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">Agua dulce</span>+++

  Lingua Bhojpuri (Devanāgarī):::
    +++<span lang="bho">ताजा पानी</span>+++

  Lingua Iacutica (Abecedarium Cyrillicum):::
    +++<span lang="sah">Ньулуун уу</span>+++

  Lingua Udmurtica (Abecedarium Cyrillicum):::
    +++<span lang="udm">Шӧг ву</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">淡水</span>+++

  Macrolingua Suahelica (Abecedarium Latinum):::
    +++<span lang="sw">Maji matamu</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">İçməli su</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Тұщы көл</span>+++

  Lingua Kazachica (Abecedarium Arabicum):::
    +++<span lang="kk-arab">تۇششى كول</span>+++

  Lingua Kazachica (Abecedarium Cyrillicum):::
    +++<span lang="kk-cyrl">Тұщы көл</span>+++

  Lingua Kazachica (Abecedarium Latinum):::
    +++<span lang="kk-latn">Tuşçı köl</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">питка вода</span>+++

  Lingua Somalica (Abecedarium Latinum):::
    +++<span lang="so">Xareed</span>+++





[id='1_183129']
==== [`1_183129`] /water pollution/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q183129[Q183129]

Rēs linguālibus (73)::
  Linguae multiplīs (Scrīptum incognitō):::
    /water pollution/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">تلوث المياه</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Ջրի աղտոտում</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">পানি দূষণ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">загрязнение пресных вод</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">जल प्रदूषण</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">Water Pollution</span>+++

  Lingua Gujaratensis (/ISO 15924 Gujr/):::
    +++<span lang="gu">પાણીનું પ્રદૂષણ</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਪਾਣੀ ਪ੍ਰ੍ਰ੍ਦਦੁਸ੍ਣ੍</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಜಲ ಮಾಲಿನ್ಯ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">수질 오염</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">זיהום מים</span>+++

  Macrolingua Orissensis (/ISO 15924 Orya/):::
    +++<span lang="or">ଜଳ ପ୍ରଦୂଷଣ</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">நீர் மாசுபாடு</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">నీటి కాలుష్యం</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">มลพิษทางน้ำ</span>+++

  Lingua Sanscrita (/ISO 15924 Zyyy/):::
    +++<span lang="sa">जलमालिन्यम्</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">水污染</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">poluição da água</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">water pollution</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">pollution de l'eau</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">watervervuiling</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Gewässerverschmutzung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">contaminación hídrica</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">inquinamento idrico</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">vattenförorening</span>+++

  Macrolingua Albanica (/Abecedarium Latinum/):::
    +++<span lang="sq">Ndotja e ujit</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">zanieczyszczenia wody</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">Vesien saastuminen</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">poluarea apei</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">ô nhiễm nước</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">contaminació de l'aigua</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">забруднення прісних вод</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">замърсяване на водите</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Onesnaženje voda</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">vannforurensning</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">znečištění vody</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">Vandforurening</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水質汚染</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">vassureining</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">river pollution</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">pencemaran air</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">آلودگی آب</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">Vízszennyezés</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Uraren kutsadura</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Contaminación do medio hídrico</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">akvopoluado</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">Pencemaran air in tamil</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">Veereostus</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">su kirliliği</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Waterbesoedeling</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">水污染</span>+++

  Lingua Vallonica (Abecedarium Latinum):::
    +++<span lang="wa">Mannixhance di l' aiwe</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">水污染</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">загађење воде</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Zagađenje vode</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">Ūdens piesārņojums</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">Ρύπανση των υδάτων</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">जल प्रदूषण</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">Contaminación hídrica</span>+++

  Lingua Bhojpuri (Devanāgarī):::
    +++<span lang="bho">पानी प्रदूषण</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">水質污染</span>+++

  Lingua Tatarica (/ISO 15924 Zyyy/):::
    +++<span lang="tt">суларның пычрануы</span>+++

  Lingua Assamica (/ISO 15924 Beng/):::
    +++<span lang="as">জল প্ৰদূষণ</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">Səth sularının ekocoğrafi problemləri</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Су айдынын ластау</span>+++

  Lingua Kazachica (Abecedarium Arabicum):::
    +++<span lang="kk-arab">سۋ ايدىنىن لاستاۋ</span>+++

  Lingua Kazachica (Abecedarium Cyrillicum):::
    +++<span lang="kk-cyrl">Су айдынын ластау</span>+++

  Lingua Kazachica (Abecedarium Latinum):::
    +++<span lang="kk-latn">Sw aýdının lastaw</span>+++

  /Central Kurdish/ (Abecedarium Arabicum):::
    +++<span lang="ckb">پحسبئنی او</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">Загадување на водата</span>+++

  Macrolingua Afganica (Abecedarium Arabicum):::
    +++<span lang="ps">د اوبو ککړتيا</span>+++

  Lingua Sindhuica (Abecedarium Arabicum):::
    +++<span lang="sd">آبي گدلاڻ</span>+++





[id='1_336191']
==== [`1_336191`] /wastewater/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q336191[Q336191]

Rēs linguālibus (62)::
  Linguae multiplīs (Scrīptum incognitō):::
    /wastewater/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">مياه صرف</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Կեղտաջրեր</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">сточные воды</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">अपजल</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">ჩამდინარე წყალი</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ತ್ಯಾಜ್ಯ ನೀರು</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">폐수</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">שפכים</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">கழிவு நீர்</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">น้ำเสีย</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">污水</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">águas residuais</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">wastewater</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">eaux usées</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">afvalwater</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Abwasser</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">aguas residuales</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">acque reflue</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">avloppsvatten</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">ścieki</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">jätevesi</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Ape uzate</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Nước thải</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">aigües residuals</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Стічні води</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Отходни води</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Odpadne vode</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">avløpsvann</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">odpadní voda</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">spildevand</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">廃水</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">avløpsvatn</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">air limbah</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">پساب</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">Szennyvíz</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Ur zikin</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Augas residuais</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">odpadová voda</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">uzita akvo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">Air kumbahan</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">reovesi</span>+++

  Lingua Occitana (Abecedarium Latinum):::
    +++<span lang="oc">Aigassas</span>+++

  Lingua Luxemburgensis (Abecedarium Latinum):::
    +++<span lang="lb">Ofwaasser</span>+++

  Lingua Bavarica (Abecedarium Latinum):::
    +++<span lang="bar">Obwossa</span>+++

  Macrolingua Sarda (Abecedarium Latinum):::
    +++<span lang="sc">Abas residuales</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">oтпадне воде</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Nuotekos</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Otpadne vode</span>+++

  Lingua Bosnica (Abecedarium Latinum):::
    +++<span lang="bs">Otpadna voda</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Offalwetter</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">Сцёкавыя воды</span>+++

  /Inari Sami/ (Abecedarium Latinum):::
    +++<span lang="smn">tuolvâčääci</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">污水</span>+++

  Lingua Tschuvaschica (Abecedarium Cyrillicum):::
    +++<span lang="cv">Аннă шывсем</span>+++

  Lingua creola Haitiana (Abecedarium Latinum):::
    +++<span lang="ht">Dlo ize</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Ағынды су</span>+++

  Lingua Kyrgyzensis (/ISO 15924 Zyyy/):::
    +++<span lang="ky">Ыплас суулар</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">отпадна вода</span>+++

  Macrolingua Mongolica (Abecedarium Cyrillicum):::
    +++<span lang="mn">Бохир ус</span>+++

  Macrolinguae Quechuae (Abecedarium Latinum):::
    +++<span lang="qu">Q'upa yaku</span>+++

  Lingua Samica septentrionalis (Abecedarium Latinum):::
    +++<span lang="se">duolvačáhci</span>+++





[id='1_506004']
==== [`1_506004`] /tap water/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q506004[Q506004]

Rēs linguālibus (40)::
  Linguae multiplīs (Scrīptum incognitō):::
    /tap water/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">ماء الصنبور</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">টেপ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">водопроводная вода</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">상수도</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">מי ברז</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">குழாய் நீர்</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">น้ำประปา</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">自来水</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">água encanada</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">tap water</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">eau du robinet</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">leidingwater</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Leitungswasser</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">agua de tubería</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">Uisce buacaire</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">kranvatten</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">vesijohtovesi</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Nước máy</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">aigua corrent</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Водопровідна вода</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">kranvann</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">Postevand</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水道水</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">springvatn</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Air keran</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">آب شیر</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Txorrotako ur</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">Aweddwr</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">entuba akvo</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">kraanivesi</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Musluk suyu</span>+++

  Lingua Saxonica (Abecedarium Latinum):::
    +++<span lang="nds">Tappwater</span>+++

  Lingua Bavarica (Abecedarium Latinum):::
    +++<span lang="bar">Ganslwein</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">自來水</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Kranavatn</span>+++

  //Macrolingua Wu// (/ISO 15924 Zyyy/):::
    +++<span lang="wuu">自来水</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">information on rainwater comes and stored likes lakes,rivers,etc.</span>+++

  /Min Nan Chinese/ (Abecedarium Latinum):::
    +++<span lang="nan">Chúi-tō-chúi</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">水喉水</span>+++





[id='1_625376']
==== [`1_625376`] /water quality/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q625376[Q625376]

Rēs linguālibus (40)::
  Linguae multiplīs (Scrīptum incognitō):::
    /water quality/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">جودة المياه</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">পানির গুণমান</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Качество воды</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">수질</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">நீர்த் தரம்</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">水質</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">qualidade da água</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">water quality</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">qualité de l'eau</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">waterkwaliteit</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Gewässergüteklasse</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">calidad del agua</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">vattenkvalitet</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">klasyfikacja jakości wód</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">vedenlaatu</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Calitatea apei</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Chất lượng nước</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">qualitat de l'aigua</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Якість води</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">vannkvalitet</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">vandkvalitet</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水質</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">vasskvalitet</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">ജലഗുണനിലവാരം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Kualitas air</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">کیفیت آب</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">Vízminőség</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">akva kvalito</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">vee kvaliteet</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Kakvoća vode</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Su kalitesi</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">水質</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">квалитет воде</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Kvaliteta vode</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">Ποιότητα του νερού</span>+++

  /Min Nan Chinese/ (Abecedarium Latinum):::
    +++<span lang="nan">Chúi-chit</span>+++

  /Inari Sami/ (Abecedarium Latinum):::
    +++<span lang="smn">čäcikvaliteet</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">квалитет на водата</span>+++

  Lingua Samica septentrionalis (Abecedarium Latinum):::
    +++<span lang="se">čáhcekvalitehta</span>+++





[id='1_1138853']
==== [`1_1138853`] /human right to water and sanitation (HRWS)/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1138853[Q1138853]

Rēs linguālibus (18)::
  Linguae multiplīs (Scrīptum incognitō):::
    /human right to water and sanitation (HRWS)/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">حق المياه</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">הזכות למים ולהיגיינה</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">享有饮水和卫生设施的人权</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Human right to water and sanitation</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">Droit à l'eau</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Recht auf Zugang zu sauberem Wasser</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">Derecho al agua y al saneamiento</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">Diritto all'acqua</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">dreptul la apă</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">വെള്ളത്തിനും ശുചീകരണത്തിനുമുള്ള മനുഷ്യാവകാശം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Hak atas air</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">حق بشری دسترسی به آب و پسابزدایی</span>+++

  Lingua Cambrica (Abecedarium Latinum):::
    +++<span lang="cy">Yr hawl ddynol i ddŵr a glanweithdra</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">人類飲水及衛生設施權力</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">पाण्याचा अधिकार</span>+++

  Lingua Tatarica (/ISO 15924 Zyyy/):::
    +++<span lang="tt">суга хокук</span>+++

  Lingua Haussana (Abecedarium Latinum):::
    +++<span lang="ha">Hakkin Dan'adam Na Ruwa Da Tsafta</span>+++





[id='1_1463025']
==== [`1_1463025`] /water purification/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1463025[Q1463025]

Rēs linguālibus (50)::
  Linguae multiplīs (Scrīptum incognitō):::
    /water purification/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">تنقية المياه</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">পানি পরিশোধন</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Водоочистка</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">ओएअइउफऱखथचट</span>+++

  Lingua Gujaratensis (/ISO 15924 Gujr/):::
    +++<span lang="gu">જળ શુદ્ધિકરણ</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಜಲಶುದ್ಧೀಕರಣ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">정수</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">טיהור מים</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">நீர் தூய்மையாக்கம்</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">నీటి శుద్ధీకరణ</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">水淨化</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Purificação de água</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">water purification</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">purification de l'eau</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">waterzuivering</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Wasseraufbereitung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">tratamiento de agua potable</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">potabilizzazione dell'acqua</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">Vattenrening</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Uzdatnianie wody</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">Purificarea apei potabile</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Lọc sạch nước</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">potabilització</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Очищення природної води</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">Пречистване на водата</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">Prečiščevanje vode</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">Vannrensing</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">čištění vody</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">浄水器</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">ജലശുദ്ധീകരണം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Air bersih</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">تصفیه آب</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">Víztisztítás</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Ur arazte</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">purigo de akvo</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">Pročišćavanje vode</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Su arıtma</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Watersuiwering</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">水淨化</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">Prеčišćavanje vode</span>+++

  Lingua Lithuanica (Abecedarium Latinum):::
    +++<span lang="lt">Vandens gerinimas</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">Pročišćavanje vode</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">Ūdens attīrīšana</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">पाणी शुद्धीकरण</span>+++

  /Min Nan Chinese/ (Abecedarium Latinum):::
    +++<span lang="nan">Chēng-chúi</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">淨水</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">İçməli suyu təmizlənməsi</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Ауыз суды тазарту</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">пречистување на водата</span>+++





[id='1_5376358']
==== [`1_5376358`] /water scarcity/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q5376358[Q5376358]

Rēs linguālibus (40)::
  Linguae multiplīs (Scrīptum incognitō):::
    /water scarcity/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">ندرة المياه</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Ջրի սակավություն</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">পানি ঘাটতি</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">дефицит водных ресурсов</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">Water scarcity</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">물 부족</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">thani pangam</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">anu</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">水荒</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">escassez de água</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">water scarcity</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">stress hydrique (écologie)</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">waterschaarste</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Wasserknappheit</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">escasez de agua</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">mancanza d'acqua</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">vattenbrist</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">niedobór wody</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">vesipula</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Tình trạng thiếu nước (Water scarcity)</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">escassetat d'aigua</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">дефіцит водних ресурсів</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">vannmangel</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">nedostatek vody</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水不足</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">തലക്കുറി നൽകുക</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Kelangkaan air</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">کمبود آب</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">malabundo de akvo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">Kekurangan air</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Su sorunu</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">Water Skaarsheid</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">Несташица воде</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">έλλειψη νερού</span>+++

  Lingua Turcomannica (Abecedarium Latinum):::
    +++<span lang="tk">Suw ýetmezçiligi</span>+++

  Macrolingua Atropatenica (Abecedarium Latinum):::
    +++<span lang="az">Su qıtlığı</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">Недостиг на вода</span>+++

  Macrolingua Afganica (Abecedarium Arabicum):::
    +++<span lang="ps">د اوبو کمښت</span>+++

  Lingua Samica septentrionalis (Abecedarium Latinum):::
    +++<span lang="se">čáhceváili</span>+++





[id='1_6269285']
==== [`1_6269285`] /Joint Monitoring Programme for Water Supply and Sanitation/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q6269285[Q6269285]

Rēs linguālibus (5)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Joint Monitoring Programme for Water Supply and Sanitation/

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">供水及廁所衞生聯合監察報告</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Joint Monitoring Programme for Water Supply and Sanitation</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水供給と衛生のための共同監視プログラム</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">供水與衛生聯合監控方案</span>+++





[id='1_20127660']
==== [`1_20127660`] /wastewater treatment/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q20127660[Q20127660]

Rēs linguālibus (24)::
  Linguae multiplīs (Scrīptum incognitō):::
    /wastewater treatment/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">معالجة المياه العادمة</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">বর্জ্যপানি শোধন</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">கழிவு நீர் மேலாண்மை</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">水污染控制</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">tratamento de águas residuais</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">wastewater treatment</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">traitement des eaux usées</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">rioolwaterzuivering</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Abwasseraufbereitung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">tratamiento de aguas residuales</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">trattamento delle acque reflue</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">oczyszczanie ścieków</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">tractament d'aigües residuals</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">廃水処理</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Pengolahan air limbah</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Hondakin-uren tratamendu</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">Depuración de augas residuais</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">reoveekäitlus</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">Пречишћавање отпадних вода</span>+++

  Macrolingua Lettonica (Abecedarium Latinum):::
    +++<span lang="lv">notekūdeņu attīrīšana</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">Επεξεργασία λυμάτων</span>+++

  Lingua Haussana (Abecedarium Latinum):::
    +++<span lang="ha">Maganin shara a ruwa</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">прочистување на отпадни води</span>+++





[id='1_48741129']
==== [`1_48741129`] /Sustainable Development Goal 6 - clean water and sanitation for all/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q48741129[Q48741129]

Rēs linguālibus (20)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Sustainable Development Goal 6 - clean water and sanitation for all/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">الهدف السادس من أهداف التنمية المستدامة</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Цель 6 - Чистая вода и санитария</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">הבטחת זמינות וניהול בר-קיימא של מים ותברואה לכול</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">目标 6 - 清洁饮用 和环境卫生</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Objetivo de Desenvolvimento Sustentável 6</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Sustainable Development Goal 6</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">Objectif de développement durable no 6 : eau propre et assainissement</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">duurzaam ontwikkelingsdoel 6</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Ziel 6 für nachhaltige Entwicklung - Sauberes Wasser und Sanitärversorgung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">Objetivo de Desarrollo Sostenible 6</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">Globalt mål 6 - Rent vatten och sanitet</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">Objectiu de Desenvolupament Sostenible 6</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Garapen Jasangarrirako 6. helburua: ur garbia eta saneamendua</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">可持續發展目標6</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">Στόχος Βιώσιμης Ανάπτυξης 6</span>+++

  Lingua Tatarica (/ISO 15924 Zyyy/):::
    +++<span lang="tt">Тотрыклы үсеш максаты 6 - Чиста су һәм санитария</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">Цел за одржлив развој 6</span>+++

  Macrolingua Afganica (Abecedarium Arabicum):::
    +++<span lang="ps">شپږمه تلپاتې پرمختیایې موخه</span>+++

  Lingua Samica septentrionalis (Abecedarium Latinum):::
    +++<span lang="se">Buhtes čáhci ja buorit buhtisvuođarusttegat</span>+++





<<<

[id='3491872']
=== [`3491872`] /Improved water source/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q3491872[Q3491872]

Rēs linguālibus (10)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Improved water source/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">مياه الشرب المحسنة</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">মানসম্মত পানির উৎস</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">中国改良饮用水源</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Improved water source</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">source d'eau améliorée</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">Fuente de agua mejorada</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水源改善</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">中國改良飲用水源</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">Подобрено водоснабдување</span>+++





[id='3491872_1049049']
==== [`3491872_1049049`] /Bottled water/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1049049[Q1049049]

Rēs linguālibus (40)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Bottled water/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">مياه معبأة</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">бутилированная вода</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">बोतलबंद पानी</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">병입수</span>+++

  Lingua Santali (/ISO 15924 Olck/):::
    +++<span lang="sat">ᱱᱚᱛᱚᱞ ᱵᱚᱸᱫ ᱫᱟᱜ</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">புட்டித் தண்ணீர்</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">瓶裝水</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Água engarrafada</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">bottled water</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">eau en bouteille</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">flessenwater</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Flaschenwasser</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">agua embotellada</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">acqua in bottiglia</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">flaskvatten</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">woda butelkowana</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">Pullovesi</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">apă plată</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Nước uống đóng chai</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">aigua embotellada</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">бутельована вода</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">flaskevann</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">balená pitná voda</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">flaskevand</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">ボトルウォーター</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">കുപ്പിവെള്ളം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Air botol</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">آب بستهبندیشده</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">palackozott víz</span>+++

  Lingua Vasconica (Abecedarium Latinum):::
    +++<span lang="eu">Botilako ur</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">enbotela akvo</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">Air botol</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Şişelenmiş su</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">瓶裝水</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Flöskuvatn</span>+++

  Lingua Iavanica (Abecedarium Latinum):::
    +++<span lang="jv">Banyu gendul</span>+++

  Lingua Neograeca (Alphabetum Graecum):::
    +++<span lang="el">εμφιαλωμένο νερό</span>+++

  Lingua Asturiana (Abecedarium Latinum):::
    +++<span lang="ast">agua embotellao</span>+++

  Lingua Yue (/ISO 15924 Zyyy/):::
    +++<span lang="yue">樽裝水</span>+++





[id='3491872_2137507']
==== [`3491872_2137507`] /rainwater harvesting/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q2137507[Q2137507]

Rēs linguālibus (28)::
  Linguae multiplīs (Scrīptum incognitō):::
    /rainwater harvesting/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">نظام الحصاد المائي</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">বৃষ্টির পানি সংগ্রহ</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Сбор дождевого стока</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">वर्षा जल संचयन</span>+++

  Lingua Cannadica (/ISO 15924 Knda/):::
    +++<span lang="kn">ಮಳೆನೀರು ಕೊಯ್ಲು</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">빗물 집수</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">மழைநீர் சேகரிப்பு</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">jala samrakshana</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">雨水撲滿</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">rainwater harvesting</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">Récupération de l'eau de pluie</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">Regenput</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Regenwassernutzung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">sistema de captación de agua de lluvias</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">Regnvatteninsamling</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">Sistema de captació d'aigua de pluges</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">sběr dešťové vody</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">雨水収穫</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">മഴവെള്ളസംഭരണം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">pengumpulan air hujan</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">استحصال آب</span>+++

  Macrolingua Malayana (/ISO 15924 Zyyy/):::
    +++<span lang="ms">Penuaian air hujan</span>+++

  Lingua Croatica (Abecedarium Latinum):::
    +++<span lang="hr">kišovodna žetva?</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Yağmur suyu hasadı</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">прикупљање кишнице</span>+++

  Lingua Frisice occidentalis (Abecedarium Latinum):::
    +++<span lang="fy">Reinwettersbak</span>+++

  Lingua Marathica (Devanāgarī):::
    +++<span lang="mr">रेन वॉटर हार्वेस्टिंग</span>+++





<<<

[id='6007834']
=== [`6007834`] /Improved sanitation/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q6007834[Q6007834]

Rēs linguālibus (8)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Improved sanitation/

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">মানসম্মত পয়ঃনিষ্কাশন</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">उन्नत स्वच्छता</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">已改善的衛生設施</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Improved sanitation</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">Saneamiento mejorado</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">現代化廁所裝置</span>+++

  Macrolingua Suahelica (Abecedarium Latinum):::
    +++<span lang="sw">Usafi wa mazingira ulioboreshwa</span>+++





[id='6007834_268534']
==== [`6007834_268534`] /Flush toilet/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q268534[Q268534]

Rēs linguālibus (41)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Flush toilet/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">مرحاض مزود بنظام شطف</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">Զուգարանակոնք</span>+++

  Lingua Bengali (/ISO 15924 Beng/):::
    +++<span lang="bn">ফ্লাশ টয়লেট</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">унитаз</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">प्रधावन शौचालय</span>+++

  Lingua Georgiana (Abecedarium Georgianum):::
    +++<span lang="ka">უნიტაზი</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">수세식 변소</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">מושב אסלה</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">ఫ్లష్ టాయిలెట్</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">抽水馬桶</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">autoclismo</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">flush toilet</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">rinçage des toilettes</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">spoeltoilet</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Spültoilette</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">cisterna de inodoro</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">water</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">vattenklosett</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">muszla klozetowa</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">WC</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Bồn cầu</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">vàter</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Унітаз</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">WC</span>+++

  /Waray language/ (Abecedarium Latinum):::
    +++<span lang="war">Dibuhos nga inidoro</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">Vannklosett</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">splachovací záchod</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">水洗式便所</span>+++

  /Nynorsk/ (Abecedarium Latinum):::
    +++<span lang="nn">vassklosett</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">kloset siram</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">سیفون توالت</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">splachovací záchod</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">akvopelilo</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">Vesiklosett</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Alafranga tuvalet</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">WC шоља</span>+++

  Lingua Iavanica (Abecedarium Latinum):::
    +++<span lang="jv">WC sentor</span>+++

  Lingua Tagalog (Abecedarium Latinum):::
    +++<span lang="tl">Kubeta</span>+++

  Lingua Tschuvaschica (Abecedarium Cyrillicum):::
    +++<span lang="cv">Унитаз</span>+++

  Lingua Sindhuica (Abecedarium Arabicum):::
    +++<span lang="sd">فلش ٽوائليٽ</span>+++





[id='6007834_30894822']
==== [`6007834_30894822`] /Ventilated improved pit latrine/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q30894822[Q30894822]

Rēs linguālibus (4)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Ventilated improved pit latrine/

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Люфт-клозет</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Ventilated improved pit</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Люфт-клозет</span>+++





[id='6007834_178496']
==== [`6007834_178496`] /Composting toilet/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q178496[Q178496]

Rēs linguālibus (27)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Composting toilet/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">مرحاض سمادي</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">Биотуалет</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">कम्पोस्टकारी शौचालय</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">שירותים אקולוגיים</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">உரப்படுத்தல் மலசலகூடம்</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">堆肥式廁所</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">banheiro seco</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">composting toilet</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">Toilettes sèches</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">composttoilet</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Komposttoilette</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">Baño seco ecológico</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">toilette compostante</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">Torrtoalett</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">Toaleta kompostująca</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">Kompostikäymälä</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">Біотуалет</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">Kompostovací toaleta</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">Multtoilet</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">バイオトイレ</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Toilet kompos</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">توالت کودساز</span>+++

  Lingua Slovaca (Abecedarium Latinum):::
    +++<span lang="sk">Kompostovací záchod</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">Kompoŝtiga necesejo</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">Kompost tuvalet</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">Þurrsalerni</span>+++





<<<

[id='7649692']
=== [`7649692`] /Sustainable sanitation/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q7649692[Q7649692]

Rēs linguālibus (7)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Sustainable sanitation/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">استدامة الصرف الصحي</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">可持续卫生设施</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">Saneamento sustentável</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Sustainable sanitation</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">Assainissement durable</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">可持續衛生設施</span>+++





<<<

[id='9999999']
=== [`9999999`] //unimproved sanitation//

Rēs linguālibus (1)::
  Linguae multiplīs (Scrīptum incognitō):::
    //unimproved sanitation//





[id='9999999_5893646']
==== [`9999999_5893646`] /Bucket toilet/ (@TODO: disambiguate QID from Honey bucket)

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q5893646[Q5893646]

Rēs linguālibus (7)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Bucket toilet/ (@TODO: disambiguate QID from Honey bucket)

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">دلو لقضاء الحاجة</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">桶式馬桶</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">Honey bucket</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">Goldeimer</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">肥溜め</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">桶式廁所</span>+++





[id='9999999_3530438']
==== [`9999999_3530438`] /Flying toilet/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q3530438[Q3530438]

Rēs linguālibus (4)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Flying toilet/

  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">المرحاض الطائر</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">flying toilet</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">toilettes volantes</span>+++





[id='9999999_17072861']
==== [`9999999_17072861`] /Open defecation/

Rēs interlinguālibus (1)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q17072861[Q17072861]

Rēs linguālibus (11)::
  Linguae multiplīs (Scrīptum incognitō):::
    /Open defecation/

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">隨地便溺</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">open defecation</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">Défécation en plein air</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">wildpoepen</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">Defecación al aire libre</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">Julkinen ulostaminen</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">Đại tiện ngoài trời</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">屋外排泄</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">Buang air besar sembarangan</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">室外排洩</span>+++






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== [PRECISAMOS DE AJUDA] O PDF gerado não tem as fontes corretas para todos os idiomas

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Primeiro, desculpe se isso afeta seu idioma favorito :(. Estamos trabalhando nisso, mas ainda não estamos aperfeiçoando a geração de livros em tantos idiomas ao mesmo tempo.
    Se você tiver fontes instaladas em seu computador, provavelmente ainda poderá copiar e colar da versão eBook.
    Observe que todos os formatos destinados ao processamento de máquina funcionarão bem.


=== [eBook com Wikidata Q] Quero ajudar! Alguma tradução está faltando ou está errada! Como muda-la?

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    A maioria (mas não todos) os conceitos estão usando o Wikidata Q. Na verdade, na maioria das vezes melhoramos o Wikidata enquanto preparamos os dicionários! Verifique se o conceito exato que você deseja tem um Q ID e clique nele. Lá você pode adicionar traduções.
    A próxima versão (provavelmente semanal) terá seus envios sem a necessidade de nos contatar diretamente.


=== [eBook com Wikidata Q] Posso encontrar o conceito Wikidata, mas não consigo editar!

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Embora o Wikidata seja mais flexível do que o da Wikipedia (por exemplo, permite conceitos sem a necessidade de criar páginas da Wikipedia), mesmo o Wikidata pode ter conceitos que exigem a criação de uma conta e não permitem edição anônima. Criar tal conta e confirmar e-mail é mais rápido do que pedir que outra pessoa faça isso por você.
    No entanto, embora o vandalismo no Wikidata seja raro, muito poucos conceitos exigirão uma conta com mais contribuições e não criada muito recentemente. Se este for o seu caso, ajude com os que você pode fazer sozinho e o resto peça para outra pessoa adicionar a você.


=== Ouvi dizer que há interesse em ter o Cōdex além da língua latina! Como fazer?!

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Por favor, entre em contato conosco. Este livro usa latim (às vezes _latim macarrónico_) para documentar todos os outros idiomas, mas obviamente podemos automatizar a geração de livros para outros usando outros sistemas de escrita e algum idioma de referência. Precisamos de ajuda especial com sistemas de escrita como Bengali, Devanagari e Tamil. Para scripts da direita para a esquerda, apesar de poder renderizar o texto, a impressão do livro exigirá um modelo diferente. Apenas substituir o latim não funcionará, por isso estamos abertos a ideias para proporcionar uma ótima experiência ao usuário!


<<<

