= Cōdex [1603:1:7]: //Dictiōnāria basibus dē rēs interlinguīs//
:doctype: book
:title: Cōdex [1603:1:7]: //Dictiōnāria basibus dē rēs interlinguīs//
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum
:front-cover-image: image:1603_1_7.mul-Latn.codex.svg["Cōdex [1603_1_7]: //Dictiōnāria basibus dē rēs interlinguīs//",1050,1600]




{nbsp} +
{nbsp} +
[quote]
**Dedicação ao Domínio Público significa que cada grande problema comum só precisa ser resolvido uma vez**

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/dictiōnārium ēditōrī/
|
EticaAI

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-01-01

|
numerus editionis
|
2022-06-10T12:26:12

|
/SPDX license ID/@eng-Latn
|
CC0-1.0

|
spōnsor
|
pro bonō publicō

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:1:7]**_ é o formato de livro dos dados estruturados legíveis por máquina do grupo de dicionários _**[1603:1:7] //Dictiōnāria basibus dē rēs interlinguīs//**_, que são distribuídos para os implementadores usarem em aplicativos externos. Este livro pretende ser um recurso avançado para outros lexicógrafos e tradutores de terminologia, inclusive para detectar e relatar inconsistências. Ele pode, no entanto, ser usado como um dicionário ad hoc se não houver trabalho derivado focado em suas necessidades específicas.
    +++<br><br>+++
    **SOBRE LEXICOGRAFIA**
    +++<br><br>+++
    A lexicografia prática é a arte ou ofício de compilar, escrever e editar dicionários. O básico não é muito diferente de um milênio atrás: ainda é um trabalho muito humano e criativo. É preciso ser humilde: a maioria dos erros de tradutores, na verdade, não é culpa do tradutor, mas falhas metodológicas. Certificar-se de uma ideia de origem do que um conceito representa, mesmo que signifique reescrever e simplificar, anexar fotos, mostrar exemplos, fazer o que for para que seja entendido, faz com que até mesmo tradutores não profissionais que se preocupam com sua própria língua entreguem melhor resultados do que qualquer alternativa. Em outras palavras: mesmo as chamadas melhores práticas da indústria de pagar tradutores e revisores profissionais não podem superar termos de origem já mal explicados.
    +++<br><br>+++
    **SOBRE TIPOS DE DICIONÁRIOS QUE ESTAMOS COMPILANDO**
    +++<br><br>+++
    Estamos preocupados com um grupo de idéias (chamamos isso de grupo de dicionários de conceitos) que podem ser divididos em partes menores, revisados quanto a inconsistências, aprimorados para definições e depois traduzidos por voluntários. Códigos interlinguais, como o que poderia ser usado na troca de dados real, também são adicionados a cada conceito. Ambos os glossários, interfaces de usuário (como rótulos na coleta de dados) e, em alguns casos, até códigos padrão para o que iria em um campo de dados podem ser compilados dessa maneira.
    +++<br><br>+++
    Como a lista completa de dicionários-prototípicos e dicionários minimamente utilizáveis é enorme, um modo de citar público-alvos típicos é o seguinte:
    +++<br><br>+++
    . Ajuda humanitária
    . Ajuda ao desenvolvimento
    . Direitos humanos
    . Socorro militar (ou conceitos relacionados a conflitos e resolução de conflitos)
    +++<br><br>+++
    Os itens 1, 2 e 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[são algumas vezes referidos como _nexus_] e são frequentemente encontrados ajudando _crise humanitária_. Já que a maioria dos colaboradores cujas ideias e críticas válidas são voluntárias, então 3 (direitos humanos, como na Anistia Internacional) para diferenciar do humanitarismo (como o Movimento da Cruz Vermelha é referência).
    +++<br><br>+++
    Observe que **dicionários não são guias de uso**. As instruções, quando existem, são principalmente dedicadas a lexicógrafos e tradutores.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    As pessoas lexicógrafas deste trabalho são voluntárias, fazendo-o gratuitamente, pro bonō publicō, e não aceitam doações por causa dos dicionários reutilizáveis ​​de todos. O trabalho anterior existente muitas vezes é baseado em livros antigos de domínio público. A maioria dos tradutores de terminologia já seriam voluntários porque acreditam em uma causa. A melhor maneira de inspirar a colaboração é sermos nós mesmos exemplos.
    +++<br><br>+++
    Há um aspecto não moralista, bastante simples de entender: quão caro seria pagar pelo trabalho de todos considerando que é viável em mais de 200 idiomas? A logística para decidir quem deve ser pago, depois a transferência de dinheiro em todo o mundo (pode incluir pessoas de países embargados), depois os mecanismos tradicionais de auditoria para verificar o uso indevido que os doadores esperam, existe? Em terminologia especial (os próprios termos do dicionário) e tantas línguas, não existe dinheiro suficiente nem humanos interessados ​​em ser coordenadores.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
Rēs interlinguālibus (1)::
  /scope and content/@eng-Latn:::
    This Numerodinatio namespace contains dictionaries related to bare minimum interlingual concepts used to understand Numerodinatio tables.
    +++<br><br>+++
    The decision making is mostly based on what is very essential to explain other tables.



=== Rēs dē factō in dictiōnāriīs
==== Concepta: 57

==== Rēs linguālibus: 2

[%header,cols="15h,25a,~,17"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
lat-Latn
|
https://glottolog.org/resource/languoid/id/lati1261[lati1261]
+++<br>+++
https://iso639-3.sil.org/code/lat[lat]
+++<br>+++ https://www.wikidata.org/wiki/Q397[Q397]
|
Lingua Latina (Abecedarium Latinum)
|
57

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
2

|===

==== Rēs interlinguālibus: 13
Rēs::
  /scope and content/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P7535[P7535]

      ix_hxlix;;
        ix_wdatap7535

      ix_hxlvoc;;
        v_wikidata_p_7535

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/scope and content/@eng-Latn</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        a summary statement providing an overview of the archival collection

      #item+rem+definitionem+i_por+is_latn;;
        uma declaração resumida fornecendo uma visão geral da coleção de arquivo

  /formatter URL/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P1630[P1630]

      ix_hxlix;;
        ix_wdatap1630

      ix_hxlvoc;;
        v_wikidata_p_1630

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/formatter URL/@eng-Latn</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        web page URL; URI template from which "$1" can be automatically replaced with the effective property value on items. If the site goes offline, set it to deprecated rank. If the formatter url changes, add a new statement with preferred rank.

      #item+rem+definitionem+i_por+is_latn;;
        URL da página da web; Modelo de URI a partir do qual "$1" pode ser substituído automaticamente pelo valor efetivo da propriedade nos itens. Se o site ficar offline, defina-o para classificação obsoleta. Se o URL do formatador for alterado, adicione uma nova instrução com classificação preferencial.

  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wdatap2479

      ix_hxlvoc;;
        v_wikidata_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        SPDX license identifier

      #item+rem+definitionem+i_por+is_latn;;
        identificador de licença SPDX

  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wdatap577

      ix_hxlvoc;;
        v_wikidata_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        Date or point in time when a work was first published or released

      #item+rem+definitionem+i_por+is_latn;;
        Data ou ponto no tempo em que um trabalho foi publicado ou lançado pela primeira vez

  /Wiki P/:::
    Rēs interlinguālibus::::
      /rēgulam/;;
        P[1-9]\d*

      ix_hxlix;;
        ix_wdatap

      ix_hxlvoc;;
        v_wiki_p

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/Wiki P/</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        Property (also attribute) describes the data value of a statement and can be thought of as a category of data, for example "color" for the data value "blue". Properties, when paired with values, form a statement in Wikidata. Properties are also used in qualifiers. Properties have their own pages on Wikidata and are connected to items, resulting in a linked data structure.

      #item+rem+definitionem+i_por+is_latn;;
        Propriedade (ou atributo) descreve o valor de dados de uma instrução e pode ser considerada como uma categoria de dados, por exemplo, "cor" para o valor de dados "azul". Propriedades, quando combinadas com valores, formam uma declaração no Wikidata. Propriedades também são usadas em qualificadores. As propriedades têm suas próprias páginas no Wikidata e são conectadas a itens, resultando em uma estrutura de dados vinculada.

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wdatap123

      ix_hxlvoc;;
        v_wikidata_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software

      #item+rem+definitionem+i_por+is_latn;;
        organização ou pessoa responsável pela publicação de livros, periódicos, música impressa, podcasts, jogos ou software

  spōnsor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P859[P859]

      ix_hxlix;;
        ix_wdatap859

      ix_hxlvoc;;
        v_wikidata_p_859

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">spōnsor</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        organization or individual that sponsors this item

      #item+rem+definitionem+i_por+is_latn;;
        organização ou indivíduo que patrocina este item

  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wdatap393

      ix_hxlvoc;;
        v_wikidata_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        number of an edition (first, second, ... as 1, 2, ...) or event

      #item+rem+definitionem+i_por+is_latn;;
        número de uma edição (primeira, segunda, ... como 1, 2, ...) ou evento

  /dictiōnārium ēditōrī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P98[P98]

      ix_hxlix;;
        ix_wdatap98

      ix_hxlvoc;;
        v_wikidata_p_98

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/dictiōnārium ēditōrī/</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        editor of a compiled work such as a book or a periodical (newspaper or an academic journal)

      #item+rem+definitionem+i_por+is_latn;;
        editor de um trabalho compilado, como um livro ou um periódico (jornal ou revista acadêmica)

  /rēgulam/:::
    Rēs interlinguālibus::::
      /Wiki QID/;;
        https://www.wikidata.org/wiki/Q185612[Q185612]

      ix_hxlix;;
        ix_regulam

      ix_hxlvoc;;
        v_regex

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/rēgulam/</span>+++

  /Wiki QID/:::
    Rēs interlinguālibus::::
      /rēgulam/;;
        Q[1-9]\d*

      ix_hxlix;;
        ix_wikiq

      ix_hxlvoc;;
        v_wiki_q

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/Wiki QID/</span>+++

      #item+rem+definitionem+i_eng+is_latn;;
        QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.

      #item+rem+definitionem+i_por+is_latn;;
        QID (ou número Q) é o identificador único de um item de dados no Wikidata, composto pela letra "Q" seguida por um ou mais dígitos. Ele é usado para ajudar pessoas e máquinas a entender a diferença entre itens com nomes iguais ou semelhantes, por exemplo, existem vários lugares no mundo chamados Londres e muitas pessoas chamadas James Smith. Este número aparece ao lado do nome na parte superior de cada item do Wikidata.


<<<

== Archīa

Rēs linguālibus (1)::
  Lingua Anglica (Abecedarium Latinum):::
    **Informações de contexto**: ignorando por um momento o fato de ter várias traduções (e otimizadas para receber contribuições regularmente, não _apenas_ um trabalho estático), então a diferença real no fluxo de trabalho usado para gerar cada grupo de dicionários em um Cōdex como este é o seguinte fato: **fornecemos formatos de arquivos estruturados legíveis por máquina mesmo quando os equivalentes em _idiomas internacionais_, como o inglês, não possuem para áreas como ajuda humanitária, ajuda ao desenvolvimento e direitos humanos**. Os mais próximos desse multilinguismo (fora da Wikimedia) são o SEMIeu da União Europeia (até 24 idiomas), mas mesmo assim têm problemas ao compartilhar traduções em todos os idiomas. As traduções das Nações Unidas (até 6 idiomas, raramente mais) não estão disponíveis por agências humanitárias para ajudar nas traduções de terminologia.
    +++<br><br>+++
    **Implicação prática**: os documentos de texto em _Archīa prō cōdice_ (tradução literal em inglês: _File for book_) são alternativas a este formato de livro que são altamente automatizados usando apenas o formato de dados. No entanto, os formatos legíveis por máquina em _Archīa prō dictiōnāriīs_ (tradução literal em inglês: _Arquivos para dicionários_) são o foco e recomendados para trabalhos derivados e destinados a mitigar erros humanos adicionais. Podemos até criar novos formatos a pedido! O objetivo aqui é permitir tradutores de terminologia e uso de produção onde isso tenha um impacto positivo.


=== Archīa prō dictiōnāriīs: 1


==== 1603_1_7.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_7.no1.tm.hxl.csv[1603_1_7.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio no contêiner HXLTM/



=== Archīa prō cōdice: 2


==== 1603_1_7.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_7.mul-Latn.codex.adoc[1603_1_7.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc é um formato de autoria de texto simples (ou seja, linguagem de marcação leve) para escrever conteúdo técnico, como documentação, artigos e livros.



==== 1603_1_7.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_1_7.mul-Latn.codex.pdf[1603_1_7.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), padronizado como ISO 32000, é um formato de arquivo desenvolvido pela Adobe em 1992 para apresentar documentos, incluindo formatação de texto e imagens, de maneira independente do software aplicativo, hardware e sistemas operacionais.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== //Dictiōnāria basibus dē rēs interlinguīs//
<<<

[id='1']
=== [`1`] /Generic numeric namespace/

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Generic numeric namespace/</span>+++





[id='1_1']
==== [`1_1`] Cōdex factō

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_codexfacto

  ix_hxlvoc:::
    v_codex_facto

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Cōdex factō</span>+++





[id='1_2']
==== [`1_2`] Numerordĭnātĭo

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_n1603

  ix_hxlvoc:::
    v_n1603

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Numerordĭnātĭo</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    a generic strategy of arranging numbers in an taxonomy-like explicit way

  #item+rem+definitionem+i_por+is_latn:::
    uma estratégia genérica de organizar os números de maneira explícita como taxonomia





[id='1_3']
==== [`1_3`] Dictiōnāria

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Dictiōnāria</span>+++





[id='1_4']
==== [`1_4`] Dictiōnāria necessitātibus

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_dctnrnncssttbs

  ix_hxlvoc:::
    v_dictionaria_necessitatibus

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Dictiōnāria necessitātibus</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Dictionaries groups required by this work.

  #item+rem+definitionem+i_por+is_latn:::
    Grupos de dicionários exigidos por este trabalho.





[id='1_91']
==== [`1_91`] /Wiki QID/

Rēs interlinguālibus (3)::
  /rēgulam/:::
    Q[1-9]\d*

  ix_hxlix:::
    ix_wikiq

  ix_hxlvoc:::
    v_wiki_q

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Wiki QID/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.

  #item+rem+definitionem+i_por+is_latn:::
    QID (ou número Q) é o identificador único de um item de dados no Wikidata, composto pela letra "Q" seguida por um ou mais dígitos. Ele é usado para ajudar pessoas e máquinas a entender a diferença entre itens com nomes iguais ou semelhantes, por exemplo, existem vários lugares no mundo chamados Londres e muitas pessoas chamadas James Smith. Este número aparece ao lado do nome na parte superior de cada item do Wikidata.





[id='1_92']
==== [`1_92`] /Wiki P/

Rēs interlinguālibus (3)::
  /rēgulam/:::
    P[1-9]\d*

  ix_hxlix:::
    ix_wdatap

  ix_hxlvoc:::
    v_wiki_p

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Wiki P/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Property (also attribute) describes the data value of a statement and can be thought of as a category of data, for example "color" for the data value "blue". Properties, when paired with values, form a statement in Wikidata. Properties are also used in qualifiers. Properties have their own pages on Wikidata and are connected to items, resulting in a linked data structure.

  #item+rem+definitionem+i_por+is_latn:::
    Propriedade (ou atributo) descreve o valor de dados de uma instrução e pode ser considerada como uma categoria de dados, por exemplo, "cor" para o valor de dados "azul". Propriedades, quando combinadas com valores, formam uma declaração no Wikidata. Propriedades também são usadas em qualificadores. As propriedades têm suas próprias páginas no Wikidata e são conectadas a itens, resultando em uma estrutura de dados vinculada.





[id='1_93']
==== [`1_93`] /Wiki LID/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_wikil

  ix_hxlvoc:::
    v_wiki_l

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Wiki LID/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    LID (or L number) The identifier for a lexeme entity in Wikidata, comprising the letter "L" followed by one or more digits.

  #item+rem+definitionem+i_por+is_latn:::
    LID (ou número L) O identificador de uma entidade lexema no Wikidata, compreendendo a letra "L" seguida por um ou mais dígitos.





[id='1_95']
==== [`1_95`] /rēgulam/

Rēs interlinguālibus (3)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q185612[Q185612]

  ix_hxlix:::
    ix_regulam

  ix_hxlvoc:::
    v_regex

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/rēgulam/</span>+++





[id='1_96']
==== [`1_96`] //Cōdex annotātiōnibus internālibus//

Rēs interlinguālibus (1)::
  ix_hxlix:::
    ix_n1603ia

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//Cōdex annotātiōnibus internālibus//</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Internal annotations of a codex. List of items. Used on 1603_1_1 as undocumented tags to manage how dictionaries are exported

  #item+rem+definitionem+i_por+is_latn:::
    Anotações internas de um códice. Lista de itens. Usado em 1603_1_1 como tags não documentadas para gerenciar como os dicionários são exportados





[id='1_97']
==== [`1_97`] //opus papȳrō ex 1603//

Rēs interlinguālibus (1)::
  ix_hxlix:::
    ix_n1603op

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//opus papȳrō ex 1603//</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Worksheet index used on 1603_1_1 as undocumented feature to manage where the main table should be extracted

  #item+rem+definitionem+i_por+is_latn:::
    Índice de planilha usado em 1603_1_1 como recurso não documentado para gerenciar onde a tabela principal deve ser extraída





[id='1_200']
==== [`1_200`] /HXL Standard, hashtag, base tab, or attribute (but not readable header)/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_hxl

  ix_hxlvoc:::
    v_hxl

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/HXL Standard, hashtag, base tab, or attribute (but not readable header)/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    /HXL Standard, hashtag, base tag, or attribute (except CSV heading, if any)/

  #item+rem+definitionem+i_por+is_latn:::
    /Padrão HXL, hashtag, tag base ou atributo (exceto cabeçalho CSV, se houver)/





[id='1_201']
==== [`1_201`] /HXL Standard, full hashtag/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_hxlhstg

  ix_hxlvoc:::
    v_hxl_hashtag

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/HXL Standard, full hashtag/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    /HXL Standard, full hashtag/

  #item+rem+definitionem+i_por+is_latn:::
    /HXL Padrão, hashtag completa/





[id='1_202']
==== [`1_202`] /HXL Standard, human readable header (lat: caput)/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_hxlcpt

  ix_hxlvoc:::
    v_hxl_caput

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/HXL Standard, human readable header (lat: caput)/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    /HXL Standard, CSV heading, if any (/caput/@lat-Latn)/

  #item+rem+definitionem+i_por+is_latn:::
    /Padrão HXL, cabeçalho CSV, se houver (/caput/@lat-Latn)/





[id='1_203']
==== [`1_203`] /HXL Standard, base hashtag only/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_hxlt

  ix_hxlvoc:::
    v_hxl_t

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/HXL Standard, base hashtag only/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    /HXL Standard, base hashtag only/

  #item+rem+definitionem+i_por+is_latn:::
    /Padrão HXL, somente hashtag base/





[id='1_204']
==== [`1_204`] /HXL Standard, attributes only/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_hxla

  ix_hxlvoc:::
    v_hxl_a

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/HXL Standard, attributes only/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    /HXL Standard, attributes only/

  #item+rem+definitionem+i_por+is_latn:::
    /Padrão HXL, somente atributos/





[id='1_205']
==== [`1_205`] /Normalized CSV-like header; full header, only prefix or only suffix/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_csv

  ix_hxlvoc:::
    v_csv

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Normalized CSV-like header; full header, only prefix or only suffix/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    /Normalized CSV-like header; full header, or only prefix, or only suffix/

  #item+rem+definitionem+i_por+is_latn:::
    /Cabeçalho tipo CSV normalizado; cabeçalho completo, ou apenas prefixo, ou apenas sufixo/





[id='1_206']
==== [`1_206`] /Normalized CSV-like identifier; prefix affinity (lat: praefīxum)/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_csvprfxu

  ix_hxlvoc:::
    v_csv_praefixum

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Normalized CSV-like identifier; prefix affinity (lat: praefīxum)/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    /Normalized CSV-like identifier; prefix affinity (/praefīxum/@lat-Latn)/

  #item+rem+definitionem+i_por+is_latn:::
    /Identificador tipo CSV normalizado; afinidade de prefixo (/praefīxum/@lat-Latn)/





[id='1_207']
==== [`1_207`] /Normalized CSV-like identifier; suffix affinity (lat: suffīxum)/

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_csvsffxm

  ix_hxlvoc:::
    v_csv_suffixum

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Normalized CSV-like identifier; suffix affinity (lat: suffīxum)/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    /Normalized CSV-like identifier; suffix affinity (/suffīxum/@lat-Latn)/

  #item+rem+definitionem+i_por+is_latn:::
    /Identificador tipo CSV normalizado; afinidade de sufixo (/suffīxum/@lat-Latn)/





[id='1_208']
==== [`1_208`] /GLIDE hazard code/

Rēs interlinguālibus (1)::
  ix_hxlix:::
    ix_glidehc

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/GLIDE hazard code/</span>+++





[id='1_209']
==== [`1_209`] /Cadastro Nacional de Estabelecimentos de Saúde (CNES); Brasil/@por-Latn

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_v76vcnes

  ix_hxlvoc:::
    v_76_cnes

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Cadastro Nacional de Estabelecimentos de Saúde (CNES); Brasil/@por-Latn</span>+++





<<<

[id='2616']
=== [`2616`] /Wikidata P local numeric namespace/

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Wikidata P local numeric namespace/</span>+++





[id='2616_17']
==== [`2616_17`] civitas

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P17[P17]

  ix_hxlix:::
    ix_wdatap17

  ix_hxlvoc:::
    v_wikidata_p_17

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">civitas</span>+++





[id='2616_50']
==== [`2616_50`] scrīptor

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P50[P50]

  ix_hxlix:::
    ix_wdatap50

  ix_hxlvoc:::
    v_wikidata_p_50

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">scrīptor</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Main creator(s) of a written work (use on works, not humans)

  #item+rem+definitionem+i_por+is_latn:::
    Principais criadores de uma obra escrita (uso em obras, não em humanos)





[id='2616_98']
==== [`2616_98`] /dictiōnārium ēditōrī/

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P98[P98]

  ix_hxlix:::
    ix_wdatap98

  ix_hxlvoc:::
    v_wikidata_p_98

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/dictiōnārium ēditōrī/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    editor of a compiled work such as a book or a periodical (newspaper or an academic journal)

  #item+rem+definitionem+i_por+is_latn:::
    editor de um trabalho compilado, como um livro ou um periódico (jornal ou revista acadêmica)





[id='2616_110']
==== [`2616_110`] pictor

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P110[P110]

  ix_hxlix:::
    ix_wdatap110

  ix_hxlvoc:::
    v_wikidata_p_110

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">pictor</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Person drawing the pictures or taking the photographs in a book

  #item+rem+definitionem+i_por+is_latn:::
    Pessoa que desenhou as ilustrações ou tirou as fotos em um livro





[id='2616_123']
==== [`2616_123`] /cōdex pūblicandī/

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P123[P123]

  ix_hxlix:::
    ix_wdatap123

  ix_hxlvoc:::
    v_wikidata_p_123

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/cōdex pūblicandī/</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software

  #item+rem+definitionem+i_por+is_latn:::
    organização ou pessoa responsável pela publicação de livros, periódicos, música impressa, podcasts, jogos ou software





[id='2616_131']
==== [`2616_131`] procuratio superior

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P131[P131]

  ix_hxlix:::
    ix_wdatap131

  ix_hxlvoc:::
    v_wikidata_p_131

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">procuratio superior</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    the item is located on the territory of the following administrative entity. Use P276 for specifying locations that are non-administrative places and for items about events. Use P1382 if the item falls only partially into the administrative entity

  #item+rem+definitionem+i_por+is_latn:::
    o item situa-se no território da seguinte unidade administrativa





[id='2616_393']
==== [`2616_393`] numerus editionis

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P393[P393]

  ix_hxlix:::
    ix_wdatap393

  ix_hxlvoc:::
    v_wikidata_p_393

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">numerus editionis</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    number of an edition (first, second, ... as 1, 2, ...) or event

  #item+rem+definitionem+i_por+is_latn:::
    número de uma edição (primeira, segunda, ... como 1, 2, ...) ou evento





[id='2616_487']
==== [`2616_487`] //unicodex pūnctō//

Rēs interlinguālibus (4)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P487[P487]

  /formatter URL/@eng-Latn:::
    https://util.unicode.org/UnicodeJsps/character.jsp?a=$1

  ix_hxlix:::
    ix_wdatap487

  ix_hxlvoc:::
    v_wikidata_p_487

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">//unicodex pūnctō//</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Unicode character representing the item

  #item+rem+definitionem+i_por+is_latn:::
    Caractere Unicode que representa o item





[id='2616_577']
==== [`2616_577`] /publication date/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P577[P577]

  ix_hxlix:::
    ix_wdatap577

  ix_hxlvoc:::
    v_wikidata_p_577

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/publication date/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Date or point in time when a work was first published or released

  #item+rem+definitionem+i_por+is_latn:::
    Data ou ponto no tempo em que um trabalho foi publicado ou lançado pela primeira vez





[id='2616_655']
==== [`2616_655`] /translator/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P655[P655]

  ix_hxlix:::
    ix_wdatap655

  ix_hxlvoc:::
    v_wikidata_p_655

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/translator/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    agent who adapts any kind of written text from one language to another

  #item+rem+definitionem+i_por+is_latn:::
    agente que adapta qualquer tipo de texto escrito de um idioma para outro





[id='2616_854']
==== [`2616_854`] /reference URL/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P854[P854]

  ix_hxlix:::
    ix_wdatap854

  ix_hxlvoc:::
    v_wikidata_p_854

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/reference URL/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    should be used for Internet URLs as references

  #item+rem+definitionem+i_por+is_latn:::
    deve ser usado para URLs da Internet como referências





[id='2616_856']
==== [`2616_856`] /official website/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P856[P856]

  ix_hxlix:::
    ix_wdatap856

  ix_hxlvoc:::
    v_wikidata_p_856

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/official website/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    URL of the official page of an item (current or former) [if the page changes, add an additional statement with preferred rank. Do not remove the former URL]

  #item+rem+definitionem+i_por+is_latn:::
    URL da página oficial de um item (atual ou anterior) [se a página mudar, adicione uma declaração adicional com classificação preferencial. Não remova o URL anterior]





[id='2616_859']
==== [`2616_859`] spōnsor

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P859[P859]

  ix_hxlix:::
    ix_wdatap859

  ix_hxlvoc:::
    v_wikidata_p_859

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">spōnsor</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    organization or individual that sponsors this item

  #item+rem+definitionem+i_por+is_latn:::
    organização ou indivíduo que patrocina este item





[id='2616_1448']
==== [`2616_1448`] nomen officiale

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P1448[P1448]

  ix_hxlix:::
    ix_wdatap1448

  ix_hxlvoc:::
    v_wikidata_p_1448

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">nomen officiale</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    official name of the subject in its official language(s)

  #item+rem+definitionem+i_por+is_latn:::
    nome oficial do sujeito em sua língua oficial





[id='2616_1476']
==== [`2616_1476`] titulus

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P1476[P1476]

  ix_hxlix:::
    ix_wdatap1476

  ix_hxlvoc:::
    v_wikidata_p_1476

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">titulus</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    published name of a work, such as a newspaper article, a literary work, piece of music, a website, or a performance work

  #item+rem+definitionem+i_por+is_latn:::
    nome publicado de uma obra, como um artigo de jornal, uma obra literária, uma peça musical, um site ou uma obra performática





[id='2616_1323']
==== [`2616_1323`] Terminologia Anatomica 98 ID

Rēs interlinguālibus (5)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P1323[P1323]

  /rēgulam/:::
    A\d{2}\.\d\.\d{2}\.\d{3}[FM]?

  /formatter URL/@eng-Latn:::
    https://wikidata-externalid-url.toolforge.org/?p=1323&url_prefix=https:%2F%2Fwww.unifr.ch%2Fifaa%2FPublic%2FEntryPage%2FTA98%20Tree%2FEntity%20TA98%20EN%2F&url_suffix=%20Entity%20TA98%20EN.htm&id=$1

  ix_hxlix:::
    ix_wdatap1323

  ix_hxlvoc:::
    v_wikidata_p_1323

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">Terminologia Anatomica 98 ID</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Terminologia Anatomica (1998 edition) human anatomical terminology identifier

  #item+rem+definitionem+i_por+is_latn:::
    Terminologia Anatomica (edição de 1998) identificador de terminologia anatômica humana





[id='2616_1324']
==== [`2616_1324`] /source code repository/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P1324[P1324]

  ix_hxlix:::
    ix_wdatap1324

  ix_hxlvoc:::
    v_wikidata_p_1324

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/source code repository/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    public source code repository

  #item+rem+definitionem+i_por+is_latn:::
    repositório público de código fonte





[id='2616_1585']
==== [`2616_1585`] /código de município brasileiro do IBGE/@por-Latn

Rēs interlinguālibus (4)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P1585[P1585]

  /rēgulam/:::
    \d{7}

  ix_hxlix:::
    ix_wdatap1585

  ix_hxlvoc:::
    v_wikidata_p_1585

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/código de município brasileiro do IBGE/@por-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    identifier for municipalities in Brazil

  #item+rem+definitionem+i_por+is_latn:::
    Código do Município do IBGE, Instituto Brasileiro de Geografia e Estatística





[id='2616_1630']
==== [`2616_1630`] /formatter URL/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P1630[P1630]

  ix_hxlix:::
    ix_wdatap1630

  ix_hxlvoc:::
    v_wikidata_p_1630

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/formatter URL/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    web page URL; URI template from which "$1" can be automatically replaced with the effective property value on items. If the site goes offline, set it to deprecated rank. If the formatter url changes, add a new statement with preferred rank.

  #item+rem+definitionem+i_por+is_latn:::
    URL da página da web; Modelo de URI a partir do qual "$1" pode ser substituído automaticamente pelo valor efetivo da propriedade nos itens. Se o site ficar offline, defina-o para classificação obsoleta. Se o URL do formatador for alterado, adicione uma nova instrução com classificação preferencial.





[id='2616_1813']
==== [`2616_1813`] nomen breve

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P1813[P1813]

  ix_hxlix:::
    ix_wdatap1813

  ix_hxlvoc:::
    v_wikidata_p_1813

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">nomen breve</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    short name of a place, organisation, person, journal, Wikidata property, et

  #item+rem+definitionem+i_por+is_latn:::
    nome de referência curto de uma lugar, organização, pessoa, etc.





[id='2616_1889']
==== [`2616_1889`] /different from/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P1889[P1889]

  ix_hxlix:::
    ix_wdatap1889

  ix_hxlvoc:::
    v_wikidata_p_1889

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/different from/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    item that is different from another item, with which it may be confused

  #item+rem+definitionem+i_por+is_latn:::
    item diferente de outro item, com o qual pode ser confundido





[id='2616_2479']
==== [`2616_2479`] /SPDX license ID/@eng-Latn

Rēs interlinguālibus (5)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P2479[P2479]

  /rēgulam/:::
    [0-9A-Za-z\.\-]{3,36}[+]?

  /formatter URL/@eng-Latn:::
    https://spdx.org/licenses/$1.html

  ix_hxlix:::
    ix_wdatap2479

  ix_hxlvoc:::
    v_wikidata_p_2479

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    SPDX license identifier

  #item+rem+definitionem+i_por+is_latn:::
    identificador de licença SPDX





[id='2616_2699']
==== [`2616_2699`] URL

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P2699[P2699]

  ix_hxlix:::
    ix_wdatap2699

  ix_hxlvoc:::
    v_wikidata_p_2699

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">URL</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    location of a resource

  #item+rem+definitionem+i_por+is_latn:::
    localização de um recurso





[id='2616_3575']
==== [`2616_3575`] /data size/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P3575[P3575]

  ix_hxlix:::
    ix_wdatap3575

  ix_hxlvoc:::
    v_wikidata_p_3575

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/data size/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    size of a software, dataset, neural network, or individual file

  #item+rem+definitionem+i_por+is_latn:::
    tamanho de um software, conjunto de dados, rede neural ou arquivo individual





[id='2616_3916']
==== [`2616_3916`] UNESCO thēsaurus

Rēs interlinguālibus (5)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P3916[P3916]

  /rēgulam/:::
    concept[1-9]\d*

  /formatter URL/@eng-Latn:::
    http://vocabularies.unesco.org/thesaurus/$1

  ix_hxlix:::
    ix_wdatap3916

  ix_hxlvoc:::
    v_wikidata_p_3916

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">UNESCO thēsaurus</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    The UNESCO Thesaurus is a controlled and structured list of terms used in subject analysis and retrieval of documents and publications in the fields of education, culture, natural sciences, social and human sciences, communication and information. Continuously enriched and updated, its multidisciplinary terminology reflects the evolution of UNESCO's programmes and activities.

  #item+rem+definitionem+i_por+is_latn:::
    O Thesaurus da UNESCO é uma lista controlada e estruturada de termos usados na análise de assuntos e recuperação de documentos e publicações nas áreas de educação, cultura, ciências naturais, ciências sociais e humanas, comunicação e informação. Continuamente enriquecida e atualizada, sua terminologia multidisciplinar reflete a evolução dos programas e atividades da UNESCO.





[id='2616_3982']
==== [`2616_3982`] /Terminologia Anatomica 98 Latin preferred term/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P3982[P3982]

  ix_hxlix:::
    ix_wdatap3982

  ix_hxlvoc:::
    v_wikidata_p_3982

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Terminologia Anatomica 98 Latin preferred term/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Latin name for anatomical subject as described in Terminologia Anatomica 98

  #item+rem+definitionem+i_por+is_latn:::
    Nome em latim para assunto anatômico conforme descrito em Terminologia Anatomica 98





[id='2616_4354']
==== [`2616_4354`] /search formatter URL/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P4354[P4354]

  ix_hxlix:::
    ix_wdatap4354

  ix_hxlvoc:::
    v_wikidata_p_4354

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/search formatter URL/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    web page search URL; URI template from which "$1" can be automatically replaced with the string to be searched for. $1 can be whatever you want.

  #item+rem+definitionem+i_por+is_latn:::
    URL de pesquisa de página da web; Modelo de URI a partir do qual "$1" pode ser substituído automaticamente pela string a ser pesquisada. $1 pode ser o que você quiser.





[id='2616_4945']
==== [`2616_4945`] /download link/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P4945[P4945]

  ix_hxlix:::
    ix_wdatap4945

  ix_hxlvoc:::
    v_wikidata_p_4945

Rēs linguālibus (2)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/download link/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    URL which can be used to download a work





[id='2616_5185']
==== [`2616_5185`] genus grammaticum

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P5185[P5185]

  ix_hxlix:::
    ix_wdatap5185

  ix_hxlvoc:::
    v_wikidata_p_5185

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">genus grammaticum</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    grammatical gender of the word

  #item+rem+definitionem+i_por+is_latn:::
    Gênero gramatical da palavra





[id='2616_6204']
==== [`2616_6204`] CNPJ (brasīliēnsī)

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P6204[P6204]

  ix_hxlix:::
    ix_wdatap6204

  ix_hxlvoc:::
    v_wikidata_p_6204

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">CNPJ (brasīliēnsī)</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    identification number issued to Brazilian companies by the Secretariat of the Federal Revenue of Brazil

  #item+rem+definitionem+i_por+is_latn:::
    Cadastro Nacional da Pessoa Jurídica (Brasil)





[id='2616_7470']
==== [`2616_7470`] /URN formatter/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P7470[P7470]

  ix_hxlix:::
    ix_wdatap7470

  ix_hxlvoc:::
    v_wikidata_p_7470

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/URN formatter/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    formatter to generate Uniform Resource Name (URN) from property value. Include $1 to be replaced with property value

  #item+rem+definitionem+i_por+is_latn:::
    formatador para gerar o Uniform Resource Name (URN) a partir do valor da propriedade. Incluir $ 1 a ser substituído pelo valor da propriedade





[id='2616_7535']
==== [`2616_7535`] /scope and content/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki P/:::
    https://www.wikidata.org/wiki/Property:P7535[P7535]

  ix_hxlix:::
    ix_wdatap7535

  ix_hxlvoc:::
    v_wikidata_p_7535

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/scope and content/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    a summary statement providing an overview of the archival collection

  #item+rem+definitionem+i_por+is_latn:::
    uma declaração resumida fornecendo uma visão geral da coleção de arquivo





<<<

[id='2617']
=== [`2617`] /Wikidata Q local numeric namespace/@eng-Latn

Rēs interlinguālibus (2)::
  ix_hxlix:::
    ix_wikiq9289584

  ix_hxlvoc:::
    v_wiki_q_9289584

Rēs linguālibus (1)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/Wikidata Q local numeric namespace/@eng-Latn</span>+++





[id='2617_355217']
==== [`2617_355217`] /to-do list/@eng-Latn

Rēs interlinguālibus (3)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q355217[Q355217]

  ix_hxlix:::
    ix_wikiq355217

  ix_hxlvoc:::
    v_wiki_q_355217

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">/to-do list/@eng-Latn</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    time management - procedures to process pending tasks and appointments within the available period

  #item+rem+definitionem+i_por+is_latn:::
    gestão do tempo - procedimentos para processar tarefas pendentes e compromissos dentro do período disponível





[id='2617_9289584']
==== [`2617_9289584`] caveat lector

Rēs interlinguālibus (3)::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q9289584[Q9289584]

  ix_hxlix:::
    ix_wikiq9289584

  ix_hxlvoc:::
    v_wiki_q_9289584

Rēs linguālibus (3)::
  Lingua Latina (Abecedarium Latinum):::
    +++<span lang="la">caveat lector</span>+++

  #item+rem+definitionem+i_eng+is_latn:::
    Caveat lector is a Latin phrase meaning "let the reader beware"

  #item+rem+definitionem+i_por+is_latn:::
    Caveat lector é uma expressão em língua latina que pode ser traduzida como "alerta ao leitor"






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== [PRECISAMOS DE AJUDA] O PDF gerado não tem as fontes corretas para todos os idiomas

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Primeiro, desculpe se isso afeta seu idioma favorito :(. Estamos trabalhando nisso, mas ainda não estamos aperfeiçoando a geração de livros em tantos idiomas ao mesmo tempo.
    Se você tiver fontes instaladas em seu computador, provavelmente ainda poderá copiar e colar da versão eBook.
    Observe que todos os formatos destinados ao processamento de máquina funcionarão bem.


=== [eBook com Wikidata Q] Quero ajudar! Alguma tradução está faltando ou está errada! Como muda-la?

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    A maioria (mas não todos) os conceitos estão usando o Wikidata Q. Na verdade, na maioria das vezes melhoramos o Wikidata enquanto preparamos os dicionários! Verifique se o conceito exato que você deseja tem um Q ID e clique nele. Lá você pode adicionar traduções.
    A próxima versão (provavelmente semanal) terá seus envios sem a necessidade de nos contatar diretamente.


=== [eBook com Wikidata Q] Posso encontrar o conceito Wikidata, mas não consigo editar!

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Embora o Wikidata seja mais flexível do que o da Wikipedia (por exemplo, permite conceitos sem a necessidade de criar páginas da Wikipedia), mesmo o Wikidata pode ter conceitos que exigem a criação de uma conta e não permitem edição anônima. Criar tal conta e confirmar e-mail é mais rápido do que pedir que outra pessoa faça isso por você.
    No entanto, embora o vandalismo no Wikidata seja raro, muito poucos conceitos exigirão uma conta com mais contribuições e não criada muito recentemente. Se este for o seu caso, ajude com os que você pode fazer sozinho e o resto peça para outra pessoa adicionar a você.


=== Ouvi dizer que há interesse em ter o Cōdex além da língua latina! Como fazer?!

Rēs linguālibus::
  Lingua Lusitana (Abecedarium Latinum):::
    Por favor, entre em contato conosco. Este livro usa latim (às vezes _latim macarrónico_) para documentar todos os outros idiomas, mas obviamente podemos automatizar a geração de livros para outros usando outros sistemas de escrita e algum idioma de referência. Precisamos de ajuda especial com sistemas de escrita como Bengali, Devanagari e Tamil. Para scripts da direita para a esquerda, apesar de poder renderizar o texto, a impressão do livro exigirá um modelo diferente. Apenas substituir o latim não funcionará, por isso estamos abertos a ideias para proporcionar uma ótima experiência ao usuário!


<<<

