= Cōdex [1603:3:12:6]: //Speciālis collēctiōnī de Vicidata Proprietātī//
:doctype: book
:title: Cōdex [1603:3:12:6]: //Speciālis collēctiōnī de Vicidata Proprietātī//
:lang: la
:toc:
:toclevels: 4
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum




{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

<<<
toc::[]


[id=0_999_1603_1]
== Praefātiō 

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
_**Cōdex [1603:3:12:6]**_ is the book format of the machine-readable dictionaries _**[1603:3:12:6] //Speciālis collēctiōnī de Vicidata Proprietātī//**_, which are distributed for implementers on external applications. This book is intended as advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies.

Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.

The initiative behind this compilation is also doing other dictionaries and accepts new suggestions of relevant topics on data exchange for humanitarian use. All have in common the fact that both have human translations and (if any) external interlingual codes related to each concept while making the end result explicitly already ready to be usable on average softwares. Naturally, each book version gives extensive explanations for collaborators on how to correct itself which become part of the next weekly release.

|===


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
numerus editionis
|
2022-02-22T23:11:59

|===


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Rēs dē factō in dictiōnāriīs
==== Concepta: 43
==== Rēs interlinguālibus: 3
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
The result of this section is a preview. We're aware it is not well formatted for a book format. Sorry for the temporary inconvenience.

|===


**1603:1:7:1:92**

[source,json]
----
{
    "#item+conceptum+codicem": "1_92",
    "#item+conceptum+numerordinatio": "1603:1:7:1:92",
    "#item+rem+definitionem+i_eng+is_latn": "Property (also attribute) describes the data value of a statement and can be thought of as a category of data, for example \"color\" for the data value \"blue\". Properties, when paired with values, form a statement in Wikidata. Properties are also used in qualifiers. Properties have their own pages on Wikidata and are connected to items, resulting in a linked data structure.",
    "#item+rem+i_lat+is_latn": "/Wiki P/",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p",
    "#item+rem+i_qcc+is_zxxx+ix_regulam": "P[1-9]\\d*",
    "#status+conceptum+codicem": "19",
    "#status+conceptum+definitionem": "50"
}
----

**1603:1:7:2616:393**

[source,json]
----
{
    "#item+conceptum+codicem": "2616_393",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:393",
    "#item+rem+definitionem+i_eng+is_latn": "number of an edition (first, second, ... as 1, 2, ...) or event",
    "#item+rem+i_lat+is_latn": "numerus editionis",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip393",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_393",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P393",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

**1603:1:7:2616:854**

[source,json]
----
{
    "#item+conceptum+codicem": "2616_854",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:854",
    "#item+rem+definitionem+i_eng+is_latn": "should be used for Internet URLs as references",
    "#item+rem+i_lat+is_latn": "/reference URL/@eng-Latn",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip854",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_854",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P854",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

<<<

== Archīa


[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
Every book comes with several files both for book format (with (Abecedarium additional information) and machine-readable formats with Latinum) documentation of how to process them. If you receive this file and cannot find the alternatives, ask the human who provide this file.

|===

=== Archīa prō dictiōnāriīs: 1

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
TIP: Is recommended to use the files on this section to  generate derived works.

|===


==== 1603_3_12_6.no1.tm.hxl.csv

NOTE: link:1603_3_12_6.no1.tm.hxl.csv[1603_3_12_6.no1.tm.hxl.csv]

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
/Numerordinatio on HXLTM container/

|===


=== Archīa prō cōdice: 2

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
WARNING: Unless you are working with a natural language you understand it\'s letters and symbols, it is strongly advised to use automation to generate derived works. Keep manual human steps at minimum: if something goes wrong at least one or more languages can be used to verify mistakes. It's not at all necessary _know all languages_, but working with writing systems you don't understand is risky: copy and paste strategy can cause _additional_ human errors and is unlikely to get human review as fast as you would need.

|
Lingua Anglica (Abecedarium Latinum)
|
TIP: The Asciidoctor (.adoc) is better at copy and pasting! It can be converted to other text formats.

|===


==== 1603_3_12_6.mul-Latn.codex.adoc

NOTE: link:1603_3_12_6.mul-Latn.codex.adoc[1603_3_12_6.mul-Latn.codex.adoc]


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/reference URL/@eng-Latn
|
https://asciidoctor.org/docs/

|===


==== 1603_3_12_6.mul-Latn.codex.pdf

NOTE: link:1603_3_12_6.mul-Latn.codex.pdf[1603_3_12_6.mul-Latn.codex.pdf]


<<<

== //Speciālis collēctiōnī de Vicidata Proprietātī//
[id='1']
=== [`1`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P2082

|
ix_hxlix
|
ix_unm49

|
ix_hxlvoc
|
+v_unm49

|===






[id='2']
=== [`2`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P2983

|
ix_hxlix
|
ix_undpcc

|
ix_hxlvoc
|
+v_undp_cc

|===






[id='3']
=== [`3`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P3024

|===






[id='4']
=== [`4`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_unpcode

|
ix_hxlvoc
|
+v_pcode

|===






[id='5']
=== [`5`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P1937

|
ix_hxlix
|
ix_unlocode

|===






[id='6']
=== [`6`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P498

|
ix_hxlix
|
ix_iso4217

|
ix_hxlvoc
|
+v_currency

|===






[id='7']
=== [`7`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P297

|
ix_hxlix
|
ix_iso3166p1a2

|
ix_hxlvoc
|
+v_iso2

|===






[id='8']
=== [`8`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P298

|
ix_hxlix
|
ix_iso3166p1a3

|
ix_hxlvoc
|
+v_iso3

|===






[id='9']
=== [`9`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P299

|
ix_hxlix
|
ix_iso3166p1n

|===






[id='10']
=== [`10`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P882

|
ix_hxlix
|
ix_usfips

|===






[id='11']
=== [`11`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P901

|===






[id='12']
=== [`12`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P1566

|
ix_hxlix
|
ix_geonameid

|===






[id='13']
=== [`13`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P218

|
ix_hxlix
|
ix_iso639p1a2

|===






[id='14']
=== [`14`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P219

|
ix_hxlix
|
ix_iso639p2a2

|===






[id='15']
=== [`15`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P220

|
ix_hxlix
|
ix_iso639p3a3

|===






[id='16']
=== [`16`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P1394

|
ix_hxlix
|
ix_glottocode

|
ix_hxlvoc
|
+v_glottocode

|===






[id='17']
=== [`17`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P506

|
ix_hxlix
|
ix_iso15924a4

|===






[id='18']
=== [`18`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P2620

|
ix_hxlix
|
ix_iso15924n

|===






[id='19']
=== [`19`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P305

|
ix_hxlix
|
ix_bcp47

|===






[id='20']
=== [`20`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P229

|
ix_hxlvoc
|
+v_iata_airline

|===






[id='21']
=== [`21`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P230

|
ix_hxlvoc
|
+v_icao_airline

|===






[id='22']
=== [`22`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P238

|
ix_hxlvoc
|
+v_iata_airport

|===






[id='23']
=== [`23`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P239

|
ix_hxlvoc
|
+v_icao_airport

|===






[id='24']
=== [`24`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P402

|
ix_hxlix
|
ix_osmrelid

|===






[id='30']
=== [`30`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_csv

|
ix_hxlvoc
|
+v_csv

|===






[id='31']
=== [`31`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_csvprfxu

|
ix_hxlvoc
|
+v_csv_praefixum

|===






[id='32']
=== [`32`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_csvsffxm

|
ix_hxlvoc
|
+v_csv_suffixum

|===






[id='34']
=== [`34`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_wikiq

|
ix_hxlvoc
|
+v_wiki_q

|===






[id='35']
=== [`35`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_wikilngm

|
ix_hxlvoc
|
+v_wiki_linguam

|===






[id='40']
=== [`40`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_hxl

|
ix_hxlvoc
|
+v_hxl

|===






[id='41']
=== [`41`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_hxlhstg

|
ix_hxlvoc
|
+v_hxl_hashtag

|===






[id='42']
=== [`42`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_hxlcpt

|
ix_hxlvoc
|
+v_hxl_caput

|===






[id='43']
=== [`43`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_hxlt

|
ix_hxlvoc
|
+v_hxl_t

|===






[id='44']
=== [`44`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
ix_hxlix
|
ix_hxla

|
ix_hxlvoc
|
+v_hxl_a

|===






[id='50']
=== [`50`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P4179

|===






[id='51']
=== [`51`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P1630

|
ix_hxlix
|
ix_wikip1630

|
ix_hxlvoc
|
+v_wiki_p_1630

|===






[id='295']
=== [`295`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P1476

|
ix_hxlix
|
ix_wikip1476

|===






[id='296']
=== [`296`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P854

|
ix_hxlix
|
ix_wikip854

|===






[id='297']
=== [`297`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P50

|
ix_hxlix
|
ix_wikip50

|===






[id='298']
=== [`298`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P110

|
ix_hxlix
|
ix_wikip110

|===






[id='299']
=== [`299`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P577

|
ix_hxlix
|
ix_wikip577

|===






[id='302']
=== [`302`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P2479

|
ix_hxlix
|
ix_wikip2479

|===






[id='335']
=== [`335`] 





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki P/
|
P1585

|
ix_hxlvoc
|
+v_br_ibge

|===







<<<

