= Cōdex [1603:44:1]: //dictiōnāria de post mortis condici//
:doctype: book
:title: Cōdex [1603:44:1]: //dictiōnāria de post mortis condici//
:lang: la
:toc:
:toclevels: 4
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge




{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
[quote]
/_**Public domain means that each major common issue only needs to be resolved once**_/@eng-Latn

<<<
toc::[]


[id=0_999_1603_1]
== Praefātiō 

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō
|
Lingua Anglica (Abecedarium Latinum)
|
_**"Cōdex [1603:44:1]"**_ is the book format of the machine-readable dictionaries _**"[1603:44:1] //dictiōnāria de post mortis condici//"**_,
which are distributed for implementers on external applications.
This book is intended as advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies.

Practical lexicography is the art or craft of compiling, writing and editing dictionaries.
The basics are not far different than a millennia ago:
it is still a very humane, creative work.
It is necessary to be humble:
most of the translator's mistakes are, in fact, not translator's fault, but methodological flaws.
Making sure of a source idea of what a concept represents,
even if it means rewrite and make simpler, annex pictures,
show examples, do whatever to make it be understood,
makes even non-professional translators that care about their own language deliver better results than any alternative.
In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.

The initiative behind this compilation is also doing other dictionaries and accepts new suggestions of relevant topics on data exchange for humanitarian use.
All have in common the fact that both have human translations and (if any) external interlingual codes related to each concept while making the end result explicitly already ready to be usable on average softwares.
Naturally, each book version gives extensive explanations for collaborators on how to correct itself which become part of the next weekly release.

|===


[%header,cols="25h,~"]
|===
| Rēs interlinguālibus
| Factum

| scrīptor
| Multiplicēs scrīptōribus

| //cōdex pūblicandī//
| EticaAI

| /publication date/@eng-Latn
| 2022-01-01

| numerus editionis
| 2022-02-08T06:07:18

| /SPDX license ID/@eng-Latn
| CC-PDDC

|===


<<<

== Methodī ex cōdice
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō
|
Lingua Anglica (Abecedarium Latinum)
|
This section explains the methodology of this book and it's machine readable formats. For your convenience the information used to explain the concepts (such as natural language and interlingual codes) which appears in this book are also summarized here. This approach is done both for reviews not needing to open other books (or deal with machine readable files) and also to spot errors on other dictionaries. +++<br><br>+++ About how the book and the dictionaries are compiled, a division of "baseline concept table" and (when relevant for a codex) "translations conciliation" is given different methodologies. +++<br><br>+++ Every book contains at minimum the baseline concept table and explanation of the used fields. This approach helps to release dictionaries faster while ensuring both humans and machines can know what to expect even when they are not ready to receive translations.

|===

=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Methodī ex verbīs in dictiōnāriīs
NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data],  which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō
|
Lingua Anglica (Abecedarium Latinum)
|
The ***[1603:44:1] //dictiōnāria de post mortis condici//*** uses Wikidata as one strategy to conciliate language terms for one or more of it's concepts.

This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up to date translations.

|
Lingua Anglica (Abecedarium Latinum)
|
**How reliable are the community translations (Wikidata source)?**

The short, default answer is: **they are reliable**, even in cases of no authoritative translations for each subject.

As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests.
This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).

However, even when the result is correct,
the current version needs improved differentiation, at minimum, acronym and long form.
For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.

|
Lingua Anglica (Abecedarium Latinum)
|
**Major reasons for "wrong translations" are not translators fault**

TIP: As a rule of thumb, for already very defined concepts where you, as human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.

NOTE: Both at concept level and (as general statistics) book level, is planned to have indication concept likelihood of being well understood for very stricter translations initiatives.

The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.

It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.

|
Lingua Anglica (Abecedarium Latinum)
|
From the point of view of data conciliation, the following methodology is used to release the terminology translations with the main concept table.

. The main handcrafted lexicographical table (explained on previous topic), also provided on `1603_44_1.no1.tm.hxl.csv`, may reference Wiki QID.
. Every unique QID of  `1603_44_1.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works.
.. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares then for general use.
. The query result, with all QIDs and term labels, is shared as `1603_44_1.wikiq.tm.hxl.csv`
. The community reviewed translations of each singular QID is pre-compiled on an individual file `1603_44_1.wikiq.tm.hxl.csv`
. `1603_44_1.no1.tm.hxl.csv` plus `1603_44_1.wikiq.tm.hxl.csv` created `1603_44_1.no11.tm.hxl.csv`

|===

=== Rēs dē factō in dictiōnāriīs

==== Rēs linguālibus: 30

[%header,cols="~,~,~,~,~"]
|===
| Cōdex linguae
| Glotto cōdicī
| ISO 639-3
| Wiki QID cōdicī
| Nōmen Latīnum

| ara-Arab
| https://glottolog.org/resource/languoid/id/arab1395[arab1395]
| https://iso639-3.sil.org/code/ara[ara]
| https://www.wikidata.org/wiki/Q13955[Q13955]
| Macrolingua Arabica (Abecedarium Arabicum)

| rus-Cyrl
| https://glottolog.org/resource/languoid/id/russ1263[russ1263]
| https://iso639-3.sil.org/code/rus[rus]
| https://www.wikidata.org/wiki/Q7737[Q7737]
| Lingua Russica (Abecedarium Cyrillicum)

| por-Latn
| https://glottolog.org/resource/languoid/id/port1283[port1283]
| https://iso639-3.sil.org/code/por[por]
| https://www.wikidata.org/wiki/Q5146[Q5146]
| Lingua Lusitana (Abecedarium Latinum)

| eng-Latn
| https://glottolog.org/resource/languoid/id/stan1293[stan1293]
| https://iso639-3.sil.org/code/eng[eng]
| https://www.wikidata.org/wiki/Q1860[Q1860]
| Lingua Anglica (Abecedarium Latinum)

| fra-Latn
| https://glottolog.org/resource/languoid/id/stan1290[stan1290]
| https://iso639-3.sil.org/code/fra[fra]
| https://www.wikidata.org/wiki/Q150[Q150]
| Lingua Francogallica (Abecedarium Latinum)

| nld-Latn
| https://glottolog.org/resource/languoid/id/mode1257[mode1257]
| https://iso639-3.sil.org/code/nld[nld]
| https://www.wikidata.org/wiki/Q7411[Q7411]
| Lingua Batavica (Abecedarium Latinum)

| deu-Latn
| https://glottolog.org/resource/languoid/id/stan1295[stan1295]
| https://iso639-3.sil.org/code/deu[deu]
| https://www.wikidata.org/wiki/Q188[Q188]
| Lingua Germanica (Abecedarium Latinum)

| spa-Latn
| https://glottolog.org/resource/languoid/id/stan1288[stan1288]
| https://iso639-3.sil.org/code/spa[spa]
| https://www.wikidata.org/wiki/Q1321[Q1321]
| Lingua Hispanica (Abecedarium Latinum)

| ita-Latn
| https://glottolog.org/resource/languoid/id/ital1282[ital1282]
| https://iso639-3.sil.org/code/ita[ita]
| https://www.wikidata.org/wiki/Q652[Q652]
| Lingua Italiana (Abecedarium Latinum)

| gle-Latn
| https://glottolog.org/resource/languoid/id/iris1253[iris1253]
| https://iso639-3.sil.org/code/gle[gle]
| https://www.wikidata.org/wiki/Q9142[Q9142]
| Lingua Hibernica (Abecedarium Latinum)

| swe-Latn
| https://glottolog.org/resource/languoid/id/swed1254[swed1254]
| https://iso639-3.sil.org/code/swe[swe]
| https://www.wikidata.org/wiki/Q9027[Q9027]
| Lingua Suecica (Abecedarium Latinum)

| pol-Latn
| https://glottolog.org/resource/languoid/id/poli1260[poli1260]
| https://iso639-3.sil.org/code/pol[pol]
| https://www.wikidata.org/wiki/Q809[Q809]
| Lingua Polonica (Abecedarium Latinum)

| fin-Latn
| https://glottolog.org/resource/languoid/id/finn1318[finn1318]
| https://iso639-3.sil.org/code/fin[fin]
| https://www.wikidata.org/wiki/Q1412[Q1412]
| Lingua Finnica (Abecedarium Latinum)

| ron-Latn
| https://glottolog.org/resource/languoid/id/roma1327[roma1327]
| https://iso639-3.sil.org/code/ron[ron]
| https://www.wikidata.org/wiki/Q7913[Q7913]
| Lingua Dacoromanica (Abecedarium Latinum)

| vie-Latn
| https://glottolog.org/resource/languoid/id/viet1252[viet1252]
| https://iso639-3.sil.org/code/vie[vie]
| https://www.wikidata.org/wiki/Q9199[Q9199]
| Lingua Vietnamensis (Abecedarium Latinum)

| cat-Latn
| https://glottolog.org/resource/languoid/id/stan1289[stan1289]
| https://iso639-3.sil.org/code/cat[cat]
| https://www.wikidata.org/wiki/Q7026[Q7026]
| Lingua Catalana (Abecedarium Latinum)

| ukr-Cyrl
| https://glottolog.org/resource/languoid/id/ukra1253[ukra1253]
| https://iso639-3.sil.org/code/ukr[ukr]
| https://www.wikidata.org/wiki/Q8798[Q8798]
| Lingua Ucrainica (Abecedarium Cyrillicum)

| bul-Cyrl
| https://glottolog.org/resource/languoid/id/bulg1262[bulg1262]
| https://iso639-3.sil.org/code/bul[bul]
| https://www.wikidata.org/wiki/Q7918[Q7918]
| Lingua Bulgarica (Abecedarium Cyrillicum)

| slv-Latn
| https://glottolog.org/resource/languoid/id/slov1268[slov1268]
| https://iso639-3.sil.org/code/slv[slv]
| https://www.wikidata.org/wiki/Q9063[Q9063]
| Lingua Slovena (Abecedarium Latinum)

| nob-Latn
| https://glottolog.org/resource/languoid/id/norw1259[norw1259]
| https://iso639-3.sil.org/code/nob[nob]
| https://www.wikidata.org/wiki/Q25167[Q25167]
| /Bokmål/ (Abecedarium Latinum)

| ces-Latn
| https://glottolog.org/resource/languoid/id/czec1258[czec1258]
| https://iso639-3.sil.org/code/ces[ces]
| https://www.wikidata.org/wiki/Q9056[Q9056]
| Lingua Bohemica (Abecedarium Latinum)

| dan-Latn
| https://glottolog.org/resource/languoid/id/dani1285[dani1285]
| https://iso639-3.sil.org/code/dan[dan]
| https://www.wikidata.org/wiki/Q9035[Q9035]
| Lingua Danica (Abecedarium Latinum)

| jpn-Jpan
| https://glottolog.org/resource/languoid/id/nucl1643[nucl1643]
| https://iso639-3.sil.org/code/jpn[jpn]
| https://www.wikidata.org/wiki/Q5287[Q5287]
| Lingua Iaponica (Scriptura Iaponica)

| mal-Mlym
| https://glottolog.org/resource/languoid/id/mala1464[mala1464]
| https://iso639-3.sil.org/code/mal[mal]
| https://www.wikidata.org/wiki/Q36236[Q36236]
| Lingua Malabarica (/Malayalam script/)

| ind-Latn
| https://glottolog.org/resource/languoid/id/indo1316[indo1316]
| https://iso639-3.sil.org/code/ind[ind]
| https://www.wikidata.org/wiki/Q9240[Q9240]
| Lingua Indonesiana (Abecedarium Latinum)

| fas-Zzzz
| 
| https://iso639-3.sil.org/code/fas[fas]
| https://www.wikidata.org/wiki/Q9168[Q9168]
| Macrolingua Persica (Abecedarium Arabicum)

| hun-Latn
| https://glottolog.org/resource/languoid/id/hung1274[hung1274]
| https://iso639-3.sil.org/code/hun[hun]
| https://www.wikidata.org/wiki/Q9067[Q9067]
| Lingua Hungarica (Abecedarium Latinum)

| glg-Latn
| https://glottolog.org/resource/languoid/id/gali1258[gali1258]
| https://iso639-3.sil.org/code/glg[glg]
| https://www.wikidata.org/wiki/Q9307[Q9307]
| Lingua Gallaica (Abecedarium Latinum)

| epo-Latn
| https://glottolog.org/resource/languoid/id/espe1235[espe1235]
| https://iso639-3.sil.org/code/epo[epo]
| https://www.wikidata.org/wiki/Q143[Q143]
| Lingua Esperantica (Abecedarium Latinum)

| est-Latn
| 
| https://iso639-3.sil.org/code/est[est]
| https://www.wikidata.org/wiki/Q9072[Q9072]
| Macrolingua Estonica (Abecedarium Latinum)

|===

==== Rēs interlinguālibus: 6


===== 1603:1:7:1:91 

[source,json]
----
{
    "#item+conceptum+codicem": "1_91",
    "#item+conceptum+numerordinatio": "1603:1:7:1:91",
    "#item+rem+definitionem+i_eng+is_latn": "QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter \"Q\" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.",
    "#item+rem+i_lat+is_latn": "/Wiki QID/",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikiq",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_q",
    "#item+rem+i_qcc+is_zxxx+ix_regulam": "Q[1-9]\\d*",
    "#status+conceptum+codicem": "19",
    "#status+conceptum+definitionem": "50"
}
----

===== 1603:1:7:2616:50 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_50",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:50",
    "#item+rem+definitionem+i_eng+is_latn": "Main creator(s) of a written work (use on works, not humans)",
    "#item+rem+i_lat+is_latn": "scrīptor",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip50",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_50",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P50",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:123 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_123",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:123",
    "#item+rem+definitionem+i_eng+is_latn": "organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software",
    "#item+rem+i_lat+is_latn": "//cōdex pūblicandī//",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip123",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_123",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P123",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:393 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_393",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:393",
    "#item+rem+definitionem+i_eng+is_latn": "number of an edition (first, second, ... as 1, 2, ...) or event",
    "#item+rem+i_lat+is_latn": "numerus editionis",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip393",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_393",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P393",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:577 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_577",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:577",
    "#item+rem+definitionem+i_eng+is_latn": "Date or point in time when a work was first published or released",
    "#item+rem+i_lat+is_latn": "/publication date/@eng-Latn",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip577",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_577",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P577",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

===== 1603:1:7:2616:2479 

[source,json]
----
{
    "#item+conceptum+codicem": "2616_2479",
    "#item+conceptum+numerordinatio": "1603:1:7:2616:2479",
    "#item+rem+definitionem+i_eng+is_latn": "SPDX license identifier",
    "#item+rem+i_lat+is_latn": "/SPDX license ID/@eng-Latn",
    "#item+rem+i_qcc+is_zxxx+ix_hxlix": "ix_wikip2479",
    "#item+rem+i_qcc+is_zxxx+ix_hxlvoc": "v_wiki_p_2479",
    "#item+rem+i_qcc+is_zxxx+ix_regulam": "[0-9A-Za-z\\.\\-]{3,36}[+]?",
    "#item+rem+i_qcc+is_zxxx+ix_wikip": "P2479",
    "#item+rem+i_qcc+is_zxxx+ix_wikip1630": "https://spdx.org/licenses/$1.html",
    "#status+conceptum+codicem": "60",
    "#status+conceptum+definitionem": "60"
}
----

<<<

== //dictiōnāria de post mortis condici//
[id='1']
=== [`1`] /pallor mortis/@eng-Latn





[%header,cols="25h,~"]
|===
| Rēs interlinguālibus
| Factum

| /Wiki QID/
| Q3493484

| ix_hxlix
| ix_pallormortis

| ix_hxlvoc
| v_lat_pallormortis

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| #item+rem+i_ara+is_arab
| +++شحوب الموت+++

| #item+rem+i_rus+is_cyrl
| +++трупная бледность+++

| #item+rem+i_por+is_latn
| +++pallor mortis+++

| #item+rem+i_eng+is_latn
| +++pallor mortis+++

| #item+rem+i_fra+is_latn
| +++pallor mortis+++

| #item+rem+i_nld+is_latn
| +++pallor mortis+++

| #item+rem+i_deu+is_latn
| +++pallor mortis+++

| #item+rem+i_spa+is_latn
| +++pallor mortis+++

| #item+rem+i_ita+is_latn
| +++pallor mortis+++

| #item+rem+i_swe+is_latn
| +++likblekhet+++

| #item+rem+i_pol+is_latn
| +++bladość pośmiertna+++

| #item+rem+i_fin+is_latn
| +++kuolonkalpeus+++

| #item+rem+i_vie+is_latn
| +++tái nhạt tử thi+++

| #item+rem+i_bul+is_cyrl
| +++трупна бледост+++

| #item+rem+i_slv+is_latn
| +++mrliška bledica+++

| #item+rem+i_ces+is_latn
| +++pallor mortis+++

|===




[id='2']
=== [`2`] /algor mortis/@eng-Latn





[%header,cols="25h,~"]
|===
| Rēs interlinguālibus
| Factum

| /Wiki QID/
| Q1500381

| ix_hxlix
| ix_algormortis

| ix_hxlvoc
| v_lat_algormortis

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| #item+rem+i_ara+is_arab
| +++برودة الموت+++

| #item+rem+i_rus+is_cyrl
| +++посмертное охлаждение+++

| #item+rem+i_por+is_latn
| +++algor mortis+++

| #item+rem+i_eng+is_latn
| +++algor mortis+++

| #item+rem+i_fra+is_latn
| +++algor mortis+++

| #item+rem+i_nld+is_latn
| +++algor mortis+++

| #item+rem+i_deu+is_latn
| +++algor mortis+++

| #item+rem+i_spa+is_latn
| +++algor mortis+++

| #item+rem+i_ita+is_latn
| +++algor mortis+++

| #item+rem+i_swe+is_latn
| +++likkyla+++

| #item+rem+i_pol+is_latn
| +++oziębienie pośmiertne+++

| #item+rem+i_fin+is_latn
| +++kuolonkylmyys+++

| #item+rem+i_vie+is_latn
| +++mát lạnh tử thi+++

| #item+rem+i_bul+is_cyrl
| +++трупно изстиване+++

| #item+rem+i_slv+is_latn
| +++mrliška ohladitev+++

| #item+rem+i_ces+is_latn
| +++algor mortis+++

| #item+rem+i_jpn+is_jpan
| +++死冷+++

|===




[id='3']
=== [`3`] /rigor mortis/@eng-Latn





[%header,cols="25h,~"]
|===
| Rēs interlinguālibus
| Factum

| /Wiki QID/
| Q274095

| ix_hxlix
| ix_rigormortis

| ix_hxlvoc
| v_lat_rigormortis

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| #item+rem+i_ara+is_arab
| +++تخشب موتي+++

| #item+rem+i_rus+is_cyrl
| +++трупное окоченение+++

| #item+rem+i_por+is_latn
| +++rigor mortis+++

| #item+rem+i_eng+is_latn
| +++rigor mortis+++

| #item+rem+i_fra+is_latn
| +++rigidité cadavérique+++

| #item+rem+i_nld+is_latn
| +++lijkstijfheid+++

| #item+rem+i_deu+is_latn
| +++totenstarre+++

| #item+rem+i_spa+is_latn
| +++rigor mortis+++

| #item+rem+i_ita+is_latn
| +++rigor mortis+++

| #item+rem+i_gle+is_latn
| +++teannáil an bháis+++

| #item+rem+i_swe+is_latn
| +++likstelhet+++

| #item+rem+i_pol+is_latn
| +++stężenie pośmiertne+++

| #item+rem+i_fin+is_latn
| +++kuolonkankeus+++

| #item+rem+i_ron+is_latn
| +++rigor mortis+++

| #item+rem+i_vie+is_latn
| +++co cứng tử thi+++

| #item+rem+i_cat+is_latn
| +++rigidesa cadavèrica+++

| #item+rem+i_ukr+is_cyrl
| +++трупне окоченіння+++

| #item+rem+i_bul+is_cyrl
| +++трупно вкочаняване+++

| #item+rem+i_slv+is_latn
| +++mrliška okorelost+++

| #item+rem+i_nob+is_latn
| +++dødsstivhet+++

| #item+rem+i_ces+is_latn
| +++posmrtná ztuhlost+++

| #item+rem+i_jpn+is_jpan
| +++死後硬直+++

| #item+rem+i_mal+is_mlym
| +++മൃത്യുജകാഠിന്യം+++

| #item+rem+i_ind+is_latn
| +++kaku mayat+++

| #item+rem+i_fas+is_zzzz
| +++جمود نعشی+++

| #item+rem+i_hun+is_latn
| +++hullamerevség+++

| #item+rem+i_glg+is_latn
| +++rigor mortis+++

| #item+rem+i_epo+is_latn
| +++kadavra rigideco+++

|===




[id='4']
=== [`4`] /livor mortis/@eng-Latn





[%header,cols="25h,~"]
|===
| Rēs interlinguālibus
| Factum

| /Wiki QID/
| Q747953

| ix_hxlix
| ix_livormortis

| ix_hxlvoc
| v_lat_livormortis

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| #item+rem+i_ara+is_arab
| +++ازرقاق الجثة+++

| #item+rem+i_rus+is_cyrl
| +++трупные пятна+++

| #item+rem+i_por+is_latn
| +++livor mortis+++

| #item+rem+i_eng+is_latn
| +++livor mortis+++

| #item+rem+i_fra+is_latn
| +++lividités cadavériques+++

| #item+rem+i_nld+is_latn
| +++livor mortis+++

| #item+rem+i_deu+is_latn
| +++totenfleck+++

| #item+rem+i_spa+is_latn
| +++livor mortis+++

| #item+rem+i_ita+is_latn
| +++livor mortis+++

| #item+rem+i_swe+is_latn
| +++likfläck+++

| #item+rem+i_pol+is_latn
| +++plamy pośmiertne+++

| #item+rem+i_fin+is_latn
| +++lautuma+++

| #item+rem+i_vie+is_latn
| +++hồ máu tử thi+++

| #item+rem+i_ukr+is_cyrl
| +++трупні плями+++

| #item+rem+i_bul+is_cyrl
| +++хипостаза+++

| #item+rem+i_nob+is_latn
| +++dødsflekk+++

| #item+rem+i_ces+is_latn
| +++posmrtné skvrny+++

| #item+rem+i_dan+is_latn
| +++livores+++

| #item+rem+i_jpn+is_jpan
| +++死斑+++

| #item+rem+i_ind+is_latn
| +++livor mortis+++

| #item+rem+i_epo+is_latn
| +++livor mortis+++

|===




[id='5']
=== [`5`] /putrefaction/@eng-Latn





[%header,cols="25h,~"]
|===
| Rēs interlinguālibus
| Factum

| /Wiki QID/
| Q671701

| ix_hxlix
| ix_putrefactiocadaveris

| ix_hxlvoc
| v_lat_putrefactiocadaveris

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| #item+rem+i_ara+is_arab
| +++تعفن+++

| #item+rem+i_rus+is_cyrl
| +++гниение+++

| #item+rem+i_por+is_latn
| +++putrefação+++

| #item+rem+i_eng+is_latn
| +++putrefaction+++

| #item+rem+i_fra+is_latn
| +++putréfaction+++

| #item+rem+i_deu+is_latn
| +++putrefizierung+++

| #item+rem+i_spa+is_latn
| +++putrefacción+++

| #item+rem+i_ita+is_latn
| +++putrefazione+++

| #item+rem+i_pol+is_latn
| +++rozpad gnilny+++

| #item+rem+i_ron+is_latn
| +++putrefacție+++

| #item+rem+i_ukr+is_cyrl
| +++гниття+++

| #item+rem+i_bul+is_cyrl
| +++гниене+++

| #item+rem+i_ces+is_latn
| +++hnití+++

| #item+rem+i_fas+is_zzzz
| +++گندیدگی+++

| #item+rem+i_epo+is_latn
| +++putrado+++

| #item+rem+i_est+is_latn
| +++roiskumine+++

|===





<<<

[appendix]
= //Open issues on exported PDF format//@eng-Latn


=== //Documentation about how to use the machine-readable dictionaries//@eng-Latn

Is necessary to give a quick introduction (or at least mention) the files generated with this implementer documentation.

=== //Missing fonts to render all term variants//@eng-Latn
The generated PDF does not include all necessary fonts.
Here potential strategy to fix it https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#custom-fonts

=== //Reliability statuses//@eng-Latn

Currently, the reliability of numeric statuses are not well explained on PDF version.
