= Cōdex [1603:44:1]: //dictiōnāria de post mortis condici//
:doctype: book
:title: Cōdex [1603:44:1]: //dictiōnāria de post mortis condici//
:lang: la
:toc: macro
:toclevels: 5
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum




{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

'''

[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
Multiplicēs scrīptōribus

|
/cōdex pūblicandī/
|
EticaAI

|
/publication date/@eng-Latn
|
2022-01-01

|
numerus editionis
|
2022-03-16T07:45:14

|
/SPDX license ID/@eng-Latn
|
CC-PDDC

|===


ifndef::backend-epub3[]
<<<
toc::[]
<<<
endif::[]


[id=0_999_1603_1]
== Praefātiō 

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    _**Cōdex [1603:44:1]**_ is the book format of the machine-readable dictionaries _**[1603:44:1] //dictiōnāria de post mortis condici//**_, which are distributed for implementers on external applications. This book is intended as an advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies. It can, however, be used as an ad hoc dictionary if there is not derived work focused on your specific needs.
    +++<br><br>+++
    **ABOUT LEXICOGRAPHY**
    +++<br><br>+++
    Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not the translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.
    +++<br><br>+++
    **ABOUT TYPES OF DICTIONARIES WE'RE COMPILING**
    +++<br><br>+++
    We're concerned with a group of ideas (we call it a group of dictionaries of concepts) which can be broken into smaller parts, reviewed for inconsistencies, improved for definitions, and then be translated by volunteers. Interlingual codes, such as what could be used on actual data exchange, are also added to each concept. Both glossaries, user interfaces (such as labels on data collection) and in some cases even standard codes for what would go on a data field could be compiled this way.
    +++<br><br>+++
    Since the full list of prototypal-dictionaries and dictionaries is huge, one way cited by objective audiences is the following:
    +++<br><br>+++
    ....
    1. Humanitarian aid
    2. Development aid
    3. Human rights
    4. Military relief (or conflict and conflict-resolution related concepts)
    ....
    +++<br><br>+++
    The itens 1, 2 and 4 https://en.m.wikipedia.org/wiki/Humanitarian-Development_Nexus[are sometimes referred as _nexus_] and are often found helping _humanitarian crisis_. Since most contributors whose ideas and valid criticism are volunteers, then 3 (human rights, as in International Amnesty) to differentiate from humanitarianism (such as Red Cross Movement is reference).
    +++<br><br>+++
    Note that **dictionaries are not usage guides**. Instructions, when they exist, are mostly dedicated to lexicographers and translators.
    +++<br><br>+++
    **/PRO BONŌ PUBLICŌ/@lat-Latn**
    +++<br><br>+++
    The lexicographers of this work are both volunteers, doing it for free, pro bonō publicō, and don't accept donations for the sake of everyone's reusable dictionaries. Existing previous work often is based on old public domain books. Most terminology translators already would be volunteers because they believe in a cause. The best way to inspire collaboration is to be examples ourselves.
    +++<br><br>+++
    There's a non-moralistic aspect, fairly simple to understand: how expensive would it be to pay for everyone's work considering it is feasible over 200 languages? The logistics to decide who should be paid, then worldwide cash transfer (may include people from embargoed countries), then traditional auditing mechanisms to check misuse donors expect, exist? In special terminology (dictionary terms themselves) and so many languages, neither sufficient money nor humans interested in being coordinators exist.


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Methodī ex verbīs in dictiōnāriīs
NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    The ***[1603:44:1] //dictiōnāria de post mortis condici//*** uses Wikidata as one strategy to conciliate language terms for one or more of it's concepts.
    +++<br><br>+++
    This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up to date translations.
    +++<br><br>+++
    **How reliable are the community translations (Wikidata source)?**
    +++<br><br>+++
    The short, default answer is: **they are reliable**, even in cases of no authoritative translations for each subject.
    +++<br><br>+++
    As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).
    +++<br><br>+++
    However, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.
    +++<br><br>+++
    **Major reasons for "wrong translations" are not translators fault**
    +++<br><br>+++
    TIP: As a rule of thumb, for already very defined concepts where you, as human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.
    +++<br><br>+++
    The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.
    +++<br><br>+++
    It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.
    +++<br><br>+++
    From the point of view of data conciliation, the following methodology is used to release the terminology translations with the main concept table.
    +++<br><br>+++
    . The main handcrafted lexicographical table (explained on previous topic), also provided on `1603_44_1.no1.tm.hxl.csv`, may reference Wiki QID.
    . Every unique QID of  `1603_44_1.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!
    .. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares then for general use.
    . The query result, with all QIDs and term labels, is shared as `1603_44_1.wikiq.tm.hxl.csv`
    . The community reviewed translations of each singular QID is pre-compiled on an individual file `1603_44_1.wikiq.tm.hxl.csv`
    . `1603_44_1.no1.tm.hxl.csv` plus `1603_44_1.wikiq.tm.hxl.csv` created `1603_44_1.no11.tm.hxl.csv`


=== Rēs dē factō in dictiōnāriīs
==== Concepta: 5

==== Rēs linguālibus: 56

[%header,cols="15h,25a,~,17"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
ara-Arab
|
https://glottolog.org/resource/languoid/id/arab1395[arab1395]
+++<br>+++
https://iso639-3.sil.org/code/ara[ara]
+++<br>+++ https://www.wikidata.org/wiki/Q13955[Q13955]
|
Macrolingua Arabica (Abecedarium Arabicum)
|
5

|
hye-Armn
|
https://glottolog.org/resource/languoid/id/nucl1235[nucl1235]
+++<br>+++
https://iso639-3.sil.org/code/hye[hye]
+++<br>+++ https://www.wikidata.org/wiki/Q8785[Q8785]
|
Lingua Armenia (Alphabetum Armenium)
|
1

|
rus-Cyrl
|
https://glottolog.org/resource/languoid/id/russ1263[russ1263]
+++<br>+++
https://iso639-3.sil.org/code/rus[rus]
+++<br>+++ https://www.wikidata.org/wiki/Q7737[Q7737]
|
Lingua Russica (Abecedarium Cyrillicum)
|
5

|
hin-Deva
|
https://glottolog.org/resource/languoid/id/hind1269[hind1269]
+++<br>+++
https://iso639-3.sil.org/code/hin[hin]
+++<br>+++ https://www.wikidata.org/wiki/Q1568[Q1568]
|
Lingua Hindica (Devanāgarī)
|
5

|
pan-Guru
|
https://glottolog.org/resource/languoid/id/panj1256[panj1256]
+++<br>+++
https://iso639-3.sil.org/code/pan[pan]
+++<br>+++ https://www.wikidata.org/wiki/Q58635[Q58635]
|
Lingua Paniabica (/ISO 15924 Guru/)
|
4

|
kor-Hang
|
https://glottolog.org/resource/languoid/id/kore1280[kore1280]
+++<br>+++
https://iso639-3.sil.org/code/kor[kor]
+++<br>+++ https://www.wikidata.org/wiki/Q9176[Q9176]
|
Lingua Coreana (Abecedarium Coreanum)
|
5

|
heb-Hebr
|
https://glottolog.org/resource/languoid/id/hebr1245[hebr1245]
+++<br>+++
https://iso639-3.sil.org/code/heb[heb]
+++<br>+++ https://www.wikidata.org/wiki/Q9288[Q9288]
|
Lingua Hebraica (Alphabetum Hebraicum)
|
2

|
tam-Taml
|
https://glottolog.org/resource/languoid/id/tami1289[tami1289]
+++<br>+++
https://iso639-3.sil.org/code/tam[tam]
+++<br>+++ https://www.wikidata.org/wiki/Q5885[Q5885]
|
Lingua Tamulica (/ISO 15924 Taml/)
|
1

|
tel-Telu
|
https://glottolog.org/resource/languoid/id/telu1262[telu1262]
+++<br>+++
https://iso639-3.sil.org/code/tel[tel]
+++<br>+++ https://www.wikidata.org/wiki/Q8097[Q8097]
|
Lingua Telingana (/ISO 15924 Telu/)
|
1

|
tha-Thai
|
https://glottolog.org/resource/languoid/id/thai1261[thai1261]
+++<br>+++
https://iso639-3.sil.org/code/tha[tha]
+++<br>+++ https://www.wikidata.org/wiki/Q9217[Q9217]
|
Lingua Thai (/ISO 15924 Thai/)
|
3

|
zho-Zyyy
|
https://glottolog.org/resource/languoid/id/sini1245[sini1245]
+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q7850[Q7850]
|
/Macrolingua Sinicae (/ISO 15924 Zyyy/)/
|
5

|
por-Latn
|
https://glottolog.org/resource/languoid/id/port1283[port1283]
+++<br>+++
https://iso639-3.sil.org/code/por[por]
+++<br>+++ https://www.wikidata.org/wiki/Q5146[Q5146]
|
Lingua Lusitana (Abecedarium Latinum)
|
5

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
8

|
fra-Latn
|
https://glottolog.org/resource/languoid/id/stan1290[stan1290]
+++<br>+++
https://iso639-3.sil.org/code/fra[fra]
+++<br>+++ https://www.wikidata.org/wiki/Q150[Q150]
|
Lingua Francogallica (Abecedarium Latinum)
|
5

|
nld-Latn
|
https://glottolog.org/resource/languoid/id/mode1257[mode1257]
+++<br>+++
https://iso639-3.sil.org/code/nld[nld]
+++<br>+++ https://www.wikidata.org/wiki/Q7411[Q7411]
|
Lingua Batavica (Abecedarium Latinum)
|
4

|
deu-Latn
|
https://glottolog.org/resource/languoid/id/stan1295[stan1295]
+++<br>+++
https://iso639-3.sil.org/code/deu[deu]
+++<br>+++ https://www.wikidata.org/wiki/Q188[Q188]
|
Lingua Germanica (Abecedarium Latinum)
|
5

|
spa-Latn
|
https://glottolog.org/resource/languoid/id/stan1288[stan1288]
+++<br>+++
https://iso639-3.sil.org/code/spa[spa]
+++<br>+++ https://www.wikidata.org/wiki/Q1321[Q1321]
|
Lingua Hispanica (Abecedarium Latinum)
|
5

|
ita-Latn
|
https://glottolog.org/resource/languoid/id/ital1282[ital1282]
+++<br>+++
https://iso639-3.sil.org/code/ita[ita]
+++<br>+++ https://www.wikidata.org/wiki/Q652[Q652]
|
Lingua Italiana (Abecedarium Latinum)
|
5

|
gle-Latn
|
https://glottolog.org/resource/languoid/id/iris1253[iris1253]
+++<br>+++
https://iso639-3.sil.org/code/gle[gle]
+++<br>+++ https://www.wikidata.org/wiki/Q9142[Q9142]
|
Lingua Hibernica (Abecedarium Latinum)
|
1

|
swe-Latn
|
https://glottolog.org/resource/languoid/id/swed1254[swed1254]
+++<br>+++
https://iso639-3.sil.org/code/swe[swe]
+++<br>+++ https://www.wikidata.org/wiki/Q9027[Q9027]
|
Lingua Suecica (Abecedarium Latinum)
|
4

|
pol-Latn
|
https://glottolog.org/resource/languoid/id/poli1260[poli1260]
+++<br>+++
https://iso639-3.sil.org/code/pol[pol]
+++<br>+++ https://www.wikidata.org/wiki/Q809[Q809]
|
Lingua Polonica (Abecedarium Latinum)
|
5

|
fin-Latn
|
https://glottolog.org/resource/languoid/id/finn1318[finn1318]
+++<br>+++
https://iso639-3.sil.org/code/fin[fin]
+++<br>+++ https://www.wikidata.org/wiki/Q1412[Q1412]
|
Lingua Finnica (Abecedarium Latinum)
|
4

|
ron-Latn
|
https://glottolog.org/resource/languoid/id/roma1327[roma1327]
+++<br>+++
https://iso639-3.sil.org/code/ron[ron]
+++<br>+++ https://www.wikidata.org/wiki/Q7913[Q7913]
|
Lingua Dacoromanica (Abecedarium Latinum)
|
2

|
vie-Latn
|
https://glottolog.org/resource/languoid/id/viet1252[viet1252]
+++<br>+++
https://iso639-3.sil.org/code/vie[vie]
+++<br>+++ https://www.wikidata.org/wiki/Q9199[Q9199]
|
Lingua Vietnamensis (Abecedarium Latinum)
|
4

|
cat-Latn
|
https://glottolog.org/resource/languoid/id/stan1289[stan1289]
+++<br>+++
https://iso639-3.sil.org/code/cat[cat]
+++<br>+++ https://www.wikidata.org/wiki/Q7026[Q7026]
|
Lingua Catalana (Abecedarium Latinum)
|
1

|
ukr-Cyrl
|
https://glottolog.org/resource/languoid/id/ukra1253[ukra1253]
+++<br>+++
https://iso639-3.sil.org/code/ukr[ukr]
+++<br>+++ https://www.wikidata.org/wiki/Q8798[Q8798]
|
Lingua Ucrainica (Abecedarium Cyrillicum)
|
3

|
bul-Cyrl
|
https://glottolog.org/resource/languoid/id/bulg1262[bulg1262]
+++<br>+++
https://iso639-3.sil.org/code/bul[bul]
+++<br>+++ https://www.wikidata.org/wiki/Q7918[Q7918]
|
Lingua Bulgarica (Abecedarium Cyrillicum)
|
5

|
slv-Latn
|
https://glottolog.org/resource/languoid/id/slov1268[slov1268]
+++<br>+++
https://iso639-3.sil.org/code/slv[slv]
+++<br>+++ https://www.wikidata.org/wiki/Q9063[Q9063]
|
Lingua Slovena (Abecedarium Latinum)
|
3

|
nob-Latn
|
https://glottolog.org/resource/languoid/id/norw1259[norw1259]
+++<br>+++
https://iso639-3.sil.org/code/nob[nob]
+++<br>+++ https://www.wikidata.org/wiki/Q25167[Q25167]
|
/Bokmål/ (Abecedarium Latinum)
|
2

|
ces-Latn
|
https://glottolog.org/resource/languoid/id/czec1258[czec1258]
+++<br>+++
https://iso639-3.sil.org/code/ces[ces]
+++<br>+++ https://www.wikidata.org/wiki/Q9056[Q9056]
|
Lingua Bohemica (Abecedarium Latinum)
|
5

|
dan-Latn
|
https://glottolog.org/resource/languoid/id/dani1285[dani1285]
+++<br>+++
https://iso639-3.sil.org/code/dan[dan]
+++<br>+++ https://www.wikidata.org/wiki/Q9035[Q9035]
|
Lingua Danica (Abecedarium Latinum)
|
1

|
jpn-Jpan
|
https://glottolog.org/resource/languoid/id/nucl1643[nucl1643]
+++<br>+++
https://iso639-3.sil.org/code/jpn[jpn]
+++<br>+++ https://www.wikidata.org/wiki/Q5287[Q5287]
|
Lingua Iaponica (Scriptura Iaponica)
|
3

|
mal-Mlym
|
https://glottolog.org/resource/languoid/id/mala1464[mala1464]
+++<br>+++
https://iso639-3.sil.org/code/mal[mal]
+++<br>+++ https://www.wikidata.org/wiki/Q36236[Q36236]
|
Lingua Malabarica (/Malayalam script/)
|
1

|
ind-Latn
|
https://glottolog.org/resource/languoid/id/indo1316[indo1316]
+++<br>+++
https://iso639-3.sil.org/code/ind[ind]
+++<br>+++ https://www.wikidata.org/wiki/Q9240[Q9240]
|
Lingua Indonesiana (Abecedarium Latinum)
|
2

|
fas-Zyyy
|

+++<br>+++
https://iso639-3.sil.org/code/fas[fas]
+++<br>+++ https://www.wikidata.org/wiki/Q9168[Q9168]
|
Macrolingua Persica (//Abecedarium Arabicum//)
|
2

|
hun-Latn
|
https://glottolog.org/resource/languoid/id/hung1274[hung1274]
+++<br>+++
https://iso639-3.sil.org/code/hun[hun]
+++<br>+++ https://www.wikidata.org/wiki/Q9067[Q9067]
|
Lingua Hungarica (Abecedarium Latinum)
|
1

|
glg-Latn
|
https://glottolog.org/resource/languoid/id/gali1258[gali1258]
+++<br>+++
https://iso639-3.sil.org/code/glg[glg]
+++<br>+++ https://www.wikidata.org/wiki/Q9307[Q9307]
|
Lingua Gallaica (Abecedarium Latinum)
|
1

|
epo-Latn
|
https://glottolog.org/resource/languoid/id/espe1235[espe1235]
+++<br>+++
https://iso639-3.sil.org/code/epo[epo]
+++<br>+++ https://www.wikidata.org/wiki/Q143[Q143]
|
Lingua Esperantica (Abecedarium Latinum)
|
3

|
est-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/est[est]
+++<br>+++ https://www.wikidata.org/wiki/Q9072[Q9072]
|
Macrolingua Estonica (Abecedarium Latinum)
|
1

|
tur-Latn
|
https://glottolog.org/resource/languoid/id/nucl1301[nucl1301]
+++<br>+++
https://iso639-3.sil.org/code/tur[tur]
+++<br>+++ https://www.wikidata.org/wiki/Q256[Q256]
|
Lingua Turcica (Abecedarium Latinum)
|
5

|
afr-Latn
|
https://glottolog.org/resource/languoid/id/afri1274[afri1274]
+++<br>+++
https://iso639-3.sil.org/code/afr[afr]
+++<br>+++ https://www.wikidata.org/wiki/Q14196[Q14196]
|
Lingua Batava Capitensis (Abecedarium Latinum)
|
2

|
zho-Hant
|

+++<br>+++
https://iso639-3.sil.org/code/zho[zho]
+++<br>+++ https://www.wikidata.org/wiki/Q18130932[Q18130932]
|
//Traditional Chinese// (/ISO 15924 Hant/)
|
4

|
isl-Latn
|
https://glottolog.org/resource/languoid/id/icel1247[icel1247]
+++<br>+++
https://iso639-3.sil.org/code/isl[isl]
+++<br>+++ https://www.wikidata.org/wiki/Q294[Q294]
|
Lingua Islandica (Abecedarium Latinum)
|
1

|
srp-Latn
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q21161949[Q21161949]
|
/Serbian/ (Abecedarium Latinum)
|
4

|
srp-Cyrl
|
https://glottolog.org/resource/languoid/id/serb1264[serb1264]
+++<br>+++
https://iso639-3.sil.org/code/srp[srp]
+++<br>+++ https://www.wikidata.org/wiki/Q9299[Q9299]
|
Lingua Serbica (Abecedarium Cyrillicum)
|
4

|
urd-Arab
|
https://glottolog.org/resource/languoid/id/urdu1245[urdu1245]
+++<br>+++
https://iso639-3.sil.org/code/urd[urd]
+++<br>+++ https://www.wikidata.org/wiki/Q1617[Q1617]
|
Lingua Urdu (Abecedarium Arabicum)
|
2

|
hbs-Latn
|
https://glottolog.org/resource/languoid/id/sout1528[sout1528]
+++<br>+++
https://iso639-3.sil.org/code/hbs[hbs]
+++<br>+++ https://www.wikidata.org/wiki/Q9301[Q9301]
|
Macrolingua Serbocroatica (Abecedarium Latinum)
|
4

|
bel-Cyrl
|
https://glottolog.org/resource/languoid/id/bela1254[bela1254]
+++<br>+++
https://iso639-3.sil.org/code/bel[bel]
+++<br>+++ https://www.wikidata.org/wiki/Q9091[Q9091]
|
Lingua Ruthenica Alba (Abecedarium Cyrillicum)
|
4

|
bak-Cyrl
|
https://glottolog.org/resource/languoid/id/bash1264[bash1264]
+++<br>+++
https://iso639-3.sil.org/code/bak[bak]
+++<br>+++ https://www.wikidata.org/wiki/Q13389[Q13389]
|
Lingua Baschkirica (Abecedarium Cyrillicum)
|
1

|
kaz-Zyyy
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q9252[Q9252]
|
Lingua Kazachica (/ISO 15924 Zyyy/)
|
3

|
kaz-Arab
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362991[Q64362991]
|
Lingua Kazachica (Abecedarium Arabicum)
|
2

|
kaz-Cyrl
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362992[Q64362992]
|
Lingua Kazachica (Abecedarium Cyrillicum)
|
2

|
kaz-Latn
|
https://glottolog.org/resource/languoid/id/kaza1248[kaza1248]
+++<br>+++
https://iso639-3.sil.org/code/kaz[kaz]
+++<br>+++ https://www.wikidata.org/wiki/Q64362993[Q64362993]
|
Lingua Kazachica (Abecedarium Latinum)
|
2

|
mkd-Cyrl
|
https://glottolog.org/resource/languoid/id/mace1250[mace1250]
+++<br>+++
https://iso639-3.sil.org/code/mkd[mkd]
+++<br>+++ https://www.wikidata.org/wiki/Q9296[Q9296]
|
Lingua Macedonica (Abecedarium Cyrillicum)
|
1

|
que-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/que[que]
+++<br>+++ https://www.wikidata.org/wiki/Q5218[Q5218]
|
Macrolinguae Quechuae (Abecedarium Latinum)
|
1

|
tgk-Zyyy
|
https://glottolog.org/resource/languoid/id/taji1245[taji1245]
+++<br>+++
https://iso639-3.sil.org/code/tgk[tgk]
+++<br>+++ https://www.wikidata.org/wiki/Q9260[Q9260]
|
Lingua Tadzikica (/ISO 15924 Zyyy/)
|
1

|===

==== Rēs interlinguālibus: 8
Rēs::
  /Wiki QID/:::
    Rēs interlinguālibus::::
      /rēgulam/;;
        Q[1-9]\d*

      ix_hxlix;;
        ix_wikiq

      ix_hxlvoc;;
        v_wiki_q

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/Wiki QID/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.</span>+++

  /SPDX license ID/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P2479[P2479]

      /rēgulam/;;
        [0-9A-Za-z\.\-]{3,36}[+]?

      /formatter URL/@eng-Latn;;
        https://spdx.org/licenses/$1.html

      ix_hxlix;;
        ix_wikip2479

      ix_hxlvoc;;
        v_wiki_p_2479

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/SPDX license ID/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">SPDX license identifier</span>+++

  /publication date/@eng-Latn:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P577[P577]

      ix_hxlix;;
        ix_wikip577

      ix_hxlvoc;;
        v_wiki_p_577

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/publication date/@eng-Latn</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Date or point in time when a work was first published or released</span>+++

  scrīptor:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P50[P50]

      ix_hxlix;;
        ix_wikip50

      ix_hxlvoc;;
        v_wiki_p_50

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">scrīptor</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">Main creator(s) of a written work (use on works, not humans)</span>+++

  /cōdex pūblicandī/:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P123[P123]

      ix_hxlix;;
        ix_wikip123

      ix_hxlvoc;;
        v_wiki_p_123

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">/cōdex pūblicandī/</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software</span>+++

  numerus editionis:::
    Rēs interlinguālibus::::
      /Wiki P/;;
        https://www.wikidata.org/wiki/Property:P393[P393]

      ix_hxlix;;
        ix_wikip393

      ix_hxlvoc;;
        v_wiki_p_393

    Rēs linguālibus::::
      Lingua Latina (Abecedarium Latinum);;
        +++<span lang="la">numerus editionis</span>+++

      Lingua Anglica (Abecedarium Latinum);;
        +++<span lang="en">number of an edition (first, second, ... as 1, 2, ...) or event</span>+++


<<<

== Archīa

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    **Context information**: ignoring for a moment the fact of having several translations (and optimized to receive contributions on a regular basis, not _just_ an static work), then the actual groundbreaking difference on the workflow used to generate every dictionaries on Cōdex such as this one are the following fact: **we provide machine readable formats even when the equivalents on _international languages_, such as English, don't have for areas such as humanitarian aid, development aid and human rights**. The closest to such multilingualism (outside Wikimedia) are European Union SEMICeu (up to 24 languages), but even then have issues while sharing translations on all languages. United Nations translations (up to 6 languages, rarely more) are not available by humanitarian agencies to help with terminology translations.
    +++<br><br>+++
    **Practical implication**: the text documents on _Archīa prō cōdice_ (literal English translation: _File for book_) are alternatives to this book format which are heavily automated using only the data format. However, the machine-readable formats on _Archīa prō dictiōnāriīs_ (literal English translation: _Files for dictionaries_) are the focus and recommended for derived works and intended for mitigating additional human errors. We can even create new formats by request! The goal here is both to allow terminology translators and production usage where it makes an impact.


=== Archīa prō dictiōnāriīs: 3


==== 1603_44_1.no1.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_1.no1.tm.hxl.csv[1603_44_1.no1.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container/



==== 1603_44_1.no11.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_1.no11.tm.hxl.csv[1603_44_1.no11.tm.hxl.csv]
Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    /Numerordinatio on HXLTM container (expanded with terminology translations)/



==== 1603_44_1.wikiq.tm.hxl.csv

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_1.wikiq.tm.hxl.csv[1603_44_1.wikiq.tm.hxl.csv]
  /reference URL/@eng-Latn:::
    https://hxltm.etica.ai/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    HXLTM dialect of HXLStandard on CSV RFC 4180. wikiq means #item+conceptum+codicem are strictly Wikidata QIDs.



=== Archīa prō cōdice: 2


==== 1603_44_1.mul-Latn.codex.adoc

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_1.mul-Latn.codex.adoc[1603_44_1.mul-Latn.codex.adoc]
  /reference URL/@eng-Latn:::
    https://docs.asciidoctor.org/

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books.



==== 1603_44_1.mul-Latn.codex.pdf

Rēs interlinguālibus::
  /download link/@eng-Latn::: link:1603_44_1.mul-Latn.codex.pdf[1603_44_1.mul-Latn.codex.pdf]
  /reference URL/@eng-Latn:::
    https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Portable Document Format (PDF), standardized as ISO 32000, is a file format developed by Adobe in 1992 to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems.




<<<

[.text-center]

Dictiōnāria initiīs

<<<

== //dictiōnāria de post mortis condici//
<<<

[id='1']
=== [`1`] /pallor mortis/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q3493484[Q3493484]

  ix_hxlix:::
    ix_pallormortis

  ix_hxlvoc:::
    v_lat_pallormortis

Rēs linguālibus::
  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">شحوب الموت</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">трупная бледность</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">पीलापन क्षण</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਪੇਲਰ ਮੌਰਟਿਸ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">사후창백</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">蒼白僵直</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">pallor mortis</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">pallor mortis</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">pallor mortis</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">pallor mortis</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">pallor mortis</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">pallor mortis</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">pallor mortis</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">likblekhet</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">bladość pośmiertna</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">kuolonkalpeus</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">tái nhạt tử thi</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">трупна бледост</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">mrliška bledica</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">pallor mortis</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">pallor mortis</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">pallor mortis</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">pallor mortis</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">pallor mortis</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">трупная бледнасць</span>+++





<<<

[id='2']
=== [`2`] /algor mortis/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q1500381[Q1500381]

  ix_hxlix:::
    ix_algormortis

  ix_hxlvoc:::
    v_lat_algormortis

Rēs linguālibus::
  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">برودة الموت</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">посмертное охлаждение</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">मृत्युज शीतलन</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਐਲਗਰ ਮੌਰਟਿਸ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">사후체온하강</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">การลดลงของอุณหภูมิร่างกายหลังตาย</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">尸冷</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">algor mortis</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">algor mortis</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">algor mortis</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">algor mortis</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">algor mortis</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">algor mortis</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">algor mortis</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">likkyla</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">oziębienie pośmiertne</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">kuolonkylmyys</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">mát lạnh tử thi</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">трупно изстиване</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">mrliška ohladitev</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">algor mortis</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">死冷</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">algor mortis</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">屍冷</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">algor mortis</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">algor mortis</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">algor mortis</span>+++





<<<

[id='3']
=== [`3`] /rigor mortis/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q274095[Q274095]

  ix_hxlix:::
    ix_rigormortis

  ix_hxlvoc:::
    v_lat_rigormortis

Rēs linguālibus::
  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">تخشب موتي</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">трупное окоченение</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">मृत्युज काठिन्य</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਮੌਤ ਦਾ ਅਕੜਾਅ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">사후강직</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">צפידת מוות</span>+++

  Lingua Tamulica (/ISO 15924 Taml/):::
    +++<span lang="ta">மரண விறைப்பு</span>+++

  Lingua Telingana (/ISO 15924 Telu/):::
    +++<span lang="te">చనిపోయిన తర్వాత శరీరం బిగుసుకు పోవుట (రిగార్ మోర్టీస్)</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">สภาพแข็งทื่อหลังตาย</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">尸僵</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">rigor mortis</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">rigor mortis</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">rigidité cadavérique</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">lijkstijfheid</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">totenstarre</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">rigor mortis</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">rigor mortis</span>+++

  Lingua Hibernica (Abecedarium Latinum):::
    +++<span lang="ga">teannáil an bháis</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">likstelhet</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">stężenie pośmiertne</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">kuolonkankeus</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">rigor mortis</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">co cứng tử thi</span>+++

  Lingua Catalana (Abecedarium Latinum):::
    +++<span lang="ca">rigidesa cadavèrica</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">трупне окоченіння</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">трупно вкочаняване</span>+++

  Lingua Slovena (Abecedarium Latinum):::
    +++<span lang="sl">mrliška okorelost</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">dødsstivhet</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">posmrtná ztuhlost</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">死後硬直</span>+++

  Lingua Malabarica (/Malayalam script/):::
    +++<span lang="ml">മൃത്യുജകാഠിന്യം</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">kaku mayat</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">جمود نعشی</span>+++

  Lingua Hungarica (Abecedarium Latinum):::
    +++<span lang="hu">hullamerevség</span>+++

  Lingua Gallaica (Abecedarium Latinum):::
    +++<span lang="gl">rigor mortis</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">kadavra rigideco</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">rigor mortis</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">lykstyfheid</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">屍僵</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">rigor mortis</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">rigor mortis</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">rigor mortis</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">трупнае адубенне</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Мәйіттің сіресуі</span>+++

  Lingua Kazachica (Abecedarium Arabicum):::
    +++<span lang="kk-arab">ٴمايىتتىڭ سىرەسۋى</span>+++

  Lingua Kazachica (Abecedarium Cyrillicum):::
    +++<span lang="kk-cyrl">мәйіттің сіресуі</span>+++

  Lingua Kazachica (Abecedarium Latinum):::
    +++<span lang="kk-latn">mäýittiñ sireswi</span>+++





<<<

[id='4']
=== [`4`] /livor mortis/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q747953[Q747953]

  ix_hxlix:::
    ix_livormortis

  ix_hxlvoc:::
    v_lat_livormortis

Rēs linguālibus::
  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">ازرقاق الجثة</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">трупные пятна</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">लिवोर मोर्टिस</span>+++

  Lingua Paniabica (/ISO 15924 Guru/):::
    +++<span lang="pa">ਲਾਇਵਰ ਮੌਰਟਿਸ</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">시반</span>+++

  Lingua Thai (/ISO 15924 Thai/):::
    +++<span lang="th">รอยเขียวช้ำหลังตาย</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">尸斑</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">livor mortis</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">livor mortis</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">lividités cadavériques</span>+++

  Lingua Batavica (Abecedarium Latinum):::
    +++<span lang="nl">livor mortis</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">totenfleck</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">livor mortis</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">livor mortis</span>+++

  Lingua Suecica (Abecedarium Latinum):::
    +++<span lang="sv">likfläck</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">plamy pośmiertne</span>+++

  Lingua Finnica (Abecedarium Latinum):::
    +++<span lang="fi">lautuma</span>+++

  Lingua Vietnamensis (Abecedarium Latinum):::
    +++<span lang="vi">hồ máu tử thi</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">трупні плями</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">хипостаза</span>+++

  /Bokmål/ (Abecedarium Latinum):::
    +++<span lang="nb">dødsflekk</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">posmrtné skvrny</span>+++

  Lingua Danica (Abecedarium Latinum):::
    +++<span lang="da">livores</span>+++

  Lingua Iaponica (Scriptura Iaponica):::
    +++<span lang="ja">死斑</span>+++

  Lingua Indonesiana (Abecedarium Latinum):::
    +++<span lang="id">livor mortis</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">livor mortis</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">livor mortis</span>+++

  Lingua Batava Capitensis (Abecedarium Latinum):::
    +++<span lang="af">lykvlek</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">屍斑</span>+++

  /Serbian/ (Abecedarium Latinum):::
    +++<span lang="sr-el">mrtvačke mrlje</span>+++

  Lingua Serbica (Abecedarium Cyrillicum):::
    +++<span lang="sr">мртвачке мрље</span>+++

  Lingua Urdu (Abecedarium Arabicum):::
    +++<span lang="ur">لیور مارٹیس</span>+++

  Macrolingua Serbocroatica (Abecedarium Latinum):::
    +++<span lang="sh">livor mortis</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">трупныя плямы</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Мәйіт таңдақтары</span>+++

  Lingua Kazachica (Abecedarium Arabicum):::
    +++<span lang="kk-arab">ٴمايىت تاڭداقتارى</span>+++

  Lingua Kazachica (Abecedarium Cyrillicum):::
    +++<span lang="kk-cyrl">мәйіт таңдақтары</span>+++

  Lingua Kazachica (Abecedarium Latinum):::
    +++<span lang="kk-latn">mäýit tañdaqtarı</span>+++





<<<

[id='5']
=== [`5`] /putrefaction/@eng-Latn

Rēs interlinguālibus::
  /Wiki QID/:::
    https://www.wikidata.org/wiki/Q671701[Q671701]

  ix_hxlix:::
    ix_putrefactiocadaveris

  ix_hxlvoc:::
    v_lat_putrefactiocadaveris

Rēs linguālibus::
  Macrolingua Arabica (Abecedarium Arabicum):::
    +++<span lang="ar">تعفن</span>+++

  Lingua Armenia (Alphabetum Armenium):::
    +++<span lang="hy">ամոնիֆիկացում</span>+++

  Lingua Russica (Abecedarium Cyrillicum):::
    +++<span lang="ru">гниение</span>+++

  Lingua Hindica (Devanāgarī):::
    +++<span lang="hi">सड़न</span>+++

  Lingua Coreana (Abecedarium Coreanum):::
    +++<span lang="ko">부패</span>+++

  Lingua Hebraica (Alphabetum Hebraicum):::
    +++<span lang="he">ריקבון גופה</span>+++

  /Macrolingua Sinicae (/ISO 15924 Zyyy/)/:::
    +++<span lang="zh">屍體腐敗</span>+++

  Lingua Lusitana (Abecedarium Latinum):::
    +++<span lang="pt">putrefação</span>+++

  Lingua Anglica (Abecedarium Latinum):::
    +++<span lang="en">putrefaction</span>+++

  Lingua Francogallica (Abecedarium Latinum):::
    +++<span lang="fr">putréfaction</span>+++

  Lingua Germanica (Abecedarium Latinum):::
    +++<span lang="de">putrefizierung</span>+++

  Lingua Hispanica (Abecedarium Latinum):::
    +++<span lang="es">putrefacción</span>+++

  Lingua Italiana (Abecedarium Latinum):::
    +++<span lang="it">putrefazione</span>+++

  Lingua Polonica (Abecedarium Latinum):::
    +++<span lang="pl">rozpad gnilny</span>+++

  Lingua Dacoromanica (Abecedarium Latinum):::
    +++<span lang="ro">putrefacție</span>+++

  Lingua Ucrainica (Abecedarium Cyrillicum):::
    +++<span lang="uk">гниття</span>+++

  Lingua Bulgarica (Abecedarium Cyrillicum):::
    +++<span lang="bg">гниене</span>+++

  Lingua Bohemica (Abecedarium Latinum):::
    +++<span lang="cs">hnití</span>+++

  Macrolingua Persica (//Abecedarium Arabicum//):::
    +++<span lang="fa">گندیدگی</span>+++

  Lingua Esperantica (Abecedarium Latinum):::
    +++<span lang="eo">putrado</span>+++

  Macrolingua Estonica (Abecedarium Latinum):::
    +++<span lang="et">roiskumine</span>+++

  Lingua Turcica (Abecedarium Latinum):::
    +++<span lang="tr">kokuşma</span>+++

  //Traditional Chinese// (/ISO 15924 Hant/):::
    +++<span lang="zh-hant">腐爛</span>+++

  Lingua Islandica (Abecedarium Latinum):::
    +++<span lang="is">úldnun</span>+++

  Lingua Urdu (Abecedarium Arabicum):::
    +++<span lang="ur">سڑن</span>+++

  Lingua Ruthenica Alba (Abecedarium Cyrillicum):::
    +++<span lang="be">гніенне</span>+++

  Lingua Baschkirica (Abecedarium Cyrillicum):::
    +++<span lang="ba">аммонийлашыу</span>+++

  Lingua Kazachica (/ISO 15924 Zyyy/):::
    +++<span lang="kk">Шіру</span>+++

  Lingua Macedonica (Abecedarium Cyrillicum):::
    +++<span lang="mk">гниење</span>+++

  Macrolinguae Quechuae (Abecedarium Latinum):::
    +++<span lang="qu">ismuy</span>+++

  Lingua Tadzikica (/ISO 15924 Zyyy/):::
    +++<span lang="tg">Аммонификатсия</span>+++






<<<

[.text-center]

Dictiōnāria fīnālī

<<<

== Notā bene

=== /[HELP WANTED] Generated PDF don't have right fonts for all languages/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    First, sorry if this affects your loved language. We're working on this, but we are still not perfected.
    If you have fonts installed on your computer, you very likely can still copy and paste from the eBook version.
    Please note that all formats intended for machine processing will work fine.


=== /[Book with Wikidata Q] I want to help! Some translation is missing or is wrong! How to change it?/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Most (but not all) concepts are using Wikidata Q. In fact, most of the time we improve Wikidata while preparing the dictionaries. Please check if the exact concept you want have a Q ID then click. There you can add translations.
    The next release (likely weekly) will have your submissions without need to contact us directly.


=== /[Book with Wikidata Q] I can find the Wikidata concept, but I'm unable to edit!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    While Wikidata is more flexible than Wikipedia's (for example, it allows concepts without need to create Wikipedia pages) even Wikidata can have concepts which require creating an account and don't allow anonymous editing. Creating such an account and confirming email is faster than asking someone else's do it for you.
    However, while vandalism on Wikidata is rare, very few concepts will require an account with more contributions and not created very recently. If this is your case, help with the ones you can do alone and the rest ask someone else to add to you.


=== /I heard there is an interest in having Cōdex beyond Latin language! How to do it?!/@eng-Latn

Rēs linguālibus::
  Lingua Anglica (Abecedarium Latinum):::
    Please contact us. This book uses Latin (sometimes _dog Latin_) to document all other languages, but we obviously can automated generation of books for others using other writing systems and some reference language. We need special help with writing systems such as Bengali, Devanagari and Tamil. For Right to Left scripts, despite being able to render the text, the book printing will require a different template. Only replacing Latin will not work, so we're open to ideas to make a great user experience!


<<<

