= Cōdex [1603:44:1]: //dictiōnāria de post mortis condici//
:doctype: book
:title: Cōdex [1603:44:1]: //dictiōnāria de post mortis condici//
:lang: la
:toc:
:toclevels: 4
:toc-title: Tabula contentorum
:table-caption: Tabula
:figure-caption: Pictūra
:example-caption: Exemplum
:last-update-label: Renovatio
:version-label: Versiō
:appendix-caption: Appendix
:source-highlighter: rouge
:warning-caption: Hic sunt dracones
:tip-caption: Commendātum




{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
[quote]
/**Public domain means that each major common issue only needs to be resolved once**/@eng-Latn

<<<
toc::[]


[id=0_999_1603_1]
== Praefātiō 

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
_**Cōdex [1603:44:1]**_ is the book format of the machine-readable dictionaries _**[1603:44:1] //dictiōnāria de post mortis condici//**_, which are distributed for implementers on external applications. This book is intended as advanced resource for other lexicographers and terminology translators, including detect and report inconsistencies.

Practical lexicography is the art or craft of compiling, writing and editing dictionaries. The basics are not far different than a millennia ago: it is still a very humane, creative work. It is necessary to be humble: most of the translator's mistakes are, in fact, not translator's fault, but methodological flaws. Making sure of a source idea of what a concept represents, even if it means rewrite and make simpler, annex pictures, show examples, do whatever to make it be understood, makes even non-professional translators that care about their own language deliver better results than any alternative. In other words: even the so-called industry best practices of paying professional translators and reviewers cannot overcome already poorly explained source terms.

The initiative behind this compilation is also doing other dictionaries and accepts new suggestions of relevant topics on data exchange for humanitarian use. All have in common the fact that both have human translations and (if any) external interlingual codes related to each concept while making the end result explicitly already ready to be usable on average softwares. Naturally, each book version gives extensive explanations for collaborators on how to correct itself which become part of the next weekly release.

|===


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
scrīptor
|
https://www.wikidata.org/wiki/Property:Multiplicēs scrīptōribus[Multiplicēs scrīptōribus]

|
/cōdex pūblicandī/
|
https://www.wikidata.org/wiki/Property:EticaAI[EticaAI]

|
/publication date/@eng-Latn
|
https://www.wikidata.org/wiki/Property:2022-01-01[2022-01-01]

|
numerus editionis
|
https://www.wikidata.org/wiki/Property:2022-02-26T23:31:02[2022-02-26T23:31:02]

|
/SPDX license ID/@eng-Latn
|
https://www.wikidata.org/wiki/Property:CC-PDDC[CC-PDDC]

|===


<<<

== Methodī ex cōdice
=== Methodī ex dictiōnāriōrum corde
NOTE: #`0_1603_1_7_2616_7535` ?#

=== Methodī ex verbīs in dictiōnāriīs
NOTE: /At the moment, there is no workflow to use https://www.wikidata.org/wiki/Wikidata:Lexicographical_data[Wikidata lexicographical data], which actually could be used as storage for stricter nomenclature. The current implementations use only Wikidata concepts, the Q-items./@eng-Latn

==== Methodī ex verbīs in Vicidata (Q modō)
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
The ***[1603:44:1] //dictiōnāria de post mortis condici//*** uses Wikidata as one strategy to conciliate language terms for one or more of it's concepts.

This means that this book, and related dictionaries data files require periodic updates to, at bare minimum, synchronize and re-share up to date translations.

|
Lingua Anglica (Abecedarium Latinum)
|
**How reliable are the community translations (Wikidata source)?**

The short, default answer is: **they are reliable**, even in cases of no authoritative translations for each subject.

As reference, it is likely a professional translator (without access to Wikipedia or Internal terminology bases of the control organizations) would deliver lower quality results if you do blind tests. This is possible because not just the average public, but even terminologists and professional translators help Wikipedia (and implicitly Wikidata).

However, even when the result is correct, the current version needs improved differentiation, at minimum, acronym and long form. For major organizations, features such as __P1813 short names__ exist, but are not yet compiled with the current dataset.

|
Lingua Anglica (Abecedarium Latinum)
|
**Major reasons for "wrong translations" are not translators fault**

TIP: As a rule of thumb, for already very defined concepts where you, as human, can manually verify one or more translated terms as a decent result, the other translations are likely to be acceptable. Dictionaries with edge cases (such as disputed territory names) would have further explanation.

NOTE: Both at concept level and (as general statistics) book level, is planned to have indication concept likelihood of being well understood for very stricter translations initiatives.

The main reason for "wrong translations" are poorly defined concepts used to explain for community translators how to generate terminology translations. This would make existing translations from Wikidata (used not just by us) inconsistent. The second reason is if the dictionaries use translations for concepts without a strict match; in other words, if we make stricter definitions of what concept means but reuse Wikidada less exact terms. There are also issues when entire languages are encoded with wrong codes. Note that all these cases **wrong translations are strictly NOT translators fault, but lexicography fault**.

It is still possible to have strict translation level errors. But even if we point users how to correct Wikidata/Wikipedia (based on better contextual explanation of a concept, such as this book), the requirements to say the previous term was objectively a wrong human translation error (if following our seriousness on dictionary-building) are very high.

|
Lingua Anglica (Abecedarium Latinum)
|
From the point of view of data conciliation, the following methodology is used to release the terminology translations with the main concept table.

. The main handcrafted lexicographical table (explained on previous topic), also provided on `1603_44_1.no1.tm.hxl.csv`, may reference Wiki QID.
. Every unique QID of  `1603_44_1.no1.tm.hxl.csv`, together with language codes from [`1603:1:51`] (which requires knowing human languages), is used to prepare an SPARQL query optimized to run on https://query.wikidata.org/[Wikidata Query Service]. The query is so huge that it is not viable to "Try it" links (URL overlong), such https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples[as what you would find on Wikidata Tutorials], ***but*** it works!
.. Note that the knowledge is free, the translations are there, but the multilingual humanitarian needs may lack people to prepare the files and shares then for general use.
. The query result, with all QIDs and term labels, is shared as `1603_44_1.wikiq.tm.hxl.csv`
. The community reviewed translations of each singular QID is pre-compiled on an individual file `1603_44_1.wikiq.tm.hxl.csv`
. `1603_44_1.no1.tm.hxl.csv` plus `1603_44_1.wikiq.tm.hxl.csv` created `1603_44_1.no11.tm.hxl.csv`

|===

=== Rēs dē factō in dictiōnāriīs
==== Concepta: 5

==== Rēs linguālibus: 30

[%header,cols="15h,25a,~,15"]
|===
|
Cōdex linguae
|
Glotto cōdicī +++<br>+++ ISO 639-3 +++<br>+++ Wiki QID cōdicī
|
Nōmen Latīnum
|
Concepta

|
ara-Arab
|
https://glottolog.org/resource/languoid/id/arab1395[arab1395]
+++<br>+++
https://iso639-3.sil.org/code/ara[ara]
+++<br>+++ https://www.wikidata.org/wiki/Q13955[Q13955]
|
Macrolingua Arabica (/Abecedarium Arabicum/)
|
5

|
rus-Cyrl
|
https://glottolog.org/resource/languoid/id/russ1263[russ1263]
+++<br>+++
https://iso639-3.sil.org/code/rus[rus]
+++<br>+++ https://www.wikidata.org/wiki/Q7737[Q7737]
|
Lingua Russica (Abecedarium Cyrillicum)
|
5

|
por-Latn
|
https://glottolog.org/resource/languoid/id/port1283[port1283]
+++<br>+++
https://iso639-3.sil.org/code/por[por]
+++<br>+++ https://www.wikidata.org/wiki/Q5146[Q5146]
|
Lingua Lusitana (Abecedarium Latinum)
|
5

|
eng-Latn
|
https://glottolog.org/resource/languoid/id/stan1293[stan1293]
+++<br>+++
https://iso639-3.sil.org/code/eng[eng]
+++<br>+++ https://www.wikidata.org/wiki/Q1860[Q1860]
|
Lingua Anglica (Abecedarium Latinum)
|
5

|
fra-Latn
|
https://glottolog.org/resource/languoid/id/stan1290[stan1290]
+++<br>+++
https://iso639-3.sil.org/code/fra[fra]
+++<br>+++ https://www.wikidata.org/wiki/Q150[Q150]
|
Lingua Francogallica (Abecedarium Latinum)
|
5

|
nld-Latn
|
https://glottolog.org/resource/languoid/id/mode1257[mode1257]
+++<br>+++
https://iso639-3.sil.org/code/nld[nld]
+++<br>+++ https://www.wikidata.org/wiki/Q7411[Q7411]
|
Lingua Batavica (Abecedarium Latinum)
|
4

|
deu-Latn
|
https://glottolog.org/resource/languoid/id/stan1295[stan1295]
+++<br>+++
https://iso639-3.sil.org/code/deu[deu]
+++<br>+++ https://www.wikidata.org/wiki/Q188[Q188]
|
Lingua Germanica (Abecedarium Latinum)
|
5

|
spa-Latn
|
https://glottolog.org/resource/languoid/id/stan1288[stan1288]
+++<br>+++
https://iso639-3.sil.org/code/spa[spa]
+++<br>+++ https://www.wikidata.org/wiki/Q1321[Q1321]
|
Lingua Hispanica (Abecedarium Latinum)
|
5

|
ita-Latn
|
https://glottolog.org/resource/languoid/id/ital1282[ital1282]
+++<br>+++
https://iso639-3.sil.org/code/ita[ita]
+++<br>+++ https://www.wikidata.org/wiki/Q652[Q652]
|
Lingua Italiana (Abecedarium Latinum)
|
5

|
gle-Latn
|
https://glottolog.org/resource/languoid/id/iris1253[iris1253]
+++<br>+++
https://iso639-3.sil.org/code/gle[gle]
+++<br>+++ https://www.wikidata.org/wiki/Q9142[Q9142]
|
Lingua Hibernica (Abecedarium Latinum)
|
1

|
swe-Latn
|
https://glottolog.org/resource/languoid/id/swed1254[swed1254]
+++<br>+++
https://iso639-3.sil.org/code/swe[swe]
+++<br>+++ https://www.wikidata.org/wiki/Q9027[Q9027]
|
Lingua Suecica (Abecedarium Latinum)
|
4

|
pol-Latn
|
https://glottolog.org/resource/languoid/id/poli1260[poli1260]
+++<br>+++
https://iso639-3.sil.org/code/pol[pol]
+++<br>+++ https://www.wikidata.org/wiki/Q809[Q809]
|
Lingua Polonica (Abecedarium Latinum)
|
5

|
fin-Latn
|
https://glottolog.org/resource/languoid/id/finn1318[finn1318]
+++<br>+++
https://iso639-3.sil.org/code/fin[fin]
+++<br>+++ https://www.wikidata.org/wiki/Q1412[Q1412]
|
Lingua Finnica (Abecedarium Latinum)
|
4

|
ron-Latn
|
https://glottolog.org/resource/languoid/id/roma1327[roma1327]
+++<br>+++
https://iso639-3.sil.org/code/ron[ron]
+++<br>+++ https://www.wikidata.org/wiki/Q7913[Q7913]
|
Lingua Dacoromanica (Abecedarium Latinum)
|
2

|
vie-Latn
|
https://glottolog.org/resource/languoid/id/viet1252[viet1252]
+++<br>+++
https://iso639-3.sil.org/code/vie[vie]
+++<br>+++ https://www.wikidata.org/wiki/Q9199[Q9199]
|
Lingua Vietnamensis (Abecedarium Latinum)
|
4

|
cat-Latn
|
https://glottolog.org/resource/languoid/id/stan1289[stan1289]
+++<br>+++
https://iso639-3.sil.org/code/cat[cat]
+++<br>+++ https://www.wikidata.org/wiki/Q7026[Q7026]
|
Lingua Catalana (Abecedarium Latinum)
|
1

|
ukr-Cyrl
|
https://glottolog.org/resource/languoid/id/ukra1253[ukra1253]
+++<br>+++
https://iso639-3.sil.org/code/ukr[ukr]
+++<br>+++ https://www.wikidata.org/wiki/Q8798[Q8798]
|
Lingua Ucrainica (Abecedarium Cyrillicum)
|
3

|
bul-Cyrl
|
https://glottolog.org/resource/languoid/id/bulg1262[bulg1262]
+++<br>+++
https://iso639-3.sil.org/code/bul[bul]
+++<br>+++ https://www.wikidata.org/wiki/Q7918[Q7918]
|
Lingua Bulgarica (Abecedarium Cyrillicum)
|
5

|
slv-Latn
|
https://glottolog.org/resource/languoid/id/slov1268[slov1268]
+++<br>+++
https://iso639-3.sil.org/code/slv[slv]
+++<br>+++ https://www.wikidata.org/wiki/Q9063[Q9063]
|
Lingua Slovena (Abecedarium Latinum)
|
3

|
nob-Latn
|
https://glottolog.org/resource/languoid/id/norw1259[norw1259]
+++<br>+++
https://iso639-3.sil.org/code/nob[nob]
+++<br>+++ https://www.wikidata.org/wiki/Q25167[Q25167]
|
/Bokmål/ (Abecedarium Latinum)
|
2

|
ces-Latn
|
https://glottolog.org/resource/languoid/id/czec1258[czec1258]
+++<br>+++
https://iso639-3.sil.org/code/ces[ces]
+++<br>+++ https://www.wikidata.org/wiki/Q9056[Q9056]
|
Lingua Bohemica (Abecedarium Latinum)
|
5

|
dan-Latn
|
https://glottolog.org/resource/languoid/id/dani1285[dani1285]
+++<br>+++
https://iso639-3.sil.org/code/dan[dan]
+++<br>+++ https://www.wikidata.org/wiki/Q9035[Q9035]
|
Lingua Danica (Abecedarium Latinum)
|
1

|
jpn-Jpan
|
https://glottolog.org/resource/languoid/id/nucl1643[nucl1643]
+++<br>+++
https://iso639-3.sil.org/code/jpn[jpn]
+++<br>+++ https://www.wikidata.org/wiki/Q5287[Q5287]
|
Lingua Iaponica (Scriptura Iaponica)
|
3

|
mal-Mlym
|
https://glottolog.org/resource/languoid/id/mala1464[mala1464]
+++<br>+++
https://iso639-3.sil.org/code/mal[mal]
+++<br>+++ https://www.wikidata.org/wiki/Q36236[Q36236]
|
Lingua Malabarica (/Malayalam script/)
|
1

|
ind-Latn
|
https://glottolog.org/resource/languoid/id/indo1316[indo1316]
+++<br>+++
https://iso639-3.sil.org/code/ind[ind]
+++<br>+++ https://www.wikidata.org/wiki/Q9240[Q9240]
|
Lingua Indonesiana (Abecedarium Latinum)
|
2

|
fas-Zzzz
|

+++<br>+++
https://iso639-3.sil.org/code/fas[fas]
+++<br>+++ https://www.wikidata.org/wiki/Q9168[Q9168]
|
Macrolingua Persica (//Abecedarium Arabicum//)
|
2

|
hun-Latn
|
https://glottolog.org/resource/languoid/id/hung1274[hung1274]
+++<br>+++
https://iso639-3.sil.org/code/hun[hun]
+++<br>+++ https://www.wikidata.org/wiki/Q9067[Q9067]
|
Lingua Hungarica (Abecedarium Latinum)
|
1

|
glg-Latn
|
https://glottolog.org/resource/languoid/id/gali1258[gali1258]
+++<br>+++
https://iso639-3.sil.org/code/glg[glg]
+++<br>+++ https://www.wikidata.org/wiki/Q9307[Q9307]
|
Lingua Gallaica (Abecedarium Latinum)
|
1

|
epo-Latn
|
https://glottolog.org/resource/languoid/id/espe1235[espe1235]
+++<br>+++
https://iso639-3.sil.org/code/epo[epo]
+++<br>+++ https://www.wikidata.org/wiki/Q143[Q143]
|
Lingua Esperantica (Abecedarium Latinum)
|
3

|
est-Latn
|

+++<br>+++
https://iso639-3.sil.org/code/est[est]
+++<br>+++ https://www.wikidata.org/wiki/Q9072[Q9072]
|
Macrolingua Estonica (Abecedarium Latinum)
|
1

|===

==== Rēs interlinguālibus: 7
[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
The result of this section is a preview. We're aware it is not well formatted for a book format. Sorry for the temporary inconvenience.

|===



/Wiki QID/::
#item+rem+i_lat+is_latn::: /Wiki QID/
#item+rem+i_qcc+is_zxxx+ix_regulam::: Q[1-9]\d*
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikiq
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_q
#item+rem+definitionem+i_eng+is_latn::: QID (or Q number) is the unique identifier of a data item on Wikidata, comprising the letter "Q" followed by one or more digits. It is used to help people and machines understand the difference between items with the same or similar names e.g there are several places in the world called London and many people called James Smith. This number appears next to the name at the top of each Wikidata item.


scrīptor::
#item+rem+i_lat+is_latn::: scrīptor
#item+rem+i_qcc+is_zxxx+ix_wikip::: P50
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip50
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_50
#item+rem+definitionem+i_eng+is_latn::: Main creator(s) of a written work (use on works, not humans)


/cōdex pūblicandī/::
#item+rem+i_lat+is_latn::: /cōdex pūblicandī/
#item+rem+i_qcc+is_zxxx+ix_wikip::: P123
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip123
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_123
#item+rem+definitionem+i_eng+is_latn::: organization or person responsible for publishing books, periodicals, printed music, podcasts, games or software


numerus editionis::
#item+rem+i_lat+is_latn::: numerus editionis
#item+rem+i_qcc+is_zxxx+ix_wikip::: P393
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip393
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_393
#item+rem+definitionem+i_eng+is_latn::: number of an edition (first, second, ... as 1, 2, ...) or event


/publication date/@eng-Latn::
#item+rem+i_lat+is_latn::: /publication date/@eng-Latn
#item+rem+i_qcc+is_zxxx+ix_wikip::: P577
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip577
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_577
#item+rem+definitionem+i_eng+is_latn::: Date or point in time when a work was first published or released


/reference URL/@eng-Latn::
#item+rem+i_lat+is_latn::: /reference URL/@eng-Latn
#item+rem+i_qcc+is_zxxx+ix_wikip::: P854
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip854
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_854
#item+rem+definitionem+i_eng+is_latn::: should be used for Internet URLs as references


/SPDX license ID/@eng-Latn::
#item+rem+i_lat+is_latn::: /SPDX license ID/@eng-Latn
#item+rem+i_qcc+is_zxxx+ix_wikip::: P2479
#item+rem+i_qcc+is_zxxx+ix_regulam::: [0-9A-Za-z\.\-]{3,36}[+]?
#item+rem+i_qcc+is_zxxx+ix_wikip1630::: https://spdx.org/licenses/$1.html
#item+rem+i_qcc+is_zxxx+ix_hxlix::: ix_wikip2479
#item+rem+i_qcc+is_zxxx+ix_hxlvoc::: v_wiki_p_2479
#item+rem+definitionem+i_eng+is_latn::: SPDX license identifier

<<<

== Archīa


[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
Every book comes with several files both for book format (with (Abecedarium additional information) and machine-readable formats with Latinum) documentation of how to process them. If you receive this file and cannot find the alternatives, ask the human who provide this file.

|===

=== Archīa prō dictiōnāriīs: 3

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
TIP: Is recommended to use the files on this section to  generate derived works.

|===


==== 1603_44_1.no1.tm.hxl.csv

NOTE: link:1603_44_1.no1.tm.hxl.csv[1603_44_1.no1.tm.hxl.csv]

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
/Numerordinatio on HXLTM container/

|===


==== 1603_44_1.no11.tm.hxl.csv

NOTE: link:1603_44_1.no11.tm.hxl.csv[1603_44_1.no11.tm.hxl.csv]

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
/Numerordinatio on HXLTM container (expanded with terminology translations)/

|===


==== 1603_44_1.wikiq.tm.hxl.csv

NOTE: link:1603_44_1.wikiq.tm.hxl.csv[1603_44_1.wikiq.tm.hxl.csv]


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/reference URL/@eng-Latn
|
https://www.wikidata.org/wiki/Property:https://hxltm.etica.ai/[https://hxltm.etica.ai/]

|===

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
HXLTM dialect of HXLStandard on CSV RFC 4180. wikiq means #item+conceptum+codicem are strictly Wikidata QIDs.

|===


=== Archīa prō cōdice: 2

[%header,cols="25h,~a"]
|===
|
Lingua de verba
|
Verba de conceptiō

|
Lingua Anglica (Abecedarium Latinum)
|
WARNING: Unless you are working with a natural language you understand it\'s letters and symbols, it is strongly advised to use automation to generate derived works. Keep manual human steps at minimum: if something goes wrong at least one or more languages can be used to verify mistakes. It's not at all necessary _know all languages_, but working with writing systems you don't understand is risky: copy and paste strategy can cause _additional_ human errors and is unlikely to get human review as fast as you would need.

|
Lingua Anglica (Abecedarium Latinum)
|
TIP: The Asciidoctor (.adoc) is better at copy and pasting! It can be converted to other text formats.

|===


==== 1603_44_1.mul-Latn.codex.adoc

NOTE: link:1603_44_1.mul-Latn.codex.adoc[1603_44_1.mul-Latn.codex.adoc]


[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/reference URL/@eng-Latn
|
https://www.wikidata.org/wiki/Property:https://asciidoctor.org/docs/[https://asciidoctor.org/docs/]

|===


==== 1603_44_1.mul-Latn.codex.pdf

NOTE: link:1603_44_1.mul-Latn.codex.pdf[1603_44_1.mul-Latn.codex.pdf]


<<<

== //dictiōnāria de post mortis condici//
[id='1']
=== [`1`] /pallor mortis/@eng-Latn





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q3493484[Q3493484]

|
ix_hxlix
|
ix_pallormortis

|
ix_hxlvoc
|
v_lat_pallormortis

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Macrolingua Arabica (/Abecedarium Arabicum/)
| +++<span lang="ar">شحوب الموت</span>+++

| Lingua Russica (Abecedarium Cyrillicum)
| +++<span lang="ru">трупная бледность</span>+++

| Lingua Lusitana (Abecedarium Latinum)
| +++<span lang="pt">pallor mortis</span>+++

| Lingua Anglica (Abecedarium Latinum)
| +++<span lang="en">pallor mortis</span>+++

| Lingua Francogallica (Abecedarium Latinum)
| +++<span lang="fr">pallor mortis</span>+++

| Lingua Batavica (Abecedarium Latinum)
| +++<span lang="nl">pallor mortis</span>+++

| Lingua Germanica (Abecedarium Latinum)
| +++<span lang="de">pallor mortis</span>+++

| Lingua Hispanica (Abecedarium Latinum)
| +++<span lang="es">pallor mortis</span>+++

| Lingua Italiana (Abecedarium Latinum)
| +++<span lang="it">pallor mortis</span>+++

| Lingua Suecica (Abecedarium Latinum)
| +++<span lang="sv">likblekhet</span>+++

| Lingua Polonica (Abecedarium Latinum)
| +++<span lang="pl">bladość pośmiertna</span>+++

| Lingua Finnica (Abecedarium Latinum)
| +++<span lang="fi">kuolonkalpeus</span>+++

| Lingua Vietnamensis (Abecedarium Latinum)
| +++<span lang="vi">tái nhạt tử thi</span>+++

| Lingua Bulgarica (Abecedarium Cyrillicum)
| +++<span lang="bg">трупна бледост</span>+++

| Lingua Slovena (Abecedarium Latinum)
| +++<span lang="sl">mrliška bledica</span>+++

| Lingua Bohemica (Abecedarium Latinum)
| +++<span lang="cs">pallor mortis</span>+++

|===




[id='2']
=== [`2`] /algor mortis/@eng-Latn





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q1500381[Q1500381]

|
ix_hxlix
|
ix_algormortis

|
ix_hxlvoc
|
v_lat_algormortis

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Macrolingua Arabica (/Abecedarium Arabicum/)
| +++<span lang="ar">برودة الموت</span>+++

| Lingua Russica (Abecedarium Cyrillicum)
| +++<span lang="ru">посмертное охлаждение</span>+++

| Lingua Lusitana (Abecedarium Latinum)
| +++<span lang="pt">algor mortis</span>+++

| Lingua Anglica (Abecedarium Latinum)
| +++<span lang="en">algor mortis</span>+++

| Lingua Francogallica (Abecedarium Latinum)
| +++<span lang="fr">algor mortis</span>+++

| Lingua Batavica (Abecedarium Latinum)
| +++<span lang="nl">algor mortis</span>+++

| Lingua Germanica (Abecedarium Latinum)
| +++<span lang="de">algor mortis</span>+++

| Lingua Hispanica (Abecedarium Latinum)
| +++<span lang="es">algor mortis</span>+++

| Lingua Italiana (Abecedarium Latinum)
| +++<span lang="it">algor mortis</span>+++

| Lingua Suecica (Abecedarium Latinum)
| +++<span lang="sv">likkyla</span>+++

| Lingua Polonica (Abecedarium Latinum)
| +++<span lang="pl">oziębienie pośmiertne</span>+++

| Lingua Finnica (Abecedarium Latinum)
| +++<span lang="fi">kuolonkylmyys</span>+++

| Lingua Vietnamensis (Abecedarium Latinum)
| +++<span lang="vi">mát lạnh tử thi</span>+++

| Lingua Bulgarica (Abecedarium Cyrillicum)
| +++<span lang="bg">трупно изстиване</span>+++

| Lingua Slovena (Abecedarium Latinum)
| +++<span lang="sl">mrliška ohladitev</span>+++

| Lingua Bohemica (Abecedarium Latinum)
| +++<span lang="cs">algor mortis</span>+++

| Lingua Iaponica (Scriptura Iaponica)
| +++<span lang="ja">死冷</span>+++

|===




[id='3']
=== [`3`] /rigor mortis/@eng-Latn





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q274095[Q274095]

|
ix_hxlix
|
ix_rigormortis

|
ix_hxlvoc
|
v_lat_rigormortis

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Macrolingua Arabica (/Abecedarium Arabicum/)
| +++<span lang="ar">تخشب موتي</span>+++

| Lingua Russica (Abecedarium Cyrillicum)
| +++<span lang="ru">трупное окоченение</span>+++

| Lingua Lusitana (Abecedarium Latinum)
| +++<span lang="pt">rigor mortis</span>+++

| Lingua Anglica (Abecedarium Latinum)
| +++<span lang="en">rigor mortis</span>+++

| Lingua Francogallica (Abecedarium Latinum)
| +++<span lang="fr">rigidité cadavérique</span>+++

| Lingua Batavica (Abecedarium Latinum)
| +++<span lang="nl">lijkstijfheid</span>+++

| Lingua Germanica (Abecedarium Latinum)
| +++<span lang="de">totenstarre</span>+++

| Lingua Hispanica (Abecedarium Latinum)
| +++<span lang="es">rigor mortis</span>+++

| Lingua Italiana (Abecedarium Latinum)
| +++<span lang="it">rigor mortis</span>+++

| Lingua Hibernica (Abecedarium Latinum)
| +++<span lang="ga">teannáil an bháis</span>+++

| Lingua Suecica (Abecedarium Latinum)
| +++<span lang="sv">likstelhet</span>+++

| Lingua Polonica (Abecedarium Latinum)
| +++<span lang="pl">stężenie pośmiertne</span>+++

| Lingua Finnica (Abecedarium Latinum)
| +++<span lang="fi">kuolonkankeus</span>+++

| Lingua Dacoromanica (Abecedarium Latinum)
| +++<span lang="ro">rigor mortis</span>+++

| Lingua Vietnamensis (Abecedarium Latinum)
| +++<span lang="vi">co cứng tử thi</span>+++

| Lingua Catalana (Abecedarium Latinum)
| +++<span lang="ca">rigidesa cadavèrica</span>+++

| Lingua Ucrainica (Abecedarium Cyrillicum)
| +++<span lang="uk">трупне окоченіння</span>+++

| Lingua Bulgarica (Abecedarium Cyrillicum)
| +++<span lang="bg">трупно вкочаняване</span>+++

| Lingua Slovena (Abecedarium Latinum)
| +++<span lang="sl">mrliška okorelost</span>+++

| /Bokmål/ (Abecedarium Latinum)
| +++<span lang="nb">dødsstivhet</span>+++

| Lingua Bohemica (Abecedarium Latinum)
| +++<span lang="cs">posmrtná ztuhlost</span>+++

| Lingua Iaponica (Scriptura Iaponica)
| +++<span lang="ja">死後硬直</span>+++

| Lingua Malabarica (/Malayalam script/)
| +++<span lang="ml">മൃത്യുജകാഠിന്യം</span>+++

| Lingua Indonesiana (Abecedarium Latinum)
| +++<span lang="id">kaku mayat</span>+++

| Macrolingua Persica (//Abecedarium Arabicum//)
| +++<span lang="fa">جمود نعشی</span>+++

| Lingua Hungarica (Abecedarium Latinum)
| +++<span lang="hu">hullamerevség</span>+++

| Lingua Gallaica (Abecedarium Latinum)
| +++<span lang="gl">rigor mortis</span>+++

| Lingua Esperantica (Abecedarium Latinum)
| +++<span lang="eo">kadavra rigideco</span>+++

|===




[id='4']
=== [`4`] /livor mortis/@eng-Latn





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q747953[Q747953]

|
ix_hxlix
|
ix_livormortis

|
ix_hxlvoc
|
v_lat_livormortis

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Macrolingua Arabica (/Abecedarium Arabicum/)
| +++<span lang="ar">ازرقاق الجثة</span>+++

| Lingua Russica (Abecedarium Cyrillicum)
| +++<span lang="ru">трупные пятна</span>+++

| Lingua Lusitana (Abecedarium Latinum)
| +++<span lang="pt">livor mortis</span>+++

| Lingua Anglica (Abecedarium Latinum)
| +++<span lang="en">livor mortis</span>+++

| Lingua Francogallica (Abecedarium Latinum)
| +++<span lang="fr">lividités cadavériques</span>+++

| Lingua Batavica (Abecedarium Latinum)
| +++<span lang="nl">livor mortis</span>+++

| Lingua Germanica (Abecedarium Latinum)
| +++<span lang="de">totenfleck</span>+++

| Lingua Hispanica (Abecedarium Latinum)
| +++<span lang="es">livor mortis</span>+++

| Lingua Italiana (Abecedarium Latinum)
| +++<span lang="it">livor mortis</span>+++

| Lingua Suecica (Abecedarium Latinum)
| +++<span lang="sv">likfläck</span>+++

| Lingua Polonica (Abecedarium Latinum)
| +++<span lang="pl">plamy pośmiertne</span>+++

| Lingua Finnica (Abecedarium Latinum)
| +++<span lang="fi">lautuma</span>+++

| Lingua Vietnamensis (Abecedarium Latinum)
| +++<span lang="vi">hồ máu tử thi</span>+++

| Lingua Ucrainica (Abecedarium Cyrillicum)
| +++<span lang="uk">трупні плями</span>+++

| Lingua Bulgarica (Abecedarium Cyrillicum)
| +++<span lang="bg">хипостаза</span>+++

| /Bokmål/ (Abecedarium Latinum)
| +++<span lang="nb">dødsflekk</span>+++

| Lingua Bohemica (Abecedarium Latinum)
| +++<span lang="cs">posmrtné skvrny</span>+++

| Lingua Danica (Abecedarium Latinum)
| +++<span lang="da">livores</span>+++

| Lingua Iaponica (Scriptura Iaponica)
| +++<span lang="ja">死斑</span>+++

| Lingua Indonesiana (Abecedarium Latinum)
| +++<span lang="id">livor mortis</span>+++

| Lingua Esperantica (Abecedarium Latinum)
| +++<span lang="eo">livor mortis</span>+++

|===




[id='5']
=== [`5`] /putrefaction/@eng-Latn





[%header,cols="25h,~a"]
|===
|
Rēs interlinguālibus
|
Factum

|
/Wiki QID/
|
https://www.wikidata.org/wiki/Q671701[Q671701]

|
ix_hxlix
|
ix_putrefactiocadaveris

|
ix_hxlvoc
|
v_lat_putrefactiocadaveris

|===




[%header,cols="~,~"]
|===
| Lingua de verba
| Verba de conceptiō
| Macrolingua Arabica (/Abecedarium Arabicum/)
| +++<span lang="ar">تعفن</span>+++

| Lingua Russica (Abecedarium Cyrillicum)
| +++<span lang="ru">гниение</span>+++

| Lingua Lusitana (Abecedarium Latinum)
| +++<span lang="pt">putrefação</span>+++

| Lingua Anglica (Abecedarium Latinum)
| +++<span lang="en">putrefaction</span>+++

| Lingua Francogallica (Abecedarium Latinum)
| +++<span lang="fr">putréfaction</span>+++

| Lingua Germanica (Abecedarium Latinum)
| +++<span lang="de">putrefizierung</span>+++

| Lingua Hispanica (Abecedarium Latinum)
| +++<span lang="es">putrefacción</span>+++

| Lingua Italiana (Abecedarium Latinum)
| +++<span lang="it">putrefazione</span>+++

| Lingua Polonica (Abecedarium Latinum)
| +++<span lang="pl">rozpad gnilny</span>+++

| Lingua Dacoromanica (Abecedarium Latinum)
| +++<span lang="ro">putrefacție</span>+++

| Lingua Ucrainica (Abecedarium Cyrillicum)
| +++<span lang="uk">гниття</span>+++

| Lingua Bulgarica (Abecedarium Cyrillicum)
| +++<span lang="bg">гниене</span>+++

| Lingua Bohemica (Abecedarium Latinum)
| +++<span lang="cs">hnití</span>+++

| Macrolingua Persica (//Abecedarium Arabicum//)
| +++<span lang="fa">گندیدگی</span>+++

| Lingua Esperantica (Abecedarium Latinum)
| +++<span lang="eo">putrado</span>+++

| Macrolingua Estonica (Abecedarium Latinum)
| +++<span lang="et">roiskumine</span>+++

|===





<<<

